### ISSUE TITLE
Maintaining full LOINC description (long_common_name) in CONCEPT_NAME field

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#10]
There are LOINC concepts whose name are the LOINC short-form, making them ambiguous. It would be better to use the LOINC long_common_name as concept name instead. 

For example:

Both concepts 3035064 and 43055681 have concept_name "Creatinine", whereas the corresponding LOINC long_common_names are 'Deprecated Creatinine' and 'Creatinine [Mass/time] in unspecified time Urine by calculation' resp.

**Comment by cgreich** [comment]
Fixed
