### ISSUE TITLE
Concept Class ID correction

### ISSUE THREAD

**Issue by dkwollam** [OHDSI/Vocabulary-v5.0#1001]
Concept ID 596889 has an incorrect Concept Class ID and needs to be corrected to **Question** Concept Class ID.

https://athena.ohdsi.org/search-terms/terms/596889

Contribution link: https://docs.google.com/spreadsheets/d/11i-3rLZX5tdb0HlFBhrEQbt5xcMVDM--/edit#gid=2051797039

**Comment by IrynaZherka** [comment]
@dkwollam the issue was fixed during the August 2024 release.
Thanks a lot for the contribution!
