### ISSUE TITLE
Loop Diuretics ATC Group 4th no descendents drugs 

### ISSUE THREAD

**Issue by rfherrerac** [OHDSI/Vocabulary-v5.0#1005]
**Describe the problem in content or desired feature**
 the ATC 4th class group Loop diuretics 
It has no drug concept linked to that hierarchy, basically it is empty. It comes from the EphMRA ATC vocabulary. It is a bit weird because it is not quite useful since it has no descendants. 
**How to find it**
[Help us reproducing the problem and researching the issue. Links to Athena concepts can be helpful.](https://athena.ohdsi.org/search-terms/terms/723656)

**Expected adjustments**
Mapping to some related ingredients

**Comment by cgreich** [comment]
@rfherrerac:

Forget the EphMRA ATC. Nobody is using it, nobody is maintaining it. Use ATC [C03C](https://athena.ohdsi.org/search-terms/terms/21601516).
