### ISSUE TITLE
Non standard mapped to another non standard?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#1006]
![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/13936600/33930250-b16e-49af-a713-2bf88a2f47ff)

https://athena.ohdsi.org/search-terms/terms/2211334

is mapped to
![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/13936600/00020f86-b922-4d1f-96ab-82d00b28f133)

but that is non standard?
https://athena.ohdsi.org/search-terms/terms/4308718

![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/13936600/fe0b80d3-496c-4236-8dc4-b3527961c69d)

**Comment by TinyRickC137** [comment]
The real fix is the absence of mapping, but CPT4 - SNOMED eq relationships are not considered mapping. They are provided by UMLS and we make no corrections to them.

**Comment by m-khitrun** [comment]
Hello, @gowthamrao 

Just letting you know, that [this CPT4 code](https://athena.ohdsi.org/search-terms/terms/2211334) has been mapped to a standard target.
Thank you!

Sincerely,
Masha
