### ISSUE TITLE
Map of ICD10 for primary malignant neoplasm (unknown)

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#101]
Hi @cgreich,

The ICD10CM code C80.1 is for "Malignant (primary) neoplasm, unspecified" and has concept_id of 45561836. It currently maps to standard concept_id 439392 for "Primary malignant neoplasm." The unspecified nature of the cancer is lost in translation. Perhaps it should be mapped to standard concept_id 436919 for "Primary malignant neoplasm of unspecified site"?

Thanks,
Ajit

**Comment by cgreich** [comment]
No. Unspecified doesn't mean unspecified site. It means nothing is specified, it's histology, origin or spread. Just like in "Primary malignant neoplasm". 
Why are you asking?

**Comment by ericaVoss** [comment]
@alondhe or @cgreich is this an issue or a forum discussion?  Could we close if not an issue?

**Comment by cgreich** [comment]
Ask @alondhe.

**Comment by ericaVoss** [comment]
@alondhe - could we close this?
