### ISSUE TITLE
Reactive arthritis of joint of foot - SNOMED CT May 24 version

### ISSUE THREAD

**Issue by stephanieshong** [OHDSI/Vocabulary-v5.0#1012]
# Instructions

**0. Create the initial GitHub issue.**

Please create the initial issue that briefly describes the content of the intended contribution and the rationale behind it. This will allow us to keep track of requests and connect you with other contributors who may be working on the same content.

**1. Read the documentation.**

Please familiarize yourself with the documentation [here](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Community-contribution) before initiating the submission.

**2. Choose the category of the submission.**

Choose the category of your submission and download the corresponding template:

- Template 1: Add non-standard concept(s) to an existing vocabulary (with or without synonyms or mappings);
- Template 2: Add synonym(s) to existing concept(s);
- Template 3: Add mapping(s) to existing concept(s);
- Template 4: Add new non-standard vocabulary (with or without mappings).

**3. Fill out the template.**

Please download the corresponding template from [this folder](https://drive.google.com/drive/u/1/folders/1D7hSGKQkWgJCAKXDNOjfoFcnRca0-57w) and fill it out. Instructions and examples are provided within the template. If questions occur, use comments in the current issue to contact the Vocabulary Team. 

Make sure that you complete the checklist!

**4. Upload the template.**

Please go to [this folder](https://drive.google.com/drive/u/1/folders/1wXB3CK08-sPa0EdyLlIL8jHaBkuH7k3g), create a subfolder (name it *GitHubIssueNumber_ContributionName_YourName*) and upload your files there.

**5. Reference the template in the new GitHub issue.**

Please add the link to your submission to the newly created GitHub issue.

**6. See your contribution in the next release!**

'Add content' contributions are not reviewed by the Vocabulary Team and you generally can expect to see them in the next release if the submission is made at least 2 months prior to the release date.

**Comment by stephanieshong** [comment]
Could not find it in Athena which is OMOP Vocabulary version: v5.0 29-FEB-24 version.  It was reported by Maggie Hall from Emory.

**Comment by m-khitrun** [comment]
Hello, @stephanieshong!

Yes, the concept 1288006003 | Reactive arthritis of joint of foot (disorder) will be added to the August 2024 release.

Regards,
Masha.

**Comment by m-khitrun** [comment]
Hello, @stephanieshong 

Just letting you know, that the [concept](https://athena.ohdsi.org/search-terms/terms/1244519) is already in Athena.
Thank you!

Sincerely,
Masha
