### ISSUE TITLE
LEVOTHYROXINE ingredient standard concept missing / wrong name?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#102]
For example, concept 40169766 ('Levothyroxine Sodium 0.1 MG Oral Tablet') via drug_strength links to ingredient concept 1501700 ('Thyroxine', RnNorm ID = 10582). This ingredient is not linked to ATC concept 21602754 ('levothyroxine sodium'). In the original RxNorm  (RnNorm ID = 10582) the preferred name is levothyroxine.

So two problems: 
1. The name of concept 1501700 should be Levothyroxine, not Thyroxine (they are isomers)
2. There should be a link from ATC concept 21602754 ('levothyroxine sodium')

Vocab version:  2016-12-18

**Comment by dimshitc** [comment]
These changes appeared in the last release of RxNorm,
so internally we already have these changes and next release will not
contain this problem.

2017-01-16 11:40 GMT+02:00 Martijn Schuemie <notifications@github.com>:

**Comment by schuemie** [comment]
Thanks! I will keep an eye out for this in the next vocab release.

**Comment by aostropolets** [comment]
@schuemie  please ckeck

**Comment by ericaVoss** [comment]
### QUESTION 1
```sql
SELECT *
FROM CONCEPT
WHERE CONCEPT_ID = 1501700
```

This concept looks to now be named levothyroxine, so this looks complete to me. :+1: 

### QUESTION 2
@schuemie I'm not sure if I'm writing the query right for this:

```sql
SELECT *
FROM CONCEPT c
	JOIN CONCEPT_RELATIONSHIP cr
		ON c.CONCEPT_ID = cr.CONCEPT_ID_1
	JOIN CONCEPT c2
		ON c2.CONCEPT_ID = cr.CONCEPT_ID_2
		AND c2.CONCEPT_ID = 1501700
WHERE c.CONCEPT_ID = 21602754
```

**Comment by aostropolets** [comment]
simply like that:
SELECT * FROM concept_ancestor WHERE ancestor_concept_id = 21602754  and descendant_concept_id = 1501700;
