### ISSUE TITLE
which type concept id should we use to specify the data provenance:  app genderated or manually entered using a paper form? 

### ISSUE THREAD

**Issue by stephanieshong** [OHDSI/Vocabulary-v5.0#1020]
**Describe the problem in content or desired feature**
A clear and concise description of what you found or what you want to add (including features, documentation, etc.) and how it is affecting your processes, ETL or analysis. If you want to contribute your conent or modify existing, please refer to the corresponding categories of issues.

There is no type concept id we can use to specify the provenance the data:  1) app genderated or 2) manually entered using a paper form. 

We have Montreal Cognitive Assessement measurement data that we are mapping and ETLing into the OMOP CDM. These data can be app generated and it can also be manually entered from a paper form. We did not find a type concept that we can use to specify the provenance of the data source, i.e. app generated or manually entered from a paper form.
We found the following concept ids, but they are not of the type_concept class
37161935
37161934

**How to find it**
Help us reproducing the problem and researching the issue. Links to Athena concepts can be helpful.

Could you add following two type_concept ids that we can use in our ETL process?

The following concepts we found have the procedure as the domain_id
37161934 - information gathered from automated entry
37161935 - information gathered from manual entry 
The data we are capturing are for the measurement domain for various Montreal cognitive score and assessment for the measurement domain.

**Expected adjustments**
A clear and concise description of what you expect the Vocabulary Team to change. If you have collected information in a spreadsheet, please share it with us.
Request: following new type concept ids to describe the provenance of the data
1. app generated 
2. manually entered from a paper form

**Screenshots**

**Additional context**

**Comment by stephanieshong** [comment]
@aostropolets and @cgreich - thoughts?

**Comment by stephanieshong** [comment]
let me provide you with bit more context -
use case 1) Montreal Cognitive Assessment tests are completed on the app but the assessment score measurement by the app is then entered into the survey form by the Procter.
use case 2) When it is not possible to enter the assessment score via online survey form, the paper form is submitted and it is then manually entered at a later time.

**Comment by stephanieshong** [comment]
@TinyRickC137  - what was the resolution?

**Comment by stephanieshong** [comment]
@TinyRickC137

**Comment by Alexdavv** [comment]
Hi @stephanieshong 
As @cgreich suggested let’s continue this discussion on the forums, come up with a conclusion and then proceed with a new change request if needed.
