### ISSUE TITLE
Information on Statins drug strength not available for ATC

### ISSUE THREAD

**Issue by urvishah3** [OHDSI/Vocabulary-v5.0#103]
While doing analysis for the following who atc 5 for statins, we realized these drugs do not have any information in the drug_strength table. Will there be an update to this? 

                Who ATC 5         concept_name
1              C10AA03              Pravastatin
2              C10AA08              pitavastatin
3              C10AA05              atorvastatin
4              C10AA01              Simvastatin
5              C10AA07              rosuvastatin
6              C10AA02              Lovastatin
7              LOVASTATIN      No matching concept
8              C10AA04              fluvastatin

**Comment by dimshitc** [comment]
ATC-concepts never have drug_strength,
but related RxNorm Drug concepts have information in the drug_strength
table.
Here is an a example:

select c.concept_name, c.vocabulary_id, z.concept_name, z.concept_code,
ds.* from concept c
join concept_relationship r on r.concept_id_1 = c.concept_id
join concept z on r.concept_id_2 = z.concept_id
join drug_strength ds on drug_concept_id = c.concept_id
where z.concept_code in (
'C10AA08',
'C10AA05',
'C10AA01',
'C10AA07',
'C10AA02',
'C10AA04'
)
and c.concept_class_id = 'Clinical Drug' and c.vocabulary_id ='RxNorm'

2017-01-16 21:51 GMT+02:00 urvishah3 <notifications@github.com>:
