### ISSUE TITLE
Incorrect record in CONCEPT_ANCESTOR table

### ISSUE THREAD

**Issue by hamedabedtash** [OHDSI/Vocabulary-v5.0#104]
Hi @dimshitc ,

I found two incorrect records in CONCEPT_ANCESTOR table that link 'Other blood glucose lowering drugs, excl. insulins' ATC drug class to 'Aluminum Hydroxide' and 'Magnesium Hydroxide':

```
ANCESTOR_CONCEPT_ID	DRUG_CLASS_NAME	MIN_LEVELS_OF_SEPARATION	MAX_LEVELS_OF_SEPARATION	DESCENDANT_CONCEPT_ID	DESCENDANT_NAME
21600788	Other blood glucose lowering drugs, excl. insulins	1	1	985247	Aluminum Hydroxide
21600788	Other blood glucose lowering drugs, excl. insulins	1	1	992956	Magnesium Hydroxide
```

Thanks,
Hamed

**Comment by cgreich** [comment]
@hamedabedtash:

We know. There is a bug in ATC. We will fix it soon, as soon as we wrestled down the current RxNorm Extension issue.

**Comment by hamedabedtash** [comment]
Thanks @cgreich for the hard work! We are aware of the challenges with ATC, too.

**Comment by ericaVoss** [comment]
Testing 20180609

Looks like it is gone now
```sql
SELECT *
FROM CONCEPT_ANCESTOR
WHERE ANCESTOR_CONCEPT_ID = 21600788
AND DESCENDANT_CONCEPT_ID IN (
985247,992956)
```

@hamedabedtash  can we close this issue?

**Comment by abedtashh** [comment]
@ericaVoss Yes, we can. Thanks!

**Comment by ericaVoss** [comment]
@abedtashh you hold the power to do it.  :)
