### ISSUE TITLE
Missing denominator_value values in Drug Strength

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#1042]
**Describe the problem in content or desired feature**
If there is a denominator unit then I expect there to denominator value. How can you have a unit if there is no value? Or in which circumstances is this possible?

I found this to be the case for concept_id = [1126750](https://athena.ohdsi.org/search-terms/terms/1126750), APAP 100 MG/ML Oral Solution which is a solution. Is this because the denominator is assumed to be = 1? If yes, then this should be populated with '1' in the Drug Strength table to make is human readable and logically correct. 

**How to find it**
SELECT *
FROM drug_strength
WHERE denominator_unit_concept_id > 0
AND denominator_value is NULL

**Expected adjustments**
Answered above

**Screenshots**

**Additional context**

**Comment by TinyRickC137** [comment]
It is not an issue, but a design choice, identical to RxNorm's approach to handle drug formulations. Please compare

```
SELECT *
FROM drug_strength
WHERE drug_concept_id = 1126750

UNION 

SELECT *
FROM drug_strength
WHERE drug_concept_id = 21077603;
```
