### ISSUE TITLE
Prioritized list of unmapped ICD9CM codes to map

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#105]
Team:

On the version of the vocabulary I'm using, there are 96 ICD9CM codes that don't map into a standard (SNOMED).  Across the datasets I have access to, there are only 8 codes that make up 93% of the unmapped records. 

![image](https://cloud.githubusercontent.com/assets/731930/22574613/eada70fc-e97d-11e6-80c0-a0834c8e7f8a.png)

**Comment by ericaVoss** [comment]
I believe this is a duplicate on issue #88.  Agree this is an important issue.

**Comment by ericaVoss** [comment]
@pbr6cornell  can you close this issue as it is duplicate.  I will test this on 20170920 as soon as I get the Vocab next to the source data.
