### ISSUE TITLE
CPT4 Code Description download fails partially

### ISSUE THREAD

**Issue by michaelheese** [OHDSI/Vocabulary-v5.0#1052]
Dear OHDSI Community
we have a problem with downloading the CPT4 Code Descriptions for the latest Vocabulary update (v20240830).
When running the cpt4.jar there are 283 concepts left where the UMLS name cannot be resolved (see attached log files)

[Vocabulary-Cpt-Concept-Errors.txt](https://github.com/user-attachments/files/17023529/Vocabulary-Cpt-Concept-Errors.txt)
[not-processed-concepts-09-13-2024-13-09-29.txt](https://github.com/user-attachments/files/17023530/not-processed-concepts-09-13-2024-13-09-29.txt)

Did anyone had the same problem with the latest Vocabulary update?

**Comment by TinyRickC137** [comment]
Dear @michaelheese 
This issue has been [fixed](https://forums.ohdsi.org/t/latest-vocabulary-files-cpt4-processing-issues/22391/3).

Please request a new bundle in Athena and use the updated cpt4 tool.
You can run it against the content you already have, even after previous unsuccessful attempts.

**Comment by michaelheese** [comment]
> Dear @michaelheese This issue has been [fixed](https://forums.ohdsi.org/t/latest-vocabulary-files-cpt4-processing-issues/22391/3).
> 
> Please request a new bundle in Athena and use the updated cpt4 tool. You can run it against the content you already have, even after previous unsuccessful attempts.

thanks for taking this up so quickly!
