### ISSUE TITLE
Add NCIt "route of administration" codes as concepts, add standard maps to SNOMED terms

### ISSUE THREAD

**Issue by scottfavre** [OHDSI/Vocabulary-v5.0#1056]
We commonly see routes encoded with NCIt codes (e.g., `C38288 Oral Route of Administration`).

There do not appear to be any NCIt route codes in the OMOP vocabularies.

Proposal is:
- add NCIt "route of administration" codes as concepts. A naive search of NCIt shows < 300 codes
- add non-standard to standard relationships to SNOMED Route codes.

# Instructions

**0. Create the initial GitHub issue.**

Please create the initial issue that briefly describes the content of the intended contribution and the rationale behind it. This will allow us to keep track of requests and connect you with other contributors who may be working on the same content.

**1. Read the documentation.**

Please familiarize yourself with the documentation [here](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Community-contribution) before initiating the submission.

**2. Choose the category of the submission.**

Choose the category of your submission and download the corresponding template:

- Template 1: Add non-standard concept(s) to an existing vocabulary (with or without synonyms or mappings);
- Template 2: Add synonym(s) to existing concept(s);
- Template 3: Add mapping(s) to existing concept(s);
- Template 4: Add new non-standard vocabulary (with or without mappings).

**3. Fill out the template.**

Please download the corresponding template from [this folder](https://drive.google.com/drive/u/1/folders/1D7hSGKQkWgJCAKXDNOjfoFcnRca0-57w) and fill it out. Instructions and examples are provided within the template. If questions occur, use comments in the current issue to contact the Vocabulary Team. 

Make sure that you complete the checklist!

**4. Upload the template.**

Please go to [this folder](https://drive.google.com/drive/u/1/folders/1wXB3CK08-sPa0EdyLlIL8jHaBkuH7k3g), create a subfolder (name it *GitHubIssueNumber_ContributionName_YourName*) and upload your files there.

**5. Reference the template in the new GitHub issue.**

Please add the link to your submission to the newly created GitHub issue.

**6. See your contribution in the next release!**

'Add content' contributions are not reviewed by the Vocabulary Team and you generally can expect to see them in the next release if the submission is made at least 2 months prior to the release date.

**Comment by scottfavre** [comment]
filled out template 1 here: https://drive.google.com/drive/u/1/folders/1Id0t_eW0YMdy_VMMuovhsv9c5x4esxID

which includes:
- new concepts for all NCIt codes that contain the string "route of administration"
- new "maps to" relationships from the NCIt codes to SNOMED codes based on two criteria:
  - using UMLS as a crosswalk
  - lexical comparison of the NCIt and SNOMED codes (e.g., `XYZ route of administration` maps to `XYZ route (qualifier value)`

There are still quite a few NCIt codes that didn't have an immediately obvious equivalent SNOMED code, which is an opportunity for future work, but this set of maps should cover the vast majority of data.

**Comment by cgreich** [comment]
@scottfavre:

Hold the horses. Right now, we want to fix up the route of administration. Plenty of [debates](https://forums.ohdsi.org/t/new-routes-and-de-standardization-of-old-snomed-routes/20488) and several CDM Work Group sessions have happened. The idea is to simplify them, make them compatible with RxNorm Dose Forms and have all the others, like from SNOMED or NCIt, mapped to them.

Let us know your use case, so we can make sure you can do what you need to do.

**Comment by scottfavre** [comment]
My use case is coming from the ETL side: we commonly see NCIt route codes in CDAs that we are trying to ingest.

The "maps to" relationships I put in the template file are to the current standard concepts, but it should be simple enough to remap them to a different set of concepts such as the hierarchy proposed in that illuminating forum discussion.

**Comment by scottfavre** [comment]
I am pausing this work based on what I learned in the Vocabulary WG meeting at the 2024 Symposium:

- the route update is scheduled for Februray 2025 (https://github.com/OHDSI/Vocabulary-v5.0/wiki/Release-planning)
- I need to either find mappings for all of the NCIt route terms or remove the proposed non-standard terms that don't have a mapping

Closing this issue for now, will reopen with better files some time after the routes are updated.
