### ISSUE TITLE
ATC code - Concept code missing in concept table

### ISSUE THREAD

**Issue by tas-you** [OHDSI/Vocabulary-v5.0#1058]
I have searched for ATC codes in Athena website and found them. So I downloaded the latest vocabulary. However the codes are not found in the vocabulary. 
for example: when i search for atc code L01FX27, with concept id 954983. I get it on athena site : https://athena.ohdsi.org/search-terms/terms/954983
but in the downloaded concept table, concept id is found but the concept code column is empty. 

similar problem is found in following. 
L01FX27
L01FX28
L01FX29
L01FY02
L01XK52
L01XX75

Thanks for help.

**Comment by tas-you** [comment]
The downloaded vocabulary Id : v20240830 that has the notified issue.

**Comment by TinyRickC137** [comment]
Hey @tas-you 
It is strange. Double-check: did you include ATC in your download?

**Comment by tas-you** [comment]
![image](https://github.com/user-attachments/assets/1b6b132a-7be3-48be-bfcc-df77025620e1)
![Skjermbilde 2024-10-09 083043](https://github.com/user-attachments/assets/9d9a3bf8-cd68-4b58-be73-dfc59af1f764)

**Comment by TinyRickC137** [comment]
@tas-you so what was the problem?

**Comment by tas-you** [comment]
It did not show right in Excel, had to import it to the database.
