### ISSUE TITLE
Downloaded vocabulory data vs Athena website data mismatch

### ISSUE THREAD

**Issue by isingh41** [OHDSI/Vocabulary-v5.0#1060]
**Describe the problem in content or desired feature**
We are using the concepts data along with relationships data from Athena and thats why we had to download all the vocab as ZIP files. While extracting the contents of the ZIP files, we found couple of issues (as mentioned below) and wanted to understand if those are actually issues or some understanding gaps:

1. When we download any vocab zip from Athena interface, in addition to the downloaded vocab e.g. SNOMED, there would also be many other vocab's data into the CSV (CONCEPT.CSV) and similarly for CONCEPT_RELATIONSHIP.csv files. Is that a known issue/expected behaviour? 
For example in the downloaded ICD10 vocabulory fril CONCEPT.csv, there are total of 224,646 records and if we filter on Vocabulry column as ICD100, only 9044 records are available in that filder. If I try to filter the same on another value available in the vocabulory column as "OSM", I can see 203,199 records available. Is this something expected?

2. The other issue we have come across is that the relationship shown in the Athena website are much more as compared to the same relationships available in the downloaded CONCEPT_RELATIONSHIP.csv file for the same concept_id.
For example, I take an example of a concept_id 43531008(SNOMED). When I search this in Athena website, it shows me 27 mappings available for this concept(refer attached screenshot), however if I try to check the same in CONCEPT_RELATIONSHIP.csv file extracted form SNOMED Vocabulory ZIP file, the mappings available are only 9. Can you please help understand why is this diffeence?

**How to find it**
Already provided with sample codes in the examples for both the issues

**Expected adjustments**
Need to first understand if this is a know issue/expected behaviour. If its an exected behaviour, then how can we find the remaining concepts/missing relationships which are missing from downloaded concept*.csv files

**Screenshots**

**Additional context**

![45531008](https://github.com/user-attachments/assets/a9f35838-b23e-4e80-990a-3f48e7035a4d)

**Comment by TinyRickC137** [comment]
Hello, @isingh41 
The content in Athena should match the content in your downloaded vocabularies. 

You should check the formatting issues if you don't import vocabularies into the database. 

As for the second question, I think you did not include all the vocabularies in your download. As you can see, there are plenty of vocabularies 43531008 SNOMED has relationships to (ICD10, ICD10GM, KCD7, etc.) 

To see all the relationships, you must include all the vocabularies in your download package.

**Comment by TinyRickC137** [comment]
What you describe is unexpected. We do not experience anything like this on our side. 

The suggested process is the following: you include all the vocabularies you need in one bundle and then download them as one package, not one by one.

You can try creating a new bundle and downloading it again.

**Comment by isingh41** [comment]
Ahh...ok...I was not sure about this. We have been downloading vocab by vocab as individual downloads. Let me try with downloading SNOMED and ICD10 in a single package to validate if this resolves the mapping issue between these 2 vocabs, as I mentioned in the ticket. If this works fine, I will download all the ones required in a single package. Thanks.

**Comment by TinyRickC137** [comment]
Download all vocabs you need, this is a trusted process and reduces the number of unnecessary downloads from Athena.

**Comment by isingh41** [comment]
I tried this with combining SNOMED and ICD10 and it showed the mappings which were not appearing earlier while downloading individual Vocab packages. Looks like it has worked. Thanks @TinyRickC137. WIll revert back in case of any issue further.
