### ISSUE TITLE
Name field for some Athena records doesn't have proper value.

### ISSUE THREAD

**Issue by saigopip26** [OHDSI/Vocabulary-v5.0#1064]
**Describe the problem in content or desired feature**
There are certain records in athena where the Name/concept_name field is set to either NA or None. These records lack a defined concept, which may affect our data integrity and reporting capabilities.
 
**How to find it:**
Search the below mentioned concept_ids in athena 
Example:  3425575,	45941644,	35941375,	40198731,	35918947,	714711,	35941962,	35941400,	35941750,	35941894,	35941270,	35922743,	35925788,	35922738,	36311145,	45878582,	1332721,	42001286,	4124462,	45880107,    8497 .
 
**Expected adjustments**
Query from our side is are these valid records. If yes, why they do not have the proper name. Need confirmation on the Name value for the corresponding records.
 
**Screenshots:**  
Please refer to the attached screenshots for some of the concept_ids
![Capture_1](https://github.com/user-attachments/assets/e8b255c4-7741-4311-9334-ac96c93748ab)
![Capture_2](https://github.com/user-attachments/assets/77ea71e2-2a86-4ff2-8001-26f16996996e)

**Comment by TinyRickC137** [comment]
Dear @saigopip26 

The names are not set to NA or None. The values you see are coming directly from the sources of the vocabularies. In other words, the above-mentioned concepts have the name 'None' in the sources.
