### ISSUE TITLE
Missing CPT4 Vocabulary Records

### ISSUE THREAD

**Issue by saigopip26** [OHDSI/Vocabulary-v5.0#1065]
**Describe the problem in content or desired feature**

We have recently updated the OMOP concept, relationship, and ancestor index using the Athena bundle zip containing 70 vocabularies. We actually included CPT4 as well in the bundle zip but somehow the CONCEPT excel file obtained from the bundle zip doesn't have any records of CPT4 vocabulary.
 
Details:

Update Performed: OMOP concept, relationship, and ancestor index

Vocabulary Affected: CPT4

Impact: The absence of these records in Concept index may significantly affect our data in ancestor index
 
**How to find it**

After update we found 74390 records odd records in ancestor but the same are not present in Concept index .. And when searched in Athena they were of CPT4 Vocabulary 

Below are some of the concept ids for your reference: 45888554,45889768,45890498,45887890,45889768,46257627,45888007
 
**Expected adjustments**

Could you please investigate the cause of the missing CPT4 vocabulary records? 

If there are any steps we can take to rectify this issue or if a new approach is available, that information would be greatly appreciated.
 
 
**Screenshots**

Please find the attached screenshots for your reference.
 
**Additional context**

We have even downloaded CPT4 vocabulary file as a separate but couldn't find any CPT4 vocabs inside its CONCEPT excel file as well..

 
![Bundle_zip_70_vocabs_CONCEPT](https://github.com/user-attachments/assets/1458b543-e2a8-4c99-a15e-520d6917dd6b)
![Capture_3](https://github.com/user-attachments/assets/e86558a7-406e-41a0-a4c0-78cbae727b07)
![Capture_4](https://github.com/user-attachments/assets/8b51af78-3b7d-406b-be59-95446303966f)
![Capture_5](https://github.com/user-attachments/assets/5a31a9ef-989d-4ebd-b41a-622028042db3)
![CPT4_Vocab_CONCEPT_file](https://github.com/user-attachments/assets/84ccee21-18aa-48c0-b7b1-bbc1d23a57eb)

**Comment by don-torok** [comment]
Did you run cpt4.jar per the readme.txt?

**Comment by TinyRickC137** [comment]
Dear @saigopip26 
As @don-torok suggested, you should use the cpt4.jar as described in readme.txt

This is not an issue of the vocabularies.
