### ISSUE TITLE
\" in concept names

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Vocabulary-v5.0#107]
In many concept names in the RXNorm Extension vocab there is a "...\\".." pattern. This creates problems when loading the vocab with JCDMBuilder and probably also when loading with SQL. 

For example:

43684848	"100 MG Bitter orange oil 0.1 MG/MG / Humulus lupulus whole extract 0.2 MG/MG / Melissa officinalis flowering top extract 0.15 MG/MG / Peppermint preparation 0.15 MG/MG / ... Oral Powder [Beruhigungstee I] by Pfingstweide-Apotheke Juergen Duerrwang e. K.\\"	Drug	RxNorm Extension	Marketed Product	S	OMOP822985	20160701	20991231	"

It stars with a " and ends with a " and had \\" in the middle. This creates a concept name that is longer than 255 characters.

Vocab version: 30-DEC-2016. RxNorm Extension 20161223

**Comment by cgreich** [comment]
Peter. 

Not sure what you mean. When you say \" is that an escaped quote? I.e., a quote inside a quoted string? I don't see that in your example. The first quote is at the beginning, the second at the end of the string. And if you cut them off, you should be exactly at 255. We go to extraordinary efforts to make sure that shoving these endless lists of ingredients into the concept_name will not cut off the Durg Form (Oral Powder), Brand Name (Beruhigungstee I) and the supplier (Pfingstweide-Apotheke).

**Comment by PRijnbeek** [comment]
yes, it is a problem of redering at this website \\ is also an escape here I have added a extra one now you see it in the issue

**Comment by cgreich** [comment]
So, let's not use these characters at all, because I am confused.

Are you complaining about the presence of quotes, or slashes, or triple dots in concept_name?

**Comment by dimshitc** [comment]
100 MG Bitter orange oil 0.1 MG/MG / Humulus lupulus whole extract 0.2 MG/MG / Melissa officinalis flowering top extract 0.15 MG/MG / Peppermint preparation 0.15 MG/MG / ... Oral Powder [Beruhigungstee I] by Pfingstweide-Apotheke Juergen Duerrwang e. K."

@cgreich, if you look on this concept, name looks like that
so in the original dataset we don't use backslashes

**Comment by cgreich** [comment]
I think what Peter is saying is that he doesn't like the quote in the string. Because it screws up the delimiters. Correct?

**Comment by PRijnbeek** [comment]
:0 

The problem is that there is a backslash before the quote after Duerrwang e. K.

**Comment by PRijnbeek** [comment]
![img_3353](https://cloud.githubusercontent.com/assets/7252105/22896576/0329065e-f221-11e6-9cfe-df163e03ae7e.JPG)

So the concept_name starts with a quote than has backslash quote at the end of the concept name and there is again a quote at the end of the line. Maybe you cut the concept_name to 255 just before a single quote?

Do i make sense now?

**Comment by cgreich** [comment]
Oh. You do. Two problems here:
1. Your loader cannot escape the combination of backslash and quote properly. It should be translated into a quote.
2. There shouldn't be quotes like that.

The first problem is yours. The second ours. :)

**Comment by PRijnbeek** [comment]
Well.. I think the loader (=JCDMBuilder) is probably escaping it correctly because there is a quote at the start of the conceptname and all the way at the end of the line after invalid_reason. These should not be there.

I also posted an issue on JCDMBuilder to double check this.

**Comment by cgreich** [comment]
After invalid_reason? I doubt it.
Look: The string in the CSV file is "Long German Drug\\"".
Your loader should read it into the field as Long German Drug"

**Comment by cgreich** [comment]
Obviously, the quote at the end is semantically wrong, but not syntactically.

**Comment by PRijnbeek** [comment]
[quote-issue.txt](https://github.com/OHDSI/Vocabulary-v5.0/files/772092/quote-issue.txt)

see this file which is taken directly from the concept.csv file I got from ATHENA.

There is a quote all the way at the end of the line!

**Comment by schuemie** [comment]
Actually, it is my bad. The quote at the end of the line is inserted by Usagi. Usagi first sorts the file by concept ID before using it, and during the sort it both reads and writes every row. Usagi has a problem with the sole trailing quote at the end of the concept name.

For now, the quickest workaround is extracting the concept.csv file from the Athena zip file again, and overwriting the sorted concept.csv file.

**Comment by PRijnbeek** [comment]
Aha ☺

So after unzipping the Athena zip file and using the folder for USAGI the files are changed by USAGI which results in the problem for JCDMBuilder.

Would still recommend to remove the trailing quotes in the vocab.

Thanks

**Comment by cgreich** [comment]
Phew. 

Trailing quotes in the names, you mean, Peter? Yes, it is already in the backlog.
