### ISSUE TITLE
concept_relationship records drop compared to Aug 2023 version

### ISSUE THREAD

**Issue by xj2193** [OHDSI/Vocabulary-v5.0#1076]
Hi we recently downloaded Aug 2024 vocabulary and ran Tantalus on the new version compared with Aug 2023 vocab version. And the results show there's about 15% records drop in the newest relationship table.

<img width="1134" alt="Screenshot 2024-12-02 at 4 32 07 PM" src="https://github.com/user-attachments/assets/6b5cc113-4461-4613-976e-46b59d960581">

I also checked specifically the row count drop on 'is a' and 'maps to' relationships.

<img width="756" alt="Screenshot 2024-12-02 at 4 54 36 PM (1)" src="https://github.com/user-attachments/assets/a03747a8-72b5-4550-b10e-7ef057868d0b">

Is the scope of the row drops expected?

**Comment by aostropolets** [comment]
It is. In Feb we deduplicated identical entries in dm+d and SNOMED UK module, hence the drop. I didn't remember it but here's how I figured out: 
I went to release notes https://github.com/OHDSI/Vocabulary-v5.0/releases and looked at the Standard concept changes table for Aug release. No big counts, so I proceeded to Feb release. There I saw 186,074 dm+ds loosing their mappings to SNOMED and becoming standard. Then I looked up dm+d in the release notes text and found an explanation.

While dm+d is not relevant for you guys, you can also confirm my assumption above by looking at changes stratified by vocabulary.

**Comment by xj2193** [comment]
@aostropolets that makes sense, thank you!
