### ISSUE TITLE
Compatibility for deprecated concepts in CONCEPT_ANCESTOR? (question)

### ISSUE THREAD

**Issue by dsbader** [OHDSI/Vocabulary-v5.0#108]
I see that the convenience table CONCEPT_ANCESTOR is limited to standard and valid concepts, however, I'm interested in providing some backwards-compatibility for deprecated concepts. I.e., Roll-up a deprecated concept to its former ancestor concepts, even though the relationship may now be invalidated.

Is there a SQL script or any documentation that I could use to try to replicate the logic used for generating CONCEPT_ANCESTOR?

**Comment by cgreich** [comment]
@dsbader:
Yes. https://github.com/OHDSI/Vocabulary-v5.0/blob/master/Final_Assembly/concept_ancestor.sql.

**Comment by dsbader** [comment]
Thanks Christian
