### ISSUE TITLE
Discrepancy in HIPAA place of service

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#109]
Originally described [here](http://forums.ohdsi.org/t/discrepancy-hipaa-place-of-service-codes/2153)

There seems to be some discrepancy that needs correction. Could we please correct them.

Here is the full list of HIPAA place of service codes https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set.html

[ATLAS Search - HIPAA place of service codes.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/840221/ATLAS.Search.-.HIPAA.place.of.service.codes.xlsx)

The most recent vocabulary file information for HIPAA place of service codes is attached:

They are incomplete or inaccurate -

Incomplete
02	Telehealth	The location where health services and health related services are provided or received, through a telecommunication system. (Effective January 1, 2017)
19	Off Campus-Outpatient Hospital	A portion of an off-campus hospital provider based department which provides diagnostic, therapeutic (both surgical and nonsurgical), and rehabilitation services to sick or injured persons who do not require hospitalization or institutionalization. (Effective January 1, 2016)

27-30	Unassigned	N/A
but are in the vocabulary as assigned. They are incorrectly assigned as
![image](https://cloud.githubusercontent.com/assets/13936600/23884905/25e09d2a-0846-11e7-9509-194762a428b4.png)

35-40	Unassigned	N/A
incorrectly assigned as
![image](https://cloud.githubusercontent.com/assets/13936600/23884909/2c37fda8-0846-11e7-935f-8aec5a385675.png)

82-98	Unassigned	N/A
incorrectly assigned as
![image](https://cloud.githubusercontent.com/assets/13936600/23884917/396345a0-0846-11e7-9ba2-81046026f21a.png)

**Comment by cgreich** [comment]
@gowthamrao:

Not sure why those unassigned were assigned. The source we had had them assigned. But why would we take them out? We need Inpatient Long-term Care and Adult Living Care Facility. 

I'll add 02 and 19.

But generally: These places of service are an artefact of the CMS system, where they worry about the funding mechanism, but not the way healthcare is delivered. What is a "Federally Qualified Health Center"? How is that "federal qualification" useful for any analytical use case. What's an "Independent Clinic"? "Independent Laboratory"? The other ones are dependent? "Indian Health Service Free-standing Facility" and "Tribal 638 Free-standing Facility"? "Mobile Unit"? "Office"? How do all of these work with international data?

We need something better.

**Comment by gowthamrao** [comment]
We just need to take the source code value out. I.e. keep 8979, 8892, 8882, 8677 concept id. Just take out the mapping to 27, 28, 35 and 95 HIPAA place of service. Change the vocabulary to OMOP vocabulary.

The ETL expert uses the mapping to joins between the string source code to integer concept id. If we don't clean it, this is burden if technical debt.

Agreed, we need something better. The HIPAA place of service is a 'dirty' vocabulary.

**Comment by gowthamrao** [comment]
In the change, can we also make source code to characters? I.e. '02' instead of 2? The letting zero is part of the source code value.

**Comment by cgreich** [comment]
I can't take codes out. Every concept has to have a code. I cannot trace where they came from, and whether that was local code in some state. I can make them OMOP though.

It is "02". If you import it to Excel it takes the leading zeros off. I have learned the hard way to never use Excel for any of that, because it constantly is trying to be smart.

**Comment by gowthamrao** [comment]
Can we make 27, 28, 35, 95 as invalid? They dont exist in CMS Hipaa place of service https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set.html

**Comment by cgreich** [comment]
@gowthamrao:

Why does that bother you? If they don't show up in the data, it doesn't matter. If they do, let people use them.

We'll add 18.

**Comment by ericaVoss** [comment]
Looks like 18 still doesn't exist in 20171201 and I'm not sure if we were going to invalidate the other codes but they are still valid.

```{sql}
SELECT *
FROM CONCEPT
WHERE CONCEPT_CODE IN (
	'27', '28', '35', '95', /*invalid?*/
	'18' /*missing*/
)
AND VOCABULARY_ID = 'Place of Service'
```

**Comment by gowthamrao** [comment]
@dimshitc 

18 is still not added :)

**Comment by dimshitc** [comment]
@gowthamrao , thanks for reminder. We'll add

**Comment by ericaVoss** [comment]
@dimshitc  and @aostropolets still missing in 20180609

**Comment by cgreich** [comment]
Will fix together with the [Place of Service clean-up](http://forums.ohdsi.org/t/care-sites-and-specialty-specialty-code-clean-up/4538/6).

**Comment by TinyRickC137** [comment]
[Changed a lot](https://forums.ohdsi.org/t/new-comprehensive-hierarchy-for-providers-visits-and-place-of-service-specialty-care-site/5633) since 2018
