### ISSUE TITLE
Vocab_ID = Domain, Note?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#110]
Should there be a "Note" in the VOCABULARY_ID = 'Domain'

**Comment by cgreich** [comment]
Yes. Added.

**Comment by ericaVoss** [comment]
Could we get the CONCEPT_ID . . . updating and ETL right now.

**Comment by cgreich** [comment]
5085

**Comment by cgreich** [comment]
How did you do that??? :)

**Comment by ericaVoss** [comment]
What the thumbs up?  Look to the right of each post, there is a smiley face, you just click on it.  :)

**Comment by ericaVoss** [comment]
I see this concept exists in 20170503.  Thank you @cgreich !
