### ISSUE TITLE
Duplicated OMOP Generated Codes

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#113]
These look like pure duplicates:

45756774	Female Pelvic Medicine and Reconstructive Surgery
45756773	Female Pelvic Medicine and Reconstructive Surgery

**Comment by cgreich** [comment]
True. Killing the first.

**Comment by ericaVoss** [comment]
I see that 45756774 is now INVALID_REASON = 'U' in Vocab 20170503.  This issue should now be closed.

```{SQL}
SELECT *
FROM CONCEPT
WHERE CONCEPT_ID IN (
45756774,	
45756773	
)
```
