### ISSUE TITLE
ATC and RxNorm 42707371-Clonidine Hydrochloride 0.15 MG Oral Tablet

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#114]
The RxNorm `42707371-Clonidine Hydrochloride 0.15 MG Oral Tablet` should map to ATC `C02AC01` however it looks like the relationship has been deprecated.

```{SQL}
SELECT c.concept_ID, c.CONCEPT_NAME, 
	cr.*, 
	c1.concept_id, c1.concept_name, c1.concept_code
FROM CONCEPT_RELATIONSHIP cr
	JOIN CONCEPT c
		ON c.concept_id = cr.concept_id_2
		AND c.CONCEPT_CODE = 'C02AC01'
	JOIN CONCEPT c1
		ON c1.concept_id = cr.concept_id_2
WHERE cr.CONCEPT_ID_1 = 42707371
```

However the WHO still suggests this should still be an active map.
https://www.whocc.no/atc_ddd_index/?code=C02AC01&showdescription=yes

I found some other codes that seem to be exhibiting the same behavior however I did not investigate them all:
`1517912
19019301
19101800
19133614
19133621
19133622
19133654
19134555`

**Comment by cgreich** [comment]
We need to fix the ATC mappings. Will get back.

**Comment by ericaVoss** [comment]
In Vocab 20170503 there is just no relationship now which leads me to believe this should remain open.

**Comment by ericaVoss** [comment]
Just noting this still exists in 20170920

**Comment by ericaVoss** [comment]
Just noting this still exists in 20171201.

**Comment by cgreich** [comment]
@dimshitc has a small ATC working group.

**Comment by ericaVoss** [comment]
Sorry for the harassment, but still exists in 20180609

**Comment by clairblacketer** [comment]
Still exists in 20181119

**Comment by cgreich** [comment]
Very soon.
