### ISSUE TITLE
Bug in CONCEPT_ANCESTOR construction for combination products in RxNorm mapping up to ATC classes

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#119]
We have an issue with CONCEPT_ANCESTOR constructor for how combination products are pulling in ingredients that roll up to drug class.

Ex:   pioglitazone (http://www.ohdsi.org/web/atlas/#/concept/1525215) is an ingredient that has 'inferred class of '  'Thiazolidinediones' (http://www.ohdsi.org/web/atlas/#/concept/21600779).   If I look at all ingredients with 'inferred class of' to TZD, the lists looks correct.   However, if I look at what ingredients fall under TZD when I use the CONCEPT_ANCESTOR table, I see that ingredients that are part of combination products with an ingredient that has 'inferred class of' incorrectly get picked up.  So, in this example, metformin is incorrectly classified as TZD (presumably because there is a RxNorm clinical drug of metformin+pioglitazone)  (see by filtering here on RxNorm ingredients, 3 make sense, 3 don't: http://www.ohdsi.org/web/atlas/#/concept/21600779)

Awhile back, we had a solution for making sure we only used 'inferred class' ingredients and did not use all combination ingredients in constructing the CONCEPT_ANCESTOR table.  However, it appears this bug has crept back in, and this produces a lot of problems for any conceptset defined using ATC/ETC classes that involves a query on the DRUG_ERA table.

**Comment by cgreich** [comment]
This is already being fixed right now. We are testing.

**Comment by ericaVoss** [comment]
Has this been fixed?

**Comment by cgreich** [comment]
Nope. Still working on the ATC problem. there is a Working Group now, led by Hamed.
