### ISSUE TITLE
SPL vocabulary needs to be refreshed

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#120]
We need to use LAERTES to create negative controls for our all of population-level effect estimation studies.  In order to refresh LAERTES, we need the vocabularies that contain the component data to be up-to-date in the vocabulary.  One piece of LAERTES comes from the structured product labels, but we need the ability to map from SPL_ID to RxNorm CONCEPT_ID.   The current ATHENA vocabulary has not refreshed SPL vocabulary since Oct2015, but current labels and newly marketed drugs are needed.  Can we bump this up the priority list for upcoming vocabulary release?

**Comment by cgreich** [comment]
Will do.
