### ISSUE TITLE
CONCEPT_ANCESTOR table inconsistencies

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#121]
Not all drugs roll up directly to their ATC ancestors, but they do in a two-step approach. For example, 'Diclofenac 35 MG Oral Capsule [Zorvolex]' is not a descendant of NSAIDS:
```sql
SELECT * FROM concept_ancestor WHERE ancestor_concept_id = 21603933 AND descendant_concept_id = 44507534;
--zero rows
```
But diclofenac is a descendant of NSAIDS:
```sql
SELECT * FROM concept_ancestor WHERE ancestor_concept_id = 21603933 and descendant_concept_id = 1124300;
--ancestor_concept_id	descendant_concept_id	min_levels_of_separation	max_levels_of_separation
--21603933	1124300	3	3
```
and 'Diclofenac 35 MG Oral Capsule [Zorvolex]' is a descendant of diclofenac:
```sql
SELECT * FROM concept_ancestor WHERE ancestor_concept_id = 1124300 and descendant_concept_id = 44507534;
--ancestor_concept_id	descendant_concept_id	min_levels_of_separation	max_levels_of_separation
--1124300	44507534	2	2
```

There are quite a few drugs like this:
```sql
SELECT COUNT(*)
FROM concept descendant
LEFT JOIN (SELECT * FROM concept_ancestor WHERE ancestor_concept_id = 21603933) concept_ancestor
ON descendant_concept_id = descendant.concept_id
WHERE descendant_concept_id IS NULL
AND standard_concept = 'S'
AND descendant.concept_name LIKE '%Diclofenac%';
--1000
```

**Comment by ericaVoss** [comment]
Testing in 20180609

Looks like this problem still exits and now has increased with RxNorm Extension.  That last query now pull 6843 rows.

**Comment by cgreich** [comment]
So, two things:

1) With ATC, the hierarchy is not complete, meaning, the son of your son may not be your grandson. The reasons is this: ATC defines ingredients in combination with indications, forms or strength. For example, an opthalmological doxycyclin cream has doxycyclin as the descendant, and doxycyclin has some systemic solution for injection as a descendant. And yet ophthalmological doxycyclin does not have that systemic injection solution as a descendant.

2) We are fixing this right now. It's a construction zone. Hamed Abedtash has a [Working []([](Group](http://forums.ohdsi.org/t/atc-working-group-meeting-agenda-and-minutes/4394/10))) solving this problem as we speak.

Makes sense?

**Comment by cgreich** [comment]
The Working Group is here: http://forums.ohdsi.org/t/atc-working-group-meeting-agenda-and-minutes/4394/10
