### ISSUE TITLE
CPT4 21 a Modifier?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#127]
Is this CPT4 supposed to be a CONCEPT_CLASS_ID = 'CPT4 Modifier'?

```{SQL}
SELECT *
FROM CONCEPT
WHERE CONCEPT_CODE = '21'
AND VOCABULARY_ID = 'CPT4'
```

CONCEPT_CLASS_ID = 'CPT4' currently.

**Comment by cgreich** [comment]
Why not?

**Comment by ericaVoss** [comment]
Ugg - I'm in 20161218 maybe my copy is outdated?

**Comment by cgreich** [comment]
Oh, I see. Let me see.

**Comment by dimshitc** [comment]
@ericaVoss , no, the current vocabulary version also has this, 
I'm just curious, how'd you find this issue? - just routinely checked up the vocabulary or was there some use case, i.e. found it in a patient data?

@cgreich , so we need to make some kind of manual update because this '21' is deprecated in 2004 year and generic update will not pick this up.

**Comment by ericaVoss** [comment]
I double checked too, this issue exists in 20170503.

@dimshitc - Most of the errors I find are when we are building CDMs and something looks weird.  In this case I think I was testing mapping procedures to standards in the Vocabulary and noticed the 2-digit code when we were specifically excluding modifiers from the map.  

I also test the Vocabularies every time we adopt a new one (like I'm doing now, we want to go from 20161231 to 20170503).  I also have a lame test script that I run that isn't finding too much any more.  Additionally I go through the issue log and check things.

**Comment by ericaVoss** [comment]
Actually looks like there is a whole bunch of them in 20170920, however they are all listed as invalid.

```{SQL}
SELECT *
FROM CONCEPT
WHERE VOCABULARY_ID = 'CPT4'
AND LEN(CONCEPT_CODE) <= 2
AND CONCEPT_CLASS_ID = 'CPT4'
```

I'm not familiar with the CPT4 modifier Vocabulary, do codes deprecate over time?  Should we treat them like NDCs or DRGs?  Should all the codes above be associated to CONCEPT_CLASS_ID = 'CPT4 Modifier'

**Comment by ericaVoss** [comment]
I'm guessing we could close this issue as they are all listed as invalid?  (tested in 20171201)

**Comment by ericaVoss** [comment]
@aostropolets should we just close this issue?  All these concepts have been deprecated.

**Comment by aostropolets** [comment]
Sure, I will
