### ISSUE TITLE
New Type Concepts

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#128]
There are type concepts that would be useful in US claims when the position of a drug or procedure is unknown:

1. Diagnosis from claim
2. Procedure from claim

**Comment by cgreich** [comment]
@clairblacketer:

Agreed. We have a proposal to disentangle these anyway in the WG. We should discuss it there.

**Comment by ericaVoss** [comment]
Just noting that I don't think we have what we are looking for in 20170920 yet.

```{SQL}
SELECT *
FROM CONCEPT
WHERE CONCEPT_NAME LIKE '%claim%'
AND (CONCEPT_NAME LIKE '%diagnosis%' OR CONCEPT_NAME LIKE '%procedure%')
```

**Comment by ericaVoss** [comment]
@clairblacketer or @cgreich I'm assuming this will go in with the list of concepts Clair is keeping?  I don't see them in 20171201.

**Comment by ericaVoss** [comment]
Testing 20180609

I see this `44818705-Inferred from procedure claim` as a type concept but specifically listed as a `Device type`.  Would it make sense to have one that is generic or from procedure type?

Nothing like `Diagnosis from claim` though.

@clairblacketer I know you are handling a list, are these on there?

**Comment by mik-ohdsi** [comment]
@clairblacketer - Just reviewing open issues: We have a couple of "claims" type concepts now in the new [vocab](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Vocab.-TYPE_CONCEPT). I guess you agree that we can close this issue, right?
