### ISSUE TITLE
Anemia is a Measurement?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#129]
I noticed that Anemia is not a MEASUREMENT in 20170503, is this correct?

**Comment by cgreich** [comment]
There is no such concept_id.

But in general, Anemia, Proteinuria and all those measurements can also be used as a diagnosis. We are trying to make sure they all exist twice going forward.

**Comment by dimshitc** [comment]
@cgreich , 20170503 means release date, not ID:)
"Proteinuria and all those measurements can **also** be used as a diagnosis", according to https://github.com/OHDSI/Vocabulary-v5.0/issues/80 last two comments it should be **only** diagnoses, and as @olenakalashnikova said LOINC concepts will be measurements.
BTW, closest SNOMED parent of "271737000 anemia" is "38292009 red blood cell disorder", so SNOMED itself treats Anemia as a disease/diagnosis. So should we change the domain definition?

**Comment by pbr6cornell** [comment]
the issue is this snomed concept was in condition domain and is now in
measurement domain.  if this was a deliberate change, we need to understand
why it moved.  my general inclination is this should remain a condition.

**Comment by ericaVoss** [comment]
Sorry for the poorly logged issue - the VOCAB ID = 03-MAY-2017 and the CONCEPT_ID = 439777.

Yes, and as Patrick said it used to be a CONDITION and now it is a MEASUREMENT.  We wanted to understand why this might have changed to understand if we should be expecting other similar changes.

**Comment by OlenaKalashnikova** [comment]
I really want to have one rule for all the concepts of this type. So then do not get confused. We do not have concepts like "Measurement" in SNOMED. I'd like it to be CONDITION.

**Comment by dimshitc** [comment]
You know, the problem here, that SNOMED changed it's hierarchy and now **Anemia** is a "child" of "Measurement finding (finding)", so it's correct according to out domain definition algorithms. 
Once we make some unambiguous decision on it, we'll inform you

**Comment by ericaVoss** [comment]
Related to issue #130

**Comment by ericaVoss** [comment]
Looks like it has gone back.

```{SQL}
SELECT CONCEPT_ID, CONCEPT_NAME, DOMAIN_ID
FROM CONCEPT
WHERE CONCEPT_ID = 439777
```

```
CONCEPT_ID	CONCEPT_NAME	DOMAIN_ID
439777	Anemia	Condition
```

It is good that we understand why something like this happens so thank you for the thread above.  I'm going to closed however since it is back in the domain we want it to be in.
