### ISSUE TITLE
Ancestry shows drugs as descendent of conditions

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#13]
Code used to identify an unusual finding:

select     a.*, 

                                                                b.concept_name as descendant_name, 

                                                                c.concept_name as ancestor_name 

                                                                

from 

         REF_OMOP_VOCAB..CONCEPT_ancestor a

         left outer join 

         REF_OMOP_VOCAB..concept b

    on a.descendant_concept_id = b.concept_id

                                left outer join 

         REF_OMOP_VOCAB..concept c

    on a.ancestor_concept_id = c.concept_id

    

    where a.ancestor_concept_id = 4352270

**Comment by cgreich** [comment]
Fixed
