### ISSUE TITLE
Broken link for vocab documentation

### ISSUE THREAD

**Issue by wibeasley** [OHDSI/Vocabulary-v5.0#131]
Hi.  The link in the readme is broken.
```
If you do want to recreate the vocabulary please find the step-by-step description here: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:vocabulary:vocabulary_creation_etl_process
```

![screenshot 2017-07-21 at 9 22 24 pm](https://user-images.githubusercontent.com/1372890/28487647-be876750-6e5a-11e7-8c7d-f9c5f955a465.png)

**Comment by aostropolets** [comment]
Right, you should use readme in a vocabulary's folder, for instance 
https://github.com/OHDSI/Vocabulary-v5.0/blob/master/UMLS/readme.md for UMLS.
When it comes to drug vocabularies please look at http://www.ohdsi.org/web/wiki/doku.php?id=documentation:international_drugs

**Comment by ericaVoss** [comment]
@wibeasley or @aostropolets  could we please close this issue?
