### ISSUE TITLE
Missing NDCs

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#132]
There are some NDCs for drugs that were approved in the US in 2016 that are not in the 20170503 vocabulary. These are : 
```sql
0074057928
0074056114
0074056607
0074056111
0074056611
0074057611
0074057622
```

There are RxNorm concepts for these drugs: 

concept_id|	concept_name|	domain_id|	vocabulary_id	|concept_class_id|	standard_concept|	concept_code|	valid_start_date|	valid_end_date	|invalid_reason
:---|:---|:----|:----|:---|:---|:---|:---|:---|:---
36249440|	venetoclax Oral Product	|Drug	|RxNorm	|Clinical Dose Group|	C	|1747558	2016-08-01|	2099-12-31|	NULL
36249441|	venetoclax Pill|	Drug|	RxNorm|	Clinical Dose Group|	C	|1747559	|2016-08-01	|2099-12-31	|NULL|
36249442|	Venclexta Oral Product|	Drug|	RxNorm	|Branded Dose Group|	C|	1747565	|2016-08-01	|2099-12-31|	NULL|
36249551|	Venclexta Pill	|Drug|	RxNorm	|Branded Dose Group|	C|	1747566|	2016-08-01	|2099-12-31|	NULL|
35604606|	{14 (venetoclax 10 MG Oral Tablet [Venclexta]) / 21 (venetoclax 100 MG Oral Tablet [Venclexta]) / 7 (venetoclax 50 MG Oral Tablet [Venclexta]) } Pack [Venclexta Starting Pack]	|Drug	|RxNorm	|Branded Pack|	S|	1747580|	2016-05-02|	2099-12-31	|NULL|
35604209|	Venclexta|	Drug	|RxNorm|	Brand Name|	NULL	|1747562|	2016-05-02|	2099-12-31|	NULL|
35604776|	{14 (venetoclax 10 MG Oral Tablet) / 21 (venetoclax 100 MG Oral Tablet) / 7 (venetoclax 50 MG Oral Tablet) } Pack	|Drug	|RxNorm	|Clinical Pack|	S	|1747575|	2016-05-02|	2099-12-31	|NULL|
35604207|	venetoclax Oral Tablet|	Drug|	RxNorm|	Clinical Drug Form|	S	|1747560	|2016-05-02	|2099-12-31	|NULL|
35604205	|venetoclax	|Drug	|RxNorm|	Ingredient	|S|	1747556	|2016-05-02	|2099-12-31	|NULL|
35604211|	venetoclax Oral Tablet [Venclexta]	|Drug|	RxNorm|	Branded Drug Form|	S	|1747564	|2016-05-02	|2099-12-31|	NULL|
35604206|	venetoclax 100 MG	|Drug|	RxNorm|	Clinical Drug Comp|	S	|1747557|	2016-05-02	|2099-12-31	|NULL
35604216|	venetoclax 10 MG	|Drug|	RxNorm	|Clinical Drug Comp|	S	|1747571	|2016-05-02|	2099-12-31|	NULL|
35604218|	venetoclax 50 MG	|Drug	|RxNorm	|Clinical Drug Comp	|S|	1747573|	2016-05-02|	2099-12-31|	NULL
35604210|	venetoclax 100 MG [Venclexta]|	Drug |RxNorm	|Branded Drug Comp	|S	|1747563|2016-05-02|	2099-12-31|	NULL|
35604220	|venetoclax 10 MG [Venclexta]	|Drug	|RxNorm|	Branded Drug Comp|	S	|1747576	|2016-05-02|	2099-12-31|	NULL|
35604222|	venetoclax 50 MG [Venclexta]	|Drug	|RxNorm|	Branded Drug Comp|	S|	1747578|	2016-05-02	|2099-12-31	|NULL
35604208	|venetoclax 100 MG Oral Tablet|	Drug|	RxNorm|	Clinical Drug|	S|	1747561	|2016-05-02|	2099-12-31|	NULL|
35604217|	venetoclax 10 MG Oral Tablet	|Drug|	RxNorm	|Clinical Drug|	S	|1747572	|2016-05-02|	2099-12-31	|NULL|
35604219	|venetoclax 50 MG Oral Tablet|	Drug|	RxNorm|	Clinical Drug|	S|	1747574	|2016-05-02|	2099-12-31|	NULL|
35604212|	venetoclax 100 MG Oral Tablet [Venclexta]	|Drug|	RxNorm|	Branded Drug	|S	|1747567	|2016-05-02	|2099-12-31|	NULL|
35604221|	venetoclax 10 MG Oral Tablet [Venclexta]	|Drug|	RxNorm|	Branded Drug|	S	|1747577	|2016-05-02	|2099-12-31|	NULL|
35604223|	venetoclax 50 MG Oral Tablet [Venclexta]|	Drug|	RxNorm|	Branded Drug|	S	|1747579|	2016-05-02|	2099-12-31|	NULL|

That I found using this query:

```sql
SELECT * 
FROM CONCEPT
WHERE (CONCEPT_NAME like '%venetoclax%'
    OR CONCEPT_NAME LIKE '%VENCLEXTA%')
    AND VOCABULARY_ID = 'RxNorm'
```

**Comment by aostropolets** [comment]
We haven't updated NDC for quite a long time indeed. Need to take care of it.

**Comment by ericaVoss** [comment]
Just making a note that these haven't made it into 20170920

```{SQL}
SELECT *
FROM CONCEPT
WHERE CONCEPT_CODE IN (
'0074057928','0074056114','0074056607','0074056111','0074056611','0074057611','0074057622'
)
```

**Comment by dimshitc** [comment]
We are working on NDC update now,
interesting that we found concepts mentioned here:
http://forums.ohdsi.org/t/ndc-code-not-found-in-concept-table/3475
and they will be included in Monday, 18/12/17 release,
but concepts mentioned in this tread are still unavailable
