### ISSUE TITLE
Duplicate "Diffuse large B-cell lymphoma"?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#134]
Does it make sense to have 2 standard "Diffuse large B-cell lymphoma" in the CONDITION domain?

SELECT *
FROM CONCEPT
WHERE CONCEPT_ID IN (
44808122,4300704
)

**Comment by dimshitc** [comment]
Well, we keep UK and international versions of SNOMED. 404148006 code
belongs to international version, and 847741000000106 code - to UK. So this
is OK to have such a duplicates

2017-08-15 22:21 GMT+03:00 ericaVoss <notifications@github.com>:

**Comment by cgreich** [comment]
They will de-dup it over time, @ericaVoss. For us, there is no way to detect the dups and pick the right one. In this case it would be trivial, but SNOMED has more than this one.
