### ISSUE TITLE
Missing HCPCS Q5102

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#135]
I was looking for Q5102, which is a code used for billing a biosimilar drug: https://www.cms.gov/Medicare/Medicare-Fee-for-Service-Part-B-Drugs/McrPartBDrugAvgSalesPrice/Part-B-Biosimilar-Biological-Product-Payment.html

The code became effective April2016.

Can this be included in the next vocabulary, assuming our HCPCS feed does contain the code?  And if it doesn't, can we determine why it hasn't made its way to us yet?

**Comment by ericaVoss** [comment]
Checked for 20170920 and this has not made it in

```{SQL}
SELECT *
FROM CONCEPT
WHERE CONCEPT_CODE = 'Q5102'
```

**Comment by aostropolets** [comment]
Yep, preparing it to be released.

**Comment by ericaVoss** [comment]
This code is currently in Vocab 20171201.  @pbr6cornell  or @aostropolets  could you please close this issue?
