### ISSUE TITLE
GRR Gone?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#137]
Was the GRR Vocabulary dropped?  I had it in 20170503 but it is gone in 20170920.

**Comment by dimshitc** [comment]
well, it's there now.  
select count(*) from concept where vocabulary_id = 'GRR' and invalid_reason is null
;
I can't even imagine how did that happened that you couldn't find in a previous version

**Comment by ericaVoss** [comment]
@cgreich & @dimshitc would it make sense that I should have access to GRR?  I got it pulled once.  Could you check my access to ericaStanoch email.

**Comment by aostropolets** [comment]
Please try to request it on Athena

**Comment by cgreich** [comment]
@ericaVoss:

The new Athena will know. If not, just request, and we pass you through. No backend sneaking in anymore.

**Comment by ericaVoss** [comment]
@cgreich  and @dimshitc - I just went to ATHENA and I am not even allowed to select GRR.

![image](https://user-images.githubusercontent.com/6305439/33567012-d212eb0a-d8ef-11e7-8304-05a5526b6400.png)

**Comment by mpozhidaeva** [comment]
@ericaVoss - please try to request а license through the link "license required" on the right of the vocabulary name

**Comment by ericaVoss** [comment]
@mpozhidaeva first of all +1 on your SlowPoke icon.

I requested it as you said and then I think I broke ATHENA.  I got the following message and now can't get back into ATHENA.  :(

```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

**Comment by mpozhidaeva** [comment]
@ericaVoss - hello, thanks)
Your actions are right - but the next hour we will update vocabularies and Athena will be not available.
I'm really sorry - will inform you after the completion of work

**Comment by ericaVoss** [comment]
Okay, no problem!  I'm just doing some testing - I don't actually need the new Vocab at the moment.

**Comment by mpozhidaeva** [comment]
@ericaVoss - Athena is ready for use now. Your request of GRR was sent successfully and after accepting (you will receive an email notification) you can download GRR.

**Comment by aostropolets** [comment]
@ericaVoss  can we close it? :)

**Comment by ericaVoss** [comment]
I still can't download GRR, this is what it looks like now.  Mostly concerned to help with ATHENA testing, not so much that I need the Vocab.

![image](https://user-images.githubusercontent.com/6305439/41687060-688aa2ac-74b4-11e8-94d1-3f5d7b6f0c81.png)

**Comment by aostropolets** [comment]
Did you request the license? And did @cgreich approve?

**Comment by ericaVoss** [comment]
related to #143 

Yeah, in the image you can see it say "license requested", @cgreich is probably just ignoring my request!

**Comment by cgreich** [comment]
@ericaVoss: You got it.

**Comment by clairblacketer** [comment]
we can close this issue - this has been resolved.
