### ISSUE TITLE
LOINC: document how classes are organized

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#138]
I would like to implement analytical roll-up to LOINC classes.
I can see the new concepts in Athena.
E.g., here
http://www.ohdsi.org/web/atlas/#/concept/45876161
(and at the bottom)

Where can I find documentation on how is LOINC ingested into Athena?

exhibit 1
![image](https://user-images.githubusercontent.com/7526119/32067625-df24d32e-ba51-11e7-800d-9d9cbd8baf60.png)

**Comment by ericaVoss** [comment]
@vojtechhuser  - I think this is more of a forum question than an issue.  Mine pushing it over there?  Else I can do it for you.

**Comment by vojtechhuser** [comment]
@ericaVoss - let't do it this way - you do the initial post  (since you offered)  and I will chime in with support for it.

**Comment by ericaVoss** [comment]
Here you go:
http://forums.ohdsi.org/t/loinc-document-how-classes-are-organized/3773

**Comment by ericaVoss** [comment]
@vojtechhuser mind if we close this issue and allow the forum post to move forward?
