### ISSUE TITLE
Fix ICD-9 to SNOMED duplicate mappings

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#14]
There are duplicate mappings in ICD-9 to SNOMED:
201.20 Hodgkin's sarcoma, unspecified site, extranodal and solid organ sites - being cut into
437817 Hodgkin's sarcoma of extranodal AND/OR solid organ site
4038840 Hodgkin's sarcoma

**Comment by cgreich** [comment]
Fixed
