### ISSUE TITLE
HCPCS C9399, procedure or drug domain?

### ISSUE THREAD

**Issue by abedtashh** [OHDSI/Vocabulary-v5.0#140]
HCPCS C9399 code (Unclassified drugs or biologicals) is currently assigned DOMAIN_ID='Procedure'. There are other similar HCPCS codes that belong to 'Drug' domain, like 'J3490', 'J3590', 'J8999', 'J9999'. To be consistent, wouldn't it be more proper to move C9399 to 'Drug' domain?

**Comment by cgreich** [comment]
@abedtashh:

Correct. Will fix.

**Comment by ericaVoss** [comment]
Testing 20171201 obviously this hasn't been fixed yet but just making notes that I tested it in 20171201.

```{sql}
SELECT *
FROM CONCEPT
WHERE CONCEPT_CODE = 'C9399'
```

**Comment by aostropolets** [comment]
Fixed

**Comment by abedtashh** [comment]
C9399 code has changed to 'Drug' domain, so closing the issue. Thanks!
