### ISSUE TITLE
Weird CPT4 Codes

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#142]
In Vocab 20171201

This CPT4s looks weird to me.  They are too long or contain letters.
```{SQL}
SELECT *
FROM CONCEPT
WHERE CONCEPT_ID IN (
42627879,42627880,42627881,42627882,42627883,42627884,42627913,42627922,42627923,42627924,42627925,42627926,42627927,42627966,42627967,42627968,42627969,42627970,42627971,42627972,42627973,42627974,42627975,42628011,42628012,42628013,42628014,42628015,42628016,42628034,42628047,42628048,42628049,42628050,42628051,42628052,42628591,42628592,42628593,42628594,42628595,42628596,42628597,42628598,42628599,42628634,42628635,42628636,42628637,42628638,42628641,42628667,42628668,42628669,42628670,42628671,42628672
)
```

Examples:
```
1028561
0002U
1021869
```

**Comment by aostropolets** [comment]
Seem strange indeed. Will take a look.

**Comment by clairblacketer** [comment]
@ericaVoss @aostropolets I think the codes with letters are correct but the long ones look like place of service codes

**Comment by dimshitc** [comment]
@clairblacketer, you are right 
The source gives us them, so we need to keep them making them non-standard and make the mappings to the Place of Service vocabulary

**Comment by ericaVoss** [comment]
Testing in 20180609

Just a reminder @dimshitc - make these non-standard and make mappings to the POS Vocabulary

**Comment by cgreich** [comment]
Will fix that together with the [overhaul of the PoS](http://forums.ohdsi.org/t/care-sites-and-specialty-specialty-code-clean-up/4538/6).

**Comment by dimshitc** [comment]
well, those places of services are already non-standard:
SELECT *
FROM CONCEPT
WHERE CONCEPT_ID IN (
42627879,42627880,42627881,42627882,42627883,42627884,42627913,42627922,42627923,42627924,42627925,42627926,42627927,42627966,42627967,42627968,42627969,42627970,42627971,42627972,42627973,42627974,42627975,42628011,42628012,42628013,42628014,42628015,42628016,42628034,42628047,42628048,42628049,42628050,42628051,42628052,42628591,42628592,42628593,42628594,42628595,42628596,42628597,42628598,42628599,42628634,42628635,42628636,42628637,42628638,42628641,42628667,42628668,42628669,42628670,42628671,42628672
) and standard_concept ='S'
;
and yes, as @cgreich says, we'll build the mappings a bit later

**Comment by m-khitrun** [comment]
The mentioned places of service were [mapped over](https://athena.ohdsi.org/search-terms/terms?domain=Visit&standardConcept=Non-standard&vocabulary=CPT4&page=1&pageSize=500&query=) to the 'Visit' domain.
