### ISSUE TITLE
AMIS Vocab Gone?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#143]
In 20171201 I noticed AMIS vocabulary is gone.  I don't think we use this for anything but wondering if that is correct or a mistake.

**Comment by aostropolets** [comment]
@ericaVoss 
It is sitting in our database as it was :)
Seems to be the same problem as  #137

**Comment by ericaVoss** [comment]
Closing this as it is the same thing as #137
