### ISSUE TITLE
Scientific notation in Numeric data fields

### ISSUE THREAD

**Issue by abedtashh** [OHDSI/Vocabulary-v5.0#144]
**_Please convert scientific notations to decimal format in DRUG_EXPOSURE table_**

We are seeing a new change in numeric data fields of DRUG_STRENGTH table (OMOP vocab releases after September 2017) that numbers are shown in scientific notation instead of decimal notation. For example:
`41047447	40799107			1.5E7	8718		8587		20170824	20991231`
`42718551	40798622			5.0E-4	8576		8576	1	20170824	20991231`	
`41213571	40798584			1.06E-4	8576		8576	10	20170824	20991231`
`41295396	40798640	5.0E-7	8576						20170824	20991231`
`41128776	42899038			8.0E-4	8576		8587		20170824	20991231`
`41317281	43526082			2.5E-4	8576		8576		20170824	20991231`
`41128776	42899483			5.0E-4	8576		8587		20170824	20991231`

This is making some issues in our loading pipeline, and I'm not sure if the change was intentional. It would be great to keep these numbers in **"decimal format"** as it was before. So, the above records will be converted to these:
`41047447	40799107			15000000	8718		8587		20170824	20991231`
`42718551	40798622			0.0005	8576		8576	1	20170824	20991231`	
`41213571	40798584			0.000106	8576		8576	10	20170824	20991231`
`41295396	40798640	0.0000005	8576						20170824	20991231`
`41128776	42899038			0.0008	8576		8587		20170824	20991231`
`41317281	43526082			0.00025	8576		8576		20170824	20991231`
`41128776	42899483			0.0005	8576		8587		20170824	20991231`

Thanks!

**Comment by mpozhidaeva** [comment]
@abedtashh, hello - ok, will fix soon and inform your.

BR

**Comment by mpozhidaeva** [comment]
@abedtashh, I'm sorry for delay - now it seems fixed.

BR

**Comment by abedtashh** [comment]
@mpozhidaeva It if fixed now. Thank you!
