### ISSUE TITLE
cost concepts

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#147]
Please add cost concepts from [spreadsheets](https://docs.google.com/spreadsheets/d/1EMSNUkeW3ixLh8uHe_E8I3ambczmITsDBxVbZS1RBIM/edit?usp=sharing)
proposed and accepted here  https://github.com/OHDSI/CommonDataModel/issues/81

There is no mapping between concepts
There are no external codes  - these are omop-codes/omop-concepts

@dimshitc @cgreich 

Thank you!

**Comment by dimshitc** [comment]
done
