### ISSUE TITLE
Mismatched ICD-9/10-CM to standard concept mappings

### ISSUE THREAD

**Issue by abedtashh** [OHDSI/Vocabulary-v5.0#148]
I analyzed the mapping of a code list of malignant neoplasms of bronchus and lung neoplasm diagnoses in ICD-9-CM and ICD-10-CM to OMOP standard concepts, and found some of the codes are mapped to non-specific standard concepts, and in some cases mapped to a very specific concepts while the source code is unspecified. The original analysis was done on vocabulary version 2017-10-17, and double-checked with v. 2017-12-22.

### 44827555 | 162.9 | ICD9CM | Malignant neoplasm of bronchus   and lung, unspecified

v. 2017-10-17 mapped to: 4311499 | SNOMED | Primary malignant neoplasm of respiratory tract
v. 2017-12-22 mapped to: 4311499 | SNOMED | Primary malignant neoplasm of respiratory tract

This code can be mapped to more specific standard concepts instead of the higher level "Primary malignant neoplasm of respiratory tract" that includes 2 other unrelated concepts of "Primary malignant   neoplasm of trachea" and "Primary malignant neoplasm of upper   respiratory tract" (shown in the image below). The suggestion is to break this (and similar) concept to "lung" and bronchus" neoplasms. Thus, 162.9 ICD-9-CM code   may get mapped to "Malignant neoplasm of bronchus" and   "Malignant neoplasm of lung" under "Malignant neoplasm of   lower respiratory tract" standard concepts.

![image](https://user-images.githubusercontent.com/25333997/34631850-658f0c4c-f240-11e7-97f0-fe5633eaf63a.png)

### 1567486 | C34 | ICD10CM | Malignant neoplasm of bronchus and lung

v. 2017-10-17 mapped to: Mapped to 258375 | SNOMED | Overlapping malignant neoplasm of bronchus and lung
v. 2017-12-22 mapped to: Mapped to 40493428 | SNOMED | Malignant neoplasm of respiratory system

This  ICD-10-CM code was mapped to "Overlapping malignant neoplasm of bronchus and lung" in v2017-10-17 while it does not explicitly indicate overlapping (site) neoplasms, but it has children codes of C34.80-C34.82 specifically designed for this purpose. The   new mapping in v2017-12-22 still is not specific, and does not represent the   accurate semantic of the code. "Malignant neoplasm of respiratory   system" covers malignancy of other organs of respiratory system, as follows:
![image](https://user-images.githubusercontent.com/25333997/34632080-7856d78c-f241-11e7-817d-e4d1708b48c8.png)

It is not a billable code, so it will not affect data analysis; however, to be accurate, it is suggested to map the code to 2 separate  "Malignant neoplasm of bronchus" and "Malignant neoplasm of lung" standard concepts that represent both types of malignancies.

### 45581206 | C34.92 | ICD10CM | Malignant neoplasm of   unspecified part of left bronchus or lung

v. 2017-10-17 mapped to: 443388 | SNOMED | Malignant tumor of lung
v. 2017-12-22 mapped to: 4094876 | SNOMED | Malignant neoplasm of lower   lobe, bronchus or lung

This   ICD-10-CM code captures both bronchus and lung malignant neoplasms, but it was mapped to a "Malignant tumor of lung" in v2017-10-17 that only represents lung cancer, and does not include bronchial neoplasm. Only C34.9 is not a billable code, so it will not affect data analysis; however, other children codes are billable that need to be corrected. It is suggested to map the parent and children codes to 2 separate "Malignant neoplasm of bronchus" and "Malignant neoplasm of lung" standard concepts. 
Quick Note: SNOMED does not differentiate between right or left part of lung or bronchus.

The new mapping in v2017-12-22 still is not accurate as indicates a specific site   (lower lobe) of malignancy of bronchus and lung neoplasms, while the ICD code   is "unspecified".

**Comment by dimshitc** [comment]
Hi @abedtashh 

Thanks for tracking this, 
We know about the idea of mapping to a several concepts if we have some "OR" source concept.
Look, if we map  **Malignant neoplasm of bronchus and lung, unspecified** to a "**Malignant neoplasm of bronchus**" and "**Malignant neoplasm of lung**", which standard concept should we put into CDM?

If we put both concepts into CDM it will mean that patient had **Malignant neoplasm of lung** and **Malignant neoplasm of bronchus** in the same time, while the patient had only one tumor, and we don't know which exact place it was. Thus we map to a more general concept in this case: Primary malignant neoplasm of respiratory tract.
The same rule applies for other cases you described.

so, actually for this case:
v. 2017-10-17 mapped to: 443388 | SNOMED | Malignant tumor of lung
v. 2017-12-22 mapped to: 4094876 | SNOMED | Malignant neoplasm of lower lobe, bronchus or lung
correct mapping was in a previous version. 
Need to be fixed.

And of course our approach is not perfect as we lose granularity. We have been thinking a lot about this, but haven't found any better solution.
We would be happy, if you suggest some

**Comment by abedtashh** [comment]
Thanks @dimshitc. I totally agree with you no perfect approach exists to map ICD codes to SNOMED concepts, in particular if the goal is one-to-one matching. 

You're right. It may not be a good practice to map "OR" concepts to multiple SNOMED concepts because we do not know exactly which organ was involved. So, we need to find a better match for ICD-10-CM codes of C34.90-C34.92. 

But, in case of ICD-9-CM code of 162.9 (Malignant neoplasm of bronchus and lung, unspecified) that represents both lung and bronchus joined together with "AND", it would make sense to map it to both lung and bronchial malignant neoplasms. Otherwise, it gets easily fallen out of code list to select lung cancer patients with the current, very broad mapped SNOMED concept.

Let me review more codes, and will get back to you in few days with better suggestions about "OR" concepts. @cgreich let us know if you have any suggestions.

Thanks!

**Comment by dimshitc** [comment]
> But, in case of ICD-9-CM code of 162.9 (Malignant neoplasm of bronchus and lung, unspecified) that represents both lung and bronchus joined together with "AND"

ah. typical trap of ICD-9-CM:) saying "AND" they mean "OR", so the doctors encode any localization cancer in this case, look:
http://www.icd9data.com/2014/Volume1/140-239/160-165/162/162.9.htm

The decision allows us to represent OR relationship is SNOMED Extension.
We have a discussion on the forum: 
http://forums.ohdsi.org/t/condition-mapping-improvement-using-snomed-extension-proposal/3880/15
