### ISSUE TITLE
Pharmacy visits

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#149]
Two new concepts are requested based on the discussion here
http://forums.ohdsi.org/t/pharmacy-claims-drug-exposure-how-to-identify-the-dispensing-billing-pharmacy/3795/14

**Comment by gowthamrao** [comment]
Request 

concept id | Concept_Code | Concept Name | Domain | Vocabulary | Concept_Class | Standard
-- | -- | -- | -- | -- | -- | --
  | OMOP generated | Visit derived from encounter on pharmacy claim | Type Concept | Visit Type | Visit Type | S
  | OMOP generated | Pharmacy visit | Visit | Visit | Visit | S


@cgreich @gklebanov

**Comment by cgreich** [comment]
For Type Concept, why not 44818517 "Visit derived from encounter on claim"

**Comment by gowthamrao** [comment]
makes sense @cgreich . so we don't need 'Pharmacy visit' Type Concept? We only need to request one concept_id


concept id | Concept_Code | Concept Name | Domain | Vocabulary | Concept_Class | Standard
-- | -- | -- | -- | -- | -- | --
  | OMOP generated | Pharmacy visit | Visit | Visit | Visit | S

Makes it even easier and cleaner. Only one concept_id needed.!

**Comment by dimshitc** [comment]
done. 
concept_id = 581458
