### ISSUE TITLE
Multiple mappings of NDC codes to RxNorm

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#15]
There appear to be some NDC codes that map to multiple RxNorm concepts.  I would have expected a 1-to-1 relationship, unless it was a combination drug that could only be mapped to the component ingredients, but this query shows other examples.

select c1.concept_code, count(8) from concept_relationship r, concept c1, concept c2 where 1=1

and relationship_id='Maps to' and r.invalid_reason is null

-- and r.concept_id_1=9229 

and c1.concept_id=r.concept_id_1 

and c2.concept_id=r.concept_id_2 

and c1.vocabulary_id='NDC' and c2.vocabulary_id='RxNorm'

group by c1.concept_code having count(8)>1;

**Comment by ericaVoss** [comment]
@cgreich or @pbr6cornell  - this doesn't seem to be a bug any more, please close the issue.

**Comment by cgreich** [comment]
It's fixed.
