### ISSUE TITLE
plasme typo in lab concept name

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#150]
see details here
https://github.com/OHDSI/OMOP-Standardized-Vocabularies/issues/11

(posted in the wrong repo)

**Comment by ericaVoss** [comment]
Testing in 20180609

Still a problem with CONCEPT_NAME

```sql
SELECT *
FROM CONCEPT
WHERE CONCEPT_ID = 	3001784
```

`Free/Total PSA serum/plasme`

True name found here:
[Prostate Specific Ag Free/​Prostate specific Ag.total in Serum or Plasma](https://r.details.loinc.org/LOINC/12841-3.html?sections=Comprehensive)

**Comment by vojtechhuser** [comment]
+1 on keeping it on the radar


I would also like to know from where come the concept descriptions for LOINC. For ThemisObservations and ThemisUnits work

**Comment by cgreich** [comment]
@aostropolets, @dimshitc: Can you poke LOINC and have them fix it?

**Comment by vojtechhuser** [comment]
In LOINC version 2.38 I see this long common name 
![image](https://user-images.githubusercontent.com/7526119/42600596-ea24ca5e-8530-11e8-9e4c-16596895fcb7.png)

**Comment by clairblacketer** [comment]
This looks to be fixed and the issue can be closed

**Comment by Alexdavv** [comment]
> This looks to be fixed and the issue can be closed

Indeed
