### ISSUE TITLE
"Porfimer Sodium" case: Are all 'Precise Ingredient' concepts non-standard?

### ISSUE THREAD

**Issue by abedtashh** [OHDSI/Vocabulary-v5.0#153]
@dimshitc 
RxNorm has "Porfimer Sodium" (CID: 19090420) only as a 'Precise Ingredient', and there is no 'Ingredient' concept_class_id. The current logic is "At ingredient level, only class_id=Ingredient concepts are standard" (correct me if I'm wrong). But, "Porfimer Sodium" is one of 814+ cases that only appear as 'Precise Ingredient' in RxNorm, and no other 'Ingredient' level record is available. So, suggesting to make an exception in these cases, and mark them as "standard" concepts.

**Impact:**
When selecting drugs to define a cohort, we look up ingredient names and filter the query to DOMAIN_ID='Drug' and VOCABULARY_ID='RxNorm' and STANDARD_CONCEPT='S' and INVALID_REASON is null. If only 'Precise Ingredient' exists for the matched drug ingredient name, it gets filtered out from the query result since no 'Precise Ingredient' is standard.
Also, there is no descendent is available in CONCEPT_ANCESTOR for these concepts. It would be very helpful to populate the info for these, too.

**Other cases:**
I just looked at the latest release of RxNorm, and there are more than 814 RXCUIs having 'Precise Ingredient' with no 'Ingredient' atomic concepts.

**Comment by dimshitc** [comment]
"Porfimer Sodium" 
is linked to 
Form of (RxNorm) | Dihematoporphyrin Ether | 19089602
http://athena.ohdsi.org/search-terms/terms/19090420
;
All Precise ingredients are linked to Ingredients by relationship_id ='Form of'

**Comment by ericaVoss** [comment]
Should this issue be closed?
