### ISSUE TITLE
Visit type - professional, pharmacy, facility

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#156]
We have the following Visit type concept id

concept_id | concept_name | concept_class_id | standard | domain_id | vocabulary_id
-- | -- | -- | -- | -- | --
44818517 | Visit derived from encounter on claim | Visit Type | S | Type Concept | Visit Type
44818518 | Visit derived from EHR record | Visit Type | S | Type Concept | Visit Type
44818519 | Clinical Study visit | Visit Type | S | Type Concept | Visit Type

In US healthcare, claims are generally of the following type
1. Facility medical claim
2. Professional medical claim
3. Pharmacy claim

All these three may be considered descendants of 

concept_id | concept_name | concept_class_id | standard | domain_id | vocabulary_id
-- | -- | -- | -- | -- | --
44818517 | Visit derived from encounter on claim | Visit Type | S | Type Concept | Visit Type

So, is it possible to add three new concepts for Facility medical claim, Professional medical claim, Pharmacy claim to visit types?
Would it be also possible to create a hierarchy among them?

@cgreich

**Comment by cgreich** [comment]
@gowthamrao: I see no reason why not, if it helps you. Make sure you talk to the right Themis group so they won't come up with something else.

**Comment by dimshitc** [comment]
@gowthamrao  please ping me directly, if you decide to add these to the vocabulary

**Comment by gowthamrao** [comment]
We are requesting the following new concept_id's 
See discussion here http://forums.ohdsi.org/t/duplicate-diagnosis-themis-wg3/3966/21
This is a hierarchy/concept ancestor relationship.

concept_id | concept_name | concept_class_id | standard | domain_id | vocabulary_id | descendant of
-- | -- | -- | -- | -- | -- | --
44818517 | Visit   derived from encounter on claim | Visit   Type | S | Type   Concept | Visit   Type |  
  | Visit   derived from encounter on medical claim | Visit   Type | S | Type   Concept | Visit   Type | 44818517
  | Visit   derived from encounter on medical facility claim | Visit   Type | S | Type   Concept | Visit   Type | Visit   derived from encounter on medical claim
  | Visit   derived from encounter on medical professional claim | Visit   Type | S | Type   Concept | Visit   Type | Visit   derived from encounter on medical claim
  | Visit   derived from encounter on vision claim | Visit   Type | S | Type   Concept | Visit   Type | 44818517
  | Visit   derived from encounter on dental claim | Visit   Type | S | Type   Concept | Visit   Type | 44818517
44818518 | Visit   derived from EHR record | Visit   Type | S | Type   Concept | Visit   Type |  
  | Visit derived from EHR billing record | Visit   Type | S | Type   Concept | Visit   Type | 44818518
  | Visit derived from EHR encounter record | Visit   Type | S | Type   Concept | Visit   Type | 44818518
