### ISSUE TITLE
Change domain from 'Place of service' to 'Visit'

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#158]
http://forums.ohdsi.org/t/visit-vs-place-of-service/4006/

- Vocabulary Place of Service belongs to the domain Place of Service and is used to populate place_of_service_concept_id in the care_site table.
- Vocabulary Visit belongs to the domain Visit and is used to populate Visit_concept_id.
- Vocabulary Place of Service is mapped to Visit in both concept_relationship and concept_ancestor table (I dont know how complete this is @Dymshyts ?) Place of Service is a child of Visit
- There is a n:1 relationship between visit_occurrence table and care_site table - so there may not be more than one care_site_id per visit_occurrence_id record. As an extension, there may not be more than one place_of_service_concept_id per visit_occurrence_id.
- Vocabulary Place of Service belongs to the domain Place of Service and is used to populate place_of_service_concept_id in the care_site table.
- Vocabulary Visit belongs to the domain Visit and is used to populate Visit_concept_id.
- Vocabulary Place of Service is mapped to Visit in both concept_relationship and concept_ancestor table (I dont know how complete this is @Dymshyts ?) Place of Service is a child of Visit
- There is a n:1 relationship between visit_occurrence table and care_site table - so there may not be more than one care_site_id per visit_occurrence_id record. As an extension, there may not be more than one place_of_service_concept_id per visit_occurrence_id.

Would it then be reasonable to add all the concept's in Place of Service vocabulary from Place of Service domain into Visit domain, as a standard_concept and maintain hierarchical relationship?

I wanted to ask - of the 59 standard and about 487 total concept's in the Place of Service domain, can we change their domain to visit - so that they may be used in the visit_occurrence table as either visit_concept_id and visit_source_concept_id?

The classification of visit's into inpatient and outpatient is then natural using the concept ancestor table

@dimshitc

**Comment by dimshitc** [comment]
I got the idea, in a few words:
Why do we need to have both "Visit" and "Place of cervice" if "Place of cervice" is enough as it has relationship to Visit?

@cgreich , should we make these changes?
- I would add the relationships to the hierarchy (there are 12 Place of Service aren't linked to a Visit)
and change from Place of Service domain into Visit domain

**Comment by gowthamrao** [comment]
Yes, change domain from place of service to Visit. We don't need the domain place of service

**Comment by dimshitc** [comment]
Actually, I have doubts:
CARE_SITE 
place_of_service_concept_id describes type of the clinic, i.e. Rural Clinic, Mental asylum, etc.

VISIT_OCCURRENCE 
Visit_concept_id describes type of visit: in or out-patient, ER

So you suggest to populate place_of_service_concept_id and Visit_concept_id with the same concept, say place_of_service_concept_id = "Inpatient Psychiatric Facility" 
Visit_concept_id = "Inpatient Psychiatric Facility"

instead of 
place_of_service_concept_id = "Inpatient Psychiatric Facility" 
Visit_concept_id = "Inpatient "
?

Can this change be confusing for the people used to  "in- or out-patient, ER" visit IDs?

**Comment by cgreich** [comment]
I'll answer in the Forum. Let's not have two places.

**Comment by dimshitc** [comment]
done
