### ISSUE TITLE
UCUM Concept code does not match concept name

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#159]
Concept id 45890995; Concept name = Million unit per liter; Concept code = 10*6.[U]/mL
The concept code indicates Million units per milliliter, not liter.

Logging for @don-torok, he found it

**Comment by dimshitc** [comment]
fixed, so in the next release it will be ok

**Comment by shinjinaka** [comment]
Concept id 9688; Concept name = microgram per hour per minute; Concept code = ug/kg/min. 
The concept code indicates microgram per kilogram per minute, not hour.

**Comment by cgreich** [comment]
Thanks. Will fix to "microgram per kilogram per minute".
