### ISSUE TITLE
Provenance of conditions

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#160]
Based on the discussion here: http://forums.ohdsi.org/t/duplicate-diagnosis-themis-wg3/3966/21

I propose 2 more condition_type_concept_ids be created.

EHR billing diagnosis
EHR encounter diagnosis
 
Code = OMOP generated
Class = Condition Type
Domain = Type Concept
Vocabulary = Condition Type
Standard concept = S

Use case: The current standard concepts from the Condition Type class include: EHR Chief Complaint, EHR Episode Entry, EHR problem list entry, and Observation recorded from EHR. None of these provide the necessary granularity to distinguish between conditions from billing tables and conditions from encounter tables in the EHR. 

@cgreich @dimshitc

**Comment by cgreich** [comment]
Why do you care again?

**Comment by MelaniePhilofsky** [comment]
Sometimes our local data requestors want encounter dx and and sometimes they want billing dx. The same Visit for one diagnosis can produce two different codes (one billing and one encounter). Providers generally want their cohorts defined by the dx the provider gave, not what was billed to the insurance company. Utilization of services looks more to the billing dx. We need both and we need to distinguish the provenance.

**Comment by cgreich** [comment]
Sounds good. @dimshitc, can you?

**Comment by dimshitc** [comment]
Sure, I can. Put it in a backlog

**Comment by dimshitc** [comment]
done
