### ISSUE TITLE
Not place of service vocabulary

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#161]
http://www.ohdsi.org/web/atlas/#/conceptset/1730004/details

These OMOP generated concept_id's have the vocabulary_id 'Place of Service', but they are OMOP generated and don't belong to the CMS place of service vocabulary
https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set.html

concept id| code | Name
-- | -- | --
581381 | OMOP generated | Emergency Room Critical Care Facility
581383 | OMOP generated | Inpatient Cardiac Care Facility
581379 | OMOP generated | Inpatient Critical Care Facility
581382 | OMOP generated | Inpatient Intensive Care Facility
581384 | OMOP generated | Inpatient Nursery
581399 | OMOP generated | Interactive Telemedicine Service
581385 | OMOP generated | Observation Room
581380 | OMOP generated | Outpatient Critical Care Facility

**Comment by dimshitc** [comment]
Yeah, these concepts don't belong to the CMS place of service vocabulary. But for some project in the past we needed them. 
Does it make some problems now?

**Comment by gowthamrao** [comment]
Does not make problems. Just found it during QC
