### ISSUE TITLE
Pain concepts

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#162]
Please add concepts for standardized pain scores as discussed [http://forums.ohdsi.org/t/n-pass-nips-cpot-wilda-pain-scales/4039](url)

I've attached a csv with the concept names and their relationships to one another. I've also added suggested standard concept ids for the relationships from the concept relationship table. 
[Pain concept sets 4 OHDSI .xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/1764341/Pain.concept.sets.4.OHDSI.xlsx)

@dimshitc

**Comment by dimshitc** [comment]
few questions for you before we add it to the vocabulary:
1. please, give the link to the source, so we indicate the reference
2. do the source give some codes for each question?

**Comment by MelaniePhilofsky** [comment]
I could not find a source coding system for these pain scales. I checked SNOMED, LOINC, and Google. All I have found are scholarly articles contributing to the validity of the scales.

**Comment by dimshitc** [comment]
I mean some source
like "National Pain association" - I just made it up:)
where did you take those concepts?

**Comment by MelaniePhilofsky** [comment]
I took the pain scales from my source data and then did a look up in Atlas, LOINC, and SNOMED. When they weren't present in those coding systems, I went to Google and found scholarly articles and educational material on how to use the pain scales. Here's [one](https://www.uwhealth.org/healthfacts/parenting/7711.pdf) about the NIPS pain scale. The pain associations/groups/organizations don't have much info on pain scales that are used in hospital. They have scales related to consumer advocation when interacting with the medical community.

**Comment by cgreich** [comment]
@MelaniePhilofsky:

The scales must be somewhere, Melanie. Want to send an email to the authors of these papers? How would we otherwise get them in?

**Comment by MelaniePhilofsky** [comment]
@cgreich ,

"How would we otherwise get them in?"

 Same way we are putting "Intensive Care" into the Place of Service domain :)  Add them in as an OMOP generated vocabulary, designate the concept names I suggested (located on the csv which matches the literature), designate a concept_id, give them relationships, and fill in the attributes for each. These panels are not contained in any standardized code set, so we/OMOP need to own them. Ok?

**Comment by cgreich** [comment]
@MelaniePhilofsky:

True. We could. But it looks like these N-PASS, CPOT, NWBN, NIPS and CNPI are panels that exist, and Melanie didn't just pull them out of her sleeve. If so, let's get the official proper source.

**Comment by MariaRohozhkina** [comment]
Hi all! While we have implemented this issue, several scales have already been introduced in other vocabularies:

N-PASS:  [Pain/agitation panel NPASS](https://athena.ohdsi.org/search-terms/terms/36032392)
NIPS:  [Neonatal infant pain scale panel](https://athena.ohdsi.org/search-terms/terms/1617433)
CNPI: [CNPI](https://athena.ohdsi.org/search-terms/terms/1991786)

Therefore, in this v20230531 release, we have only added CPOT. Please, find new concepts [using this link](https://athena.ohdsi.org/search-terms/terms/722042).
