### ISSUE TITLE
CMS Place of Service code 1-9 should have leading zero

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#163]
CMS Place of Service codes 1-9 have a leading zero in CMS Documentation.  Vocabulary is inconsistent, there is '02' for Telehealth, but the other single digit codes do not have a leading zero.

**Comment by gowthamrao** [comment]
Agree. I think it's being fixed

**Comment by dimshitc** [comment]
Yes, all such a concepts have leading zero now, 
We'll release this version of the vocabulary tomorrow

**Comment by dimshitc** [comment]
done
