### ISSUE TITLE
US SNOMED codes not in vocabulary

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#164]
Attached is a list of SNOMED codes from our EHR that do not have matches in the vocabulary.
[US_SNOMED_codes_4_OMOP.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/1776374/US_SNOMED_codes_4_OMOP.xlsx)

**Comment by dimshitc** [comment]
done
