### ISSUE TITLE
Missing ICD10PCS Codes

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocabulary-v5.0#165]
When is the next update of ICD10 procedure codes? Our data has many missing code. Here's an example of a few that seem to be new:

3E0P3VZ
099680Z
09BQ8ZX
09BQ8ZZ
09BW8ZZ
0BD88ZX
0BDC8ZX
0BDF8ZX
0BR847Z

**Comment by dimshitc** [comment]
Thanks for noticing, 
we're working on update,
Next release is expected on the next week, it'll include new ICD10PCS concepts

**Comment by cukarthik** [comment]
Great. The sooner the better for us. Since we are in need of those codes to reload our OMOP instance. Thanks!

**Comment by cukarthik** [comment]
Just following up to see if a new version of the vocabulary was released addressing this issue :)

**Comment by dimshitc** [comment]
done
