### ISSUE TITLE
ICD-9 440.24 doesn't map to gangrene

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#166]
[ICD-9 440.24 (Atherosclerosis of native arteries of the extremities with gangrene)](https://athena.odysseusinc.com/search-terms/terms/44831256) does not map to [gangrenous disorders](https://athena.odysseusinc.com/search-terms/terms/439928), but it should.

**Comment by schuemie** [comment]
This one is similar:
[ICD-9 440.4 (Chronic total occlusion of artery of the extremities)](https://athena.odysseusinc.com/search-terms/terms/44825448) maps to "Arteriosclerosis of artery of extremity" instead of "Chronic occlusion of artery of extremity" (44782819).

Interestingly, the equivalent [ICD10 concept](https://athena.odysseusinc.com/search-terms/terms/45596247) is mapped correctly.

**Comment by dimshitc** [comment]
ok. thanks, we'll schedule the ICD9CM review
