### ISSUE TITLE
'TRUETEST GLUCOSE TEST STRIPS' doesn't map to right standard concepts.

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocabulary-v5.0#167]
When I run the  below code:

```
SELECT cr.concept_id_1, c1.concept_name, cr.concept_id_2, c2.*
FROM concept c1
  left JOIN concept_relationship cr ON c1.concept_id = cr.concept_id_1 AND cr.relationship_id = 'Maps to'
  left JOIN concept c2 ON c2.concept_id = cr.concept_id_2
WHERE c1.concept_name = 'TRUETEST GLUCOSE TEST STRIPS'
```

I see that TRUETEST GLUCOSE TEST STRIPS  maps to CHROMIUM PICOLINATE 0.4 MG Oral Tablet and a few other that do not seem correct.

**Comment by dimshitc** [comment]
Oh, seems that source gives us this relationship. So we need to make the comprehensive algorithm of finding such an issues. Will keep you in touch

**Comment by aostropolets** [comment]
fixed. @cukarthik you also need to add cr.invalid_reason is null not to get old deprecated 'Maps to'
