### ISSUE TITLE
Weird CONCEPT_NAMES

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#171]
Do others have the following text for these CONCEPT_IDs:
`4164770,254443`

![image](https://user-images.githubusercontent.com/6305439/38253280-4709e674-3724-11e8-9630-66c2e4f5e996.png)

Text looks like it got garbled, but not sure if it is just a bad load on our part.

Thanks to Rupa for finding this!

**Comment by dimshitc** [comment]
on my instance it's fine:
Sjögren's syndrome, 
Guillain-Barré syndrome

**Comment by ericaVoss** [comment]
Got it, looks like we had a loading issue.  Thank you!
