### ISSUE TITLE
Celsius in UCUM is wrong

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#173]
This concept has wrong concept code

http://www.ohdsi.org/web/atlas/#/concept/8653

![image](https://user-images.githubusercontent.com/7526119/39478219-c72b18ca-4d2f-11e8-8b4d-93eb57758a7f.png)

change [degC] into cel in Concept code.

![image](https://user-images.githubusercontent.com/7526119/39478243-d91aa8a2-4d2f-11e8-9846-c8f8bab5e2f5.png)

**Comment by cgreich** [comment]
See http://forums.ohdsi.org/t/ucum-code-for-celsius-doesnt-match-ucum-specs/4363/5.
