### ISSUE TITLE
Histrelin: Missing NDC relationships to RxNorm

### ISSUE THREAD

**Issue by abedtashh** [OHDSI/Vocabulary-v5.0#174]
The relationships from the below NDCs to RxNorm are missing:

Histrelin | 62157007801 | AX PHARMACEUTICAL - histrelin acetate powder
Histrelin | 75839014201 | HISTRELIN ACETATE - histrelin acetate powder

**Comment by abedtashh** [comment]
@aostropolets Yes, I do that I'll send them to you. I also noticed we do not track recycled NDCs in the vocabulary. Is that true? I have a list for the recycled too.

**Comment by aostropolets** [comment]
Correct, as a vocabulary can only have the unique codes. Therefore, we can’t, for example, store one recycled code as dead and the same new code with a different meaning as alive one.
I remember a discussion about that; people eventually came to an agreement that it wasn’t a big issue

**Comment by cgreich** [comment]
@aostropolets: We said  that we will create a list like that outside as a THEMIS thing. Remember? Tammy or Olivier have a list like this to get started with.

**Comment by aostropolets** [comment]
It doesn’t mean we can’t keep gathering more. Just means that further data will go to a second iteration, right? Or we had something else in mind?

**Comment by cgreich** [comment]
The idea is because it is so rare it makes no sense to change the way the vocabulary system works (no duplicate concept_code). And for those who care about those NDCs they can put in a separate ETL script based on this list. Let's create that list.
