### ISSUE TITLE
Duplicate ICDO3 Code - 9342/3

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#176]
In Vocabualry 20180609 there is source code duplicated:

`
9342/3-Odontogenic carcinosarcoma
`

The two CONCEPT_IDs are:
`36402927, 44498515`

![bitmoji](https://render.bitstrips.com/v2/cpanel/7e3bc453-64fb-4a34-bcaa-481724e5d3d9-f9de47cd-e918-4b50-831d-d887a6386e5f-v1.png?transparent=1&palette=1&width=246)

**Comment by aostropolets** [comment]
Yeah. It's due to a space in the end of one of the codes.
Will fix when updating ICDO
