### ISSUE TITLE
Add CHECK for invalid_reason values

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#181]
moving [CDM issue](https://github.com/OHDSI/CommonDataModel/issues/192) here as I think it fits better. 

Would be great to add CHECK constraint for limiting the number of values which could be put into invalid_reason field of concept table. Somehow we got the picture below, which could be preserved by the presence of the constraint. 

![image](https://user-images.githubusercontent.com/12911960/42181921-8c1dffa2-7e0a-11e8-94c3-a7fc80c8aa5c.png)

tagging @pavgra

**Comment by aostropolets** [comment]
Thanks, Clair! It fits better here indeed

**Comment by aostropolets** [comment]
done
