### ISSUE TITLE
AllOfUs OMOP concepts violating no-duplicative axiom for OMOP Vocab

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#182]
If 'Never' or 'Not at all' are answers and have OMOP concept code, there should be just one such concept for an answer.

Similarly to LOINC has only one code for Yes and answer (LA-xxxx)
Snomed also has only one code for 'daily' 
   Daily (qualifier value) SCTID: 69620002

Many AllOfUs terms violate that assumption.

See example here:
http://athena.ohdsi.org/search-terms/terms?vocabulary=PPI&conceptClass=Answer&page=1&pageSize=15&query=not+al+all

![image](https://user-images.githubusercontent.com/7526119/43337203-1eb46dc0-91a1-11e8-914c-511ae33cf158.png)

**Comment by vojtechhuser** [comment]
frequency is

![image](https://user-images.githubusercontent.com/7526119/43337840-d4d96d5c-91a2-11e8-9cdb-4f9504589ff7.png)

**Comment by aostropolets** [comment]
Correct. It was done on purpose: to ensure the ability to recognize the meaning of "Not at all" and not to mix up answers to different questions. If you take a look at the codes, you'll see the actual representations of the questions.

**Comment by vojtechhuser** [comment]
Can we re-open this issue. I don't think this 'on purpose' approach is right.

 We must change something in our model or content to fix the problem.
