### ISSUE TITLE
"Inhalation" not a "Route of administration value" in SNOMED

### ISSUE THREAD

**Issue by abedtashh** [OHDSI/Vocabulary-v5.0#184]
After looked up "Inhalation" [(45956874)](http://athena.ohdsi.org/search-terms/terms/45956874) in SNOMED on UMLS, I noticed the concept is not a "Route" but a "unit of product usage". We have it right now under "Route of administration value" ([4106215](http://athena.ohdsi.org/search-terms/terms/4106215)) concept which seems incorrect according to UMLS. I also could not find any concept with code [18679011000001101](http://athena.ohdsi.org/search-terms/terms/45956874) in SNOMED. 

If you look up "Inhalation" in UMLS, there are other terminologies like NCI denoting "inhalation" as a route of administration, but the reference in OMOP vocabulary is SNOMED not NCI.

One probable cause might be that "Inhalation" is a synonym of a "Route of administration value" child, but I could not find one. 

The closest concept to what we know as inhalation route is "Intrapulmonary route" ([4169270](http://athena.ohdsi.org/search-terms/terms/4169270)), which NCI defines as "Administration of a substance in the form of a gas, aerosol, or fine powder via the respiratory tract, usually by oral or nasal inhalation, for local or systemic effect."

Should we remove "Inhalation" from "Route" domain?

**Comment by cgreich** [comment]
@abedtashh:

Inhalation as a unit is called "actuation" in RxNorm lingo. Like a puff of an inhaler. So, if it really is used as a unit then just use that.

**Comment by dimshitc** [comment]
@abedtashh , thanks for noticing this.
We take the descendants of "Route of administration value" (4106215) to define the Route concept set.
"Inhalation" (45956874) is a "Route of administration value" (4106215) descendant in UK-SNOMED extension.
look:
http://ontoserver.csiro.au/shrimp/?concept=18679011000001101&system=http://snomed.info/sct&versionId=http://snomed.info/sct/999000031000000106/version/20180321
In the OHDSI vocabulary SNOMED vocabulary is a mix of SNOMED international and UK SNOMED.
So technically "Inhalation" (45956874) has domain_id = 'Route' is right

**Comment by aostropolets** [comment]
Actually, most of inhalants target bronchi; inhalation is more generic name than intra-pulmonary and in the same time more convenient

**Comment by dimshitc** [comment]
Thanks, @aostropolets 
so it means that we need to leave our routes as is
@abedtashh , what do you think?

**Comment by abedtashh** [comment]
@aostropolets @dimshitc  Inhalers and nebulizers are used to deliver drugs in forms of powder, liquid, gas, aerosol, or emulsion to lower respiratory tract including bronchi and lungs. Some act locally like bronchodilators for treating asthma but some systemically like inhalable insulin. Basically "Intrapulmonary" and "Inhalation" are technically synonyms as both indicate "delivering drugs by inhaling air (or breathing) into lungs and bronchi", so both can be used for e.g., "salmeterol inhaler" products that may make confusions/inconsistencies across CDMs.
Since "Intrapulmonary" route has the "Intrabronchial" child in SNOMED hierarchy meaning "administration of a drug within bronchi", I suggest to either:

- Pick "Inhalation" as the Standard concept for "administration of drugs in forms of powder, liquid, gas, aerosol, or emulsion to lower respiratory tract" AND put "Intrapulmonary" as a Classification concept.
- Or, make "Inhalation" non-standard AND keep "Intrapulmonary" as the only Standard route concept for such dose forms.

**Comment by aostropolets** [comment]
The first option sounds perfectly fine. You are absolutely correct in your explanation, I favor “Inhalation” only in terms of a name being wildely known

**Comment by abedtashh** [comment]
@aostropolets @dimshitc Great! I think the first option is the a good solution as well.

**Comment by m-khitrun** [comment]
Hello,

Just to let you know, the concept [Inhalation ](https://athena.ohdsi.org/search-terms/terms/45956874)was invalidated as it belongs to the retired SNOMED UK Drug Extension Module. It was mapped to the [Respiratory tract](https://athena.ohdsi.org/search-terms/terms/40486069) SNOMED route.

Regards,
Masha.
