### ISSUE TITLE
ATC INSULINS AND ANALOGUES Children?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#188]
Might be related to #100 

using Vocabulary 20180609

```sql
  SELECT  DISTINCT
  	'Insulin' AS CODE_LIST_NAME,
  	'Insulin' AS CODE_LIST_DESCRIPTION,
  	c1.CONCEPT_ID, c1.CONCEPT_NAME
  FROM CONCEPT_ANCESTOR ca
  	JOIN CONCEPT c1
  		ON c1.CONCEPT_ID = ca.DESCENDANT_CONCEPT_ID
  		AND c1.STANDARD_CONCEPT = 'S'
  WHERE ca.ANCESTOR_CONCEPT_ID IN (
  	21600713 /*INSULINS AND ANALOGUES*/
  )
  AND CONCEPT_ID = 	19009384 /*insulin human, isophane 70 UNT/ML / Regular Insulin, Human 30 UNT/ML Injectable Suspension [Humulin]*/
```

Why does the ATC 
`21600713 - INSULINS AND ANALOGUES` 

not pick up 
`19009384-insulin human, isophane 70 UNT/ML / Regular Insulin, Human 30 UNT/ML Injectable Suspension [Humulin]`

Tagging @alondhe

**Comment by aostropolets** [comment]
It has been a long road toward an ATC release that will cover most of the drugs and fix these holes; we see the light at the end of the tunnel. The release will be coming shortly
