### ISSUE TITLE
Create concepts for all CDM fields

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#191]
To support [CDM v6.0](https://github.com/OHDSI/CommonDataModel/blob/cdm_v6/Sql%20Server/OMOP%20CDM%20sql%20server%20ddl.txt) we need concepts created for all fields and tables that exist in the CDM with appropriate ancestor-child relationships created as well.

tagging @cgreich

**Comment by cgreich** [comment]
Initiated. I didn't incorporate Versions. Because that would make somebody's day job. So, OMOP tables and fields are just sitting there as concepts. Whether or not it's ok to refer to them within a certain OMOP CDM version is not enforced by the data.

**Comment by dimshitc** [comment]
They are added and linked to versions, see these two for example:

http://athena.ohdsi.org/search-terms/terms/1147070
http://athena.ohdsi.org/search-terms/terms/1147869
