### ISSUE TITLE
self harm codes mapping to accident 

### ISSUE THREAD

**Issue by jreps** [OHDSI/Vocabulary-v5.0#192]
I was trying to find a standard concept for the ICD10CM:
concept id 17639, code T36.8X2 -"Poisoning by other systemic antibiotics, intentional self-harm"
and noticed it maps to concept id 437760 "Accidental poisoning by antibiotic"

**Comment by dimshitc** [comment]
Thanks for reporting. We'll fix it and let you know when it's done.

**Comment by jreps** [comment]
Also (although not incorrect) the 
concept id 17627, code T36.6X2 "Poisoning by rifampicins, intentional self-harm" is currently mapping to concept id 4056726 , code 212509008 "Poisoning by rifampin"

but I found a map that may be more specific:
to concept id 4160669, code 291677005 "Intentional rifampin poisoning"

**Comment by dimshitc** [comment]
Yeah, the whole chapter will be reviewed.

I'm just curious, are you making some research on this? People rarely pay
attention to such a concepts.

**Comment by jreps** [comment]
Yeah, I was trying to use a published ICD9/ICD10 definition for Suicide, so I was looking to map that definition as closely as possible to SNOMED

**Comment by p-talapova** [comment]
We have already updated mapping from ICD10CM to SNOMED. All your remarks were taken into account. Thank you!

**Comment by p-talapova** [comment]
We have finally released such changes in mappings. You may find them in the Athena.
