### ISSUE TITLE
VMP and SNOMED CT duplication

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#196]
concept_code of  408036003 seems to be there twice.

(It could be on purpose.)

![image](https://user-images.githubusercontent.com/7526119/49752474-7c857500-fc7e-11e8-8a25-3b66db530305.png)

**Comment by cgreich** [comment]
Yes. dm+d gets also added into SNOMED. Neither is a standard concept, so no need for de-duplication.
