### ISSUE TITLE
Human t-cell lymphotrophic virus code to HIV SNOMED

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#198]
The ICD-9 code 079.51 for Human T-Cell lymphotrophic virus type I (concept_id [44821693](http://athena.ohdsi.org/search-terms/terms/44821693)) maps to SNOMED concept_id [4253472](http://athena.ohdsi.org/search-terms/terms/4253472). This SNOMED concept stands for Human Immunodeficiency Virus Type I, which is very different than HTLV-I.

**Comment by dimshitc** [comment]
Hi @clairblacketer thanks for noticing. and Happy New Year!
We are working on ICD9CM mapping improvement currently. This one is already fixed internally, it waits all corpus to be reviwed before going to release

**Comment by dimshitc** [comment]
Now it's mapped to 443540 Human T-lymphotropic virus 1 infection.

**Comment by clairblacketer** [comment]
@dimshitc Thanks!
