### ISSUE TITLE
Add groups to CVX

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Vocabulary-v5.0#199]
Add Is a relationship from a vaccine code to vaccine group code from here:
https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=vg

**Comment by dimshitc** [comment]
Will do. so, vaccine group codes will be added as Clasiffication concepts

**Comment by dimshitc** [comment]
Actually, we can't add these groups as hierarchical concepts directly
Please, look on here
![image](https://user-images.githubusercontent.com/8568959/58342500-32253880-7e59-11e9-983c-54547198f22e.png)

MMR stands for the combo Drug and it's "descendants" are mono-component.
So, it's opposite to the hierarchical principles used in OHDSI vocabulary.

**Comment by dimshitc** [comment]
So, we add the relationship_id='Has vaccine group (CVX)' to represent this information given by the source, but will build hierarchy manyually based on RxNorm principles mostly

**Comment by cukarthik** [comment]
That would be great for us at Columbia. Do we know when we could add these groups into the relationship? Thanks!

**Comment by cgreich** [comment]
> will build hierarchy
When?

**Comment by cukarthik** [comment]
Hi, just seeing when this would be added to the vocabulary? Thanks.

**Comment by cukarthik** [comment]
Just checking if this was incorporated into the vocabulary?

**Comment by cukarthik** [comment]
Hi, just checking if vaccine groups where added in the concept_relationship table. I did notice CVX-RxNorm mappings. @mik-ohdsi

**Comment by MariaRohozhkina** [comment]
I'm glad to inform you that in this v20230531 release ‘Has vaccine group’ relationships were added to help with vaccine grouping. Furthermore, the Vaccine Group concept class has been introduced, showcasing how a set of related vaccines can be organized into a family for easy reference.
