### ISSUE TITLE
Vocabulary Identification in VOCAB table

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#20]
Before in the VOCABULARY table there used to be

```{txt}
VOCABULARY_ID - VOCABULARY_NAME
0 - OMOP Vocabulary v4.5 20-Oct-2014
```

I do not believe this concept still exists in the VOCAB v5 version however it is extremely useful.  You could still have a VOCAB_ID = 0 with the VOCABULARY_NAME equal to the version ID.

**Comment by cgreich** [comment]
Still there. 

 

select vocabulary_version from vocabulary where vocabulary_id='None';

 

results in “v5.0 2014-10-15”.

 

C

**Comment by ericaVoss** [comment]
I see it now, thank you.
