### ISSUE TITLE
ICD-10 intentional self-harm codes do not map to self-harm standard concepts

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#200]
All T42.* codes reflecting intentional self-harm (e.g. [T42.6X2](http://athena.ohdsi.org/search-terms/terms/17977)) just map to 'Poisoning', so not reflecting the intentional self-harm nature.

In contrast, ICD-9 codes indicating self-inflicted poisoning (e.g. [E950.1](http://athena.ohdsi.org/search-terms/terms/44827266)) do map to ['Suicide deliberate poisoning'](http://athena.ohdsi.org/search-terms/terms/444362). 

Here are the ICD-10 codes I could find, but there are many more. It also holds true for some of the ancestors, for example T42.0X2:
T42.0X2A
T42.1X2A
T42.2X2A
T42.3X2A
T42.4X2A
T42.5X2A
T42.6X2A
T42.72XA
T42.8X2A
T42.0X2D
T42.1X2D
T42.2X2D
T42.3X2D
T42.4X2D
T42.5X2D
T42.6X2D
T42.72XD
T42.8X2D
T42.72
T41.1X2A

Probably a review of the whole T36-T50 range ('Poisoning by, adverse effect of and underdosing of drugs, medicaments and biological substances ') makes sense.

This issue is similar to [this one](https://github.com/OHDSI/Vocabulary-v5.0/issues/192), but is not yet resolved.

**Comment by schuemie** [comment]
It actually extends beyond that range. For example [T71.232 ("Asphyxiation due to being trapped in a (discarded) refrigerator, intentional self-harm")](http://athena.ohdsi.org/search-terms/terms/19205) just maps to ["Oxygen supply absent"](http://athena.ohdsi.org/search-terms/terms/313601). 

Just searching for the string "intentional self-harm" finds a lot of these.

**Comment by p-talapova** [comment]
Thanks for your report! We are going to fix inconsistency of these mappings in early February.

**Comment by dimshitc** [comment]
@p-talapova , where are we with this? can we close this one?

**Comment by p-talapova** [comment]
@dimshitc yes, we can.

@schuemie I wish to draw your attention to the concept codes given by you. All of them are ICD-10-CM codes, not ICD-10. But it is not a problem. Currently,  using the logic for the upcoming SNOMED Extension we fixed the most of such bugs in the 'T' chapter.  But it is so big (14 214 concepts), that its review will have to be repeated again in the future.

**Comment by p-talapova** [comment]
We have finally released such changes in mappings. You may find them in the Athena.
