### ISSUE TITLE
Athena URL in the README wrong

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#205]
Go to 
https://github.com/OHDSI/Vocabulary-v5.0/blob/master/README.md

It links out to:
http://www.ohdsi.org/web/athena

It should be:
http://athena.ohdsi.org

**Comment by aostropolets** [comment]
Thanks!

**Comment by ericaVoss** [comment]
I still see an issue with this . . . 
http://www.athena.ohdsi.org/

I think it needs to be:
http://athena.ohdsi.org/
