### ISSUE TITLE
CPT4.jar not processed concepts

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Vocabulary-v5.0#206]
When I run the cpt4.jar with my UMLS account i see this output:

 Updated CPT4 records: 15640, records to update: 0                        
 Not processed cpt4 concepts: 12454
 See not-processed-concepts.out file.
 Writing updated data to CONCEPT.csv
 CPT successfully updated.

1) What does this mean that most were not processed?
2) If I run the tool again to see if it was a network error etc. will it not add the CPT4 codes twice?
3) it says CPT successfully updated... is that really the case?? 

I use the 20190211 vocabulary version.

Thanks

**Comment by ssuvorov-fls** [comment]
Hello
1. An error occurred while interacting with the UMLS
2. No, duplicate records will be skipped
3. No, it only means that program finished without csv handling errors

**Comment by PRijnbeek** [comment]
Thanks,

So your suggestion is to keep trying? or is there a way to see the error?

**Comment by ssuvorov-fls** [comment]
No, unfortunatelly there is no way to see such errors.
Please, try again

**Comment by PRijnbeek** [comment]
Did it again twice with different results:

 Updated CPT4 records: 15640, records to update: 0                        
 Not processed cpt4 concepts: 9429
 See not-processed-concepts.out file.
 Writing updated data to CONCEPT.csv
 CPT successfully updated.

 Updated CPT4 records: 15640, records to update: 0                        
 Not processed cpt4 concepts: 13152
 See not-processed-concepts.out file.
 Writing updated data to CONCEPT.csv
 CPT successfully updated.

Since CPT 4 Codes are Standard concepts it is important this is fixed. (not sure we map to any of these but anyway).

I would i suggest to fix that message though since people may think it is successful and then end up with a different concept table.

@cgreich what do you think?

**Comment by cgreich** [comment]
@PRijnbeek:

Yes, we need to improve the error handling. The concepts should all be there, all the tool does is download the descriptions. This is a stop gap solution, and we have really no choice but using it. And in 99% of users it works, but obviously there is something going on here. My hunch is timing out. Will put it on the backlog.

**Comment by vojtechhuser** [comment]
For me it also ran super slow. I had to with half a day for all concepts to update.
AMA......... sigh.....

**Comment by Alexdavv** [comment]
https://github.com/OHDSI/Vocabulary-v5.0/issues/752
