### ISSUE TITLE
LOINC: sql file generic_update from step 15 is missing

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#208]
in LOINC/readme.md file - it says

> 15.  Run generic_update.sql (from working directory)

can  you please add instructions where this file is?

**Comment by dimshitc** [comment]
https://github.com/OHDSI/Vocabulary-v5.0/blob/master/working/generic_update.sql

it is said exactly "working directory". 
please suggest the way how to explain this properly

**Comment by cgreich** [comment]
It should say "Run generic_update.sql from the directory "Working". The "working directory" is the current directory the command line is running from.

**Comment by dimshitc** [comment]
we run generic update as a procedure, 
so we changed description everywhere to 
"Run generic_update: devv5.GenericUpdate();"
