### ISSUE TITLE
Duplicated CONCEPT_CODEs in MESH

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#21]
for v5.0 2014-10-15

```{sql}
SELECT CONCEPT_CODE, VOCABULARY_ID, DOMAIN_ID, COUNT(*)
FROM CONCEPT
WHERE INVALID_REASON IS NULL
AND VOCABULARY_ID NOT IN (
    'MedDRA','SMQ','DRG'
)
AND CONCEPT_CODE NOT IN (
    'OMOP generated'
)
GROUP BY CONCEPT_CODE, VOCABULARY_ID, DOMAIN_ID
HAVING COUNT(*) > 1;
```

```{text}
CONCEPT_CODE  VOCABULARY_ID       DOMAIN_ID              COUNT(*)
D014508	Mesh	Drug/Measurement	2
D014364	Mesh	Condition/Drug	2
D001646	Mesh	Condition/Drug	2
```

These Mesh CONCEPT_CODES get duplicated because they have this multi-domain (like "Drug/Measurement") but then they further break down later into their separate CONCEPT_CLASS_IDs.  It just feels odd and there are only 3 of them.

**Comment by ericaVoss** [comment]
Did we every decide if this is okay or not?

**Comment by cgreich** [comment]
Going to fix it

**Comment by ericaVoss** [comment]
Just making a note that this still exists in **v5.0 3-Apr-2015** - it is not high priority.

**Comment by cgreich** [comment]
Understood. Mesh will be refactored entirely. Stand by please.

**Comment by ericaVoss** [comment]
This is additionally discussed in this issue so we may want to just close this one:
https://github.com/OHDSI/Vocabulary-v5.0/issues/38

**Comment by cgreich** [comment]
Fixed.
