### ISSUE TITLE
Gabapentin incorrectly mapped to Device domain

### ISSUE THREAD

**Issue by crabcakeworld** [OHDSI/Vocabulary-v5.0#213]
Hello,

I found following 3 standard concepts that belong to Device domain:

45291762
45205932
45203876

They all stand for ‘GABAPENTIN POWDER’.  They should be mapped to Drug domain.

**Comment by TinyRickC137** [comment]
Hi, @crabcakeworld 

I know that is's been almost five years, but we fixed this issue! Thank you for the reporting. There is an overhaul of the Drug domain upcoming, and we will try to address NDC issues - among others.
