### ISSUE TITLE
Apparent spurious LOINC->PPI relationship

### ISSUE THREAD

**Issue by RobertJCarroll** [OHDSI/Vocabulary-v5.0#225]
There appears to be a concept_relationship that should not exist and yields some interesting hierarchy behavior:
40766240 is a 43528895

I'm can't identify a source PPI vocab item that's yielding this link. I'm happy to clean that up if there is one on our end! Thanks for investigating. @cukarthik for visibility.

**Comment by p-talapova** [comment]
Thanks for noticing!

The LOINC concept of "40766240  Are you covered by health insurance or some other kind of health care plan [PhenX]" is a standard equivalent of 2 non-standard PPI Questions from different PPI Modules ("1586134 The Basics" and "3528895 Healthcare Access & Utilization"). At first glance, they look similar, but semantically they are not identical:
1) [ 1585386 Insurance: Health Insurance](http://athena.ohdsi.org/search-terms/terms/1585386) with a long name as a synonym: "_Are you covered by health insurance or some other kind of health care plan?_" - correct.   
2) [1384450 Insurance: Insurance Type](http://athena.ohdsi.org/search-terms/terms/1384450)  with a long name as a synonym: "_Are you currently covered **by any of the following types** of health insurance or health coverage plans?_" - incorrect. 

Thus, we will change the mapping of 1384450 from 40766240 to "40766241 What kind of health insurance or health care coverage do you have [PhenX]" as soon as possible. Also, this will solve the problem for all its descendants too.

**Comment by RobertJCarroll** [comment]
Awesome! Thank you!

**Comment by p-talapova** [comment]
You are welcome! And thank you too :)

We've already fixed the bug (please, see in the Athena).
