### ISSUE TITLE
Missing PPI relationship.

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocabulary-v5.0#227]
I'm looking at the non-standard [1585807](http://athena.ohdsi.org/search-terms/terms/1585807). Even though it's an answer class, it does not have a "maps to value" relationship. It only "maps to" the question. I believe there should be a concept it "maps to value".

**Comment by TinyRickC137** [comment]
The approach to Questionnaires changed a lot since 2019. More info [here](https://forums.ohdsi.org/t/uk-biobank-vocabulary-release/13014).
For this particular concept answer is mapped to the event, no need for another mapping.
