### ISSUE TITLE
ICD10CM codes T36 to T50- issue with SNOMED mapping

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#229]
T36-T50: https://www.icd10data.com/ICD10CM/Codes/S00-T88/T36-T50

T36 to T50 has ICD10CM codes that correspond to poisoning. The codes also provide additional context of whether the poisoning is self-harm, assault or undetermined. Current mapping does not capture this additional context. 

**Recommendation:** (updated)

If the sixth character is '2' then this represents 'self-harm'. Suggest mapping to SNOMED 439235 Intentional self poisoning and 439235 self-inflicted injury.
If the sixth character is '3' then this represents 'assault'. Suggest mapping to SNOMED 440599 assault by poisoning; 435437 Assault by poisoning by drugs or medicines.
If the sixth character is '4' then this represents 'undetermined'. Suggest mapping to SNOMED 442023

This would help us define phenotypes were poisoning was with an intent to self-harm (suicide); vs other forms of poisoning like poisoning because of assault (homicide); or undetermined.

**Comment by dimshitc** [comment]
So I would add
If the sixth character is '2' then this represents 'self-harm'. Suggest mapping to SNOMED 4152376 **or its descendant**
If the sixth character is '3' then this represents 'assault'. Suggest mapping to SNOMED 
**35625043 - when it's Late effect code.
440599 - when it's initial or subsequent 
or their descendant concepts**
If the sixth character is '4' then this represents 'undetermined'. Suggest mapping to SNOMED 442023 **or its descendant**

**Comment by cgreich** [comment]
> If the sixth character is '4' then this represents 'undetermined'. Suggest mapping to SNOMED 442023
Just leave out. "Undetermined" is flavor of null. We don't capture that

> or its descendant
How do you map to descendants?

**Comment by gowthamrao** [comment]
@dimshitc @cgreich we also need to correct a mapping logic

When concept description is ICD10 has key-words 'self-harm' and 'poisoning' - we should also map it to  'intentionally SELF poisoning'  concept_id = 4152376. Some are mapped to 'intentionally poisoning by drug' 4196024, which is accurate - but not complete representation.

**Comment by gowthamrao** [comment]
Updated post above for T36 to T50 code

> If the sixth character is '3' then this represents 'assault'. Suggest mapping to SNOMED (440599 assault by poisoning; 435437 Assault by poisoning by drugs or medicines)



Similar issue with T51 to T65
https://www.icd10data.com/ICD10CM/Codes/S00-T88/T51-T65

Sixth character of ICD10CM

If the sixth character is '1' then this represents 'accidental'. Suggest mapping to SNOMED 440279 (accident)
If the sixth character is '2' then this represents 'self-harm'. Suggest mapping to SNOMED 439235 self-inflicted injury
If the sixth character is '3' then this represents 'assault'. Suggest mapping to SNOMED 40445412 Assault (there is no assault because of toxic in SNOMED)
If the sixth character is '4' then this represents 'undetermined' - then give up like @cgreich  recommended  :)

**Comment by gowthamrao** [comment]
Similar issue with T71

https://www.icd10data.com/ICD10CM/Codes/S00-T88/T66-T78/T71-

**Comment by p-talapova** [comment]
We have finally released such changes in mappings. You may find them in the Athena.
