### ISSUE TITLE
DRG codes missing (Rimma Belenkaya)

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Vocabulary-v5.0#23]
We also noticed that some of the DRG codes are missing:

009 BONE MARROW TRANSPLANT
018 CRANIAL & PERIPHERAL NERVE DISORDERS W CC
045 NEUROLOGICAL EYE DISORDERS
046 OTHER DISORDERS OF THE EYE AGE >17 W CC
050 SIALOADENECTOMY
105 CARDIAC VALVE & OTH MAJOR CARDIOTHORACIC PROC W/O CARD CATH
107 CORONARY BYPASS W CARDIAC CATH
108 OTHER CARDIOTHORACIC PROCEDURES
109 CORONARY BYPASS W/O PTCA OR CARDIAC CATH
110 MAJOR CARDIOVASCULAR PROCEDURES W CC
111 MAJOR CARDIOVASCULAR PROCEDURES W/O CC
112 PERCUTANEOUS CARDIOVASCULAR PROCEDURES.
126 ACUTE & SUBACUTE ENDOCARDITIS
127 HEART FAILURE & SHOCK
142 SYNCOPE & COLLAPSE W/O CC
143 CHEST PAIN
144 OTHER CIRCULATORY SYSTEM DIAGNOSES W CC
170 OTHER DIGESTIVE SYSTEM O.R. PROCEDURES W CC
174 G.I. HEMORRHAGE W CC
209 MAJOR JOINT & LIMB REATTACHMENT PROCEDURES OF LOWER EXTREMITY
210 HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT AGE >17 W CC
211 HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT AGE >17 W/O CC
212 HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT AGE 0-17
266 SKIN GRAFT &/OR DEBRID EXCP FOR SKIN ULCER OR CELLULITIS W/O CC
267 PERIANAL & PILONIDAL PROCEDURES
268 SKIN, SUBCUTANEOUS TISSUE & BREAST PLASTIC PROCEDURES
274 MALIGNANT BREAST DISORDERS W CC
277 CELLULITIS AGE >17 W CC
278 CELLULITIS AGE >17 W/O CC
279 CELLULITIS AGE 0-17
320 KIDNEY & URINARY TRACT INFECTIONS AGE >17 W CC
321 KIDNEY & URINARY TRACT INFECTIONS AGE >17 W/O CC
359 UTERINE & ADNEXA PROC FOR NON-MALIGNANCY W/O CC
365 OTHER FEMALE REPRODUCTIVE SYSTEM O.R. PROCEDURES
396 RED BLOOD CELL DISORDERS AGE 0-17
397 COAGULATION DISORDERS
399 RETICULOENDOTHELIAL & IMMUNITY DISORDERS W/O CC
400 LYMPHOMA & LEUKEMIA W MAJOR O.R. PROCEDURE
404 LYMPHOMA & NON-ACUTE LEUKEMIA W/O CC
426 DEPRESSIVE NEUROSES
427 NEUROSES EXCEPT DEPRESSIVE
430 PSYCHOSES
431 CHILDHOOD MENTAL DISORDERS
449 POISONING & TOXIC EFFECTS OF DRUGS AGE >17 W CC
452 COMPLICATIONS OF TREATMENT W CC
519 CERVICAL SPINAL FUSION W CC
520 CERVICAL SPINAL FUSION W/O CC

**Comment by schuemie** [comment]
I see these DRG codes are now in the vocab, but they don't map to standard concepts. For example, this returns 0 rows:
```sql
SELECT *
FROM concept drg
LEFT JOIN concept_relationship
	ON drg.concept_id = concept_id_1
LEFT JOIN concept standard
	ON standard.concept_id = concept_id_2
WHERE drg.vocabulary_id = 'DRG'
	AND standard.standard_concept = 'S'
	AND drg.concept_code IN ('127','143')
	AND relationship_id = 'Maps to'
```

**Comment by ericaVoss** [comment]
Looks like they are all in there by deprecated now.

```sql
SELECT *
FROM CONCEPT 
WHERE VOCABULARY_ID = 'DRG'
AND CONCEPT_CODE IN (
'009',-- BONE MARROW TRANSPLANT
'018',-- CRANIAL & PERIPHERAL NERVE DISORDERS W CC
'045',-- NEUROLOGICAL EYE DISORDERS
'046',-- OTHER DISORDERS OF THE EYE AGE >17 W CC
'050',-- SIALOADENECTOMY
'105',-- CARDIAC VALVE & OTH MAJOR CARDIOTHORACIC PROC W/O CARD CATH
'107',-- CORONARY BYPASS W CARDIAC CATH
'108',-- OTHER CARDIOTHORACIC PROCEDURES
'109',-- CORONARY BYPASS W/O PTCA OR CARDIAC CATH
'110',-- MAJOR CARDIOVASCULAR PROCEDURES W CC
'111',-- MAJOR CARDIOVASCULAR PROCEDURES W/O CC
'112',-- PERCUTANEOUS CARDIOVASCULAR PROCEDURES.
'126',-- ACUTE & SUBACUTE ENDOCARDITIS
'127',-- HEART FAILURE & SHOCK
'142',-- SYNCOPE & COLLAPSE W/O CC
'143',-- CHEST PAIN
'144',-- OTHER CIRCULATORY SYSTEM DIAGNOSES W CC
'170',-- OTHER DIGESTIVE SYSTEM O.R. PROCEDURES W CC
'174',-- G.I. HEMORRHAGE W CC
'209',-- MAJOR JOINT & LIMB REATTACHMENT PROCEDURES OF LOWER EXTREMITY
'210',-- HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT AGE >17 W CC
'211',-- HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT AGE >17 W/O CC
'212',-- HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT AGE 0-17
'266',-- SKIN GRAFT &/OR DEBRID EXCP FOR SKIN ULCER OR CELLULITIS W/O CC
'267',-- PERIANAL & PILONIDAL PROCEDURES
'268',-- SKIN, SUBCUTANEOUS TISSUE & BREAST PLASTIC PROCEDURES
'274',-- MALIGNANT BREAST DISORDERS W CC
'277',-- CELLULITIS AGE >17 W CC
'278',-- CELLULITIS AGE >17 W/O CC
'279',-- CELLULITIS AGE 0-17
'320',-- KIDNEY & URINARY TRACT INFECTIONS AGE >17 W CC
'321',-- KIDNEY & URINARY TRACT INFECTIONS AGE >17 W/O CC
'359',-- UTERINE & ADNEXA PROC FOR NON-MALIGNANCY W/O CC
'365',-- OTHER FEMALE REPRODUCTIVE SYSTEM O.R. PROCEDURES
'396',-- RED BLOOD CELL DISORDERS AGE 0-17
'397',-- COAGULATION DISORDERS
'399',-- RETICULOENDOTHELIAL & IMMUNITY DISORDERS W/O CC
'400',-- LYMPHOMA & LEUKEMIA W MAJOR O.R. PROCEDURE
'404',-- LYMPHOMA & NON-ACUTE LEUKEMIA W/O CC
'426',-- DEPRESSIVE NEUROSES
'427',-- NEUROSES EXCEPT DEPRESSIVE
'430',-- PSYCHOSES
'431',-- CHILDHOOD MENTAL DISORDERS
'449',-- POISONING & TOXIC EFFECTS OF DRUGS AGE >17 W CC
'452',-- COMPLICATIONS OF TREATMENT W CC
'519',-- CERVICAL SPINAL FUSION W CC
'520'-- CERVICAL SPINAL FUSION W/O CC
)
ORDER BY CONCEPT_CODE
```

It also still looks like they don't map to standard concepts, however this ticket is so old, maybe they aren't supposed to anymore?

**Comment by dimshitc** [comment]
Just curious, does anybody uses DRG concepts?
If yes, we need to map them to the standard ones

**Comment by clairblacketer** [comment]
@dimshitc I think you can close this issue. The necessary codes are in the vocab which addresses the initial issue, though they are all deprecated.
