### ISSUE TITLE
Impossible Concept Relationship valid_start_dates

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#231]
select valid_start_date, count(*) from vocabulary_5_0_apr_19.concept_relationship where  date_part(year,valid_start_date) < 1900 group by 1

valid_start_date | count
-- | --
0001-01-01 | 16
0017-05-17 | 428
0017-05-23 | 4
0017-05-25 | 8

vocabulary_version
--
v5.0 28-MAR-19

**Comment by dimshitc** [comment]
Fixed in a current version of the vocabulary.
