### ISSUE TITLE
ICD-CM external causes of injury accident - passenger vs driver vs pedestrian

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#232]
ICD10CM and ICD9CM codes describe if the person injured in the accident is a driver vs passenger vs pedestrian. 

External causes of injury codes: V00-Y99

In cases where we map one ICD-CM code to one or more SNOMED codes, it would be nice to map to a SNOMED concept that distinguishes if the injured is the driver vs passenger.

This will help with use-cases where we the subject is the driver and not just the passenger or pedestrian.

**Comment by cgreich** [comment]
Do you have an observational research use case where that is relevant?

**Comment by gowthamrao** [comment]
Yes. Incidence of road traffic accident as driver

**Comment by gowthamrao** [comment]
Yes. Incidence of visits with road traffic accident as driver

**Comment by cgreich** [comment]
Because the driver might be driving under the influence of something?

**Comment by dimshitc** [comment]
@p-talapova 
Do we have any automatic way to assign these?

**Comment by p-talapova** [comment]
@dimshitc, yes we do. To indicate a victim of an accident, it is possible to add automatically the following: 

V01-V09 => 441188	32906002	Victim, pedestrian in vehicular AND/OR traffic accident
V10-V19 => 433099	47397001	Victim, cyclist in vehicular AND/OR traffic accident
V20-V29 => 438310	10298002	Victim, motorcycle rider in vehicular AND/OR traffic accident
V30-V86 => 434228	21107000	Passenger in vehicular AND/OR traffic accident

**Comment by p-talapova** [comment]
We have finally released such changes in mappings. You may find them in the Athena.
