### ISSUE TITLE
Some Read concepts have NULL concept name

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#234]
This is in reference to issue #98. When I run the query 

```sql
Select *
from concept c
where c.concept_name = ' ' and c.vocabulary_id = 'Read'
```

I find 118 codes without names. These are all deprecated but typically we worry more about deprecation for standard codes and still map source codes that are deprecated given they are within the valid start and end dates.

**Comment by dimshitc** [comment]
I see, you still need these concepts.
Technically, you don't have any problem here. You use concept_code and don't care about the name. 
And the actual meaning you derive from what these concepts are mapped to (anyway, you need to obtain standard concepts).
But for kind of aesthetic purpose we can assign the same names as target concept names.

I have another question:
Have you noticed Read codes present in your patient data, but absent in the vocabulary?

**Comment by cgreich** [comment]
Good news is that Read is on its way out.

**Comment by TinyRickC137** [comment]
Fixed
