### ISSUE TITLE
Problem downloading concepts from ATHENA

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#235]
I downloaded a copy of the vocabulary on June 10, 2019. It had some issue in the concept table where only concepts that belong to vocabularies starting with the letters A-R were included. This means that all SNOMEDs were excluded. I am not sure what happened but it was odd.

**Comment by dimshitc** [comment]
Yeah, that's odd. We uploaded the vocabularies lately, and it was totally fine.
Can you please reupload the vocabulary and if the error persists, forward me the e-mail with download link.

**Comment by TinyRickC137** [comment]
@clairblacketer hello, can we close this issue? 
I hope the process is fine now

**Comment by clairblacketer** [comment]
Hi yes this can be closed
