### ISSUE TITLE
J1745 (concept id 2718445) RxNorm mapping is not available

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#236]
J1745 -> 'Injection, infliximab, excludes biosimilar, 10 mg'  is mapped to RxNorm extension 41205480 'infliximab Injectable Solution'. This is then mapped to biosimilars like Inflectra.

This mapping does not allow us to differentiate between Remicade and other Biosimilars. We need a better mapping to say this is 'Remicade'.

**Comment by dimshitc** [comment]
Good catch!
So, we'll remap J1745  to 19079573 infliximab 10 MG/ML [Remicade] (RxNorm)
It'll be done in the next HCPCS refresh (we planned it after SNOMED release, in August)
Let me know, if it's urgent.

**Comment by m-khitrun** [comment]
@gowthamrao, we've fixed It. Please look at rthe result here: https://athena.ohdsi.org/search-terms/terms/2718445
