### ISSUE TITLE
Missing 'Maps to' relationships

### ISSUE THREAD

**Issue by abedtashh** [OHDSI/Vocabulary-v5.0#239]
There are a good list of 'Maps to' relationships missing in the vocabulary (17-JUN-19):

SOURCE_VOCABULARY_ID | COUNT
-- | --
LPD_Belgium | 19740
NDC | 175
GCN_SEQNO | 49
VA Product | 31
RxNorm | 89
Multum | 29
SPL | 4
dm+d | 3
SNOMED | 3
MeSH | 1

Hate to do this, but I'm pasting only the list of missing relationships for NDC and RxNorm here that may help incorporating these faster:

SOURCE_CONCEPT_ID | TARGET_CONCEPT_ID
-- | --
40011713 | 40011713
40231358 | 40231358
45114063 | 19057476
45062954 | 19057476
45023166 | 19057476
40173167 | 40173167
45110999 | 40224933
19057416 | 19057416
19129631 | 19129631
45157071 | 778765
45061059 | 40220451
40140943 | 40140943
45277684 | 781062
45089790 | 781062
45072956 | 781062
45368470 | 19077058
45281761 | 44098343
45110899 | 19078921
45335128 | 1636816
1128700 | 1128700
44850325 | 19058653
1511397 | 1511397
1194754 | 1194754
40004392 | 1194754
40077210 | 19127111
19127111 | 19127111
45268078 | 40240688
45248134 | 40240688
45057773 | 19123558
44841882 | 19074586
792868 | 792868
44994186 | 40239555
40106711 | 43011615
43011615 | 43011615
19033125 | 43011615
45376478 | 1131831
19072105 | 19072105
19083420 | 42901275
42901275 | 42901275
45264532 | 44032462
40173168 | 40173168
45298679 | 36408146
45162171 | 19073642
45840709 | 42899975
44991426 | 19126173
45212884 | 46287338
45093675 | 46287338
45332403 | 46287338
45059699 | 46287338
45010903 | 19077057
45342626 | 19077057
45198780 | 19077057
45034013 | 19077057
40044657 | 40044657
45162715 | 19078632
44953817 | 42898829
45110098 | 42898829
1723767 | 1366694
1366694 | 1366694
1723255 | 1366694
19099426 | 19099426
963795 | 963795
19135127 | 19135127
1723254 | 1366695
1723768 | 1366695
1366695 | 1366695
44874037 | 19081251
1121889 | 1121889
1138066 | 1138066
40161367 | 1138066
45178629 | 19079960
44957275 | 19079960
40173170 | 40173170
45088800 | 1132179
45127429 | 19077379
45298470 | 19057592
45110802 | 19057592
45366649 | 42628955
45230362 | 42628955
40231319 | 40231319
40173172 | 40173172
19103028 | 19103028
40138024 | 40138024
45046226 | 1113346
45078002 | 1113346
40146602 | 40155488
40155488 | 40155488
40045251 | 40155488
40011729 | 40011729
44845090 | 44072724
1723761 | 1593508
35526422 | 1593508
44875180 | 19077055
1723760 | 1593508
35526423 | 1593508
1767933 | 1593508
35522049 | 1593508
1593508 | 1593508
45116424 | 19077055
45291672 | 19077055
1723763 | 1593508
1723762 | 1593508
1768240 | 1593508
1768238 | 1593508
1768239 | 1593508
1723257 | 1593508
44472326 | 1593508
44446626 | 1593508
1723253 | 1593508
1768241 | 1593508
45351294 | 42708733
45289540 | 19044563
44422047 | 40220806
44472318 | 40220806
19125444 | 19125444
40220806 | 40220806
40044315 | 40044315
45105781 | 19076077
45173907 | 19058076
45120177 | 19076077
19129837 | 19129837
45156752 | 42628875
45334337 | 1344244
45068860 | 35605208
44889718 | 35605208
35604281 | 35604281
45268117 | 40232439
40017895 | 40017895
40107029 | 40017895
40161319 | 40161319
45013817 | 40930194
44890245 | 19046742
45063341 | 19046742
44846645 | 40233691
44883138 | 19019336
40004393 | 1128795
35604361 | 35604361
1128795 | 1128795
45144486 | 19077990
45247212 | 19077990
45093672 | 19077990
44970719 | 19077990
45298581 | 19077990
45144487 | 19077990
19127440 | 19127440
44951185 | 19019337
44905686 | 35603169
45224462 | 40226066
45036848 | 40226066
45206249 | 45776321
963797 | 963797
45014527 | 19074977
44991148 | 19074977
44920181 | 1584953
1121453 | 1121453
45211201 | 40226084
45009604 | 42708388
19130107 | 19130107
44992563 | 1707772
44906485 | 1707772
1121523 | 1121523
19126753 | 19126753
45077398 | 19014903
44931635 | 19044564
45144515 | 19073722
19006499 | 42899232
42899232 | 42899232
45233837 | 19027831
1593507 | 1593507
44431546 | 1593507
1767932 | 1593507
1768243 | 1593507
44472324 | 1593507
1768244 | 1593507
44838050 | 19073214
45236020 | 40220493
45014124 | 40220493
19033506 | 19033506
40116148 | 19033506
40036511 | 40036511
19061445 | 42901450
42901450 | 42901450
45306550 | 19027385
40063209 | 40063209
44889629 | 35603225
45332737 | 35603225
45127725 | 35603225
45193527 | 35605886
45193528 | 35605886
45272715 | 976780
45289863 | 976780
45050848 | 976780
44838224 | 1724711
35201705 | 35201705
35604282 | 35604282
45344597 | 19033500
45174209 | 19033500
45310842 | 19033500
45122306 | 19033500
44912436 | 19033500
40011721 | 40011721
40156419 | 40156419
40061276 | 40156419
19127495 | 19127495
45162180 | 36257150
45008611 | 19076753
19129630 | 19129630
19097811 | 19097811
45133625 | 19121949
40173174 | 40173174
729541 | 1511305
1511305 | 1511305
729283 | 1511305
1136878 | 1136878
45165506 | 19057890
45210062 | 19020053
45213954 | 19020053
44886487 | 19020053
40044614 | 40044614
45178638 | 19073526
45159942 | 42799447
19028573 | 19028573
44947493 | 19028573
45056349 | 19028573
45340431 | 19028573
40005455 | 19028573
19042629 | 40236210
45311106 | 19074847
45160828 | 19074847
45105343 | 19074847
40236210 | 40236210
45191420 | 19074847
45293314 | 19074847
40113540 | 40236210
45208629 | 19074847
45110279 | 19074847
45156651 | 19074847
35201704 | 35201704
45027527 | 19023490
45266396 | 19023490
19132640 | 19132640
45077969 | 19027805
44893024 | 19027805
44912299 | 19124046
45344863 | 19027805
44983562 | 19027805
44940084 | 40227819
45023669 | 40227819
45110801 | 36406613
45078570 | 19081229
45079642 | 19056879
45318517 | 19056879
45222514 | 35605491
19127262 | 19127262
44986546 | 43012658
40161317 | 40161317
45041882 | 40174494
35305126 | 35305126
45225357 | 19080159
19085439 | 19085439
45085079 | 19080159
19085437 | 19085437
19085438 | 19085438
44976907 | 1181865

**Comment by Alexdavv** [comment]
I will take care of the NDC-RxNorm mappings from the list.
Thanks, @abedtashh

**Comment by abedtashh** [comment]
@Alexdavv Hi, any estimation on when these mappings will return to vocab? Thanks!

**Comment by Alexdavv** [comment]
@abedtashh We're planning to fix reported missing/erroneous NDC mappings in one of the next releases (1-2 weeks or so).

**Comment by Alexdavv** [comment]
@abedtashh 
We [released](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20190916_1568656293) the mappings for requested NDC codes some time ago, so the issue is going to be closed.
