### ISSUE TITLE
Diabetic - poor control is a finding in SNOMED that doesnt map to Diabetes or Diabetic Complication

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#240]
Per screenshot below, I noted in my vocab that 'Diabetic-poor control', which contains a couple prevalent concepts, including 'Type II diabetes mellitus uncontrolled' does not currently map into either 'DIabetes Mellitus' or 'Diabetic complication', which are the two concepts commonly used when defining diabetes phenotypes.  Could we confirm SNOMED isn't capturing some mapping here that we could use?
![image](https://user-images.githubusercontent.com/731930/61332635-be693180-a7f2-11e9-890a-5772aa96c349.png)

**Comment by dimshitc** [comment]
Right, SNOMED has pretty poor hierarchy for 'Diabetic-poor control'
![image](https://user-images.githubusercontent.com/8568959/61363592-f3c25d80-a88c-11e9-88d7-1380ba8a9ceb.png)

The least we can do is to capture both concepts ('Diabetic-poor control' and descendant of either 'DIabetes Mellitus' or 'Diabetic complication') in mapping of ICD concepts to SNOMED.
For example 
[ICD9CM 249.21 Secondary diabetes mellitus with hyperosmolarity, uncontrolled ](http://athena.ohdsi.org/search-terms/terms/37016355)

**Comment by cgreich** [comment]
@dimshitc :

Don't close it yet. We need to bring this up on the 30th with SNOMED. Either they fix it, or we consider putting bandaids on this and similar problems.

**Comment by m-khitrun** [comment]
Hello, @pbr6cornell 

Please, be informed that the concept [Diabetic - poor control](https://athena.ohdsi.org/search-terms/terms/443238) and its SNOMED descendants were mapped to the respective types of diabetes mellitus in the hierarchy of Conditions.

Regards,
Masha.
