### ISSUE TITLE
"none of the above" answer mapping to "none"

### ISSUE THREAD

**Issue by RobertJCarroll** [OHDSI/Vocabulary-v5.0#242]
Hi there! The following term is mapped to "None", when it's a "None of the above" type answer. Given it's a question-specific "other" type answer, I expect this should just be mapped to itself.
http://athena.ohdsi.org/search-terms/terms/1585849

Thank you for considering, and I'm happy to provide more information.

**Comment by cgreich** [comment]
Hm. Not quite. gender_concept_id is defined as sex at birth. If we don't have any then the mapping is to concept_id=0. Any non-answer to the question is a 0, whether we don't know the answer or whether there is no answer. No?

**Comment by RobertJCarroll** [comment]
In the context of the Person table, that seems reasonable- there is "No matching [sex] concept" in the standard concepts for that domain. 

In the context of the Observation table, where this concept resides, there is an answer ("None of these describe me") to the specific question being asked ("What was your biological sex assigned at birth?"). That's different than the currently mapped answer "None".

**Comment by cgreich** [comment]
I understand that. But how is an analytic application going to deal with it? It doesn't have a value. Why - because it "doesn't describe me" or "not known" - won't help it. I really don't understand why this subject is so fascinating to people and why we are constantly debating why this particular information is missing. It's not the vocabulary that's responsible. We don't have the information, ergo we cannot use it for analytics and ergo concept_id=0. Doesn't matter why.

**Comment by RobertJCarroll** [comment]
I may not have communicated well the underlying concern I have, or maybe I'm not understanding the solution you are suggesting. 
Concept_id=1585849 (None of these describe me) is currently mapping to concept_id=4124462 (None) from SNOMED, which seems to be inaccurate.  
Is your suggestion that this concept_id should map to concept_id=0 (No matching concept)? Or perhaps that the whole concept should be removed?

**Comment by RobertJCarroll** [comment]
Hello there. I'm following up on the above. I'd be grateful for more clarity about how to resolve this mapping. Thank you!

**Comment by cgreich** [comment]
Oh. You are correct @RobertJCarroll. Sorry, I didn't realize your point. Will fix the mapping.

**Comment by RobertJCarroll** [comment]
Ok, thank you!

**Comment by TinyRickC137** [comment]
This issue has been fixed during our [latest release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20230531_1685563519.000000).
