### ISSUE TITLE
STANDARD_CONCEPT NULLs now blanks

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#243]
In a recent (17 June 2019) version of the vocabulary, the field STANDARD_CONCEPT in the CONCEPT table now has blanks instead of NULLs. We had to revert the blanks back to NULLs so that ATLAS can pick them up as non-standard concepts.

**Comment by dimshitc** [comment]
Just downloaded it from Athena. Opened in notepad. everything is fine.
Do you still have this issue?
