### ISSUE TITLE
Adding visit concept id for 'health examination'

### ISSUE THREAD

**Issue by chandryou** [OHDSI/Vocabulary-v5.0#245]
Most commonly used visit concept id would be
Inpatient visit (9201), Outpatient visit (9202), Emergency Room visit (9203), and ER and Inpatient visit (262) from [OMOP vocabulary](http://athena.ohdsi.org/search-terms/terms?domain=Visit&standardConcept=Standard&page=1&pageSize=50&query=&sort=vocabulary_id&order=desc). 

In Korea, many hospitals run health examination program. Patients visit hospitals for a specific purpose, health examination.
Since this visit is very distinct, we want to add visit concept id for 'health examination'

https://github.com/ohdsi-korea/ThemisKorea/issues/14

**Comment by chandryou** [comment]
It is added. 
https://forums.ohdsi.org/t/new-concept-ids-for-cost-and-payer-plan-in-korea/7841/7
http://athena.ohdsi.org/search-terms/terms/32693

**Comment by cgreich** [comment]
@dimshitc: Don't forget to create an "Is a" to 8756 "Outpatient Hospital".

**Comment by dimshitc** [comment]
'Is a' created
