### ISSUE TITLE
LOINC: link LOINC parts to the concepts they help define (LoincPartLink.csv file)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#251]
In LoincPartLink.csv this loinc code https://loinc.org/14682-9/  (CID http://athena.ohdsi.org/search-terms/terms/3020564)
has several parts defined and linked
e.g.,
![image](https://user-images.githubusercontent.com/7526119/64789688-d505dd80-d542-11e9-9c30-17576ee8adb0.png)

COMPONENT Creatinine  (LP14355-9) (CID http://athena.ohdsi.org/search-terms/terms/40775801)
The LP concepts seems to be imported into Athena - very good. 

In order to determine what other lab test have a component of creatinine the relationships from LoincPartLink.csv would be very useful to have in Athena OMOP Vocabulary CONCEPT_REALTIONSHIP table.

The LP concepts (present in Athena) are not linked to their lab test they help define. (not good at all)

Why are they not added? (not visible in athena browser) neither for the Loing Part concept or the main LOINC concept.

This forces me to use the raw LOINC CSV files in addition to Athena OMOP vocab  (when I would rather rely solely on the Athena OMOP Vocab).

Can they be added in next cycle of ETL of LOINC?

(I did study this folder briefly here  https://github.com/OHDSI/Vocabulary-v5.0/tree/master/LOINC)
(We seem to use LOINC/SNOMED CT Expression Association and Map Sets File and the file LoincPartLink is much better I think)

**Comment by Alexdavv** [comment]
5 link types of primary LOINC model were introduced.
@vojtechhuser if consumer names are needed, could you please create a separate issue?
Thanks
