### ISSUE TITLE
ERROR:  value too long for type character varying(255) (CONCEPT.csv)

### ISSUE THREAD

**Issue by evgenii-vilchinsky** [OHDSI/Vocabulary-v5.0#253]
Hi Team! 
While trying to import a CONCEPT.csv into Postgres Im getting the following:

```
ERROR:  value too long for type character varying(255)

CONTEXT:  COPY concept, line 375157, column concept_name: "SYRINGE WITH NEEDLE,INSULIN DISPOSABLE,0.5 ML 29 gauge X 1/2 MISCELL SYRINGE, EMPTY DISPOSABLE   Drug    ..."
```

Please let me know if you need any additional information.

**Comment by evgenii-vilchinsky** [comment]
Yes, I`ll try to adjust loading command. 

Seems like the script is for Windows environment.

**Comment by dimshitc** [comment]
And you must keep this
...WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

**Comment by evgenii-vilchinsky** [comment]
Yes. 
 QUOTE E'\b'  - solved the issue for both cases! 

Thank you a lot!
