### ISSUE TITLE
Duplicate CDM table and field concepts

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#265]
Example:

concept_id | concept_name | domain_id | vocabulary_id | concept_class_id | standard_concept | concept_code | valid_start_date | valid_end_date | invalid_reason
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1147195 | care_site.care_site_id | Metadata | CDM | Field | S | CDM251 | 2014-11-11 | 2099-12-31
1147654 | care_site.care_site_id | Metadata | CDM | Field | S | CDM700 | 2018-10-11 | 2099-12-31

Query to get the others
select c2.concept_code, c1.*
from concept c1
JOIN
concept c2 ON c1.concept_name = c2.concept_name 
          AND c1.domain_id = c2.domain_id 
          and c1.concept_class_id = c2.concept_class_id 
          AND c1.concept_id > c2.concept_id
WHERE  c1.vocabulary_id = 'CDM' -- and c1.concept_class_id = 'Table'
AND  c1. standard_concept = 'S' AND c2.standard_concept = 'S';

**Comment by Alexdavv** [comment]
Hi @don-torok!
I think it was done intentionally because these concepts have links to different CDM versions.
Probably the definitions of the fields were slightly changes.
@cgreich and @clairblacketer should know better

**Comment by don-torok** [comment]
Yes, concepts belong to different versions. This query shows the CDM versions the concepts belong to, so that you can choose the correct concept for the care_site_id.
```
SELECT concept_id_1, c2.concept_name
FROM concept_relationship
JOIN concept c2 ON c2.concept_id = concept_id_2
WHERE concept_id_1 IN( 1147654 , 1147195)
AND relationship_id = 'Contained in version'
ORDER BY concept_id_1, c2.concept_name;
```
<html><head><style>table, th, td { border: 1px solid black; border-collapse: collapse; } th, td { padding: 5px; text-align: left; } table tr:nth-child(even) { background-color: #eee; } table tr:nth-child(odd) { background-color:#fff; } table th { background-color: black; color: white; }</style></head><body>


concept_id_1 | concept_name
-- | --
1147195 | OMOP CDM Version 5.0.0
1147195 | OMOP CDM Version 5.0.1
1147195 | OMOP CDM Version 5.1.0
1147195 | OMOP CDM Version 5.1.1
1147195 | OMOP CDM Version 5.2.0
1147195 | OMOP CDM Version 5.2.2
1147195 | OMOP CDM Version 5.3.0
1147195 | OMOP CDM Version 5.3.1
1147195 | OMOP CDM Version 5.3.2
1147195 | OMOP CDM Version 5.4.0
1147654 | OMOP CDM Version 6.0.0


</body></html>
