### ISSUE TITLE
route_concept_id mapping

### ISSUE THREAD

**Issue by noahgengel** [OHDSI/Vocabulary-v5.0#266]
Hello,

Would it be possible for someone to tell me the best route_concept_id to use for the following route_source_values?

![image](https://user-images.githubusercontent.com/53097542/69556636-123f1080-0f73-11ea-894e-c61a454dbc01.png)

I could not find any route_concept_ids that were as generic as the descriptions given in the above route_source_values. I do not want to use overly specific route_concept_ids and wanted to see the most clinically equivalent concept_ids to use.

**Comment by dimshitc** [comment]
Techically, injection is not a route, but approach.
Route means a place where drug got delivered.
So, you might just map that to 0.

**Comment by cgreich** [comment]
Is there any way you can specify from the data? Usually, as @dimshitc says, it could be any route requiring an injection: http://athena.ohdsi.org/search-terms/terms?standardConcept=Standard&domain=Route&page=1&pageSize=50&query=intra.

In real life, they only mean intravenous, intramuscular or subcutaneous. Can you figure that out by elimination, maybe?

**Comment by p-talapova** [comment]
Should be closed as a not technical issue.
