### ISSUE TITLE
Map inflammatory disease of cervix to Inflammatory disorder of male genital organ

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#267]
select c1.concept_code, c1.concept_name, c2.concept_code, c2.concept_name
FROM concept c1 
JOIN concept_relationship ON relationship_id = 'Maps to' AND concept_id_1 = c1.concept_id
JOIN concept c2 on c2.concept_id = concept_id_2
WHERE c1.concept_code IN( '616.9', '616.89', '616.89' ) and c1.vocabulary_id = 'ICD9CM' 

concept_code | concept_name | concept_code | concept_name
-- | -- | -- | --
616.9 | Unspecified inflammatory disease of cervix, vagina, and vulva | 128478005 | Inflammatory disorder of male genital organ
616.89 | Other inflammatory disease of cervix, vagina and vulva | 128478005 | Inflammatory disorder of male genital organ

**Comment by don-torok** [comment]
Has this been corrected in current vocabulary release?

**Comment by p-talapova** [comment]
Dear @don-torok, better late than never, the vocabulary team has finally fixed these mappings. Thank you!
