### ISSUE TITLE
Run Tantalus and provide the report

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#268]
For each milestone release of vocab, provide a report that compares it to the previous milestone release

Example https://mi-erasmusmc.shinyapps.io/Tantalus/_w_a23f2847/report/diffSummary.html#changes_by_standard_concept

https://github.com/OHDSI/Tantalus

**Comment by hardhouse** [comment]
https://github.com/OHDSI/Vocabulary-v5.0/releases
