### ISSUE TITLE
drop v5 from the repo name

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#269]
we are not at version 6  so the name seems not correct. we should drop version from the repo name

**Comment by cgreich** [comment]
True, but I don't think you can change repo names. You'd have to rebuild and entire new repo.

**Comment by hardhouse** [comment]
only owner can do this https://help.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by TinyRickC137** [comment]
Can we keep it and close the issue? 
5 years later we can call It a feature :) 
@vojtechhuser @cgreich

**Comment by cgreich** [comment]
Not sure why what we gain by changing the name and killing all existing URLs. Is there a reason other than optics?

**Comment by TinyRickC137** [comment]
I can't agree more
