### ISSUE TITLE
vocabulary issues around Notes  table

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#27]
LOINC has a set of terms for representing documents.

Here
Document ontology
http://www.ohdsi.org/web/hermes/index.html#/concept/40791774

They are now part of domain measurement.
Our EHR data have notes and I am working on a CDMv5 note table.
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:note

especially the 'note_type_concept_id'

Do want a domain Note (or document) and assign a discharge summery concept this domain?
http://www.ohdsi.org/web/hermes/index.html#/concept/3020091

Will we use LOINC Document Ontology in Notes table like we use SNOMED for Conditions?

**Comment by cgreich** [comment]
@vojtechhuser :+1: 
Don't understand: We already have Note Types: 
- Discharge summary
- Admission note
- Inpatient note
- Outpatient note
- Radiology report
- Pathology report
- Ancillary report
- Nursing report
- Note
- Emergency department note
What else do you need?

**Comment by ericaVoss** [comment]
@vojtechhuser is this still an issue or can we close this one?
