### ISSUE TITLE
Concept of milestone releases

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#270]
Each Feb and Aug, we should have a milestone release.

(taking in Jan and July releases of SCT and LOINC)

For sites updating twice a year, these milestone releases would be more consistent.

(related to prior issue about comparison reports using Tantalus)

**Comment by aostropolets** [comment]
Three years later, here's the roadmap with semi-annual releases: https://github.com/OHDSI/Vocabulary-v5.0/wiki/Release-planning :) Funny enough, we independently arrived at the same cadence: Feb and Aug. Good job, Vojtech :)
