### ISSUE TITLE
NDC and RxNorm codes not mapping to standard concepts

### ISSUE THREAD

**Issue by margamarga** [OHDSI/Vocabulary-v5.0#277]
Hi,

We found a problem where NDC and RxNorm codes are not correctly mapping to standard concepts.
I've attached a list of NDC codes not mapped to standard concepts from our drug exposure data.
Can someone from the vocabulary team please review this list and update the vocabulary?

Please let me know if you need any further information.
Thank you very much!
Margaret
[unmapped.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/4201915/unmapped.xlsx)

**Comment by mik-ohdsi** [comment]
Dear Margaret,
thank you for letting us know. Let us look into this and we will get back to you as soon as possible. 
Kind regards
 Michael

**Comment by Alexdavv** [comment]
Most of the NDC codes requested were mapped in one of the recent vocabulary releases.
