### ISSUE TITLE
Non-Standard Measurement Codes with No Standard Mappings

### ISSUE THREAD

**Issue by mborsje** [OHDSI/Vocabulary-v5.0#281]
Hello,

I came across a few non-standard measurement codes that are not mapped to a standard LOINC code.  Is it possible to get these mapped?

Measurement Concept Ids
3003147
3020331
3014773
3016920
3037637
3016436

**Comment by don-torok** [comment]
This post would be a lot more interesting if you listed what the concept information along with the codes


concept_id | concept_name | domain_id | vocabulary_id | concept_class_id | standard_concept | concept_code | valid_start_date | valid_end_date | invalid_reason
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
3003147 | Deprecated Fibrin D-dimer | Measurement | LOINC | Lab Test |   | 30240-6 | 1970-01-01 | 2019-06-20 | D
3014773 | Deprecated Thyroxine (T4) uptake [Mass/volume] in Serum or Plasma | Measurement | LOINC | Lab Test |   | 3023-9 | 1970-01-01 | 2019-06-20 | D
3016436 | Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma | Measurement | LOINC | Lab Test |   | 2532-0 | 1970-01-01 | 2019-06-20 | D
3016920 | Lactate dehydrogenase [Enzymatic activity/volume] in Cerebral spinal fluid | Measurement | LOINC | Lab Test |   | 2528-8 | 1970-01-01 | 2019-06-20 | D
3020331 | Lead [Mass/volume] in Blood | Measurement | LOINC | Lab Test |   | 5671-3 | 1970-01-01 | 2019-06-20 | D
3037637 | Reticulocytes [#/volume] in Blood by calculation | Measurement | LOINC | Lab Test |   | 42758-3 | 1970-01-01 | 2015-06-29 | D

**Comment by mborsje** [comment]
Thank you. I will do that next time I post an issue.

**Comment by mik-ohdsi** [comment]
Solved in the current vocabulary version
3003147 - mapped, deprecated
3020331 - mapped, deprecated
3014773 - deprecated
3016920 - mapped, deprecated 
3037637 - mapped, deprecated 
3016436 - mapped, deprecated
