### ISSUE TITLE
CPT4 87635 not in UMLS so does not update

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#288]
In the vocab version 2020320 the CPT4 [87635](http://athena.ohdsi.org/search-terms/terms?vocabulary=CPT4&page=1&pageSize=50&query=700360&sort=concept_code&order=asc) cannot update after running the CPT.BAT file because it is not yet in UMLS. For now, I added the record manually based on the ATHENA information.

**Comment by mickyr** [comment]
@clairblacketer I have the same problem. Can you please share your manual update script or details on what to update where?
I would really appreciate it. Thanks!

**Comment by Alexdavv** [comment]
Issue fixed.

**Comment by acumarav** [comment]
Updated CPT4.jar has been released.

**Comment by acumarav** [comment]
During the production operation activities, an old version of the CPT4.jar has been rewritten which cause this issue. Patched version with the latest concepts is restored now but bundles should be reassembled (archived-restored) to include it in the pack.
Another option is to download only updated CPT4.jar from the Athena repository:
https://github.com/OHDSI/Athena/blob/develop/src/main/docker/cpt4.jar
