### ISSUE TITLE
Support for new LOINC codes for COVID-19

### ISSUE THREAD

**Issue by kmkostka** [OHDSI/Vocabulary-v5.0#303]
Based on the vocabs loaded into atlas-covid19.ohdsi.org, looks like we still have some LOINC codes released that are not retrievable yet for concept sets.

For reference, we're using these in the [N3C phenotype](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/wiki/Latest-Phenotype) and would like to see them incorporated in an upcoming vocab release.

LOINC Code | Name | Provenance
-- | -- | --
94758-0	| SARS-CoV-2 E gene, any respiratory specimen	| https://loinc.org/sars-coronavirus-2/|
94759-8	| SARS-CoV-2 N overall result, nasopharyngeal specimen	| 	https://loinc.org/sars-coronavirus-2/|
94760-6	| SARS-CoV-2 N gene result, nasopharyngeal specimen	| 	https://loinc.org/sars-coronavirus-2/|
94762-2	| SARS-CoV-2 Ab qualitative	| 	https://loinc.org/sars-coronavirus-2/|
94763-0	| SARS-CoV-2, unspecified specimen	| 	https://loinc.org/sars-coronavirus-2/|
94764-8	| SARS-CoV-2 whole genome	| 	https://loinc.org/sars-coronavirus-2/|
94765-5	| SARS-CoV-2 E gene, serum or plasma	| 	https://loinc.org/sars-coronavirus-2/|
94766-3	| SARS-CoV-2 N gene, serum or plasma	| 	https://loinc.org/sars-coronavirus-2/|
94767-1	| SARS-CoV-2 S gene, serum or plasma	| 	https://loinc.org/sars-coronavirus-2/|
94768-9	| SARS-CoV-2 IgA, serum or plasma	| 	https://loinc.org/sars-coronavirus-2/|
94769-7	| SARS-CoV-2 IgA, serum or plasma	| 	https://loinc.org/sars-coronavirus-2/|
94819-0	| SARS-CoV-2 N gene, unspecified specimen	| 	https://loinc.org/sars-coronavirus-2/|

**Comment by Alexdavv** [comment]
Added within the recent [release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20200519_1589892092).
