### ISSUE TITLE
Coronavirus READ codes

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#316]
Between April and June 2020 new codes relating to coronavirus were added to the READ vocabulary but these are not yet represented in ATHENA. Here is what is in the application:

![image](https://user-images.githubusercontent.com/12911960/83532903-ef129200-a4bc-11ea-80b9-9f0ec0d27920.png)

And here are the codes available in the CPRD/READ code browser. 
![image](https://user-images.githubusercontent.com/12911960/83534475-dd31ee80-a4be-11ea-8b66-62124751fdcc.png)

Can these be added to an upcoming version?

**Comment by Alexdavv** [comment]
Hi @clairblacketer,

These codes are sort of not official since the Read vocabulary is no longer supported by the NHS. The only reference is [this announcement](https://www.scimp.scot.nhs.uk/archives/2733) which explains the local nature of these codes. It looks like some of the systems (EMIS, TPP, Vision) added SNOMED equivalents using the placeholders in vocabs, [look here on slide 15](https://publichealth.jmir.org/2020/2/e18606/PDF) or [here](https://covid19-phenomics.org/#section-primary-care-terms-ctv3).

Please let us know, what's is your understanding of how these codes should be managed: locally through the custom mapping or we still can manually introduce them into the Read terminology?

**Comment by clairblacketer** [comment]
Hi @Alexdavv so I got these codes from the CPRD GOLD code browser so these are codes coming in through Vision. Since these exist in CPRD GOLD and will be there for all users of that data product I would recommend manually introducing them rather than keeping it local.

**Comment by Alexdavv** [comment]
@clairblacketer 
Can you please provide an electronic version of this list?
Thanks!

**Comment by cgreich** [comment]
@clairblacketer: Now that we are at it, can you run a diff in CPRD and list out all missing Read codes in computer readable format (not bitmap)? The Terminology Server of the NHS no longer updates that vocabulary.

**Comment by clairblacketer** [comment]
Hi @Alexdavv here is a [csv](https://github.com/OHDSI/ETL-LambdaBuilder/blob/master/docs/CPRD/Vocab%20Updates/COVID_Read_codes.csv) with these codes and their descriptions.

@cgreich once I get the June download of data I should be able to do this easily. Right now the online code browser does not allow a diff or search on recently added.

**Comment by ekorchmar** [comment]
Hello @clairblacketer 

Is it possible that other databases that use Read may have introduced their own versions of these concepts with different codes? These seem to be outside of common Read vocabulary.

**Comment by clairblacketer** [comment]
Hi @ekorchmar so these codes were pulled from the CPRD code brower that covers all of CPRD GOLD. GOLD, in turn, is comprised of data from ~15mil people across the UK whose primary care providers use the vision software. CPRD Aurum is comprised of patients whose GPs use the EMIS software. As I understand it, Read codes are only used in GP practices in the UK and are mostly in practices that use vision because EMIS supports use of SNOMED. It is possible that there are other local codes out there but, most likely, the practices that still use Read are represented in GOLD.

**Comment by cgreich** [comment]
@ekorchmar: as @clairblacketer said. Short answer: if there are others they can bring it on. Till then we take these.

**Comment by Alexdavv** [comment]
> Hi @Alexdavv here is a [csv](https://github.com/OHDSI/ETL-LambdaBuilder/blob/master/docs/CPRD/Vocab%20Updates/COVID_Read_codes.csv) with these codes and their descriptions.
> 
> @cgreich once I get the June download of data I should be able to do this easily. Right now the online code browser does not allow a diff or search on recently added.

Thank you!
We will include it to the next release (approx. the middle of the next week).

**Comment by Alexdavv** [comment]
[Published in Athena](https://athena.ohdsi.org/search-terms/terms?vocabulary=Read&page=1&pageSize=15&query=noovel+coronavirus) within the [recent release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20200611_1591872865).
