### ISSUE TITLE
"Clavien-Dindo classification scale grade" OBS --> MEAS

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#317]
I would like to recommend moving this code from the OBSERVATION domain to the MEASUREMENT domain.
`37311606-Clavien-Dindo complication grade`

Here is discussion around how we would like to implement the scale:
https://forums.ohdsi.org/t/classifying-surgical-complications/6276

Tagging @Alexdavv & @aostropolets

**Comment by Alexdavv** [comment]
Also, we need to create the pre-coordinated ones in OMOP Extension.
https://github.com/OHDSI/Vocabulary-v5.0/issues/318
https://forums.ohdsi.org/t/classifying-surgical-complications/6276/24

**Comment by MariaRohozhkina** [comment]
Good news! We've added new precoordinated concepts for Clavien-Dindo complication scale in the last release:
https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20220409_1649488692
