### ISSUE TITLE
Adding Grade Scale Values IIIA, IVA, IVB

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#318]
We are using LOINC to represent the answers to a grade scale ([see discussion here](https://forums.ohdsi.org/t/classifying-surgical-complications/6276)).  However we are missing the following and would like to request OMOP CONCEPT_IDs

- IIIA
- IVA
- IVB
- VI

Tagging @Alexdavv & @aostropolets

**Comment by Alexdavv** [comment]
The decision [here](https://forums.ohdsi.org/t/classifying-surgical-complications/6276) (and in many similar cases) was to pre-coordinate in OMOP Extension. Unless it's done, you can still use values out of the different vocabularies. They're not deduped or standardized anyway.


> * IIIA

https://athena.ohdsi.org/search-terms/terms/36309815


> * IVA

https://athena.ohdsi.org/search-terms/terms/35919361


> * IVB

https://athena.ohdsi.org/search-terms/terms/35919532



> * VI

https://athena.ohdsi.org/search-terms/terms/4118820
