### ISSUE TITLE
Duplicate B-Cell Standard Concepts

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#319]
Are these duplicates?
`4300704	Diffuse large B-cell lymphoma`
`44808122	Diffuse large B-cell lymphoma`

**Comment by cgreich** [comment]
It's worse. Now we have a Nebraska Lexicon one mapped to one of them: 3268374 "Diffuse large B-cell lymphoma".

**Comment by mik-ohdsi** [comment]
4300704 | 404148006 | Diffuse large B-cell lymphoma   <= SNOMED International
Preferred term should be: Diffuse large B-cell lymphoma **(nodal/systemic with skin involvement)**

44808122 | 847741000000106 | Diffuse large B-cell lymphoma  <= exists only in SNOMED UK

We might want to add the missing part to the concept name to show the difference?

**Comment by denyskaduk** [comment]
Unfortunately, they all indicate the same disease. Probably need be done mapping between it where international SNOMED will be standard, with all such terms?

**Comment by m-khitrun** [comment]
Hello,

Please, be informed that the mapping was created from [Diffuse large B-cell lymphoma](https://athena.ohdsi.org/search-terms/terms/44808122) to [Diffuse large B-cell lymphoma (nodal/systemic with skin involvement)](https://athena.ohdsi.org/search-terms/terms/4300704).

Regards,
Masha
