### ISSUE TITLE
New COVID LOINC Codes

### ISSUE THREAD

**Issue by kmkostka** [OHDSI/Vocabulary-v5.0#321]
These COVID LOINC codes are being used by the [N3C Phenotype](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/wiki/Latest-Phenotype) but are not available in ATHENA.

LOINC Code| Name | Provenance
-- | -- | --
95125-1 | SARS-CoV-2 RNA, serum or plasma | https://loinc.org/sars-coronavirus-2/
95209-3 | SARS-CoV-2 RNA, respiratory specimen | https://loinc.org/sars-coronavirus-2/
95406-5 | SARS-CoV-2 RNA, nose | https://loinc.org/sars-coronavirus-2/
95409-9 | SARS-CoV-2 N gene, nose | https://loinc.org/sars-coronavirus-2/
95410-7 | SARS-CoV-2 neutralizing antibody, serum | https://loinc.org/sars-coronavirus-2/
95411-5 | SARS-CoV-2 neutralizing antibody, serum | https://loinc.org/sars-coronavirus-2/

Can you notify when these are released? We will need to cascade this into our phenotype concept set (community version is stored: http://atlas-covid19.ohdsi.org/#/cohortdefinition/1015).

**Comment by Alexdavv** [comment]
Hi, @kmkostka 
It was published in Athena within the [recent release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20200611_1591872865).
