### ISSUE TITLE
Mapping ovarian tumors

### ISSUE THREAD

**Issue by awrosen** [OHDSI/Vocabulary-v5.0#327]
Dear everyone,

I've encountered an issue when trying to map some ovarian tumors. The most common histological subtype is called surface epithelial-stromal tumors. A subtype of these tumors are called 'Brenner tumors'. However, in the common vocabulary, the concept 'Brenner tumor' is considered a synonym surface epithelial-stromal tumor. Thus the subtype and parent appear to be equal.  https://athena.ohdsi.org/search-terms/terms/35625720

**Comment by cgreich** [comment]
@awrosen:

Yeah, this looks a little strange. We need to bring it up with SNOMED. 

However, the generic Brenner tumor seem to me a histological category. In real cases, you have [malignant](https://athena.ohdsi.org/search-terms/terms/4173156), [borderline](https://athena.ohdsi.org/search-terms/terms/4234377) or [benign](https://athena.ohdsi.org/search-terms/terms/4099817) versions. Those are clean concepts. I would use those.

**Comment by awrosen** [comment]
@cgreich:

That sounds great. Thank you for the feedback. Unfortunately, most of our tumors are of the subtype 'surface epithelial-stromal tumors', since 'Brenner tumors' are an uncommon subtype of these, so this would still imply a special case of tumors, which our data does not support.

**Comment by m-khitrun** [comment]
@awrosen 
We have reported this issue to SNOMED editors and received the following reply:

"The non-semantically equal synonym that you refer to in your request has been inactivated. Many thanks for informing us of this inaccuracy.  

The change will be available in the 1st August release of SNOMED CT subject to the usual review process.

Based on the WHO ICD-O-3.2 classification, and aligned with the WHO Blue books we have 3 neoplastic morphologies for Brenner tumor:
253051001 |Benign Brenner tumor (morphologic abnormality)|
42194009 |Brenner tumor, malignant (morphologic abnormality)|
89996007 |Brenner tumor, borderline malignancy (morphologic abnormality)|"

Please, note, that our Summer 2024 release will not include these changes yet.

Kind regards,
Masha
