### ISSUE TITLE
LOINC code with 1-day valid period

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#331]
I have ~3mil records in one of my databases with the LOINC code 24365-9, concept [3022113](https://athena.ohdsi.org/search-terms/terms/3022113). All of these records are mapped to zero but it looks like it's because the LOINC code was only valid for one day in June of 2015. Is this correct?

**Comment by cgreich** [comment]
No. Because it is a panel. You can't have a panel in the measurement table. You need one measurement at a time. The source data will have that (hopefully). This thing is just a bucket.

**Comment by Alexdavv** [comment]
Panels are Standard in LOINC, though. So the technical reason is that we added this concept after it had been already deprecated by the source.

> The source data will have that (hopefully)
Yes, it would be great if you can extract this.

If no, considering how the results recorded in the source, mapping to [Microscopic observation [Identifier] in Urine sediment by Light microscopy](https://athena.ohdsi.org/search-terms/terms/3038224) might be applied. At least we're planning to use this mapping in our ongoing work on deprecated LOINCs.
