### ISSUE TITLE
Townsend deprivation index

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#332]
https://en.wikipedia.org/wiki/Townsend_deprivation_index

One of the datasets we have has a score called Townsend Deprivation Index.  We would like to store this in the OBSERVATION or MEASUREMENT table with a standard concept.  For now we'll just use the 2B+ but I would like to make a request for a formal code.

**Comment by MariaRohozhkina** [comment]
Good news! We have added this concept in the new release:
https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20220409_1649488692
