### ISSUE TITLE
Duplicate: Heart Rate

### ISSUE THREAD

**Issue by dlaxar** [OHDSI/Vocabulary-v5.0#344]
Consider a heart beating at a certain rate. Following the ideas of standardized concepts as I understand them, I'd expect the _Standard Vocabulary_ to contain exactly one _concept_id_ that is both valid and standard, representing exactly the fact, that a heart beats at a certain rate.

However, as of now, there are two concepts in the _Measurement_ Domain, that represent the same fact:

- 4239408, the SNOMED "Heart rate"
- 3027018, the LOINC "Heart rate"

I propose to deprecate either of the concepts in favor of the other. 

Initial discussion of this topic can be found here: https://forums.ohdsi.org/t/measurement-entity-which-vocabulary-to-consider/5813/8

**Comment by dlaxar** [comment]
Here's a list of different heart rate measurements that are valid and standard. Other than the two mentioned above all of them seem to describe a somewhat different concept.

https://athena.ohdsi.org/search-terms/terms?standardConcept=Standard&domain=Measurement&invalidReason=Valid&page=1&pageSize=15&query=%22heart+rate%22

**Comment by dimshitc** [comment]
Thanks for reporting!
It's a known issue when SNOMED duplicates LOINC.
There's an ongoing effort to standardize SNOMED measurements.
Once we have the results to share we'll let you know.
Tagging @p-talapova and @mik-ohdsi

**Comment by m-khitrun** [comment]
Hello,

Please, be informed that we have performed the deduplication of these concepts with SNOMED being mapped to LOINC.

Regards,
Masha
