### ISSUE TITLE
LOINC update needed 

### ISSUE THREAD

**Issue by kmkostka** [OHDSI/Vocabulary-v5.0#346]
LOINC vocab was last updated in OHDSI vocab 11-JUN-20. 

[LOINC issued version 2.68 on 2020-06-17](https://loinc.org/downloads/archive/). As of 07-AUG-20 release, this has still not been incorporated into the OHDSI vocabularies. Can this be added to the next vocab release?

**Comment by Alexdavv** [comment]
Hi @kmkostka,
We're working on this since LOINC released it. Will try to release it shortly.

**Comment by Alexdavv** [comment]
@kmkostka New LOINC has been just released in Athena.
