### ISSUE TITLE
CONCEPT_NAME with \t in it

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#35]
**VERSION v5.0 21-Mar-2015**

The following concept has a tab in the name.  Between "task 	due"

```{sql}
concept_id	concept_name
45877004	Large-amplitude (>2 cm), violent, jerky tremor resulting in difficulty completing the task 	due to spilling or inability to hold a pen to paper
```

**Comment by leeevans** [comment]
This issue has been fixed in the latest file available on the vocabulary download web site.
