### ISSUE TITLE
Hydroxychloroquine Oral Suspensions

### ISSUE THREAD

**Issue by burrowse** [OHDSI/Vocabulary-v5.0#350]
Hello, we have the Hydroxychloroquine 25MG/ML Oral Suspension present in our source data but there is only [Hydroxychloroquine 24 MG/ML Oral Suspension](https://athena.ohdsi.org/search-terms/terms/21125529) present in the database. Is it possible to get the 25MG/ML added ? Thank you!

**Comment by cgreich** [comment]
You do, @burrowse? It doesn't sell in the US as suspension, only in the UK and other countries. There it is 120 mg/teaspoon (=5 mL), which comes out to 24 mg/mL). What are you administering your patients? :)

**Comment by burrowse** [comment]
@cgreich Moving conversation to [forum post](https://forums.ohdsi.org/t/hydroxychloroquine-oral-suspensions/11683) per request :)

**Comment by mik-ohdsi** [comment]
closing issue, @cgreich explained the approach in the forum.
