### ISSUE TITLE
ICD10CM C54.1 and ICD10 C54.1 - Difference in mapping

### ISSUE THREAD

**Issue by mfernandezchas** [OHDSI/Vocabulary-v5.0#351]
I came across **ICD10CM C54.1 - Malignant neoplasm of endometrium** required for a cancer study and I noticed it has been mapped as follows:

**Non-standard to Standard map (OMOP)**:
Name: _Neoplasm of endometrium_
Concept Id: 4048225
Vocabulary: SNOMED

I would like to know if there is a reason for this mapping to be different from the mapping of **ICD10 C54.1 - Malignant neoplasm: Endometrium** described below:

**Non-standard to Standard map (OMOP)**
Name: _Primary malignant neoplasm of endometrium_
Concept Id: 4247238
Vocabualry: SNOMED

My concern is that the first mapping would also retrieve patients with benign growths which won't be of interest in a cancer study.

Thanks!

**Comment by p-talapova** [comment]
The issue is already fixed.
https://athena.ohdsi.org/search-terms/terms/35206248
