### ISSUE TITLE
ICD10 concepts not mapped, but ICD10CM concepts with same concept_code and name are

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#353]
There are a number of ICD10 codes that have the same code and description as their ICD10CM counter part, where the ICD10CM code is mapped but the ICD10 is NOT.

In vocab release v5.0 28-MAR-19 the following query list 48 ICD10 concepts

SELECT concept_id, target_concept_id, 'Maps to', valid_start_date, valid_end_date
FROM
(
  SELECT concept_id, concept_code, concept_name
  FROM concept
  WHERE vocabulary_id = 'ICD10'
    AND invalid_reason IS NULL
    AND concept_id NOT IN
    ( SELECT concept_id_1
        FROM concept_relationship
        WHERE relationship_id = 'Maps to'
    )
 ) ICD10
JOIN
(
  SELECT concept_code, concept_name, concept_id_2 AS target_concept_id, rel.valid_start_date, rel.valid_end_date
  FROM concept
  JOIN concept_relationship rel ON relationship_id = 'Maps to' AND concept_id_1 = concept_id
  WHERE vocabulary_id = 'ICD10CM'
)ICD10CM
ON ICD10CM.concept_code = ICD10.concept_code AND ICD10CM.concept_name = ICD10.concept_name;

**Comment by mik-ohdsi** [comment]
this query did not return any hits as of today, closing this issue
