### ISSUE TITLE
Zoster Vaccine - NDC 58160082903 - Not Mapped

### ISSUE THREAD

**Issue by mfernandezchas** [OHDSI/Vocabulary-v5.0#355]
Hi,

The following vaccine doesn't seem to have been mapped. Would you be able to update it?

NDC 58160082903 - 0.5 ML Varicella zoster virus glycoprotein E, recombinant 0.1   MG/ML Injection [Shingrix]

Many thanks,

Margarita

**Comment by Alexdavv** [comment]
It's mapped now.
