### ISSUE TITLE
Year prior to 1900 in concept_relationship table in 17-MAR-19

### ISSUE THREAD

**Issue by nishanthpp93** [OHDSI/Vocabulary-v5.0#358]
The All of Us Research Program has been using `v5.0 22-DEC-17` and we are planning to upgrade to `v5.0 17-MAR-19`. In the concept_relationship table in `v5.0 17-MAR-19`, there seem to be dates like `01-01-0001` and `05-17-0017`. They can be found using the query

```sql
SELECT
    cr.valid_start_date d,
    COUNT(1) n
FROM v.concept_relationship cr
GROUP BY d
ORDER BY d
```

d | n
--- | ---
0001-01-01 | 16
0017-05-17 | 428
0017-05-23 | 4
0017-05-25 | 8

Digging in further, they seem to be coming from the PPI vocabulary (AllOfUs_PPI). 

```sql
SELECT
    c.valid_start_date concept_date,
    crn.valid_start_date crn_date,
    c.*
FROM v.concept_relationship crn
JOIN v.concept c
ON crn.concept_id_1 = c.concept_id
WHERE crn.valid_start_date < '1900-01-01'
ORDER BY crn_date
```

![Screen Shot 2019-04-04 at 3 56 00 PM](https://user-images.githubusercontent.com/9842056/55584436-3010ea00-56f2-11e9-8bbf-cffdab6aac41.png)

At first glance it appears as though some of the `0017-05-17` dates might be a typo. I used the following query to investigate:

```sql
SELECT
    c.valid_start_date concept_date,
    crn.valid_start_date crn_date,
    COUNT(1) n
FROM v.concept_relationship crn
JOIN v.concept c on crn.concept_id_1 = c.concept_id
WHERE crn.valid_start_date = '0017-05-17'
GROUP BY concept_date, crn_date
```

concept_date | crn_date | n
--- | --- | ---
2017-05-17 | 0017-05-17 | 216
2017-05-26 | 0017-05-17 | 210
2017-04-24 | 0017-05-17 | 2

Is there a particular reason the dates were chosen that way?

**Comment by TinyRickC137** [comment]
This issue is fixed
