### ISSUE TITLE
Can the SNOMED code '59000001' be moved to the Procedure domain?

### ISSUE THREAD

**Issue by mgurley** [OHDSI/Vocabulary-v5.0#361]
SNOMED code '59000001' is 'Surgical pathology consultation and report on referred slides prepared elsewhere".  This is the only concept I can find within OMOP that represents a pathology procedure performed on outside slides.  This SNOMED code lives within the SNOMED Procedure axis and it has a 'Pocedure' concept class.  Currently this concept (4244107) is placed in the 'Observation' domain.  I believe it should be in the 'Procedure' domain.  We at Northwestern have important use cases surrounding pathology procedures/reports.  Being able to distinguish between In-house and outside surgical pathology procedures would help serve those use cases.

**Comment by Alexdavv** [comment]
> yes, they are procedures.

It still lives in the Observation Domain.
Are you agreed on something?

**Comment by mgurley** [comment]
Can this be completed?  It looks like the final decision was to move it into the procedure domain.   We are getting dinged on data quality checks because we override it locally

**Comment by cgreich** [comment]
Remind us why this is a Procedure?

**Comment by mgurley** [comment]
> As I said, I am no ideolog. If "Me" (=@mgurley) thinks that way - I am all for it. Procedures they are. :)

**Comment by mgurley** [comment]
> Remind us why this is a Procedure?
See above.  And here for explanation:

https://forums.ohdsi.org/t/how-to-store-pathological-examination-result-in-cdm/8032/4

But the upshot is that all pathology procedures should be within the same domain. Not scattered across many.  A pathology procedure yields many measurements that are normally recorded within a note.  I would say common sense within the healthcare domain views pathology examinations as a paradigmatic diagnostic **procedure**.  So can we please move this concept into the procedure domain and change the definition of a procedure to align common practice.

"The PROCEDURE_OCCURRENCE table contains records of activities or processes ordered by, or carried out by, a healthcare provider on the patient, **OR A SPECIMEN EXTRACTED FROM THE PATIENT**, to have a diagnostic or therapeutic purpose. Procedures are present in various data sources in different forms with varying levels of standardization."

**Comment by TinyRickC137** [comment]
Hello, @mgurley 
Finally, 59000001 'Surgical pathology consultation and report on referred slides prepared elsewhere' has been moved to Procedure domain. 
The release will be soon accessible in Athena, at the moment you can check the release notes [here](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20220829_1661776786)

**Comment by mgurley** [comment]
Hip Hip Hooray!
