### ISSUE TITLE
minimum standard for release notes, standardized metrics for each release

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#363]
It can be hard to know what has changed in a release.
Minimum standard should be that just bullet point is not specific enough. Perhaps we should consider to ahve at least one sentence must be added to a bullet point.

See example below. It is not clear what changed for SNOMED.

![image](https://user-images.githubusercontent.com/7526119/45364780-01da8a00-b5a9-11e8-8d77-97ccbbe597f9.png)

Also, having a standard script count active concepts and retired concepts and have that metric be part of release notes would be good.

**Comment by Alexdavv** [comment]
Now we provide detailed [statistics](https://github.com/OHDSI/Vocabulary-v5.0/releases).
Also, some comments will be added soon.
