### ISSUE TITLE
Request for new cost concepts

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#364]
I would like to request two new cost-concepts.

concept_id | code | name | class | concept | validity | domain | vocab
-- | -- | -- | -- | -- | -- | -- | --
to   be assigned | OMOP generated | Patient liability | Summary | Standard | Valid | Cost | Cost
to be assigned | OMOP  generated | Patient liability | Detail | Standard | Valid | Cost | Cost

**Comment by Alexdavv** [comment]
https://athena.ohdsi.org/search-terms/terms?standardConcept=Standard&page=1&pageSize=15&query=Actual+acquisition+cost
