### ISSUE TITLE
Create concepts for all tables and fields

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#367]
This is in relation to CommonDataModel issue [#164](https://github.com/OHDSI/CommonDataModel/issues/164) and [#172](https://github.com/OHDSI/CommonDataModel/issues/172). We would like to create concept_ids for all tables and fields in the CDM

**Comment by Alexdavv** [comment]
Was done some time ago, [look](https://athena.ohdsi.org/search-terms/terms?domain=Metadata&conceptClass=Field&conceptClass=Table&page=1&pageSize=15&query=).
