### ISSUE TITLE
Character Encoding Types needed for Note Table

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Vocabulary-v5.0#371]
Current DDL (v5.3):

encoding_concept_id | Yes | integer | A foreign key to the predefined Concept in the Standardized Vocabularies reflecting the note character encoding type
-- | -- | -- | --

@cgreich, @clairblacketer do we actually  have this in the vocab? What should we use for UTF-8?

**Comment by cgreich** [comment]
We do: [32678](https://athena.ohdsi.org/search-terms/terms/32678)
