### ISSUE TITLE
Standard Mapping of ICD-10 c22.7 'Other specified carcinomas of liver'

### ISSUE THREAD

**Issue by awrosen** [OHDSI/Vocabulary-v5.0#377]
Dear everyone,

Is there a specific reason that ICD-10 c22.7 is mapped to SNOMED 'Liver cell carcinoma' ID 4001171? The concept 'Primary malignant neoplasm of liver' ID 201519 seems more fitting to me, since the ICD-10 concept refers to 'other' and the liver cell carcinoma is specified in c22.0.

KR

Andreas

**Comment by divakhnenko** [comment]
Hello Andreas, thank you for your interest in this topic. You are right, ICD-10 concept of "С22.7 Malignant neoplasm: Other specified carcinomas of liver" which is currently mapped to more generic concept "4001171	109841003	Liver cell carcinoma", should be remapped to "4094864	187769009	Primary carcinoma of liver".  Thus we will not miss the histological type of a neoplasm. We suggest fixing this issue during our scheduled release.

**Comment by irinazherko** [comment]
We are pleased to inform you that the issue has been successfully corrected during the February 2024 Release.
