### ISSUE TITLE
Two concepts incorrectly rolled up to disorder of male genital organ

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#378]
The [DQD](https://github.com/ohdsi/dataqualitydashboard) has been identifying many issues with the concept 197605 because often women have records that roll up to this code. Upon further investigation it looks like it is a vocabulary issue. ICD9CM codes [616.8](https://athena.ohdsi.org/search-terms/terms/44834851) and [616.89](https://athena.ohdsi.org/search-terms/terms/44837204) are both rolling up to 197605 (inflammatory disease of male genital organ) though they both stand for inflammatory diseases of cervix, vagina, and vulva.

**Comment by mik-ohdsi** [comment]
Dear @clairblacketer, 
this is a duplicate to issue #267 and Don was quicker than the DQD. ;-) 
But please let us know more about discrepancies that you detect with the DQD.
Good news are that we finally get to fixing this one. Expect it to be solved by an ICD9CM refresh in the near future.
~ Mik

**Comment by p-talapova** [comment]
The good news, we have finally fixed these mappings.
