### ISSUE TITLE
Type Concepts not standard anymore? 

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Vocabulary-v5.0#380]
Running Tantalus showed that compared to the June 11th release all the concept type concepts are not standard anymore.

Is there a reason for this change ? Did I miss something?

![image](https://user-images.githubusercontent.com/7252105/91640869-f811f180-ea20-11ea-827c-d04e5987ae1c.png)

I am testing putting all the vocab releases under actual version control and that also confirms this change nicely:

![image](https://user-images.githubusercontent.com/7252105/91640835-bc772780-ea20-11ea-92e5-cd77a7bdf577.png)

**Comment by Alexdavv** [comment]
Look: https://forums.ohdsi.org/t/important-vocabulary-release-type-concept-and-condition-status/11760

**Comment by PRijnbeek** [comment]
Great thanks.

**Comment by PRijnbeek** [comment]
Do still have some questions @Alexdavv 

1. Was there a way we could have seen this coming for this release on a roadmap? This will have impact in all the 45 ETLs we are working on. 

2. For example observation period we now have only one option it seems? or do we need to look for other things now? 

![image](https://user-images.githubusercontent.com/7252105/91643314-47ace900-ea32-11ea-8a28-e331b7072cdb.png)

3. This does break functionality in Rabbit-in-a-hat where you could nicely see the options for the type field. 

Thanks for your help

**Comment by cgreich** [comment]
@PRijnbeek:

1. Yes: https://forums.ohdsi.org/t/concept-type-consolidation-please-take-a-look/8306
2. The Type Concepts are no longer attached to the Domains. So, if you infer your Observation Period from claims records you would point that out.
3. What's broken there?

**Comment by PRijnbeek** [comment]
Thanks. I understand the challenges ...

1. I saw this but it is a long discussion over a change that is going to happen with a last post in june. What i mean is if there is a way i could have known this ETL breaking change would happen in August? It is i think almost impossible for all data owners to participate in all these discussions. We need to find a way to better communicate this. I saw a tag in the message of @Alexdavv but there are way more people that are doing ETL in the world. Good thing is that DQD will flag it if they miss this in this case. I will discuss this also with the EHDEN vocabulary people to make sure these things are communicated in advance to our teams.
2. I understand but that means we loose the Period while enrolled in insurance or the often used Period covering health encounters correct? Not saying it is bad (as long as they share the ETL Document and make this clear) but we need to be able to explain this in workshops we are doing and need to update all on this that already had their ETL workshop.
3. In Rabbit-in-a-hat you can click on the type field in a table and it will show the concept_ids that would belong to that domain. This will not be possible anymore and will require code fixes i think. We would now experience this issue if a data partner is onboarded and downloads the latest version of the vocabulary (and they have no other choice).

**Comment by cgreich** [comment]
1) I agree. But I don't have a good idea. The CDM category of the Forum was supposed to accomplish this, so folks could subscribe to only that one if they are involved in ETL.
2) Not sure I am following. The Type Concepts should have no effect of what records you write. It should only tell where you got the information from.
3) I had no idea it does that. Yes, then we crashed it. Sorry about that. Is Maxim in charge of maintenance?

**Comment by mik-ohdsi** [comment]
@PRijnbeek - can we close this issue or is there something that needs fixing?

**Comment by mik-ohdsi** [comment]
almost two years later - I guess we can close the issue now. (doesn't mean I do not feel your pain at that time @PRijnbeek )
