### ISSUE TITLE
Acetaminophen NDCs include latex gloves

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#384]
Hi all,

I’ve got a concept set for the RxNorm ingredient of Acetaminophen (concept id 1125315) and all its descendants.

When I inspect the NDCs coming along for the ride, I’m seeing some strange descriptions:

BLOOD PRESSURE MANUAL KIT
LATEX GLOVES-MEDIUM
LATEX GLOVES
LATEX GLOVES
VINYL GLOVES
VINYL GLOVES
LATEX GLOVES
LATEX GLOVES-SMALL

When I inspect one of these NDCs, it appears that the LATEX GLOVES-MEDIUM NDC is mapped to “acetaminophen 325 MG / guaifenesin 200 MG / phenylephrine hydrochloride 5 MG Oral Tablet)”, which doesn’t seem right:

https://athena.ohdsi.org/search-terms/terms/45167797

Thanks,
Ajit

**Comment by aostropolets** [comment]
Concept re-use! They used to be paracetamol and now NDC decided to assign those codes to gloves. Tagging @Alexdavv

**Comment by alondhe** [comment]
@aostropolets -- ah! Is there any good way to identify these re-used ids, or just I'd need to inspect the concept names?

**Comment by aostropolets** [comment]
There is a small list here https://forums.ohdsi.org/t/ndcs-changing-over-time/903/2 + requests here and there. Unfortunately, there is no single database of reused NDCs, so for now inspecting the names will be the safest albeit time-consuming option

**Comment by TinyRickC137** [comment]
Better late than never! 

We fixed this. However, NDC reuse is not yet fully addressed in the OMOP Vocabularies. The overhaul of the Drug domain is coming and we hope to address this issue among others.
