### ISSUE TITLE
No replacement concepts for concepts with invalid reason 'U', updated

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#386]
Version: v5.0 28-AUG-20

Select count(*)
     ,SUM( case when relationship_id IS NOT NULL THEN 1 ELSE 0 END) AS has_replacement
     ,SUM( case when relationship_id IS NULL THEN 1 ELSE 0 END) AS no_replacement
FROM concept
LEFT OUTER JOIN concept_relationship ON relationship_id = 'Concept replaced by' AND concept_id_1 = concept_id
WHERE concept.invalid_reason = 'U';

count | has_replacement | no_replacement
-- | -- | --
405005 | 245589 | 159416

**Comment by Alexdavv** [comment]
SNOMED has a couple of subtypes for 'Concept replaced by'.
Here is a full list:

```
Select count(*)
,SUM( case when relationship_id IS NOT NULL THEN 1 ELSE 0 END) AS has_replacement
,SUM( case when relationship_id IS NULL THEN 1 ELSE 0 END) AS no_replacement
FROM concept
LEFT OUTER JOIN concept_relationship ON relationship_id IN ('Concept replaced by',
                                                            'Concept same_as to',
                                                            'Concept alt_to to',
                                                            'Concept poss_eq to',
                                                            'Concept was_a to')
    AND concept_id_1 = concept_id
WHERE concept.invalid_reason = 'U';
```

count | has_replacement | no_replacement
-- | -- | --
492130 | 492125 | 5

**Comment by don-torok** [comment]
Now two people know about these other relationships ;)
