### ISSUE TITLE
Separate Outpatient Hospital codes that roll up to 9202

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#387]
Currently, outpatient hospital visit concept ids roll up to the high-level concept 9202. Here is the standard concept for outpatient hospital: https://athena.ohdsi.org/search-terms/terms/8756

I think they should be considered as separate from the high-level outpatient. Outpatient hospitals handle procedures slightly more complicated that those that can be completed in an office but slightly less complicated that those done in an inpatient setting. When you look at the average length of stay for visits with concept id 9202 it should be 0 but it is artificially inflated by those occasional times when a person has to stay overnight at an outpatient hospital.

**Comment by cgreich** [comment]
If they stay overnight it is an inpatient hospital by definition. Even though it says "Outpatient Clinic" on the door. One day, patient comes to the healthcare provider = outpatient. More than one day, bed, providers come to the patient = inpatient.

**Comment by Alexdavv** [comment]
When we say 'Inpatient Hospital' it basically implies 'Hospital Inpatient visit' and does not reflect the hospital type.
So it would be better to rename, but we can't since they're from the external vocabs.

**Comment by clairblacketer** [comment]
ok that makes sense. I will re-categorize those records
