### ISSUE TITLE
concept_name and concept_synonym_name exceeding the character limit set in DDL

### ISSUE THREAD

**Issue by ksdkalluri** [OHDSI/Vocabulary-v5.0#389]
We tried to download the latest vocabulary and could not load the vocabulary without updating the schema for the `concept_name` column in `concept` and `concept_synonym_name` in `concept_synonym` tables.
A size error was returned for the concept table and concept_synonym tables due to values columns exceeding the size limit.

The DDL at https://github.com/OHDSI/CommonDataModel/blob/master/Sql%20Server/OMOP%20CDM%20sql%20server%20ddl.txt states the limit was set to `varchar(255)` for `concept_name` and `varchar(1000)` for `concept_synonym_name`.

There were 292 concepts violating the max length in the concept table and 2 concepts in the concept_synonym table.

Interestingly, Athena displays the truncated version of the concept name and concept synonyms as well, e.g. https://athena.ohdsi.org/search-terms/terms/35942558 and https://athena.ohdsi.org/search-terms/terms/40652442. I guess Athena's backend also truncated the data without issuing an error.

Attached are the list of concepts and the length of the corresponding concept_names and concept_synonym_names that are violating the character limit set in the DDL.

[concept_synonym_schema_violators.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/5256915/concept_synonym_schema_violators.xlsx)
[concept_schema_violators.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/5256920/concept_schema_violators.xlsx)

**Comment by mark-velez** [comment]
I hope this can be addressed. This will be an issue for 50 sites in the AOU project when they try to load the vocabulary.

**Comment by cukarthik** [comment]
@dimshitc @cgreich  is this the same issue as this forum [post](https://forums.ohdsi.org/t/length-of-concept-name/6432/9)?

**Comment by mik-ohdsi** [comment]
@cukarthik it is more likely that it is similar to this [issue](https://github.com/OHDSI/Vocabulary-v5.0/issues/253).

@ksdkalluri and @mark-velez : can you check your load routines? the source field content in the csv files does not exceed the character limit. The abundance of quotation marks and pipe symbols in those NAACCR measurement values could theoretically be the culprit here. Do you need NAACCR for AllofUs?

Please get back to us, if this solved the problem.

Thanks
 Mik

**Comment by cukarthik** [comment]
@mik-ohdsi, we need NAACCR since some sites might be using it and we'll need it in the future.  

I just downloaded the newest version of our vocabulary bundle on Athena, and I don't see this issue. It seems to only exist in the version (28-AUG-20) we downloaded last month. There's not way to go back and re-download that version, so I can't confirm if it's something wrong w/ the version specifically or an issue we introduced when running cpt.sh, which is unlikely.

**Comment by mik-ohdsi** [comment]
Has this issue resolved and can we close it? 
Thanks ~ Mik

**Comment by mik-ohdsi** [comment]
Hi!
@cukarthik , @ksdkalluri and @mark-velez - we had made this a high priority issue. Please let us know if the problem persists or if the issue can be closed.
Thank you so much for your cooperation!
Cheers 
 Mik

**Comment by ksdkalluri** [comment]
@mik-ohdsi There weren't any issues while Karthik tried to download new vocabulary and try to upload it. But I am still seeing that issue when I downloaded it yesterday. I will work with Mark today to see if there is anything that's on our side which need's to be fixed.

**Comment by ksdkalluri** [comment]
@mik-ohdsi It's a database-specific issue, It's been resolved now. 
Thanks for following up with us.

**Comment by mik-ohdsi** [comment]
@ksdkalluri 
Krishna, would you like to tell us how you resolved this. It might be valuable information for others encountering this or a similar issue. Can you provide suggestions how the load scripts could be improved to prevent this from happening?
Thanks
 Mik

**Comment by mark-velez** [comment]
Hi @mik-ohdsi. This has to do with our process for loading the vocabulary files. In BigQuery there is no way to ingest the vocabulary files in the format provided by Athena without doing some ETL on them first- date fields must be converted from `yyyymmdd` format, and, as in this case, some ETLs will give some characters special treatment. Our [Python-based ETL was](https://github.com/all-of-us/curation/blob/develop/data_steward/tools/load_vocab.sh#L64) encoding `"` as described [here](https://stackoverflow.com/a/17808731) and also [RFC-4180](https://tools.ietf.org/html/rfc4180#section-2) but BigQuery just interprets these as additional `"` characters in the text field. Our solution was to move some of the transforms from Python to BigQuery.

It would be wonderful if Athena would allow users to specify some of these file format parameters prior to download- we might more easily share our bundles with the 50 OMOP sites. Should we submit a separate issue for this? If this is on your team's roadmap, we'd be happy to help out with testing.

**Comment by mik-ohdsi** [comment]
Can you try to specify the requirements in more details? What would you need Athena to do? Produce DB specific versions of the download? In either way, this would definitely justify to create a separate issue / request. It might probably also call for a discussion on the forum. Following that we could learn the need in the community for that enhancement. For now I will close this issue.
Thanks ~ Mik

**Comment by pjlammertyn** [comment]
There is a difference in the number of characters and the number of bytes. In the [DDL file](https://github.com/OHDSI/CommonDataModel/blob/main/inst/ddl/5.4/sql_server/OMOPCDM_sql_server_5.4_ddl.sql#L464C4-L464C25) for SQL Server, the concept_synonym_name of the concept_synonym table, is a varchar(1000). A varchar is 8 bit (see [Single-byte and multibyte character sets](https://learn.microsoft.com/en-us/cpp/c-runtime-library/single-byte-and-multibyte-character-sets?view=msvc-170)). So in the concept_synonym_name column only 1000 bytes can be stored! But it seems that multibyte characters are used in the vocabulary CSV's!
I put the vocabulary CSV's that we are using in a dataframe, and calculated the max character length and the max byte length:
![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/1187178/305433cf-a103-48a6-9dc0-8e89c84a1d6a)
