### ISSUE TITLE
New COVID ICD10PCS codes 

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#392]
Hi,

We should add the new ICD10PCS codes issued by CMS for COVID-19 therapeutics (like remdesivir and convalescent plasma):

https://www.cms.gov/files/document/icd-10-ms-drgs-version-372-effective-august-01-2020.pdf

Thanks,
Ajit

**Comment by TinyRickC137** [comment]
@alondhe these codes were added, we really hope you found them!
