### ISSUE TITLE
update Athena downloads with latest UMLS. 

### ISSUE THREAD

**Issue by vagarwal77** [OHDSI/Vocabulary-v5.0#394]
Current UMLS version is outdated by 30 months. 
Can we get the UMLS refreshed or suggest who we can contribute for the same? 

Without latest UMLS, it is not a starter for us.

**Comment by mik-ohdsi** [comment]
Hi,
I am afraid we need a bit more background. Which part of UMLS are you referring to?
There is no vocabulary "UMLS" in Athena, but a number of important distinctive ones that are part of UMLS such as SNOMED, LOINC, CPT4 and others. 
What are you after and what do you mean with starter?
Kind regards
 Mik

**Comment by mik-ohdsi** [comment]
Hi @vagarwal77 
any additional information you could share with us?
Thanks 
 Mik

**Comment by vagarwal77** [comment]
We are looking a refresh for NCIT which had not been refreshed from Jan 2018.  ODHSI has 2226  concepts for NCIT but UMLS have 146993 for NCI.          	

NCItNCI Thesaurus (National Cancer Institute)01-Jan-2018

Please suggest how we can help to prioritize this request?

**Comment by mik-ohdsi** [comment]
Hi @vagarwal77 
This NCIt vocabulary has been created from the latest available data cut to support a particular Oncology use case around Gene variants. It is unfortunately not the complete NCI Thesaurus. Please review this [post](https://forums.ohdsi.org/t/newly-added-standardized-vocabularies/11687/2?u=mik) in the forum. 
The date that you see in Athena downloads does not reflect the the time of update but the release date of the source. The NCIt data source that has been used was valid starting January 2018 and apparently a more recent version has not been yet released.
@cgreich could tell you more about this and the plans around completion and maintenance of NCIt.
Out of curiosity: what is your full name and for which organisation are you speaking?

Kind regards
 Mik
(Michael Kallfelz - Odysseus Data Services)

**Comment by vagarwal77** [comment]
Thanks Mik. Looking forward to NCIt plans. 

Thanks
Vivek Agarwal
ConcertAI

**Comment by mik-ohdsi** [comment]
Additions to NCIt will remain on the long term roadmap.
