### ISSUE TITLE
Secondary malignant neoplasms no longer Conditions, but Measurements (Cancer Modifiers)

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Vocabulary-v5.0#399]
All SNOMED/ICD* and similar starting with "Secondary malignant neoplasm of.." is no longer a Condition. It is a modifier to a Primary neoplasm. Therefore we need to:

- For standard ones (in SNOMED), we have to de-standardize them
- For all of them we need to maintain the mapping to the equivalent concepts in the "Cancer Modifier" vocabulary.
- Existing Maps to have to be protected from overwrites when those other vocabularies get refreshed.

**Comment by Alexdavv** [comment]
Are they just modifiers for neoplasms or neoplasms by itself + modifier?
So why not to map to SNOMED "Malignant neoplasm of..." also?

**Comment by cgreich** [comment]
They are just modifiers. Not Conditions in their own account.

**Comment by Alexdavv** [comment]
> a modifier to a Primary neoplasm

If there are no crosswalks provided, what would be a primary neoplasm concept then?

**Comment by cgreich** [comment]
Well, we haven't added them, it was a hotfix job with Dima on holiday 3 minutes before 12. But we have them.

**Comment by m-khitrun** [comment]
Hello,

Please, be informed that SNOMED secondary neoplasms are now mapped to Cancer Modifier.

Regards,
Masha.
