### ISSUE TITLE
Review ICD9 codes that map to multiple SNOMED concepts

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#40]
We accept that some ICD9 codes that have composite meanings must be decomposed into 2 or more SNOMED concepts.

However, upon review of the ICD9 codes that map to multiple SNOMED concepts, some seem unnecessarily redundant.

As a general principle, I would recommend that if the ICD9 code has a map with a verbatim string match in SNOMED, I think we should have had additional mappings.

Examples of mappings that could potentially be revised:

![image](https://cloud.githubusercontent.com/assets/731930/6956524/c8f1f262-d8bd-11e4-8892-4837935311b1.png)

Here's the SQL to pull out the multiple codes, which I used to examine these:

select t1.*, c2.concept_id, c2.concept_name
from
(
select c1.concept_id, c1.concept_name, c1.concept_code, count(c2.concept_id) as num_maps
from
(
select *
from concept
where vocabulary_id = 'ICD9CM'
) c1
inner join concept_relationship cr1
on c1.concept_id = cr1.concept_id_1
and relationship_id = 'Maps to'
inner join concept c2
on cr1.concept_id_2 = c2.concept_id
and c2.vocabulary_id = 'SNOMED'
where c2.invalid_reason is null
group by c1.concept_id, c1.concept_name, c1.concept_code
having count(c2.concept_id) > 1
) t1
inner join concept_relationship cr1
on t1.concept_id = cr1.concept_id_1
and relationship_id = 'Maps to'
inner join concept c2
on cr1.concept_id_2 = c2.concept_id
and c2.vocabulary_id = 'SNOMED'
where c2.invalid_reason is null
order by t1.concept_code, c2.concept_id
;

**Comment by cgreich** [comment]
Patrick:

Most of them are cleaned up exactly as you say: Just look at the cr1.relationship_id:

select t1.*, cr1.invalid_reason as ir, c2.concept_id, c2.concept_name
from
(
select c1.concept_id, c1.concept_name, c1.concept_code, count(c2.concept_id) as num_maps
from
(
select *
from concept
where vocabulary_id = 'ICD9CM'
) c1
inner join concept_relationship cr1
on c1.concept_id = cr1.concept_id_1
and relationship_id = 'Maps to'
inner join concept c2
on cr1.concept_id_2 = c2.concept_id
and c2.vocabulary_id = 'SNOMED'
where c2.invalid_reason is null
group by c1.concept_id, c1.concept_name, c1.concept_code
having count(c2.concept_id) > 1
) t1
inner join concept_relationship cr1
on t1.concept_id = cr1.concept_id_1
and relationship_id = 'Maps to'
inner join concept c2
on cr1.concept_id_2 = c2.concept_id
and c2.vocabulary_id = 'SNOMED'
where c2.invalid_reason is null
order by t1.concept_code, c2.concept_id
;

**Comment by cgreich** [comment]
We could delete deprecated relationship, but so far we have used the deprecatin life cycle.

**Comment by pbr6cornell** [comment]
Ah, ok, sorry, forgot to look at invalid reason for relationship.

**Comment by hripcsa** [comment]
Are these new relationships that are not in the demo version of HERMES yet (http://www.ohdsi.org/web/hermes/index.html#/concept/133123)?

And does HERMES know to skip deprecated relationships?

George

**Comment by cgreich** [comment]
@hripcsa:

Not yet. Lee will upload them this week.

**Comment by leeevans** [comment]
@hripcsa On Monday I completed the upload of the March 21st 2015 Vocabulary V5 data to the ohdsi web, so you should now see newer vocabulary data in HERMES.  If you need the very latest vocab data with April changes from Christian then let me know and I can load it.
