### ISSUE TITLE
Map new HCPCS code for infliximab biosimilar

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#407]
Hi,

The HCPCS code Q5121 is new, it's "Injection, infliximab-axxq, biosimilar, (avsola), 10 mg". Can this be added to the Vocabulary? 

Thanks,
Ajit

**Comment by Tsemharb** [comment]
Hi,
I've checked the source that is used to build HCPCS vocabulary, and it doesn't contain that code.

**Comment by alondhe** [comment]
Hi @mik-ohdsi  -- checking back on this. CMS does have it as a valid code:

https://www.cms.gov/medicare-coverage-database/view/article.aspx?articleid=52423

![image](https://user-images.githubusercontent.com/8037742/155616216-8654b78f-3581-4245-a0c9-1ea44b19c9f2.png)

Can you please review and see if we can get this into the Vocabulary?

**Comment by alondhe** [comment]
Hi @Tsemharb -- we do see some usage of this HCPCS code in US Claims data. We should get this added as a source concept and map possibly to standard concept 37498068.

**Comment by alondhe** [comment]
@TinyRickC137 can you please provide an update on this? This is a valid biosimilar drug with usage in data. According to Avsola's site and US CMS,  it should be for 10 MG, but I don't see an RxNorm for it. Therefore, we could map to simply the Branded Drug Form of infliximab-axxq Avsola concept (37498068).

**Comment by TinyRickC137** [comment]
@alondhe hello. We are working on the HCPCS refresh. The rough estimation is 2-3 months.

**Comment by alondhe** [comment]
Thanks for the update!

**Comment by m-khitrun** [comment]
Hello! @alondhe, the concept was added and mapped: https://athena.ohdsi.org/search-terms/terms/801057
