### ISSUE TITLE
ICD10 codes missing

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Vocabulary-v5.0#41]
Missing a large number of ICD10 codes. It looks like any codes with 2 or more digits after the period are missing in this new release. The parent codes are there, but no codes below them.

select * from concept
where concept_code='A02.20'
returns no rows.

I compared the codes from the current version of the vocabulary we have running now:

with cte_old_vocab as (
select distinct source_code, SOURCE_CODE_DESCRIPTION from vocabulary.dbo.SOURCE_TO_CONCEPT_MAP
where source_vocabulary_id=34 and invalid_reason is null)
,
cte_new_vocab as (
select distinct concept_code, concept_name from concept
where vocabulary_id='ICD10' and invalid_reason is null

)
select * from cte_old_vocab a
left outer join cte_new_vocab b on a.source_code=b.concept_code
where b.concept_code is null
order by source_code

**Comment by cgreich** [comment]
Rupa:

Two answers:

1. A02.20 is in there ("Localized salmonella infection, unspecified"). When you downloaded, did you click on ICD10?
2. Don't compare to the old vocabulary_id 34. That was an ungodly mixture of ICD10 (WHO version) and ICD10CM (American expanded version). They are not identical, even where the codes are the same. We created a new vocabulary for ICD10CM, but it isn't populated yet, because nobody is using it yet. If that is not the case and you need ICD10CM than let me know and we accelerate the addition.

Let me know if not, or I close.

**Comment by rmakadia** [comment]
Hi Christian,

  I will check with Erica and make sure we have the ICD10 vocabulary loaded correctly. It seems like we got some codes but not all. We are not using ICD10 currently, I was just trying to be complete in my checks, which one of them being to check the source codes and make sure we didn’t lose any codes.

I’ll check with Erica and team and make sure the vocabulary was loaded correctly and get back to you so you can close the ticket. Thanks!

**Comment by pbr6cornell** [comment]
Note there are two different icd10....icd10 and icd10cm

**Comment by rmakadia** [comment]
Yes I was looking at ICD10 only, that’s the only one in the vocab currently.

**Comment by cgreich** [comment]
Rupa: ICD10 today is WHO ICD10. vocab 34 in the old one was an awful mix of ICD10 and ICD10CM. So, a lot of stuff will be missing when compared to 34.

**Comment by ericaVoss** [comment]
I checked our raw files and "A02.20" doesn't exist, but I could not tell you if I checked the ICD10 or not.  Maybe I missed one.  :(

Rupa, I would say we could close this issue, looks like we wouldn't be able to test it now anyway.  But keep your script, we need to make sure it is in our next release.

**Comment by cgreich** [comment]
Makes sense. Believe me, we spent a not of sweat on getting ICD10 in. It is there now. You won't believe it, but you actually cannot download a complete good set from the WHO. And UMLS has their own one cobbled together, and so are numerous sources on the web. I can show you the hilarious email exchange with the WHO. Almost as good as the AMA (ask Patrick about that one).
