### ISSUE TITLE
CVX Codes Update

### ISSUE THREAD

**Issue by MNairn** [OHDSI/Vocabulary-v5.0#414]
Hello,
    I have received the following request from a colleague for an update on CVX codes. 

There are a small number of CVX codes on the CDC website that are not in the vocabulary_id = ‘CVX’ – I only included active US CVX codes in this list.

CVX Code | CVX Short Description
-- | --
196 | Td, adsorbed, preservative free,   adult use, Lf unspecified
197 | influenza, high-dose,   quadrivalent
203 | meningococcal polysaccharide   (groups A, C, Y, W-135) TT conjugate
205 | Influenza vaccine, quadrivalent,   adjuvanted

CDC website with CVX codes is here:

https://www2.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=cvx

Please let me know any further information I can provide.

Thank You!

**Comment by dimshitc** [comment]
Hi @MNairn 
Thanks for reporting.
Looks like we have slightly outdated version of CVX in OMOP.
We'll put this CVX update in our backlog and let you know when it is going to be done.

**Comment by cukarthik** [comment]
@dimshitc @cgreich, I wanted to follow up on this ticket. The CDC release the CVX codes that it will be using for COVID vaccines ([207 and 208](https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=vg)). It also has a separate vaccine group (213).

**Comment by kfairley** [comment]
We would appreciate the update to the CVX vocabulary as well. Thanks

**Comment by dimshitc** [comment]
We are going to add new concepts it in the next week. We'll comment here, once it's done

**Comment by dimshitc** [comment]
We've added new CVX codes, but just after our release they added 
CVX Code = 212, CVX Short Description “COVID-19 vaccine, vector-nr, rS-Ad26, PF, 0.5 mL” (Janssen)
In the end of this week we are going to add this code to our vocabulary

**Comment by MariaRohozhkina** [comment]
Sorry for the long answer, all these concepts are in OMOP now.
