### ISSUE TITLE
Ibuprofen NDC changes

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#417]
Hello,

These NDCs mapped to ibuprofen should have their valid end date changed:

|Id                                                                                                                              |Code    |Name       |Class                                                                  |Standard Concept Caption|Domain      |Vocabulary|
|--------------------------------------------------------------------------------------------------------------------------------|--------|-----------|-----------------------------------------------------------------------|------------------------|------------|----------|
|46334684                                                                                                                        |69176003501|TOXICOLOGY SALIVA COLLECTION KIT - toxicology saliva collection kit kit|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45900318                                                                                                                        |691760035|toxicology saliva collection kit ORAL KIT|9-digit NDC                                                            |Non-Standard            |Drug        |NDC       |
|45357780                                                                                                                        |41163047533|EQL ANTIBACTERIAL BANDAGES|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45357770                                                                                                                        |41163041760|EQL BANDAGE ROLL 4.5" X 3 YARD|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45349433                                                                                                                        |96295011285|SUPER MOLESKIN|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45315425                                                                                                                        |96295011298|STERILE BANDAGES|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45315388                                                                                                                        |87701095986|GNP UNIVERSAL 1 THIN 26G LANCT|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45304579                                                                                                                        |11917011434|EARLOOP-STYLE FACE MASK|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45304520                                                                                                                        |11917001489|INSULIN 1/2 ML SYRINGE|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45212860                                                                                                                        |96295011218|OVULATION PREDICTOR KIT|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45127339                                                                                                                        |96295011292|SILICONE EAR PLUGS|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45118012                                                                                                                        |35515095040|QC OVULATION PREDICTOR KIT|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|45099632                                                                                                                        |11917001487|INSULIN 1 ML SYRINGE|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|44980310                                                                                                                        |11917001492|INSULIN 3/10 ML SYRINGE|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|44979982                                                                                                                        |10939008611|FLEXIBLE EX-LARGE BANDAGE|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|44974153                                                                                                                        |96295011293|KIDS SILICONE EAR PLUGS|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|44963171                                                                                                                        |11822039380|RA EAR SYRINGE 3OZ|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|44962990                                                                                                                        |10939068411|BANDAGE SHEER 1"|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|44940401                                                                                                                        |96295011291|FOAM EAR PLUGS|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |
|44860982                                                                                                                        |10939068401|BANDAGE SHEER 1"|11-digit NDC                                                           |Non-Standard            |Drug        |NDC       |

Thanks,
Ajit

**Comment by TinyRickC137** [comment]
Fixed among other NDC issues
