### ISSUE TITLE
drug mapping contradiction

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#42]
I am working on mapping NCD shaped data using OHDSI Vocabulary v5.
While doing that, I found a contradition in the vocabulary.

A concept 1321636 (bosentan) is related to concept 19098352  (branded drug form of bosentan)
They are both standard concepts

but yet - they are connected via relationship of
'Standard to Non-standard map (OMOP)'

That is a contradiction. (Because they are both standard concepts).

http://www.ohdsi.org/web/hermes/#/concept/1321636
http://www.ohdsi.org/web/hermes/#/concept/19098352

Should we worry about it?

**Comment by cgreich** [comment]
@vojtechhuser:

We should, except I cannot reproduce it. I got both concepts, but no relationship between them. Even if I had a wrong one before, it would still be there, just deprecated. What version are you in? And what's your query?

**Comment by vojtechhuser** [comment]
I am using Hermes on ohdsi.org. version is 
You start at this URL
http://www.ohdsi.org/web/hermes/#/concept/1321636
using advanced filter - filter to RxNorm relation
make the table display all fields.

and then you should be able to see it.
![2015-04-07 11_49_25-hermes](https://cloud.githubusercontent.com/assets/7526119/7027190/37c7d01e-dd1c-11e4-9f4f-c1b51062f62e.png)

**Comment by aostropolets** [comment]
@vojtechhuser

**Comment by aostropolets** [comment]
@vojtechhuser 
They both (and the rest of standard concepts) can have 'Standard to Non-standard map (OMOP)' relationship as it basically Maps to relationship. If a concept is standard, it has it pointing out to itself.

**Comment by cgreich** [comment]
Friends: Let's kill it. Hermes is long been incorporated into Atlas.
