### ISSUE TITLE
Duplicate concept for concept_name = 'procedure_occurrence.procedure_occurrence_id'

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#423]
Returns concepts 1147082 and 1147810.  Both standard.
Similar problem with 'drug_exposure.drug_exposure_id', returns concepts 1147094 and 1147707
and 'device_exposure.device_exposure_id' returns concepts 1147115,1147693
In fact, should check all CDM fields.

**Comment by Alexdavv** [comment]
It's pretty the same for all the fields. The difference is the following. But I have no idea why do we need new ones. @cgreich @dimshitc 

![image](https://user-images.githubusercontent.com/32357692/100146190-92f85b80-2eaa-11eb-9acf-adf20db21bad.png)
![image](https://user-images.githubusercontent.com/32357692/100146235-a86d8580-2eaa-11eb-9730-0f97338274bf.png)

**Comment by don-torok** [comment]
I can live with table/column per CDM version.  But what is query to get the concept_id for drug_exposure.drug_exposure_concept_id for version 6.0.0?

**Comment by cgreich** [comment]
> it reflects the conventional changes

Indeed it does. If the definition of the field changes it gets a new concept ID.

> what is query to get the concept_id for drug_exposure.drug_exposure_concept_id for version 6.0.0?

There is none, since such a field does not exist. You probably mean [drug_exposure.drug_concept_id](https://athena.ohdsi.org/search-terms/terms/1147096) or [drug_exposure.drug_exposure_id](https://athena.ohdsi.org/search-terms/terms/1147707).

**Comment by Alexdavv** [comment]
> what is query

Here you are:

`SELECT *
FROM concept c`

`JOIN concept_relationship cr
    ON c.concept_id = cr.concept_id_1
        AND cr.invalid_reason IS NULL
        AND cr.relationship_id = 'Contained in version'`

`JOIN concept c2
    ON cr.concept_id_2 = c2.concept_id
    AND c2.concept_name = 'OMOP CDM Version 6.0.0'`

`WHERE c.concept_class_id = 'Field'
    AND c.standard_concept = 'S'
    AND c.concept_name LIKE 'drug_exposure.%'`
