### ISSUE TITLE
Mapping of ICD-10 code for Z59.4 Lack of adequate food and safe drinking water

### ISSUE THREAD

**Issue by margshin** [OHDSI/Vocabulary-v5.0#424]
Hi all,

I've been working on populating social determinants of health data, and found some diagnosis data on **Z59.4: Lack of adequate food and safe drink.**
https://athena.ohdsi.org/search-terms/terms/35225203

Currently this concept is mapped to a SNOMED Observation concept:
**217632008: Accident due to hunger, thirst, exposure and neglect**
https://athena.ohdsi.org/search-terms/terms/4311919

Looking at the definition of the ICD10 concept: https://icdlist.com/icd-10/Z59.4
I think it should be mapped to Food Insecurity instead:
**SNOMED 733423003: Food Insecurity**
https://athena.ohdsi.org/search-terms/terms/37116643

As this concept is "lack of adequate food and safe drinking water" and could be used to specify such resource finding/food insecurity conditions, not an _accident_ due to food insecurity?

**Comment by mik-ohdsi** [comment]
Hi @margshin !
Sounds about right, thanks for flagging that for us.
I also found "[Water supply insufficient](https://ontoserver.csiro.au/shrimp/?concept=424466003&version=http%3A%2F%2Fsnomed.info%2Fsct%2F900000000000207008%2Fversion%2F20200731&valueset=http%3A%2F%2Fsnomed.info%2Fsct%2F900000000000207008%3Ffhir_vs)", but as this is rather a sanitation issue, I think the Food insecurity term is best suited (see also [here](https://frac.org/wp-content/uploads/Overview_of_Food_Insecurity_Coding_Report_Final-1.pdf)).
We will pick this up and try to fix it with one of the next ICD10 updates.
Best regards 
Mik

**Comment by p-talapova** [comment]
@margshin  we have changed the mapping of ICD10CM code " [Z59.4: Lack of adequate food and safe drink](https://athena.ohdsi.org/search-terms/terms/35225203)" according to your proposal.
