### ISSUE TITLE
Add mapping to dose

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Vocabulary-v5.0#43]

**Comment by ericaVoss** [comment]
@cgreich & @dimshitc  this is a super old issue.  Should we just close it?  Is it still something even on the table?

**Comment by cgreich** [comment]
What was it?

**Comment by ericaVoss** [comment]
@cgreich  you opened it!  Close it, it is almost a year since the last time I complained.  ^_^

**Comment by cgreich** [comment]
@ericaVoss told me to close it.
