### ISSUE TITLE
2 Different Standard Concepts for Thrombosis of internal jugular vein

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/Vocabulary-v5.0#431]
There's this one - https://athena.ohdsi.org/search-terms/terms/765416 - and this one - https://athena.ohdsi.org/search-terms/terms/44811347

Each has a different SNOMED code, so perhaps one needs to be invalidated?

Thanks.

**Comment by ekorchmar** [comment]
Hello! These concepts are coming from local extensions of SNOMED (UK and US), which are not deduplicated among each other. In total there are under 100 of such concept pairs.

We have proposed solutions as to how handle such duplicates and we will try to fit the fix in the next update in January.
