### ISSUE TITLE
Typo escape character at end of concept name 

### ISSUE THREAD

**Issue by rtmill** [OHDSI/Vocabulary-v5.0#432]
Concept ID : 41919122
https://athena.ohdsi.org/search-terms/terms/41919122

The concept name and concept synonym is `"Pleasant Hill\"` which, given the `'\'` at the end of the string ends up in text as` \"` which causes delimitation issues during importing/exporting.

**Comment by Alexdavv** [comment]
We have 2 such concepts in general:
```
SELECT *
FROM concept c
WHERE c.concept_name like '%\\';
```

@hardhouse can we update the concept_names and adjust the name filtering in the Generic update function?
