### ISSUE TITLE
Failed import in CONCEPT_SYNONYM.csv for ID 45419768 #363 from CDM list

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Vocabulary-v5.0#437]
https://github.com/OHDSI/CommonDataModel/issues/363

**Comment by Alexdavv** [comment]
Let’s fix this as well: https://forums.ohdsi.org/t/concept-synonym-usage-in-concept-searching/11562

**Comment by hardhouse** [comment]
https://github.com/OHDSI/Vocabulary-v5.0/commit/02ff804c38b5f1036b83584d16072bef9eb25ef8
