### ISSUE TITLE
COVID-19 Vaccines

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#443]
Hi all,

Looks like there's new codes for the COVID-19 vaccines from Pfizer and Moderna, see below. Are these in scope for a future Vocabulary release? If not, please add them to the roadmap ASAP.

https://www.cms.gov/medicare/medicare-part-b-drug-average-sales-price/covid-19-vaccines-and-monoclonal-antibodies
https://www.ama-assn.org/system/files/2021-01/covid-19-immunizations-appendix-q-table.pdf

Thanks,
Ajit

**Comment by mik-ohdsi** [comment]
Hi Ajit (@alondhe),
thanks for reminding us. We were quite focused on adding CoViD vaccines to CVX (see issue #414) but of course we should not forget CPT. And HCPCS probably, too? We will see if we need to do additional work in the NDC section. In any case it would be helpful for us to understand what you expect / have in your source data and where your top priorities for the vaccines and antibodies are.
Thanks - Mik

**Comment by clairblacketer** [comment]
@mik-ohdsi I think most US-based sources will see mainly CPT4 coding for vaccinations so these should definitely be a priority.

**Comment by cukarthik** [comment]
I agree CPT should be included, but I'm not sure if it supersedes other vocabularies. @clairblacketer, do you have a sense if CPT will be captured well since the vaccine will be provided for free? I know state and city registries are using CVX and NDC.

**Comment by mik-ohdsi** [comment]
Hi @clairblacketer, @alondhe and @cukarthik ,
in the [related forum post](https://forums.ohdsi.org/t/preparing-for-covid-vaccine-codes-in-the-vocabulary-and-modeling-in-the-omop-cdm/12446/5), I indicated that we are trying to address CVX, CPT4/HCPCS and NDC/RxNorm (in this order, but probably all of them in very quick sequence) during February and early March. In that forum posting, Julianna Kohler had a good point in asking where we will see the source data coming up, as it will probably not be in the EHR world primarily. What are your thoughts and expectations around that? ~ mik

**Comment by clairblacketer** [comment]
Hi @cukarthik and @mik-ohdsi apologies, I should have been more specific. As of now I do see records of the COVID vaccine coming across in US EHR data. Most are not coded with anything but just identified with a description, only a few have an NDC code. I would expect that, for billing purposes, US *claims* would use the CPT codes more regularly than the NDC codes as that is how we typically see vaccines in claims. I am not really sure yet how the vaccines will continue to show up in the data. Given how we have seen pop-up vaccine clinics sponsored by local and state governments I don't know how those records will make it back to the data we regularly receive. As I mentioned, I do see some in a COVID EHR dataset but it is unclear to me still if those are patients for whom we have history or if they are one-offs.

**Comment by mik-ohdsi** [comment]
As [announced](https://forums.ohdsi.org/t/preparing-for-covid-vaccine-codes-in-the-vocabulary-and-modeling-in-the-omop-cdm/12446/20) a while ago, the SARS-CoV2 vaccine concepts are released. I close this issue.
