### ISSUE TITLE
NDC concept_id = 36385088 is not mapped in the relationship nor in the ancestor table.

### ISSUE THREAD

**Issue by ttsv** [OHDSI/Vocabulary-v5.0#447]
Dear all,

Concept_id = 36385088 athena link [here](https://athena.ohdsi.org/search-terms/terms/36385088) Does not seems to have any mapping to anything.

Best 
ttsv

**Comment by Alexdavv** [comment]
Hi,
Thanks for informing!
NDC in the workshop now due to the COVID vaccine fix.
So we can easily fix it within the further release.

**Comment by Alexdavv** [comment]
Fixed

**Comment by ttsv** [comment]
Thank you for the quick fix!
Best
T
