### ISSUE TITLE
Missing Requested CONCEPT_IDs

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#46]
**OMOP Vocabulary v4.5 3-Apr-2015**
**v5.0 3-Apr-2015**

Back on 4/18/2014 I asked Mark Kayter for the following CONCEPT_IDs and was told they would make it into the VOCABULARY.  They were requested to help the NHANES CDM.

```{sql}
--Vocab v4 Style
concept_id =  44787731 for 'Patient Self-Reported Condition', 'Condition Occurrence Type', 37;
concept_id =  44787732, 'Observation Recorded from a Survey', 'Observation Type', 39.
```

However the CONCEPT_IDs have since been reassigned to other things.

Could I request new CONCEPT_IDs?  We are looking to build NHANES soon so I need to update my BUILDER with the expected CONCEPT_IDs.

**Comment by cgreich** [comment]
No idea what you agreed with Mark a year ago. But I'll add, albeit with a new concept_id. BTW: it's called "Condition Type".

**Comment by ericaVoss** [comment]
No worries, I understand.

If you know the CONCEPT_IDs that would be appreciated too.

**Comment by cgreich** [comment]
You can never have enough!!! J

 

45905770        Patient Self-Reported Condition        Condition Type           Condition Type           Condition Type

45905771        Observation Recorded from a Survey            Observation Type        Observation Type            Observation Type

 

C

**Comment by ericaVoss** [comment]
SORRY CHRISTIAN.  But thank you for being so quick!  :blush:
