### ISSUE TITLE
"Pregnancy-induced hypertension" is not a descendant of "hypertension in obstetric context"

### ISSUE THREAD

**Issue by Jake-Gillberg** [OHDSI/Vocabulary-v5.0#464]
Pregnancy-induced hypertension is not a descendant of hypertension in obstetric context, but probably should be.

concept_id 4167493 seems like it should be a child of concept_id 4279525

Instead, it skips over a level in the hierarchy and its parent is hypertension and/or vomiting in obstetric context (concept_id 4024560)

**Comment by Alexdavv** [comment]
They sound more like duplicates. SNOMED has to figure that out.

**Comment by Jake-Gillberg** [comment]
I don't think they are duplicates.

Looking at "hypertension in obstetric context", there appears to be many other forms of hypertension that are relevant in the obstetric context without being induced by the pregnancy.

For instance, "chronic hypertension in obstetric context"

**Comment by cgreich** [comment]
@Jake-Gillberg: As @Alexdavv said, this is to the address of SNOMED. We cannot change SNOMED. Like we cannot change ICD-10.

But actually I don't know what "hypertension in obstetrics context" means. We want conditions. The patient has hypertension, or some hypertension that is clinically related to pregnancy (that does exist) or labor (never heard, but may not mean that much). Just a standard common diagnosis in some "context" is the same as the common diagnosis.

**Comment by Jake-Gillberg** [comment]
I assume the 'chronic' modifies the hypertension and not the obstetric context.

Sure, I understand that this is a problem with the SNOWMED hierarchy. Is there no process to apply patches to concept sets that serve as standard concepts? Or to choose another un-broken concept as standard? Or potentially even remove this as a standard concept if it doesn't even meet the criteria wanted for 'conditions'?

**Comment by Jake-Gillberg** [comment]
Also, for some background, I was using the concept "hypertension in obstetric context" on recommendation of a physician for finding patients who had a history of hypertension complicating pregnancy. It was useful in that it didn't require us to guess if hypertension was happening co-currently to pregnancy by some date proximity of diagnosis codes or some other fuzzy method.

**Comment by Alexdavv** [comment]
> Or potentially even remove this as a standard concept if it doesn't even meet the criteria wanted for 'conditions'?

Sounds good. And map them over to common diagnosis.

The obstetric context actually means that something was found during or after the pregnancy.

**Comment by Jake-Gillberg** [comment]
> The obstetric context actually means that something was found during or after pregnancy.

Sure, I'm being loose when I say "finding patients who had a history of hypertension during pregnancy / child birth". What I mean to say is that the physician felt that using this concept was the right way to find the patients they work looking for, rather than trying to search for multiple diagnoses codes and relate them by date or encounter or some other method.

**Comment by cgreich** [comment]
@Jake-Gillberg:

Understood. But no, there aren't any so-called pre-coordinated combinations of conditions. Would be impossible, you would have to have hypertension during childbirth, during Covid, during cancer, during whatever. Unless such combination is a condition in its own right it won't exist as a diagnosis. You have to do what you said: Find patients who have hypertension and then have a baby. Nobody will write that SNOMED concept you found, even though it exists, and it is likely to be deprecated. Nothing wrong with finding the components separately.

**Comment by Jake-Gillberg** [comment]
IIRC, these codes did appear with significant frequency in our dataset at Tufts Medical Center.

I totally understand that it is untenable to extend this code+context solution to other conditions and contexts, and it does certainly feel a bit wrong to me, but if this is how physicians want to tag and query patients, I'd be reluctant to make the change to call it a non-standard code and throw away some of the information with our mapping to standard codes.

I suppose the conversation of "do "diagnosis + context" or "diagnosis + diagnosis" codes belong as standard conditions in the vocabulary?" has extended beyond the scope of this issue.

I'm interested in the answer to "what to do with what looks to be a simple mistake in snowmed heirarchy?" If the answer is nothing - because it's snowmed maintained, I suppose I won't argue given my inexperience with the community and the vocabularies, but I would be lying if I said I wasn't a bit disappointed. I'm used to open source communities [submitting fixes downstream](https://github.com/idris-lang/Idris-dev/pull/4892) and [applying temporary patches](https://github.com/NixOS/nixpkgs/pull/114042/files) until the fixes make it into a release of the dependency. Though I am sympathetic to the difficulties and the amount of work a process like this would require, given "PALLAS... is work in progress and not ready for replication."

**Comment by cgreich** [comment]
> IIRC, these codes did appear with significant frequency in our dataset at Tufts Medical Center.

I would actually split them up. Because the fact that there is an "obstetrics context" (= birth) is much more relevant as such, as in the undiscoverable combo concept.

> what to do with what looks to be a simple mistake in Snomed hierarchy

The community will gladly consider that, @Jake-Gillberg. But it requires an analytical use case. What is it that you need to do that you cannot do within the current situation. "how physicians want to tag and query patients" is not a use case. A use case is a clearly defined scientific question, and a rationale why the splitting into "chronic hypertension" and "labor" will not support it.

Make sense?

**Comment by Alexdavv** [comment]
> I'm interested in the answer to "what to do with what looks to be a simple mistake in snowmed heirarchy?"
Also, you still can try [this request app](https://confluence.ihtsdotools.org/dashboard/content-request-service).


> (= birth)
I wouldn't say so. We don't know when and whether the actual birth happened.
Pregnancy sounds better, but again it might be in the postpartum period.
How about this:

Maps to respective hepertension
Maps to [History of clinical finding in subject within 1 year](https://athena.ohdsi.org/search-terms/terms/907932)
Maps to value [Pregnant](https://athena.ohdsi.org/search-terms/terms/4299535)

**Comment by Jake-Gillberg** [comment]
> Also, you still can try this request app.

Great, thanks. Creating an account now to submit this.

So it seems I stumbled into an area of conditions which y'all aren't very happy are released as standard. I hope that you don't split this condition up without considering a solution that works and is implemented simultaneously for other condition + contexts that exist in snowmed.

In any case, this isn't what my issue is about, and I would appreciate it if that discussion took place in another issue. If it so happens that we don't want to patch this issue because of larger changes that might take place as the result of that discussion, I'd be fine with that. In the specific use case of a query for a covid+pregnancy study I was working on, it was considered the best way to identify relevant obstetric-context hypertension.

The specific issue I am having is that concept A is mapped to concept B+C but not concept B or C, when it clearly belongs in the bucket of B. It was easy enough to fix for this study in that I just searched for concept B or concept A, but thought this might be worth fixing in case someone else tries to use this standard concept and doesn't catch this error.

A = 4167493 - Pregnancy-induced hypertension
B+C = 4024560 - Hypertension AND/OR vomiting complicating pregnancy childbirth AND/OR puerperium
B = 4279525 - Hypertension in the obstetric context
C = vomiting of pregnancy

It seems like the root cause is snowmed code [4205410 - Gestational hypertension] was deprecated and replaced with code [4167493 - Pregnancy-induced hypertension], but the hierarchy grouping that mapped [4205410 - Gestational Hypertension -is_a-> 4279525 - Hypertension in the obstetric context] was not updated to include [4167493 - Pregnancy-induced hypertension].

> Make sense?

Honestly, I don't quite get it. I find it surprising that all issues of this type would require an analytical use case more detailed than "this standard concept doesn't subsume the expected concepts".

**Comment by Jake-Gillberg** [comment]
Submitted a change request to SNOWMED: Ticket ID USCRS-32858

**Comment by mik-ohdsi** [comment]
For the time being let me close this issue. Please pick it up again @Jake-Gillberg , as soon as you hear from SNOMED.

**Comment by Jake-Gillberg** [comment]
@mik-ohdsi I do not have the ability to re-open the issue, but this change is now "Ready For Release" according to Snowmed, and can be seen in the [daily build](https://prod-dailybuild.ihtsdotools.org/?perspective=full&conceptId1=48194001&edition=MAIN&release=&languages=en).

**Comment by mik-ohdsi** [comment]
Hi @Jake-Gillberg, that is great news. I'll check with the team, but I believe this should be fixed then, as soon as SNOMED has this in a regular delivery and we would adopt that one. This is however not happening on a very frequent basis, so I might need to ask you for some patience. We rarely introduce small changes but rather collect them (or if not exactly our fault, let the source vocabularies collect them and then apply them once there is another official release), unless there is an immediate need for a "hot fix".
