### ISSUE TITLE
Covid Related ICD Codes Missing

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocabulary-v5.0#469]
The new [ICD-CM codes](https://www.cdc.gov/nchs/data/icd/Announcement-New-ICD-code-for-coronavirus-19-508.pdf) added January were not included in the recent version of the omop vocabulary.

**Comment by dimshitc** [comment]
@divakhnenko can you please add these codes?

**Comment by dimshitc** [comment]
We've taken the usual CDC release files posted in October, like it was in a pre-COVID times: just an official release and we're good, no leafleats or some PDFs to worry about.
BTW, thanks for noticing this issue, and actually we are going to release this fix this or the next week.

**Comment by mik-ohdsi** [comment]
To keep you updated: we plan to release the ICD10CM CoViD related additions early next week. If you have a very urgent need for them, we could go out of our way and make it happen earlier (but would prefer to pool some other changes and not do a separate release).
