### ISSUE TITLE
RxNorm tty=MIN, 1500 concepts missing

### ISSUE THREAD

**Issue by travisstenerson-concert** [OHDSI/Vocabulary-v5.0#470]
Hi OHDSI,

I have noticed about 1500 concepts missing from the MIN (mixed ingredient) term type from RxNorm in the Athena concept table. Is there a reason for these being absent?
An example is the MIN version of Vyxeos,  cytarabine/daunorubicin code 2017575

Thank you

PS first time posting, apologies if this isn't the right forum for a content question like this.. let me know. And thanks for the convenient vocab package!

**Comment by cgreich** [comment]
@travisstenerson-concert: We haven't incorporated MINs. As for combos, we have only Drug Forms and Branded Drug Components, and everything down the hierarchy. You have to write the those, or the ingredients separately.

**Comment by cgreich** [comment]
Analytical use case. We are studying the exposure to drugs, which, after intake, are in the blood stream as individual ingredients, with their individual mechanism of action and metabolization. In other words, in the blood there are no combination drugs. Only ingredients, no matter if you ingested them together in one pill, or each in a separate pill.

Now you could ask why have combinations at all? The drug product (or interim concepts like drug form and drug component) has a defined set of ingredients and strengths, and therefore needs to be represented as such. 

If you have only the MINs and no other information (strength or dose form) then create one DRUG_EXPOSURE record for each ingredient.

**Comment by Alexdavv** [comment]
> The drug product (or interim concepts like drug form and drug component) has a defined set of ingredients and strengths, and therefore needs to be represented as such

Maybe. But this could be in the "source" area only. Why don't we standardize the drugs upon their ingredient, route (even not form), and strength?

**Comment by travisstenerson-concert** [comment]
@cgreich 
Hey Christian, I totally get that logic and recognize that OMOP's use case tends toward the analytical - that pipelines feeding the model should split the drug into multiple records.

But this scenario won't always work for real world data. MIN codes are commonly used, particularly in pipelines that want to represent an order with a bare bones set of drugs, but do not want record expansion when they map to ingredients. That would require some complex logic on any dosing information to appropriately split the dose for mixed drugs. Also it might force the data model to make a decision about what drug caused progression or an adverse event when really it was a mixed pill and we can't make that assumption.

Also the presumption that mixed drugs split in the body are not always true. There are lots of oncology drugs that make that assumption a little less black and white.. liposomes with two molecules, antibody-drug conjugates.


But overall, leaving those drugs outs limits the usability of the model. They ARE encountered out in the wild, even if they aren't flowing directly from the medical record, and it won't be much of a negative to include them in the concept table.

Any chance you can reconsider their inclusion?

**Comment by cgreich** [comment]
@travisstenerson-concert: 

Sorry, but I will have to disagree.

I don't understand your first point. If you have dose form and strength information for your MINs you need to record combination clinical or branded drug concepts. We are talking ingredient level with no other information. 

Second point: I don't agree. A pill disintegrates in the stomach, or the duodenum the latest. At that point, whether you took a three-ingredient drug or three separate drugs becomes indistinguishable and identical from an analytical perspective.

Liposomal preparations and conjugates are single ingredients, not MINs. 

We are not leaving anything out. We are just creating separate single ingredient records. Do you need help with mapping MINs to Ingredients?

**Comment by travisstenerson-concert** [comment]
I was talking about Vyxeos. Two drugs one liposome. And yes I know RxNorm qualifies ab-drug conjugates as one PIN. I just meant the reality isn't so black and white and if we are going with RxNorm's definition of what 'one drug' is, then why are we discluding their MIN codes.

No I don't need help mapping MIN to ingredient, though I have to use UMLS for it instead of OMOP's vocabulary tables. Which was my impetus for asking in the first place. Sure I can do some string manipulation but then what is the point of a knowledge base if I need to do that.

What this does is force the hand of implementers to split a single medication order record into multiple drug_exposure records, and necessitates altering the semantics of the record concurrently with the structure. In one step I have to change the entity shape, split the medication concept into multiple concepts and in turn produce multiple records from one record and perform the calculation on the dosing to get that quantity correct.

When the alternative is to slightly adjust what is copied over from RxNorm.. which shouldn't inconvenience any other uses of these knowledge tables. They can ignore those concepts.

If thats the decision though we will just have to engineer around it.

**Comment by cgreich** [comment]
> No I don't need help mapping MIN to ingredient, though I have to use UMLS for it instead of OMOP's vocabulary tables. Which was my impetus for asking in the first place.
Let's add MINs as source concept, each mapping to their respective ingredients. That makes total sense to me.

>  split a single medication order record into multiple drug_exposure records
That is actually not a problem. If you record drugs at the ingredient level it is understood that those record don't equate to individual products, which could have a combination. If you want that write those product concepts. 

BTW: RxNorm does the same thing, but for some reason *only* for Clinical Drug Components. They only exist as singletons, not combos.

> altering the semantics of the record concurrently with the structure
The whole point of the OMOP CDM is to *standardize* the semantics. Not preserve what it was in the source. You wouldn't need a CDM if that was your goal. Just use the source.

Let's get the MINs in (we already have a [Github](https://github.com/OHDSI/Vocabulary-v5.0/issues/470) for that). That should make the engineering easy. Stay tuned.

**Comment by travisstenerson-concert** [comment]
@cgreich 

Thats great news. Thank you.

**Comment by Alexdavv** [comment]
We added MINs into OMOP vocabulary with the recent release. You can read [here](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20210608_1623156490) how it’s done.

**Comment by travisstenerson-concert** [comment]
Thank you Alexander.

Travis

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
