### ISSUE TITLE
Incorrect UCUM unit mL/min/1.73.m2 (concept_id 9117)

### ISSUE THREAD

**Issue by Andreyyiv** [OHDSI/Vocabulary-v5.0#472]
The UCUM standard Unit [concept 9117](https://athena.ohdsi.org/search-terms/terms/9117) has incorrect UCUM code `mL/min/1.73.m2`.  The OMOP description is 

> milliliter per minute per 1.73 square meter

for eGFR values. By the [UCUM specification](https://ucum.org/ucum.html#para-7), the floating-point numbers are not allowed and the period `.` is the binary multiplication operator only. The code itself is a valid UCUM unit, but the actual meaning of this code is `73.m2.mL/min`. The correct UCUM code might be like `mL/min/(173/100.m2)`.

I'm not sure what would be the best approach to solve this in the OMOP vocabularies. Probably retire this concept and create a new one.

**Comment by cgreich** [comment]
@Andreyyiv:

You are right. Yes, we need to retire it and map it over to a new correct one that needs to be created.

**Comment by dimshitc** [comment]
@cgreich why even bother?
All ETL will suffer if we make this change.

**Comment by cgreich** [comment]
Why will it suffer? Just replace one with the other.

**Comment by TinyRickC137** [comment]
Happy to inform that this bug has been fixed recently
