### ISSUE TITLE
Missing HCPCS code for Cemiplimab-rwlc

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#479]
Hello,

Can this code be added for Cemiplimab-rwlc, J9113? It is apparently valid as of 2018.

https://seer.cancer.gov/oncologytoolbox/canmed/hcpcs/J9113/

Thanks,
Ajit

**Comment by mik-ohdsi** [comment]
Hi @alondhe ,
we are consuming the UMLS source for building the HCPCS vocabulary and apparently, cemiplimab is known by J9119 there (with a deprecated one in Athena going by C9044):

cui | lat | ts | lui | stt | sui | ispref | aui | saui | scui | sdui | sab | tty | code | str
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
C5229008 | ENG | P | L16238954 | PF | S19586382 | Y | A31526331 |   | J9119 |   | HCPCS | PT | J9119 | Injection, cemiplimab-rwlc, 

This [Athena query](https://athena.ohdsi.org/search-terms/terms?invalidReason=Valid&page=2&pageSize=15&query=cemiplimab-rwlc) gave me a nice list.

Is there the faint possibility that SEER has made a small mistake? Or is there a separate / additional codeset? If so, what would be the difference between these two codes?

Cheers ~ Mik

**Comment by alondhe** [comment]
Hi @mik-ohdsi ,

I'm hearing from my team that this is a real code, and that there's others that CanMED provides that we don't have here. What's the current process for CanMED codes, do we pull from that system?

THanks,
Ajit

**Comment by cgreich** [comment]
[CanMED](https://academic.oup.com/jncimono/article/2020/55/39/5837291) might have obsolete HCPCS code we are missing. We should check that list.

However, this one was approved in 2018. Looks like this is a CanMED mistake. Do you see that in the data, @alondhe?

**Comment by alondhe** [comment]
@cgreich not following on how it's a mistake: are you saying the 2018 date is wrong, and this is actually deprecated?

I'm checking to see if it's actually in our data.

**Comment by cgreich** [comment]
It (=J9113) is in no public source of HCPCS, except CanMED. It is also not in any of the data assets available to me. Google doesn't find it either (except the CanMED entries). Makes me believe CanMED got a wrong record. The right code is J9119, and that got officially replaced by the CMS by C9044 in April 2019.
