### ISSUE TITLE
Provider Mapping Questions

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Vocabulary-v5.0#482]
Any idea where these "provider" codes should be mapped to:

Venereology
Sexology
Pedicure
Abortion Clinic

Thanks

**Comment by cgreich** [comment]
[Community sexual and reproductive health](https://athena.ohdsi.org/search-terms/terms/903266)
Probably the same
Probably not part of healthcare, unless you mean [Podiatry](https://athena.ohdsi.org/search-terms/terms/38004486)
[Obstetrics/Gynecology](https://athena.ohdsi.org/search-terms/terms/38004461)

**Comment by PRijnbeek** [comment]
Thanks yes indeed podiatry.
