### ISSUE TITLE
UB04 Point of Origin - Add Code

### ISSUE THREAD

**Issue by Piper-Ranallo** [OHDSI/Vocabulary-v5.0#485]
domain_id = 'Visit'
vocabulary_id = 'UB04 Point of Origin'
concept_class_id = 'UB04 Point of Origin'
source_code = 'G'
concept_name = 'Transfer from a Designated Disaster Alternate Care Site'
valid_start_date = '07-01-2020' (mm-dd-yyyy)

reference: https://www.nubc.org/system/files/media/file/2020/05/2020-05-22-NUBC_announcment.pdf

**Comment by cgreich** [comment]
Makes sense. 

I don't like the name, though. This is a hotel used for isolating Covid patients. And the name has to work globally. Any good idea?

**Comment by mik-ohdsi** [comment]
@cgreich , how did you come to the conclusion that this is about hotels? I agree that the name is a little awkward.

**Comment by cgreich** [comment]
https://www.cdc.gov/coronavirus/2019-ncov/hcp/alternative-care-sites.html

"A local surge in the need for medical care might require jurisdictions to establish alternate care sites (ACS) where patients with COVID-19 can remain and receive medical care for the duration of their isolation period. These are typically established in non-traditional environments, such as converted hotels or mobile field medical units."

**Comment by mik-ohdsi** [comment]
Hi @Piper-Ranallo, "UB04 Point of origin" is not an OMOP Vocabulary. Where do you think this concept should go best? "CMS-Place of Service"? CMS has normally digits as concept codes as far as I can see.

**Comment by Alexdavv** [comment]
https://athena.ohdsi.org/search-terms/terms?standardConcept=Standard&domain=Visit&page=1&pageSize=15&query=Isolation

Let’s add “Isolation in temporary medical unit”.

**Comment by Piper-Ranallo** [comment]
@mik-ohdsi i - When you say "UB04 Point of origin" is not an OMOP Vocabulary", I'm assuming you mean it's not used as a vacabulary to  standard concepts are mapped?  I am seeing it in OMOP as a vocabulary in the Visit domain.

**Comment by Piper-Ranallo** [comment]
> Let’s add “Isolation in temporary medical unit”.
> Or it’s not just infectious diseases-related?

@Alexdavv , are you recommending adding a record in table **concept_relationship** to define a mapping from (non-standard) concept  'Designated Disaster Alternate Care Site' to standard concept "Isolation in temporary medical unit”?

**Comment by cgreich** [comment]
> Let’s add “Isolation in temporary medical unit”.

It's not necessarily about isolation only. Could also be treatment.

**Comment by Piper-Ranallo** [comment]
> we don't have such a controlled vocabulary

There must be gremlins in my database then... here's what I'm seeing:

![image](https://user-images.githubusercontent.com/44986641/115899685-aa6d4d80-a424-11eb-8755-57bd7cbe261d.png)

**Comment by cgreich** [comment]
Ouch. Embarrassing. Yes, this is an existing vocabulary, and the full name is "UB04 Claim Source Inpatient Admission Code (CMS)".

Do you have the code? Should be a single letter.

**Comment by Piper-Ranallo** [comment]
> Ouch. Embarrassing.

@cgreich - I'm so glad I'm not the only one that does that kind of thing! :)

Yes:
**source_code** = 'G'
**concept_name** = 'Transfer from a Designated Disaster Alternate Care Site'
**valid_start_date** = '07-01-2020' (mm-dd-yyyy)

**Comment by Alexdavv** [comment]
The concept [has been added](https://athena.ohdsi.org/search-terms/terms/33006) with a respective Standard target.
