### ISSUE TITLE
SNOMED Concept "Finding of Sexual Orientation" should be an Observation, not a Condition

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#488]
This concept https://athena.ohdsi.org/search-terms/terms/4268837 is listed as a Condition instead of an Observation. Based on recent understanding of sexual orientation this should be moved to the Observation domain.

**Comment by TinyRickC137** [comment]
Hello, @clairblacketer 
We fixed it!
