### ISSUE TITLE
Issue in DRUG_STRENGTH table:  same drug/ingredient pair occurs multiple times

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#49]
On the latest release of VocabV5, I could not run add constraints to the data tables, becuase of the following issue:

ALTER TABLE drug_strength ADD CONSTRAINT xpk_drug_strength PRIMARY KEY NONCLUSTERED (drug_concept_id, ingredient_concept_id);

--3 drug/ingredient combinations that appear more than 1 time in drug_strength table:
19123874	1728416
19123873	1728416
529373	529411

the issue makes sense for these 3, because the drug contains have two ingredients which now map to the same rxnorm ingredient concept

in the DRUG_STRENGH ETL, we should only provide DISTINCT to ensure this situation does not manifest in the final output table.

**Comment by cgreich** [comment]
Wait. Didn't we say we remove that constraint?

**Comment by pbr6cornell** [comment]
No, this is different, it's for having multiple of same ingredient in one
drug, which doesn't make sense and should be avoided.

**Comment by cgreich** [comment]
That is the same. The reason is that they report the same ingredient with different units.

**Comment by pbr6cornell** [comment]
If that's the case, should constraint be on the drug/ingredient/unit tuple?

**Comment by cgreich** [comment]
Could try that.

 

C

**Comment by cgreich** [comment]
Fixed. We no longer have those ingredient duplicates.
