### ISSUE TITLE
Potential mapping error between ICD10CM to OMOP concept ID for Gestation period

### ISSUE THREAD

**Issue by stormliucong** [OHDSI/Vocabulary-v5.0#496]
I am working on a newborn screening phenotyping project. I realized there is a series of potential mapping errors from ICD10CM to OMOP concept ID. 

 

For example, the OMOP standard concept "Gestation period, 34 weeks" (443874) was mapped to two ICD10CM concepts (nonstandard) "Preterm newborn, gestational age 34 completed weeks" (ICD10CM code - Z3A.34) and "Preterm newborn, gestational age 34 completed weeks" (ICD10CM code - P07.37). 

 

These two ICD-CM codes are actually different things. P07.37 is used to code premature newborns while Z3A.34 is used to code pregnant women. I will suggest every source_concept_code P07.3* should be mapped to OMOP concept ID 36675035 (Prematurity of infant).

**Comment by divakhnenko** [comment]
Hello @stormliucong!
Thank you for your willingness to improve the vocabularies logic.
How you can see [here](https://athena.ohdsi.org/search-terms/terms/45572927) ICD10CM concept 
P07.37 Preterm newborn, gestational age 34 completed weeks has mapping to two concepts [Gestation period, 34 weeks](https://athena.ohdsi.org/search-terms/terms/443874) and [Prematurity of infant](https://athena.ohdsi.org/search-terms/terms/36675035) simultaneously. We use multiple mapping to preserve the original meaning of ICD10CM concept. This also works for the whole P07.3* branch.

**Comment by divakhnenko** [comment]
Actually, your comment leads us to further investigation of this mapping. 

You are totally right in saying that 
[Gestation period, 34 weeks](https://athena.ohdsi.org/search-terms/terms/443874) is an inappropriate mapping to describe the condition of an infant as far as this concept is a child of 
[Finding related to pregnancy](https://athena.ohdsi.org/search-terms/terms/444094) one. However, when this mapping was created we didn't have any alternative to reflect the full meaning of the ICD10CM concept.

But now SNOMED has created [such concepts](https://athena.ohdsi.org/search-terms/terms/37016212) which are the best choice for mapping the P07.3* branch. We are going to remap this branch and change the previous rules of mapping preterm newborn conditions according to the newly added SNOMED concepts.
