### ISSUE TITLE
MedDRA Concepts missing Class

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Vocabulary-v5.0#5]
Instead of Preferred Term , Lowest Level Term, etc.. the CONCEPT_CLASS_ID is just MedDRA

**Comment by cgreich** [comment]
Will be fixed in the upcoming release.

**Comment by ericaVoss** [comment]
This is fixed in **VERSION v5.0 21-Mar-2015** and should be closed.

**Comment by cgreich** [comment]
Fixed
