### ISSUE TITLE
Some ICD-10 codes have suboptimal mapping

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#50]
In general, the mapping for ICD-10 codes looks good. But I stumbled on some codes that had suboptimal mappings (IMHO). See below the current mapping and my suggested mapping.

With some string normalization (ignoring word order, case, and words like 'unspecified') the names of the ICD-10 and SNOMED concept would actually be the same. Perhaps we could formulate a simple algorithm to detect things like these?

<table>
<tr><td>ICD-10</td><td>ICD10_name</td><td>Concept_id</td><td>Concept_name</td><td>Suggested_concept_id</td><td>Suggested_concept_name</td></tr>
<tr><td>C82.0</td><td>Small cleaved cell, follicular non-Hodgkin's lymphoma</td><td>194878</td><td>Nodular lymphoma of extranodal AND/OR solid organ site</td><td>400235</td><td>Follicular non-Hodgkin's lymphoma, small cleaved cell</td></tr>
<tr><td>C82.1</td><td>Mixed small cleaved and large cell, follicular non-Hodgkin's lymphoma</td><td>194878</td><td>Nodular lymphoma of extranodal AND/OR solid organ site</td><td>4001329</td><td>Follicular non-Hodgkin's lymphoma, mixed small cleaved cell and large cell</td></tr>
<tr><td>C82.2</td><td>Large cell, follicular non-Hodgkin's lymphoma</td><td>194878</td><td>Nodular lymphoma of extranodal AND/OR solid organ site</td><td>4003833</td><td>Follicular non-Hodgkin's lymphoma, large cell</td></tr>
<tr><td>C82.7</td><td>Other types of follicular non-Hodgkin's lymphoma</td><td>4299152</td><td>Follicular center B-cell lymphoma</td><td>4147411</td><td>Follicular non-Hodgkin's lymphoma</td></tr>
<tr><td>C82.9</td><td>Follicular non-Hodgkin's lymphoma, unspecified</td><td>194878</td><td>Nodular lymphoma of extranodal AND/OR solid organ site</td><td>4147411</td><td>Follicular non-Hodgkin's lymphoma</td></tr>
<tr><td>C83.0</td><td>Small cell (diffuse) non-Hodgkin's lymphoma</td><td>440058</td><td>Malignant lymphoma of extranodal AND/OR solid organ site</td><td>4002356</td><td>Diffuse non-Hodgkin's lymphoma, small cell</td></tr>
<tr><td>C83.1</td><td>Small cleaved cell (diffuse) non-Hodgkin's lymphoma</td><td>40481901</td><td>Mantle cell lymphoma</td><td>4003180</td><td>Diffuse non-Hodgkin's lymphoma, small cleaved cell</td></tr>
<tr><td>C83.3</td><td>Non-Hodgkin's lymphoma, unspecified type</td><td>432571</td><td>Malignant lymphoma</td><td>4038838</td><td>Non-Hodgkin's lymphoma</td></tr>
<tr><td>C83.3</td><td>Large cell (diffuse) non-Hodgkin's lymphoma</td><td>436920</td><td>Reticulosarcoma</td><td>432574</td><td>Diffuse non-Hodgkin's lymphoma, large cell</td></tr>
<tr><td>C83.4</td><td>Immunoblastic (diffuse) non-Hodgkin's lymphoma</td><td>4003830</td><td>Diffuse non-Hodgkin's lymphoma</td><td>4003832</td><td>Diffuse non-Hodgkin's lymphoma, immunoblastic</td></tr>
<tr><td>C83.5</td><td>Lymphoblastic (diffuse) non-Hodgkin's lymphoma</td><td>200662</td><td>Lymphosarcoma</td><td>4001328</td><td>Diffuse non-Hodgkin's lymphoma, lymphoblastic</td></tr>
<tr><td>C83.6</td><td>Undifferentiated (diffuse) non-Hodgkin's lymphoma</td><td>4003830</td><td>Diffuse non-Hodgkin's lymphoma</td><td>4003831</td><td>Diffuse non-Hodgkin's lymphoma, undifferentiated</td></tr>
<tr><td>C83.8</td><td>Other types of diffuse non-Hodgkin's lymphoma</td><td>440058</td><td>Malignant lymphoma of extranodal AND/OR solid organ site</td><td>4003830</td><td>Diffuse non-Hodgkin's lymphoma</td></tr>
<tr><td>C85.1</td><td>B-cell lymphoma, unspecified</td><td>432571</td><td>Malignant lymphoma</td><td>434592</td><td>B-cell lymphoma</td></tr>
</table>

**Comment by cgreich** [comment]
@schuemie:

You got it. Next release (next week). 

Except that the first line concept_id_2 should be 4002357, and the 8th line the ICD10 code should be 85.9. 

I am not the most pedantic and anal person, so don't expect me to find these little bugs. :)
