### ISSUE TITLE
Add new HCPCS code for esketamine

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#500]
A new HCPCS code, S0013 was issued in 2021 for Spravato (see attachment). Can this please be added along with a relationship to the esketamine ingredient?

[Spravato S Code Brochure.pdf](https://github.com/OHDSI/Vocabulary-v5.0/files/6592758/Spravato.S.Code.Brochure.pdf)

**Comment by Alexdavv** [comment]
> A new HCPCS code, S0013 was issued in 2021 for Spravato (see attachment). Can this please be added along with a relationship to the esketamine ingredient?
> 
> [Spravato S Code Brochure.pdf](https://github.com/OHDSI/Vocabulary-v5.0/files/6592758/Spravato.S.Code.Brochure.pdf)

We can do this manually unless it's in the HCPCS official sources we're using. But how is it urgent?

**Comment by clairblacketer** [comment]
I wanted to make sure that the ingredient relationship was created as Spravato is a Janssen product that we are actively researching.

**Comment by Alexdavv** [comment]
[The sources ](http://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets/Alpha-Numeric-HCPCS.html) we currently use for HCPCS are almost 1 year beyond the UMLS. We have to start using UMLS here.

**Comment by mik-ohdsi** [comment]
@Alexdavv - is [this source](https://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets/HCPCS-Quarterly-Update) maybe a better one?

**Comment by Alexdavv** [comment]
> @Alexdavv - is [this source](https://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets/HCPCS-Quarterly-Update) maybe a better one?

Yes, and it has the same format. But if the effort is relatively the same, I'd switch to UMLS.

**Comment by m-khitrun** [comment]
@clairblacketer, the code was added and mapped: https://athena.ohdsi.org/search-terms/terms/801248
