### ISSUE TITLE
Improve mapping for ICD-10-CM C44.519 to map to basal cell carcinoma

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#504]
Team:

Requested improvement in ICD-10-CM to SNOMED mapping:

ICD-10-CM C44.519:   https://athena.ohdsi.org/search-terms/terms/45561802   is 'Basal cell carcinoma of skin of other part of trunk', and currrently maps to 'Malignant neoplasm of skin of trunk'.

I suggest that a better mapping location would be:  'Basal cell caricoma of truncal skin' (https://athena.ohdsi.org/search-terms/terms/4297668).

The reason this matters:  many OHDSI phenotypes for cancers try to define 'any cancer' as 'malignant neoplastic disease' + descendents , excluding 'basal cell carcinoma' and 'squamous cell carcinoma'.    Under the current vocab mapping, this code, C44.519 get captured under 'any cancer', but would be desired to be excluded as a basal cell carcinoma.

**Comment by divakhnenko** [comment]
Hello @pbr6cornell!
Actually, this is a great suggestion! 
I am going to remap it. So, this bug will be fixed in the upcoming ICD10CM release.

**Comment by divakhnenko** [comment]
I am pleased to inform you that this problem is solved in the current version.
See the latest release
https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20210713_1626193237
