### ISSUE TITLE
Concept 35206231 mapped to two standard concepts

### ISSUE THREAD

**Issue by tomseinen** [OHDSI/Vocabulary-v5.0#507]
Non standard ICD10CM concept 35206231:
Malignant neoplasm of connective and soft tissue of thorax

is mapped to two standard concepts:
4092358: Malignant neoplasm of connective and soft tissue of thorax
and
4312698: Primary malignant neoplasm of trunk

Is the second standard concept (4312698) not redundant as the first standard concept (4092358) is exactly what the non-standard concept (35206231) describes?

Tom

**Comment by divakhnenko** [comment]
Hello @tomseinen!
Thank you for your enthusiasm for improving the vocabularies!

According to the ICD-10-CM guidelines information declared, all malignant neoplasms not mentioned as secondary or unknown, are considered to be primary. So, for now, existing mapping is the best one.

However, in the upcoming ICD10CM release we are going to remap [35206231: Malignant neoplasm of connective and soft tissue of thorax](https://athena.ohdsi.org/search-terms/terms/35206231) to a single SNOMED's concept [317801: Primary malignant neoplasm of soft tissues of thorax](https://athena.ohdsi.org/search-terms/terms/317801). So, there won't be any problem with multiple mapping.

**Comment by tomseinen** [comment]
Ah, I see that makes sense, thank you for your answer!
