### ISSUE TITLE
Request for Procedure Status Vocabulary

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#509]
Hi, I would like to request a new Procedure Status Vocabulary similar to Condition Status Vocabulary. The type concept change removed the ability to identify primary vs secondary procedures as outlined in this issue: 

https://github.com/OHDSI/CommonDataModel/issues/376

We will be adding PROCEDURE_STATUS_CONCEPT_ID to CDM v5.4 and need this vocabulary to support that addition.

**Comment by Alexdavv** [comment]
Discussion continued here:
https://github.com/OHDSI/CommonDataModel/issues/376

**Comment by mik-ohdsi** [comment]
Hi @cgreich , I think we need a Titan's input here.
With 5.4 supporting this, I see no reason why we should not have that vocabulary (actually, do we have a choice?). 
So it is a new vocabulary with two concepts, new domain and new concept class.

**Comment by cgreich** [comment]
Two concepts?

**Comment by mik-ohdsi** [comment]
@cgreich  &  @maximmoinat - Yes, two concepts for now. In alignment with that condition status vocab with only a couple of concepts...

**Comment by mik-ohdsi** [comment]
@cgreich  -  what is the Titan's verdict?
