### ISSUE TITLE
cpt4.jar stores cpt4 concept id's as strings, not integers

### ISSUE THREAD

**Issue by surangak** [OHDSI/Vocabulary-v5.0#51]
I recently downloaded the OHDSI vocab, and executed the cpt4.jar to download and add the cpt4 codes. The download process worked fine.
Next, I began executing the scripts given in: https://github.com/OHDSI/CommonDataModel/tree/master/PostgreSQL/VocabImport

However, the import of the concept table data into the database failed with an error. Looking at the csv file for the conept table, I saw that this was because the cpt4.jar was storing the concept id's for each cpt4 jar as strings (i.e. surrounded with double quotes) in the csv file. My database (postgres) couldn't store these strings as integers, and therefore, failed :-(

**Comment by cgreich** [comment]
@surangak:

When did you do that? We removed the quotes recently. Let me know.

**Comment by surangak** [comment]
@cgreich , I'm afraid that I tried this last night. I wonder if the right jar file is in the download that comes with the vocab?

**Comment by cgreich** [comment]
@surangak:

Let me check it out.

**Comment by cgreich** [comment]
@surangak:

Can you check again. The jar should not create quotes any more.

**Comment by surangak** [comment]
@cgreich , thank you, the second download seems to work fine, and all is well :-)
I have the right CPT mappings in my vocab now.

**Comment by ericaVoss** [comment]
I believe this issue is closed?  @surangak?

**Comment by surangak** [comment]
Indeed it is, thank you :)
