### ISSUE TITLE
Incorporation of site specific NAACR data elements

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#513]
We would like to ETL site specific NAACCR data elements to the CDM. However, these items are not found in Athena or the Oncology Extension.

Please see the NAACCR mapping specifications here: https://www.naaccr.org/SSDI/SSDI-Manual.pdf?v=1527608547

**Comment by mik-ohdsi** [comment]
Hi @MelaniePhilofsky , 
let us investigate how much effort it would be to add SSDI the way you need it. I understand there should already be site specific variables in the NAACCR vocabulary. Maybe Eduard can give us some background.
Cheers - Mik

**Comment by mik-ohdsi** [comment]
@MelaniePhilofsky , can you provide us with some examples and illustrate the issue to us in more detail? Apparently there is some site specific content like this [one.](https://athena.ohdsi.org/search-terms/terms/35926295). But that is not what you are looking for, right?
thanks - mik

**Comment by MelaniePhilofsky** [comment]
Hi @mik-ohdsi , 

- NAACCR code 2880 (SSF#1): description seer site specific factor 1NBR
- NAACCR code 2890 (SSF #2):  description seer site specific factor 2NBR

**Comment by MelaniePhilofsky** [comment]
Hi @mik-ohdsi 

- NAACCR code 2880 (SSF#1):description seer site specific factor 1NBR
- NAACCR code 2890 (SSF#1):description seer site specific factor 2NBR

**Comment by mik-ohdsi** [comment]
Hi @vladkorsik , @dimshitc and @ekorchmar - could you take a look at what Melanie has sent and provide some input?
Thanks!
 Mik

**Comment by dimshitc** [comment]
Athena [doesn't allow to perform this type of search ](https://athena.ohdsi.org/search-terms/terms?vocabulary=NAACCR&page=1&pageSize=15&query=%2A2880%2A&boosts)
You can find these concepts using the following SQL queries:
select * from concept where concept_code like '%2880%' and vocabulary_id ='NAACCR'
;
select * from concept where concept_code like '%2890%' and vocabulary_id ='NAACCR'
;
The Variable codes are made by the concantenation of a schema_id and a concept_code
The value codes are made by the concantenation of a schema_id, concept_code and value_code.

@MelaniePhilofsky please let me know if it works for you

**Comment by dimshitc** [comment]
For more details you can see these 2 files
https://github.com/OHDSI/OncologyWG/tree/master/documentation
![image](https://user-images.githubusercontent.com/8568959/131531046-cd068878-4000-4505-b466-4604e7f0295f.png)
and a documentation here
https://www.ohdsi.org/web/wiki/doku.php?id=documentation:vocabulary:NAACCR

**Comment by mik-ohdsi** [comment]
The [NAACCR](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Vocab.-NAACCR) page already exists in the new place for vocabulary documentation, which admittedly is still work in progress...

**Comment by mik-ohdsi** [comment]
Hi @MelaniePhilofsky - have we been able to solve the issue for you, now?

**Comment by MelaniePhilofsky** [comment]
Yes, thank you @mik-ohdsi and @dimshitc !
