### ISSUE TITLE
Add standard concept for sotorasib

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#520]
Hi,

The drug sotorasib has been approved for NSCLC. Currently, Athena has some NDCs, but no ingredient level standard concept:

![image](https://user-images.githubusercontent.com/8037742/128248559-bc633d8d-3978-4127-94f3-79c28381f881.png)

Can we get this ingredient added? This is urgent, as we should start to see utilization in US claims data in the next month or so. 

Thanks,
Ajit

**Comment by Alexdavv** [comment]
It’s already in RxNorm from July’s version. If we take Aug RxNorm files that have just arrived and release it within the month or so, it makes sense because we fit a quarterly release schedule then.

Let us have a look what we can do. Otherwise, a temporary RxNorm Extension concept may be a choice.

**Comment by mik-ohdsi** [comment]
Hi @alondhe , again, thanks for highlighting this. Will it be fine if we proceed with processing the August RxNorm files? It might take a couple of weeks until the concept shows up in Athena. Is there time pressure?
Thanks - Mik

**Comment by alondhe** [comment]
Hi @mik-ohdsi  -- we do have some time sensitivity with this as we anticipate new data with this drug coming in September. Ideally we can begin analyzing this data in Atlas at that time.

**Comment by mik-ohdsi** [comment]
We will try to make it available by early September, hopefully in time for you to run another ETL before the analysis.

**Comment by dimshitc** [comment]
https://athena.ohdsi.org/search-terms/terms/1536963
added it today.

**Comment by mik-ohdsi** [comment]
Hi @alondhe  -  how do you rate your customer experience today ;-)
Glad that we would sneak that in! Don't get too used to us making your wishes true in no time. But we will always try!

**Comment by mik-ohdsi** [comment]
Hi @alondhe - just one little remark. We do not have the Sotorasib mapping NDC - RxNorm in Athena, but will soon have it. If you want to hold your breath a couple more days, we should have a small update coming quite soon.

**Comment by alondhe** [comment]
@mik-ohdsi and @dimshitc thanks so much! We will hold on till those NDCs are added before updating our Vocab. Much appreciated!

**Comment by mik-ohdsi** [comment]
Hi @alondhe - the fix should now be complete!
