### ISSUE TITLE
Dose Form Missing for RxNorm Concepts

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocabulary-v5.0#521]
There are many RxNorm concepts that don't have the dose form relationship. For example, [abemaciclib](https://athena.ohdsi.org/search-terms/terms/792649) does not have a dose form relationship, but when one looks at RxNav, the RxNorm [code](https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=1946825 ) does have a dose form relationship. It seems like these relationships might not have been loaded from source? 
Here's a list of other concept ids that do not have a 'RxNorm has dose form' relationship:

concept_id | concept_name
-- | --
792649 | abemaciclib
1348265 | anastrozole
936748 | aprepitant
1112807 | aspirin
42629079 | atezolizumab
19015523 | bendamustine
35604027 | bendamustine hydrochloride 25 MG/ML Injectable Solution
1397141 | bevacizumab
43012292 | cabozantinib
1344905 | carboplatin
1315411 | cetuximab
1397599 | cisplatin
1310317 | cyclophosphamide
19010482 | cyclosporine
1358436 | dasatinib
40222444 | denosumab
1518254 | dexamethasone
1353011 | dexrazoxane
35603900 | dexrazoxane 500 MG Injection
1315942 | docetaxel
1338512 | doxorubicin
42629353 | 10 ML doxorubicin hydrochloride liposome 2 MG/ML Injection
40230712 | eribulin
1325363 | erlotinib
1548195 | estradiol
19011440 | everolimus
1398399 | exemestane
1304850 | filgrastim
955632 | fluorouracil
35605594 | fosaprepitant
35605599 | fosaprepitant 150 MG Injection
1314924 | gemcitabine
1366310 | goserelin
1000772 | granisetron
975125 | hydrocortisone
44507848 | ibrutinib
1367268 | irinotecan
19025348 | ixabepilone
35606214 | ixazomib
1359548 | lapatinib
1315946 | letrozole
1388796 | leucovorin
1351541 | leuprolide
1300978 | megestrol
1354698 | mesna
1305058 | methotrexate
1506270 | methylprednisolone
906780 | metoclopramide
793846 | neratinib
1000560 | ondansetron
35605522 | osimertinib
1378382 | paclitaxel
37499173 | palbociclib 100 MG Oral Tablet [Ibrance]
45892075 | palbociclib
911354 | palonosetron
1325608 | pegfilgrastim
45775965 | pembrolizumab
1304919 | pemetrexed
42801287 | pertuzumab
43014237 | pomalidomide
1551099 | prednisone
19034327 | prednisone 50 MG Oral Tablet [Deltasone]
1592911 | ribociclib
1314273 | rituximab
40244464 | ruxolitinib
1436678 | tamoxifen
1636780 | testosterone
1387104 | trastuzumab
903643 | tretinoin
903963 | triamcinolone
42629018 | 1 ML triamcinolone acetonide 40 MG/ML Injection
1308290 | vincristine
1592862 | 1 ML vincristine sulfate 1 MG/ML Injection
1343346 | vinorelbine
1337651 | vorinostat

**Comment by aostropolets** [comment]
That's strange, all clinical/branded drugs you listed do have dose forms (such as [here](https://athena.ohdsi.org/search-terms/terms/42629018)). Ingredients do not really have dose forms by definition. What you see in RxNav is the dose form groups of the drugs containing those ingredients. To get the form, you can simply jump to the descendants of an ingredient and follow Has dose form/Has dose form group links.

**Comment by mik-ohdsi** [comment]
Perfect, Anna (@aostropolets)! 
@cukarthik, Here is a diagram that shows your abemaciclib example with some selected relationships and concept classes. Hope this helps. 
![relations](https://user-images.githubusercontent.com/60365423/129178663-bd69ecde-efdd-466d-a9da-cc101db059c3.png)

Please let us know, if your issue has been resolved by these comments.

**Comment by cukarthik** [comment]
Thanks, @Alexdavv ! The diagram was very helpful. I see we need to update our ETL to navigate the relationships until we find the dose form.

**Comment by mik-ohdsi** [comment]
okay, okay... @Alexdavv, of course you are right and I omitted a quicker link in the diagram... well, I didn't claim it was exhaustive... :-) Here is an updated version of it, @cukarthik 

cheers ~ Mik
![relations2](https://user-images.githubusercontent.com/60365423/129361029-abefc9b7-03a7-4326-a856-49dff59c15e4.png)

**Comment by Alexdavv** [comment]
@mik-ohdsi 

> okay, okay... @Alexdavv, of course you are right and I omitted a quicker link in the diagram... well, I didn't claim it was exhaustive... :-) Here is an updated version of it, @cukarthik
> 
> cheers ~ Mik
> ![relations2](https://user-images.githubusercontent.com/60365423/129361029-abefc9b7-03a7-4326-a856-49dff59c15e4.png)

The point was we have the concept_ancestor for this purpose.
Diagram looks great, except the ancestors should be better on the top.
