### ISSUE TITLE
MEDRT and HGNC not included in bundle

### ISSUE THREAD

**Issue by mpatel-cai** [OHDSI/Vocabulary-v5.0#528]
I already checked to make sure that HGNC and MEDRT were selected when putting the bundle together, but both vocabularies have 0 concepts in the CONCEPT table.

**Comment by mik-ohdsi** [comment]
@mpatel-cai - you are right, I can see the same in the vocabulary server. I will investigate!

**Comment by mik-ohdsi** [comment]
Hi Meera (@mpatel-cai) - both vocabularies should actually be invisible. All content from HGNC has been moved to the OMOP Genomic vocabulary. MED-RT has never been really adopted as its content didn't justify to process its very complex structure.
With the next release we will make them disappear from the download list...

**Comment by mpatel-cai** [comment]
@mik-ohdsi 

Thanks for letting me know! 

Before, HGNC being folded into the OMOP Genomic, the `Protein Variant`, `Transcript Variant` and `Gene Variant` all rolled up to an HGNC gene rather nicely. I just looked at the Concept Classes for OMOP Genomic and I do not see anything comparable with this newer version (upon cursory review of course). Is there something similar that I am not seeing. I understand that it is still being actively worked on so am not expecting a definite answer, but if this has been discussed already it would be good to know!

**Comment by mik-ohdsi** [comment]
@denyskaduk  can you tell @mpatel-cai  how to deal with the variant to Gene relationship now?

**Comment by denyskaduk** [comment]
Hello [Meera](@mpatel-cai )!

HGNC in the Standarized Vocabularies from previous version majorly changed _vocabulary_id_ and _concept_class_id_ to **'OMOP Genomic'** and **'Genetic Varation'** accordingly, and some minor _concpet_name_ changes was done. _concept_id_ has not changed.

**Comment by mpatel-cai** [comment]
@mik-ohdsi @denyskaduk 

Thanks for updating me on this. I haven't had the chance to look into this since some of my functions need to be debugged - but how about the HGNC `concept_code`. It was 4-digit integer. Has that persisted in the current version?

**Comment by denyskaduk** [comment]
_concept_code_ is also wasn't changed, it contains digits from **HGNC ID** without **_HGNC:_**

**Comment by mpatel-cai** [comment]
@mik-ohdsi @denyskaduk 

Thank you for the updates!
