### ISSUE TITLE
Remicade-specific HCPCS not mapping to Remicade RxNorm

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#529]
The HCPCS [J1745](https://athena.ohdsi.org/search-terms/terms/2718445) is the Remicade brand-specific code as detailed by the [manufacturer](https://www.janssencarepath.com/hcp/remicade/reimbursement/coding-billing) though it is labelled as _Infliximab injection excluding biosimilars_. This term is mapping to a non-specific [RxNorm extension code](https://athena.ohdsi.org/search-terms/terms/41205480) for inflixmab. I suggest this relationship should be updated and this HCPCS code should map to [937369](https://athena.ohdsi.org/search-terms/terms/937369). 

tagging @jamieweaver for awareness

**Comment by mik-ohdsi** [comment]
Thanks for bringing this to our attention, @clairblacketer ! We are planning for a HCPCS refresh and will fix this in the process.

**Comment by cgreich** [comment]
This is nasty. Because the concept name of J1745 does not call out the fact at all that it only corresponds to the brand Remicade. We need to check whether there are more such cases.

**Comment by ericaVoss** [comment]
https://www.janssencarepath.com/hcp/remicade/reimbursement/coding-billing

The product-specific HCPCS code for REMICADE® is J1745, infliximab, 10 mg. It is important to note that this code represents 1/10th of a vial. You should be sure to bill 10 units of J1745 on the claim form when indicating that a single 100-mg vial of REMICADE® was used.

**Comment by m-khitrun** [comment]
@clairblacketer, we've fixed the mapping: https://athena.ohdsi.org/search-terms/terms/2718445
