### ISSUE TITLE
2020Q4 - Achilles - Transactions after death errors (zombie errors) 

### ISSUE THREAD

**Issue by tyults** [OHDSI/Vocabulary-v5.0#532]
The following errors in Achilles are due to visits with date after the death date.

analysis_id | achilles_heel_warning | rule_id | error_count|total count
-- | -- | -- | -- | --
511 | WARNING: 511-Distribution of time from   death to last condition (count = 1); max value should not be positive,   otherwise its a zombie with data >1mo after death | 3 | 3,939|7,208,053,700
512 | WARNING: 512-Distribution of time from death to last drug (count = 1);   max value should not be positive, otherwise its a zombie with data >1mo   after death | 3 | 5,587|2,968,705,708
513 | WARNING: 513-Distribution of time from death to last visit (count = 1);   max value should not be positive, otherwise its a zombie with data >1mo   after death | 3 | 5.010|3,690,747,594
514 | WARNING: 514-Distribution of time from death to last procedure (count =   1); max value should not be positive, otherwise its a zombie with data   >1mo after death | 3 | 2,135|4,644,027,938
515 | WARNING: 515-Distribution of time from death to last observation (count =   1); max value should not be positive, otherwise its a zombie with data   >1mo after death | 3 | 1,588|3,603,465,606

**Comment by tyults** [comment]
We are not deleting any transactions after death date.  These % are really small <= .0002% so it's ok to keep them.

**Comment by clairblacketer** [comment]
sorry @tyults why is this a vocabulary issue?

**Comment by tyults** [comment]
Issue was created by mistake in the wrong repo.  Closing.
Please delete if possible.
