### ISSUE TITLE
Afghanistan is not available in Race Domain

### ISSUE THREAD

**Issue by usmanafzal89** [OHDSI/Vocabulary-v5.0#534]
Hi
The Country Afghanistan is not available under RACE vocabulary/domain. Although we can use (8515 - Asian), Better to add new value **Afghani** under race vocabulary/domain.

**Comment by usmanafzal89** [comment]
@cgreich  we are converting our patient data to omop cdm for a Covid- Specific Study. We have most of the patients from Pakistan and Afghanistan. For Pakistan we find the RACE_CONCEPT_ID (38003589 - Pakistani) in the Race Vocabulary but nothing for Afghanistan.

**Comment by usmanafzal89** [comment]
As per the the OMOP CDM documentation link for accepted race_concept_id is
https://athena.ohdsi.org/search-terms/terms?domain=Race&standardConcept=Standard&page=1&pageSize=15&query=

**Comment by cgreich** [comment]
I am increasingly coming to the conclusion that making ethnicities hierarchical descendants of races is impossible to maintain. We should have some basic racial concepts (maybe black, white, Asian (racial, not geographical), american native, maybe a few more). No mixtures of those. And have a list of ethnicities based on today's countries. And that's it. 

I'll start another debate in the Forum. But whatever we do it will be ugly and break for some use cases. I cannot help that. I wish we were all the same, irrespective of some random disequilibria in our genomes.

Urgh.

**Comment by cgreich** [comment]
In your example, you have the ethnicity Pashtun, which is both at home in Afghanistan and in Pakistan. And then you have Punjabi, Sindhi, Saraiki, Muhajir, Balooch etc. And in Afghanistan you got Tadjik and Uzbek etc. This is not a solvable problem, @usmanafzal89. I would suggest you either add another field on the side, or you use the location table, or you create two different databases for patients from Afghanistan and Pakistan.

**Comment by mik-ohdsi** [comment]
@usmanafzal89  , with your permission I will close this issue now, after Christian Reich has provided his explanation.
