### ISSUE TITLE
MedDRA Rhabdomyolysis Mapping into SNOMED

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#54]
``` sql
SELECT ca.max_levels_of_separation, ca.min_levels_of_separation, c.concept_id AS MEDDRA_CONCEPT_ID, c.concept_name AS MEDDRA_CONCEPT_NAME, 
        c2.concept_id AS SNOMED_CONCEPT_ID, c2.concept_name AS SNOMED_CONCEPT_NAME, 
        ROW_NUMBER() OVER(PARTITION BY c.CONCEPT_ID ORDER BY c.CONCEPT_ID, ca.min_levels_of_separation, ca.max_levels_of_separation, c.CONCEPT_ID, c2.CONCEPT_ID) AS ROW_NUM
FROM CONCEPT c
        JOIN concept_ancestor ca
                ON ca.ancestor_concept_id = c.concept_id
        JOIN CONCEPT c2
                ON c2.concept_id = ca.descendant_concept_id
                AND c2.vocabulary_id = 'SNOMED'
                AND c2.CONCEPT_CLASS_ID = 'Clinical Finding'
                AND c2.INVALID_REASON IS NULL
WHERE c.vocabulary_id = 'MedDRA'
AND c.concept_class_id = 'PT'
AND c.INVALID_REASON IS NULL
AND c.CONCEPT_CODE = '10039020' /*Rhabdomyolysis*/
```

I'm finding the closest maps of MedDRA code for Rhabdomyolysis are:
- `137967  Muscle, ligament and fascia disorders`
- `4345578 Rhabdomyolysis`

The first seems like a very high level map and the second is the most appropriate.  Why does the "Muscle, ligament and fascia disorders" come in as a close map?

I'm using this map in LAERTES to get Product Labels codified in MedDRA to their SNOMED mappings.  Currently I'm picking the top closest SNOMED code and in my sorting the "Muscle, ligament and fascia disorders" wins.

**Comment by cgreich** [comment]
Yeah. Hard to say. It doesn't win, it is equally far away from the MedDRA term as the Rhabdomyelosis. And it was added in 2013, when we got a whole lot of mappings form the MSSO. The quality is not bad, but not that great, either. On the good side, it doesn't do much harm, because it has no children. Which means it will soon be deprecated anyway.

If you want I just kill that relationship.

**Comment by ericaVoss** [comment]
Could I use the no sibling approach here?

**Comment by ericaVoss** [comment]
*v5.0 21-JAN-16*

This still exists, just making note.

**Comment by ericaVoss** [comment]
20160817

Boo, "Muscle, ligament and fascia disorders" just doesn't want to go away.

**Comment by ericaVoss** [comment]
BOOOOOOOOOOOOOOOOOOOOOOOOO!  @cgreich  this is still in 20161107.

**Comment by ericaVoss** [comment]
All my dreams have come true!  Thank you @cgreich  and @dimshitc !

**Comment by cgreich** [comment]
Easy to make you happy, Erica. :)
