### ISSUE TITLE
ICD10CM G04.39 mapping to SNOMED  - suggested improvement

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#555]
ICD10CM  G04.39, 'Other acute necrotizing hemorrhagic encephalopathy' (ID 45562072) currently maps to SNOMED 374021 'Acute disseminated encephalomyelitis'.

I recommend it should be mapped to:

SNOMED 72986009 'Acute hemorrhagic leukoencephalitis'  (which is the same place that currently G04.30 'Acute necrotizing hemorrhagic encephalopathy, unspecified' maps, as well as G04.3, G04.31, G04.32....the only difference in the codes is the word 'other' on G04.39)

**Comment by divakhnenko** [comment]
Hello @pbr6cornell!

Thank you for pointing out this inconsistency.
We are now working on the ICD10 vocabularies' mapping improvement and will add this issue to the scope.

**Comment by Alexdavv** [comment]
The fix has been implemented within the recent vocabulary [release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20211206_1638786340).
