### ISSUE TITLE
3,588 CPT4 Classification codes appear in Synpuf

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#558]
CPT4 codes normally map to themselves (e.g. like [this one](https://athena.ohdsi.org/search-terms/terms/40756848)), but a large number have no 'Maps to' relationship whatsoever (e.g. [this one](https://athena.ohdsi.org/search-terms/terms/45889023)). This SQL counts the number of valid CPT4 codes without mapping:

```sql
SELECT COUNT(*)
FROM concept concept_1
LEFT JOIN (
	SELECT concept_id_1
	FROM concept_relationship
	INNER JOIN concept concept_2
		ON concept_2.concept_id = concept_id_2
	WHERE relationship_id = 'Maps to'
	) maps_to_relationships
	ON concept_1.concept_id = concept_id_1
WHERE concept_id_1 IS NULL
	AND concept_1.invalid_reason IS NULL
	AND concept_1.vocabulary_id = 'CPT4';
```

**Comment by mik-ohdsi** [comment]
Hi Martijn,
thanks for highlighting this. The ones you found seem to be **classification** concepts from the (extensive) CPT4 hierarchy, which contain as child nodes (sometimes over several levels) the fully qualified CPT4 codes. Those are, as you stated, either standard themselves or mapped to a standard concept.

```SQL
SELECT c_1.concept_id, c_1.concept_name, c_1.concept_class_id
FROM concept c_1
LEFT JOIN (
	SELECT concept_id_1
	FROM concept_relationship crel
	INNER JOIN devv5.concept c_2
		ON c_2.concept_id = concept_id_2
	WHERE relationship_id = 'Maps to'
	) maps_to_relationships
	ON c_1.concept_id = concept_id_1
WHERE concept_id_1 IS NULL
	AND c_1.invalid_reason IS NULL
	AND c_1.vocabulary_id = 'CPT4'
	LIMIT 500;
```

Have you found those CPT4 codes in source data, blocking a successful ETL?

Cheers
 Mik

**Comment by schuemie** [comment]
They appear in the Synpuf data, which I'm using for demonstration purposes. I don't think this has high priority.

**Comment by m-khitrun** [comment]
Hello @schuemie! Is this discussion still relevant?

**Comment by TinyRickC137** [comment]
Hello, @schuemie 

These CPT4 codes are classificational, and from vocabulary perspective everything works as it should.

We do not participate in Synpuf as authors.

Please feel free to reach us if this issue is still valid.
