### ISSUE TITLE
UCUM Duplication

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#56]
For `OMOP Vocabulary v4.5 17-JUL-15`

The following CONCEPT_CODE is duplicated in UCUM:

```{sql}
SELECT CONCEPT_ID, CONCEPT_NAME, CONCEPT_CODE
FROM CONCEPT
WHERE VOCABULARY_ID = 11
AND CONCEPT_CODE = '10*6.[U]'
```

```{text}
CONCEPT_ID	CONCEPT_NAME	CONCEPT_CODE
9689	Million unit	10*6.[U]
45891020	megaunit	10*6.[U]
```

**Comment by cgreich** [comment]
Thanks. Fixed in next release.

**Comment by dimshitc** [comment]
We have incorrect translations from unit_source_value to UCUM concepts in a CDMs. Look:
unit_concept_id      units_source_value    concept_name
9108	               KIU/ML       	       Kelvin International Units per milliliter
8903	               K/CU MM	               Kelvin per cubic millimeter
8792	               K/UL	                       Kelvin per microliter
8792	               K/MCL	               Kelvin per microliter

But exact procedures having such units_source_values are: "Leukocytes [#/volume] in Blood by Automated count", "Alpha-1-Fetoprotein [Mass/volume] in Amniotic fluid", etc. So here they have not a Kelvin per milliliter, but 1000 per milliliter.

**Comment by cgreich** [comment]
@dimshitc:

Not sure where you are getting these from. Must be based an old vocabulary version. Now they are:

8792	K/uL	Kelvin per microliter	U
8903	K/mm3	Kelvin per cubic millimeter	U
9108	K[iU]/mL	Kelvin International Units per milliliter	U

As you can see they are all invalid_reason='U' and replaced by the proper versions:

C1_ID	C1_NAME	REL	R_IR	C2_ID	C2_NAME	C2_VOCAB
8792	Kelvin per microliter	Concept replaced by		8848	thousand per microliter	UCUM
8903	Kelvin per cubic millimeter	Concept replaced by		8961	thousand per cubic millimeter	UCUM
9108	Kelvin International Units per milliliter	Concept replaced by		9525	kilo-international unit per milliliter	UCUM

**Comment by cgreich** [comment]
I think this is closed. Those "Kelvins" are all kilos now.
