### ISSUE TITLE
LOINC Hierarchy codes not mapped

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#561]
Hi,

We're looking at the below LOINC hierarchy source concepts, and were wondering if they have any mappings to more granular LOINC concepts:

40775398,40775446,40776581,40776614,40776789,40782086,40788723,40788726,40788727,40796466

Thanks,
Ajit

**Comment by mik-ohdsi** [comment]
Hi @alondhe (Ajit),
I checked the first three and they are all deprecated in December 2019. LOINC normally gives us a replacement code if they decide to retire a code in exchange with a better one. Here they seem to simply have deleted them without replacement. I checked if I could find the 3rd one in [LOINC itself](https://loinc.org/?s=41779-7), but no luck.
My first assumption would be that these codes are pretty much unusable.
Cheers - Mik
