### ISSUE TITLE
Mvasi mappings

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#562]
Hi,

Can we add a map for this HCPCS code for Mvasi (https://athena.ohdsi.org/search-terms/terms/953212)? Perhaps to 1510542 or 1510543 if there's no standard concept for 10 mg bevacizumab-awwb.

Thanks,
Ajit

**Comment by mik-ohdsi** [comment]
Hi @alondhe ,
I think there is at least no 10mg Mvasi in [RxNorm](https://mor.nlm.nih.gov/RxNav/search?searchBy=String&searchTerm=mvasi). And the precise ingredients like bevacizumab-awwb are currently an issue under discussion between RxNorm and us. Biosimilars are a bit tricky and RxNorm is not too keen to make any changes to their current model. However, [1510542](https://athena.ohdsi.org/search-terms/terms/1510542) looks like a valid target. Let us see what can be done.

**Comment by m-khitrun** [comment]
@alondhe , the code was added and mapped: https://athena.ohdsi.org/search-terms/terms/953212
