### ISSUE TITLE
HCPCS D9222 and D9223 missing

### ISSUE THREAD

**Issue by neilmdixit** [OHDSI/Vocabulary-v5.0#563]
Hello,

I believe two HCPCS codes are missing from the Vocabulary, D9222 and D9223. They appear related to D9220 and D9221, which are already in the vocabulary. I believe if they were added, the information attached to them would look something like this:

| Code | Name | Class | Domain | Vocabulary |
| - | - | - | - | - |
| D9222 | DEEP SEDATION/GENERAL ANESTHESIA - INITIAL 15 MINUTES | HCPCS | Procedure | HCPCS |
| D9223 | DEEP SEDATION/GENERAL ANESTHESIA - EACH SUBSEQUENT 15 MINUTE INCREMENT | HCPCS | Procedure | HCPCS |

Thank you, please let me know if I should provide additional information.

**Comment by cgreich** [comment]
These are CDT codes, and in Athena, @neilmdixit.

**Comment by neilmdixit** [comment]
@cgreich thank you! Would you mind sharing the search you performed to identify these in Athena?

**Comment by cgreich** [comment]
Just type the codes into the search box.

**Comment by neilmdixit** [comment]
@cgreich, thanks, that's really helpful. Below is what I see when I just 'type the codes into the search box'. Clearly, these codes are missing...
![image](https://user-images.githubusercontent.com/49662664/143893002-788399b1-fbeb-4d58-9631-03b582b89111.png)

**Comment by cgreich** [comment]
That's because you haven't got access to CDT. Athena will only show you concepts you can see. Which are all, except the ones you need a license for.

**Comment by neilmdixit** [comment]
I see. Yes, that explains it. Thank you for clarifying that for me, I really appreciate it.
