### ISSUE TITLE
Require Standard Concept, more specific mapping for ICD-10-CM U09.9 ” Post COVID condition

### ISSUE THREAD

**Issue by DaveraGabriel** [OHDSI/Vocabulary-v5.0#567]
The ICD10CM code for “long COVID” (U09.9 Post COVID condition) is required to support research use cases in N3C. Current non-standard concept mapping provides a standard concept that is is too far up the hierarchy to meet the semantic needs for any research use cases

![image](https://user-images.githubusercontent.com/48331201/144520234-04945927-3346-4752-a9fb-ae124e1be977.png)
please provide a standard code modeled to a much more specific location. Suggest a child concept of Disease due to Coronaviridae (27619001)

**Comment by DaveraGabriel** [comment]
follow-up to forum post: https://forums.ohdsi.org/t/require-standard-concept-more-specific-mapping-for-icd-10-cm-u09-9-post-covid-condition/15296

**Comment by mik-ohdsi** [comment]
Hi @DaveraGabriel , let's discuss your research use cases in a direct call so that we can find a universal yet well suited solution for N3C and the rest of OHDSI. I will ping you directly. ~ Mik

**Comment by Alexdavv** [comment]
Released and announced [here](https://forums.ohdsi.org/t/require-standard-concept-more-specific-mapping-for-icd-10-cm-u09-9-post-covid-condition/15296/34).
