### ISSUE TITLE
Keep a record of the changes with every release during the statistics run

### ISSUE THREAD

**Issue by mik-ohdsi** [OHDSI/Vocabulary-v5.0#570]
While creating the statistics that are attached to every release in the github, please also create a dump of the actual concepts and concept relationships that are represented here and make them available for download.
Naming convention could be {dateofrelease}_concept_delta.csv and {dateofrelease}_concept_relationship_delta.csv. We need to find a place to store these csv's (github?).

@DaveraGabriel @stephanieshong

**Comment by mik-ohdsi** [comment]
On a second thought, it might be more suitable that the tables would not have the regular concept and concept_relationship structure but rather have one table for all concept changes (including the nature of the change) and another table for all relationship changes, so they would also be human readable without running comparisons with the full vocabulary as well as providing information about removed relationships. This feature could be replaced by an Athena capability to keep multiple versions as described in this [Athena issue](https://github.com/OHDSI/Athena/issues/265).

**Comment by TinyRickC137** [comment]
Part of the Athena project and is available under [Athen](https://athena.ohdsi.org/vocabulary/list)
