### ISSUE TITLE
CPT4 records from CONCEPT_CPT4 showing up as "Non-Standard" Value

### ISSUE THREAD

**Issue by andyjessen** [OHDSI/Vocabulary-v5.0#574]
There are 151 CPT4 records from the Drug Domain that map as a "Non-Standard" value. This prevents them from being included in the concept_ancestor table.

Question: Is this a bug in the build? If not, can you explain why these CPT4 records are mapped this way? 

https://athena.ohdsi.org/search-terms/terms?domain=Drug&vocabulary=CPT4&standardConcept=Non-standard&page=1&pageSize=15&query=

**Comment by mik-ohdsi** [comment]
Hi @andyjessen - please let me know if the issue persists to be an actual problem or if my explanation was satisfactory for you! thanks - Mik
