### ISSUE TITLE
Invalid Concept_Relationship values within CPT4 codes

### ISSUE THREAD

**Issue by andyjessen** [OHDSI/Vocabulary-v5.0#575]
There are relationships within the CPT4 codes that appear invalid. 

See Example: 
https://athena.ohdsi.org/search-terms/terms/43527906
![image](https://user-images.githubusercontent.com/62343929/145608262-12ea273a-040b-49c6-8c11-5d4e6d55dec5.png)

This code has two parents (42628072 and 45889163 ). 45889163 is also related to 42628072 as their parent. Essentially, parent has a child with their child. Instead of directed acyclic, this relationship appears to be cyclic. 

Consider dropping the “Is a” relationship for the “Intra-Arterial-Intra-Aortic Vascular Injection Procedures” on the root level code (43527906). This duplication appears to affect about 180 CPT4 codes.

**Comment by m-khitrun** [comment]
It's fixed now. The 42628072 has been deprecated by the source, so cyclic relationships have deprecated too.
