### ISSUE TITLE
CPT4 utility for CDM v4 failed to process 312 codes.

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#578]
Vocabulary version: OMOP Vocabulary v4.5 06-DEC-21
[not-processed-concepts-12-21-2021-10-22-43.out.txt](https://github.com/OHDSI/Vocabulary-v5.0/files/7756834/not-processed-concepts-12-21-2021-10-22-43.out.txt)

**Comment by mik-ohdsi** [comment]
Hi @don-torok , thanks for bringing this up. Looks a lot like what has been brought up in this forum [thread](https://forums.ohdsi.org/t/cpt4-cpt-bat-process-issue/15175).
We have fixed it by providing a slightly adjusted cpt4.jar, but apparently the updated version is only being packaged with the v5.0 vocab download.
Let me check if I can get you a patched version.

**Comment by mik-ohdsi** [comment]
Hi @don-torok, I have tested the cpt4.jar that comes with the v5 download and it apparently also works with the v4 files. So if you can get a v5 download just with CPT4 and then copy that ctp4.jar over to your vocab folder (maybe a good idea to start over fresh by unpacking the previously downloaded zip file).
Please let me know if that helped! ~ Mik

**Comment by don-torok** [comment]
Thank you for looking into this.  I copied the missing concepts from a v5 download.

**Comment by cgreich** [comment]
@don-torok: You are still using V4??? Are you also doing your SQL work on punch cards?

**Comment by Siddhesh-Nalawade** [comment]
@don-torok @cgreich @mik-ohdsi 
Hi I got the error mentioned below while running CPT4 jar file. 

![image](https://user-images.githubusercontent.com/97395597/171100524-548b5a61-e317-475c-8692-651b536fbfd2.png)

> Hi @don-torok, I have tested the cpt4.jar that comes with the v5 download and it apparently also works with the v4 files. So if you can get a v5 download just with CPT4 and then copy that ctp4.jar over to your vocab folder (maybe a good idea to start over fresh by unpacking the previously downloaded zip file).

could you please help with how to solve this issue?  From where I can get this CPT4 v5 jar file? Thank you
