### ISSUE TITLE
Missing CONCEPT_IDs?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#58]
Comparing `OMOP Vocabulary v4.5 17-JUL-15` vs `OMOP Vocabulary v4.5 3-Apr-2015` I'm finding 84,405 missing CONCEPT_IDs.  Here are some examples:

```{text}
21000003-Invasive Procedure on Brain
21000011-Paratyphoid Fever 
43542337-U100 Safety single use insulin syringe with 8mm needle (30G) 0.3ml 
```

**Comment by cgreich** [comment]
These are concept from restricted vocabularies: FDB Indication and Multilex. We don't currently have a distribution license, but if you want I could give you the old thing back.

**Comment by ericaVoss** [comment]
I don't think we need them, was just spot checking the Vocab
