### ISSUE TITLE
CPT-4  concept_cpt4 table not concept_name column data

### ISSUE THREAD

**Issue by youdation** [OHDSI/Vocabulary-v5.0#580]
I downloaded the latest version of CPT-4 data through [Athena,](https://athena.ohdsi.org/search-terms/start) and update by cpt4.jar，and then I will proceed concept_ CPT4 and concept_ Relationship is imported into PostgreSQL Table, but  concept_Name column in Concept_cpt4 table  is empty. How to solve it?
![image](https://user-images.githubusercontent.com/40634721/147454252-5346aef3-04da-4156-abfc-7e2dbd95ebfe.png)

**Comment by don-torok** [comment]
cop4.jar updates the Concept table with CPT-4 codes.  Then import Concept, not concept_CPT4 into the database.

**Comment by youdation** [comment]
Thank you very much. I imported concept table and solved my problem.

**Comment by mik-ohdsi** [comment]
Thank you @don-torok ! much appreciated! closing the issue!
