### ISSUE TITLE
Change ICD10CM mapping for elective termination of pregnancy

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#583]
For concept 45547303, which is an ICD10CM for "Encounter for elective termination of pregnancy". 

Currently, it maps to:

308335008 | Patient encounter procedure
386639001 | Termination of pregnancy

As it's elective, I'm thinking we should consider mapping it to concept 4081422, "Elective termination of pregnancy"

**Comment by irinazherko** [comment]
The changes were implemented during the latest release
