### ISSUE TITLE
Create Simplified Acute Physiology Score III (SAPS-3) Concept

### ISSUE THREAD

**Issue by carlosalcampos** [OHDSI/Vocabulary-v5.0#587]
**Forum OHDSI:** [SAPS-3: Simplified Acute Physiology Score III](https://forums.ohdsi.org/t/saps-3-simplified-acute-physiology-score-iii/15557)

I noticed that we do not have SAPS-3 in our vocabularies.
I found SAPS and SAPS-2, but not SAPS-3

As we usually use this measurement in many studies, I believe we should add this measurement to our vocabularies

Regards

**Comment by MariaRohozhkina** [comment]
Good news! We have added this concept in the new release:
https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20220409_1649488692
