### ISSUE TITLE
Non-standard units not available as standards

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#592]
I see 2 non-standard unit concept_ids for beats per minute (4118124,3195754) and breaths per minute (4117833,3197833), however, there are not standard unit concept_ids for these data. Can we make one of these options standard for each unit?

**Comment by Alexdavv** [comment]
This is the [{polinas}'s issue](https://forums.ohdsi.org/t/units-of-measure-to-add/11260/11).

 The recommendation would be to use [counts per minute](https://athena.ohdsi.org/search-terms/terms/8483) for both.

**Comment by mik-ohdsi** [comment]
Hi @Alexdavv and @MelaniePhilofsky - We had an even earlier [forum post](https://forums.ohdsi.org/t/unit-concepts-request/1410) about the exact same units again with the conclusion to use "[per minute](https://athena.ohdsi.org/search-terms/terms/8541)" (concept id = 8541, slightly different) .

How about we create a [discussion](https://github.com/OHDSI/Vocabulary-v5.0/discussions) and vote for the best solution? Maybe that would mean actual mapping to one of those, too...

**Comment by MelaniePhilofsky** [comment]
I think counts per minute is best because it is more specific for these two measurements. The per minute Mik suggests would probably be more appropriate for other uses.

Thanks!
