### ISSUE TITLE
concepts with no names

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Vocabulary-v5.0#6]
approximately 9k concepts have no names

**Comment by cgreich** [comment]
Frank:

 

Will be fixed for all but the GPI ones. Those are restricted. So, for your public tools it shouldn’t matter. For you private tools – give me the money. J

 

C

**Comment by cgreich** [comment]
Now only GPI codes left. Talking to Medi-Span about a new license.

**Comment by ericaVoss** [comment]
For **v5.0 12-FEB-16**, this still exists.

```{SQL}
SELECT VOCABULARY_ID, COUNT(*)
FROM CONCEPT
WHERE CONCEPT_NAME IS NULL
OR CONCEPT_NAME = ''
GROUP BY vocabulary_id
```

```{TEXT}
Read	158
GPI	16359
ICD10CM	282
```

**Comment by cgreich** [comment]
Will be fixed:

GPI: Will add the source.
ICD10CM: Isn't released yet. Will have them all then.

**Comment by ericaVoss** [comment]
Still exists in **v5.0 11-MAR-16**

**Comment by cgreich** [comment]
Yup. Coming up.

**Comment by ericaVoss** [comment]
Still exists in 20160817

```{text}
Read	158
GPI	12683
```

**Comment by cgreich** [comment]
Correct. But they are all deprecated. I have no way to get those concept_names. Because they are missing from current releases, and the old ones are not available. 

If you have records from the data that provide those names, please give us.

**Comment by ericaVoss** [comment]
I will send you the READ codes that I have.  Only got 45/158.

**Comment by ericaVoss** [comment]
If I update the query to this I think we can close the issue (tested in 20171201)

```{sql}
SELECT VOCABULARY_ID, COUNT(*)
FROM CONCEPT
WHERE (CONCEPT_NAME IS NULL
OR CONCEPT_NAME = '')
AND INVALID_REASON IS NULL
GROUP BY vocabulary_id
```
