### ISSUE TITLE
New SNOMED Code (MIS-C)

### ISSUE THREAD

**Issue by boss-sam** [OHDSI/Vocabulary-v5.0#601]
Hello, it looks like SNOMED code **895448002** corresponding to **Pediatric Multisystem Inflammatory Syndrome (MIS-C)** is currently not available in the vocabulary. Can this please be added in the next release? Thank you!

**Comment by boss-sam** [comment]
Sounds good. Thank you!

**Comment by RowanErasmus** [comment]
Hi, is there any idea about when we can expect a new SNOMED release to be available in the vocabulary? 
UK should be in line with the International January 2022 release in mid July, am I right to presume we shouldn't expect an update until some time after that date? 
Thanks!

**Comment by mik-ohdsi** [comment]
Hi @RowanErasmus - at the moment we are targeting a SNOMED refresh to Athena around beginning of July. The sources are however older, with the UK added as the last one with the January 2022 release, afaik.
@TinyRickC137 can probably tell you about the version dates of the other parts (US, Int.).

**Comment by TinyRickC137** [comment]
Hello, @boss-sam 
I am happy to inform you, that this code is included in the current release. 
The release will be soon accessible in Athena, at the moment you can check the release notes [here](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20220829_1661776786)

**Comment by RowanErasmus** [comment]
Thank you very much @TinyRickC137 !
