### ISSUE TITLE
tezepelumab-ekko standard concept

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#603]
Hi,

We have a new drug, tezepelumab-ekko, as of December 17, 2021. I see there are NDCs for it in Athena, but no standard concept for it to map to. Can we add one, perhaps as RxNorm Extension?

Thanks,
Ajit

**Comment by mik-ohdsi** [comment]
Hi @alondhe , we are currently processing the RxNorm release 01/2022 and that one should [contain](https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=2587790) it. We want to release this rather soon, so watch out for the next release. We are even considering to process the March RxNorm release, with a shorter cycle than usual. Once we release the January one, I will close this issue.

**Comment by mik-ohdsi** [comment]
Hi @alondhe  - it [showed up](https://athena.ohdsi.org/search-terms/terms/702499) as a precise ingredient. While this is somewhat debatable, this is how RxNorm handles it. Closing this issue!
