### ISSUE TITLE
Remove the word route from the concept name where Domain_id = 'Route'

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#605]
ETL mapping to get the Route_concept_id is most likely going to try matching on the concept name.  Unlikely that source with say 'Oral route' instead of simply 'Oral'. Same for all other entries in Route domain.

**Comment by m-khitrun** [comment]
Hello, @don-torok 

Please, be informed that we have trimmed the word 'route' from the [SNOMED concepts](https://athena.ohdsi.org/search-terms/terms?vocabulary=SNOMED&domain=Route&page=1&pageSize=15&query=https://athena.ohdsi.org/search-terms/terms?vocabulary=SNOMED&domain=Route&page=1&pageSize=15&query=) in the Route domain.

Regards,
Masha
