### ISSUE TITLE
Missing geography domain concept for Chile

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#607]
From Nicolás Bravo
I’m currently building an ETL to map oncology patients in Chile to the OMOP CDM 5.4.
While building it I noticed the country “Chile” is missing from “Geography” domain concepts, therefore I can’t map a patient home address to the LOCATION.country_concept_id column.

**Comment by jpallas** [comment]
It appears there are only [19 countries](https://athena.ohdsi.org/search-terms/terms?domain=Geography&conceptClass=2nd+level&page=1&pageSize=30&query=) in the Geography domain.  This problem is more than one missing country.

**Comment by Alexdavv** [comment]
We need to consider adding the OSM concepts for the rest of the countries.
Or moving the SNOMED location concepts to the Geography Domain. And maybe assigning the "2nd level" concept class - that smells bad.
I'd go for the latter option.

Thoughts? @TinyRickC137

**Comment by MelaniePhilofsky** [comment]
I vote the SNOMED concepts for countries be moved to the Geography domain. It's clean and makes sense.
