### ISSUE TITLE
ICD9CM->SNOMED mapping is not reciprocal in 'Maps To' and 'Mapped From' relations

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#61]
It should be the case that every 'Maps To' relation between concepts has a corresponding 'Mapped From' relation in the opposite direction.  For the ICD9CM -> SNOMED mapping, there is currently a bug, as there are more 'Mapped From' relations than "Maps To' relations.

Here's a query that shows the counts don't match up.  If you look at the concept 201820, you'll see how it makes a material difference in the ICD9CM codes identified.

select 'Mapped From', count(c1.concept_id)
from concept c1
inner join concept_relationship cr1
on c1.concept_id = cr1.concept_id_1
and cr1.relationship_id = 'Mapped From'
and cr1.invalid_reason is null
inner join concept c2
on cr1.concept_id_2 = c2.concept_id
where c1.vocabulary_id = 'SNOMED'
and c2.vocabulary_id = 'ICD9CM'
and c1.invalid_reason is null
and c2.invalid_reason is null

union

select 'Maps To', count(c1.concept_id)
from concept c1
inner join concept_relationship cr1
on c1.concept_id = cr1.concept_id_1
and cr1.relationship_id = 'Maps To'
and cr1.invalid_reason is null
inner join concept c2
on cr1.concept_id_2 = c2.concept_id
where c1.vocabulary_id = 'ICD9CM'
and c2.vocabulary_id = 'SNOMED'
and c1.invalid_reason is null
and c2.invalid_reason is null

;

**Comment by cgreich** [comment]
@pbr6cornell:

Found the problem. The script that ensures that all relatioships are symmetrical don't correctly check the invalid condition. So, it creates all the reciprocal ones, but if an existing gets deprecated it doesn't correctly deprecate the twin. Will fix next release (next week).

**Comment by cgreich** [comment]
All fixed.
