### ISSUE TITLE
Missing HCPCS code: G2025

### ISSUE THREAD

**Issue by ayangp** [OHDSI/Vocabulary-v5.0#611]
Payment for a telehealth distant site service furnished by a rural health clinic (rhc) or federally qualified health center (fqhc) only

G2025 Code has been in use since March 2020 for rural telehealth visits. Can the vocabulary be updated to include the missing code? Thank you!

https://bioportal.bioontology.org/ontologies/HCPCS?p=classes
https://bioportal.bioontology.org/ontologies/HCPCS?p=classes&conceptid=http://purl.bioontology.org/ontology/HCPCS/G2025

**Comment by m-khitrun** [comment]
@ayangp, the code was added: https://athena.ohdsi.org/search-terms/terms/801014
