### ISSUE TITLE
We are missing the following CVX and NDC codes in the OMOP vocabulary table:

### ISSUE THREAD

**Issue by stephanieshong** [OHDSI/Vocabulary-v5.0#612]
These codes are becoming important in COVID-19 research.
CVX: 221 (Moderna Booster)
CVX: 225
there may be more...

**Comment by kmkostka** [comment]
@mik-ohdsi, do we have an ETA for the next CVX release?

**Comment by mik-ohdsi** [comment]
Hi @kmkostka - [roadmap](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Release-planning---quarterly-updated) says it should become available in May. I agree it is kind of due, as we have automatically updated our sources with a date of 20211123. There are however more recent ones and meanwhile the code goes up to "226". Probably an issue of a source in UMLS not yet updated with the latest CVX codes. 
Just currently I don't see how we can make it happen earlier. Okay... tell me about your timeline and when you will be really in trouble if you do not have this updated in Athena vocabularies (unless your answer is "yesterday").

**Comment by stephanieshong** [comment]
@mik-ohdsi - I can ask N3C if May timeline is acceptable.

**Comment by stephanieshong** [comment]
Found some NDCs that are not found as well. Here is the list:

09999720665 | NDC
09999720666 | NDC
09999720671 | NDC
00069100002 | NDC
33332032102 | NDC
33332032101 | NDC
46028021811 | NDC
33332042110 | NDC
09999720670 | NDC
09999197625 | NDC
33332022121 | NDC
00000000023 | NDC
46028021911 | NDC
33332042111 | NDC
09999001739 | NDC
99999008181 | NDC
09999001419 | NDC
49281054605 | NDC
00000000012 | NDC
33332022120 | NDC
00000000001 | NDC
09999008511 | NDC
09999008708 | NDC
09999001418 | NDC
00000000698 | NDC
66019030801 | NDC
49281056101 | NDC
09999008955 | NDC

**Comment by stephanieshong** [comment]
@mik-ohdsi - could you let me know when we should update to include CVXcodes that goes up to "226"?

**Comment by stephanieshong** [comment]
@mik-ohdsi  - do you have any update for us? Thought that this will be updated in May version? I think we are still missing the booster cvx code. CVX: 221 (Moderna Booster)

**Comment by mik-ohdsi** [comment]
Hi @stephanieshong , we are trying to fit in that CVX refresh with our next release. We are currently trying to finalize the SNOMED refresh (three combined sources). That next release is supposedly due end of May / beginning of June.
The NDCs you have listed look very suspicious to me. As if these are made up / local numbers by some other party.
If you can find those in the [NDC browser](https://www.accessdata.fda.gov/scripts/cder/ndc/index.cfm) I would happily stand corrected. I tried but was not successful. The ones starting with 49281 looked promising (they looked as if they could be Sanofi vaccines), but no joy either...

**Comment by stephanieshong** [comment]
@mik-ohdsi - thank you for your reply. You can ignore the NDC list if you think they are not valid. I did not take time to check each one but we are more interested in the CVX codes that contain the covid booster codes. Thank you.

**Comment by mik-ohdsi** [comment]
Hi @stephanieshong - it admittedly is a little embarassing, but our velocity right now is not stellar... We have scheduled the CVX refresh to be done now so that we can make it available with a summer release early to mid August... I am deeply sorry that this takes so long.

**Comment by MariaRohozhkina** [comment]
Hello @stephanieshong! Now 221 and 225 CVX codes are available in Athena.
