### ISSUE TITLE
Inconsistency in codes related to acre (British) and acre (US)

### ISSUE THREAD

**Issue by symedical** [OHDSI/Vocabulary-v5.0#618]
When looking at UCUM concepts on the browser, I noticed that the code value for ID 9259, acre (British), is shown as **[acr_us]**, while ID 9258, acre (US), has a code of **[acr_br]**.  All of the other codes that I've checked are consistent with the naming convention.  For example, ID 9308, fathom (British) has a code of [fth_br] and ID 9310 fathom (US) has a code of [fth_us].  Is this a mistake and if so, when could it be rectified?

![Athena screenshot](https://user-images.githubusercontent.com/103532194/163039831-05ada950-e44b-40a8-9f7c-27fa33e6fe0d.PNG)

**Comment by TinyRickC137** [comment]
Hello, @symedical. This is a great catch, so obvious and still unnoticed. 
We have to create two new concepts with correct codes and names and deprecate 9259 and 9258 without mapping because we don't know if people used codes or names. 
Thank you for your input.

**Comment by cgreich** [comment]
All imperial units exist in both British and US versions. And, of course, they differ.

I wouldn't spend a whole lot of effort fixing acres. They are not used in medicine. Imperial units that are used in medicine (feet, inches, lbs) don't have that problem, and if they did the difference is below the precision typically used in our use cases. In other words - false precision, only theoretical relevance.

I have no idea why acres made it into the vocabularies to begin with. But again, not worth spending time on this.
