### ISSUE TITLE
4103381-“Retinitis pigmentosa”

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#621]
4103381-“Retinitis pigmentosa” maps to 
4101333 - "HSMN IV"
which maps to 356.3 ICD9CM & G60.1 ICD10CM – “Refsum’s disease

I feel like retinitis pigmentosa is in the wrong branch.

Vocabulary v5.0 17-JUN-21

![image](https://user-images.githubusercontent.com/6305439/164270665-d54d65bd-d8dc-4ef4-8266-a658f8868c24.png)

**Comment by TinyRickC137** [comment]
Hello! 
Well, that was what Snomed gives us. I think they are partly right. From [published article](https://www.ncbi.nlm.nih.gov/books/NBK1353/): Clinical manifestations in adult **Refsum disease** (ARD) are **retinitis pigmentosa**, anosmia (loss of sense of smell), sensorineural hearing loss, polyneuropathy (sensory and motor), ataxia (balance issues), ichthyosis, skeletal abnormalities including shortened fingers and toes, and cardiac arrhythmias and cardiomyopathy
