### ISSUE TITLE
Tailor's bunion

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#622]
Should these concepts:
`37108619 - Tailor's bunion of right foot`
`37117100 - Tailor's bunion of left foot`

Be children of this concept:
`4194207-Tailor's Bunion`

**Comment by TinyRickC137** [comment]
That's something that should be brought up to Snomed during next meeting, thank you

**Comment by m-khitrun** [comment]
Hello, @ericaVoss,

Please, be informed, that this hierarchy is fixed now: https://athena.ohdsi.org/search-terms/terms/4194207.

Regards,
Masha
