### ISSUE TITLE
How do you load the vocabulary 

### ISSUE THREAD

**Issue by rjiang9** [OHDSI/Vocabulary-v5.0#624]
I have downloaded the vocabulary from athena.ohdsi website. 

My question is: What is the recommended way to load the vocabulary data in csv format files into a Postgres database?

Thanks
~R

**Comment by TinyRickC137** [comment]
Closing this one, because it is basically not an issue. 

Welcome to OHDSI
R, please, go to the [OHDSI Forum](https://forums.ohdsi.org/t/what-is-the-recommended-way-to-load-vocabulary-into-postgres/16467). More people will reply there.

**Comment by rjiang9** [comment]
thanks, @TinyRickC137
