### ISSUE TITLE
RxNorm concept missing from ATHENA

### ISSUE THREAD

**Issue by LynxMaxim** [OHDSI/Vocabulary-v5.0#632]
Dear reader

We are trying to understand why the following concepts from RxNorm cannot be found in ATHENA. 
Example RXCUIs: 284635, 214317

It seems that it was a conscious decision to leave them out, as my spotchecks show that none of these type of concepts (combination of drug ingredients) are present in ATHENA. However, I do not understand why. 

Could someone explain the reasoning for leaving out these concepts? 
Maybe we could also see if in a future update they could be included somehow? 

Cheers
Maxim

PS: I'd be glad to explain further why this is causing us some issues :)

**Comment by pbr6cornell** [comment]
It would be helpful to hear your usecase, but just as a quick confirmation, In my vocabulary, I see RxCUI 214317= OMOP concept Id 36029913 = name 'Bisoprolol / Hydrochlorothiazide'.     I cannot find RxCUI 84635  in RxNav  or the OHDSI vocabularies, so wondering if you have a typo there.

**Comment by LynxMaxim** [comment]
Apologies, I indeed accidentally deleted a character. The issue is now updated to reflect the correct code. (284635)
I still cannot find the ATHENA concept_id for this one, is it just me? ;)

I need to structure my thoughts a bit further on the topic, I might come back with our use case soon!

**Comment by LynxMaxim** [comment]
@pbr6cornell 

To come back to our use case:

We often have situations where we don't have full information on a drug (sometimes only the active component without mention of dosage or drug form, sometimes only the brand, etc.). This data comes from text mining, which explains the lack of details, yet the information is still relevant to us.

I was looking into the possibilities for each type of occurrence of a drug in the text and for us it would be most interesting give broad concept ids to these occurrences, namely the active ingredient. For combination products, the class "Multiple Ingredients" from RxNorm would normally be chosen. These concepts are however non-standard and do not participate in the hierarchy.

This in turn lead me to the 'missing' RxNorm concept code, but is not our main issue.

If someone can provide some guidance on how best to go about this, that would also be appreciated.

**Comment by don-torok** [comment]
@LynxMaxim You are more likely to get a response if you move your question to one of the forums rather than here in github issues.

**Comment by cgreich** [comment]
@LynxMaxim:

There are two issues. 

Issue #1 is that you are giving us an example of an RXCUI that actually doesn't exist. Can you give us the correct one?

Issue #2 is how you get the best RxNorm concepts based on your incomplete data. The vocab team has a mechanism for doing that. Please reach out with your input, and we can figure out the best mapping.

**Comment by LynxMaxim** [comment]
Issue #1: I believe I provided the correct RXCUI (after correction). I'll share the link to RxNav this time: https://mor.nlm.nih.gov/RxNav/search?searchBy=String&searchTerm=fluticasone%20%2F%20salmeterol

Isseu #2: I moved the topic to the forum. https://forums.ohdsi.org/t/drug-domain-rxnorm-why-are-concepts-for-multiple-ingredient-non-standard/16621. Is there any documentation on this mechanism? (I'm suggesting it is rule based).

**Comment by Alexdavv** [comment]
> Issue #1: I believe I provided the correct RXCUI (after correction). I'll share the link to RxNav this time: https://mor.nlm.nih.gov/RxNav/search?searchBy=String&searchTerm=fluticasone%20%2F%20salmeterol

@hardhouse Can you please confirm it's not in the UMLS source we use?

**Comment by hardhouse** [comment]
@Alexdavv we don't use UMLS in RxNorm, and this concept is in the sources: select * from sources.rxnconso where sab = 'RXNORM' and rxcui='284635'. But it has tty='MIN', which we don't use in load_stage https://github.com/OHDSI/Vocabulary-v5.0/blob/master/RxNorm/load_stage.sql#L164

**Comment by Alexdavv** [comment]
> But it has tty='MIN', which we don't use in load_stage

[Here](https://github.com/OHDSI/Vocabulary-v5.0/blob/986c59d8ce3b6353b8d9912f247aabe5bde38ff3/RxNorm/load_stage.sql#L273) we do. But why is it rxnatomarchive rather than a trivial source?

**Comment by mik-ohdsi** [comment]
Hi @hardhouse , I understand we added MIN support [here](https://github.com/OHDSI/Vocabulary-v5.0/pull/494). With the restriction that we do not allow them to be standard. This particular RXCUI (284635) seems not to have made it. Do we understand why?

**Comment by hardhouse** [comment]
hi @mik-ohdsi , because in that commit we are using rxnatomarchive, not rxnconso

**Comment by mik-ohdsi** [comment]
Hi @hardhouse - could you prepare an analysis that explains why we use rxnatomarchive over rxnconso in this case and how we still could get all proper MINs included?

**Comment by hardhouse** [comment]
@mik-ohdsi  hi, analysis is impossible, because it was the decision of @ekorchmar and @cgreich. But technically, of course, there are no problems, i can add additional concepts from rxnconso to that INSERT

**Comment by mik-ohdsi** [comment]
@hardhouse  -  it would be great if we could get a rundown of our options how we can combine rxnatomarchive and rxnconso to achieve better coverage of MINs? Maybe also try to find out why some MINs are not in rxnatomarchive / how are those different to the ones that we can find in both tables?

**Comment by cgreich** [comment]
This is part of https://github.com/OHDSI/Vocabulary-v5.0/issues/470 and therefore closed.

**Comment by mik-ohdsi** [comment]
not quite @cgreich - as there were MINs missing. New logic has been [introduced](https://github.com/OHDSI/Vocabulary-v5.0/pull/640) but has not been fully implemented as there was no RxNorm refresh since.

**Comment by mik-ohdsi** [comment]
Hi @LynxMaxim - we have added the missing MINs to the recent vocabulary release. Can you check if you find everything you need? And if you do, please close the issue!
