### ISSUE TITLE
Duplicate provider specialties

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#64]
I'm mapping provider specialties, and was wondering why there are so many **standard** concepts (from different vocabularies) for the same thing?

For example:
- Dermatology (38004452 & 44777722)
- Cardiology (38004451 & 44777721)
- Urology (43125861, 38004474 & 44777747)

**Comment by schuemie** [comment]
Oh, and while I'm bugging you: what would be the procedure for adding 'Chinese Traditional Medicine' as a specialty?

**Comment by cgreich** [comment]
You just did.

Well, the larger problem is that the specialty list we use from CMS stinks. One of the things to redo. I'll put it on the list for the CDM group.

**Comment by ericaVoss** [comment]
This one is old, but highlighting for @clairblacketer

**Comment by cgreich** [comment]
@ericaVoss: It's actually for THEMIS [Focus Group 4](http://www.ohdsi.org/web/wiki/doku.php?id=projects:workgroups:themis:focusgroup4).

**Comment by MelaniePhilofsky** [comment]
@ericaVoss & @schuemie 
I've volunteered to make some recommendations on this issue in the Themis group. What specialties are missing and which ones are duplicate? Which coding system is the most comprehensive? NUCC, AMBS, CMS, others?

**Comment by ericaVoss** [comment]
Forum post here:
http://forums.ohdsi.org/t/provider-specialty-code-set-clean-up/3888
