### ISSUE TITLE
Add new type concept request for Outpatient Prescription Drug Coverage

### ISSUE THREAD

**Issue by allfires** [OHDSI/Vocabulary-v5.0#643]
We are currently working on converting multiple PCORNet datasets into OMOP CDM.  OUT ETL process is converting directly from PCORnet CDM to OMOP CDM.  

Would it be possible to have the value of “Outpatient Prescription Drug Coverage” from the PCORNet enrollment table added to OMOP vocabulary as a type concept?  I see there are many non-standard PCORnet vocabulary in Athena, but outpatient prescription drug coverage was not added and there doesn’t seem to be anything precisely to map to without loss of semantics. 

We have explored custom mapping and will go that route if needed, but thought to request adding that value to OMOP. 

Thanks for your consideration.

**Comment by don-torok** [comment]
Would it be possible for you to create Payer Plan Records for these people and with the combination of existing concepts for payer_concept_id and plan_concept_id identify satisfy your requirement?  Otherwise, where do you expect to use the new concept you are requesting?

**Comment by allfires** [comment]
@don-torok thank you again for your time.  After much discussion and a lot of back and forth on this issue, we will utilize the existing concepts you mentioned.
