### ISSUE TITLE
standard domain_id = 'Observation' when it should be 'Drug'

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#646]
concept_id = [2615303](https://athena.ohdsi.org/search-terms/terms/2615303) is incorrectly mapped to the 'Observation' domain

**Comment by mik-ohdsi** [comment]
Hi @MelaniePhilofsky  - it is on our "to be fixed" list and we plan to deliver a refresh including fixes early to mid August

**Comment by TinyRickC137** [comment]
Hello, @MelaniePhilofsky 
All fixed now!
