### ISSUE TITLE
Adding new CVX codes - primarily for Moderna vaccines:  CVX:: 221, 227, 228

### ISSUE THREAD

**Issue by krevett-iqvia** [OHDSI/Vocabulary-v5.0#647]
We are noticing that there are some CVX codes that are currently not available: CVX 221, 227, 228.  without these codes, our Moderna counts (especially for the Booster) are almost negligible - especially compared with the Pfizer booster counts.  Note that these CVX codes are incorporated into the CDC's list of Covid-19 vaccination codes for IIS.

**Comment by krevett-iqvia** [comment]
Any status update on this ticket?

**Comment by mik-ohdsi** [comment]
Hi @krevett-iqvia  -  we have taken CVX into processing and plan to make it available in our summer release in August. Yes, it is rather overdue...

**Comment by krevett-iqvia** [comment]
Thank you @TinyRickC137 and @cgreich for taking this important ticket on!  Roughly when in August do you expect the release to go out?  Thank you.

**Comment by krevett-iqvia** [comment]
Has the CVX codes been included into the August vocab yet? @TinyRickC137 @cgreich Thank you for any updates.

**Comment by MariaRohozhkina** [comment]
Hi! 221, 227, 228 codes are available in Athena now.
