### ISSUE TITLE
Proposed Addition of Trauma Score Concepts to OHDSI Vocabulary 

### ISSUE THREAD

**Issue by code12412f** [OHDSI/Vocabulary-v5.0#652]
My organization would like the Denver ED Trauma Organ Failure Score and Exponential Injury Severity Score (overall score and scores for 6 body regions—head, facial, pelvic, chest, extremity, and external regions) to be added to the OHDSI vocabulary. See the attached document. 
 
[OHDSI_WINDOWS_custom_concepts.docx](https://github.com/OHDSI/Vocabulary-v5.0/files/9145208/OHDSI_WINDOWS_custom_concepts.docx)

**Comment by MariaRohozhkina** [comment]
Thank you for the proposal. We will add it in the next OMOP Extension release.

**Comment by code12412f** [comment]
Thank you! What is meant by the OMOP Extension release? Also what is the timeframe for the addition of the new concept IDs to Athena?

**Comment by MariaRohozhkina** [comment]
We have OMOP Extension vocabulary (you can see it in Athena). In this vocabulary we add new concepts, when it is needed. 
I think, at the beginning of August

**Comment by rsanka82** [comment]
Can the OMOP Extension vocabulary be downloaded from Athena, like the other Vocabularies, for the purpose of making local instances of the OMOP CDM?

**Comment by MariaRohozhkina** [comment]
Sure.

**Comment by code12412f** [comment]
What's the status on these new concepts?

**Comment by code12412f** [comment]
Hi @MariaRohozhkina, I am touching base regarding the requested concept IDs. As end-of-August nears, I have have not found any of these IDs when I search Athena (using keywords for the Name field).
Could you provide an ETA on when these IDs will be added to the next OMOP Extension release? If they already were added, can you provide the ID numbers, so I may search for them?
If there is any additional information I must provide, or any steps that still need to be taken, please let me know.
Thank you for your time.

**Comment by MariaRohozhkina** [comment]
Hi! You can find concepts by using following ID numbers: 729846, 729847, 729848, 729849, 729850, 729851, 729852, 729853
