### ISSUE TITLE
bp pressure mapping

### ISSUE THREAD

**Issue by stephanieshong** [OHDSI/Vocabulary-v5.0#655]
I see that following bp concepts are defined in Athena:
|3034703|Diastolic blood pressure–sitting|
|3019962|Diastolic blood pressure–standing|
|36304130|Diastolic blood pressure-lying L-lateral position|
|3018586|Systolic blood pressure–sitting|
|3035856|Systolic blood pressure–standing|
|36303812|Systolic blood pressure-lying L-lateral position|
When the EHR system does not provide the BP position value ( sitting, standing, or lying) which concept_id would you recommend that I use for systolic blood pressure or diastolic blood pressure concept?
Do you have a concept for 
Diastolic blood pressure–unknown position or 
Systolic blood pressure-unknown position?

**Comment by TinyRickC137** [comment]
Hello, Stephanie
Answered [here](https://forums.ohdsi.org/t/blood-pressure-mapping/8118/8?u=zhuk)

**Comment by stephanieshong** [comment]
Thank you.
