### ISSUE TITLE
Post-acute COVID-19 SNOMED-CT codes

### ISSUE THREAD

**Issue by ajoedicke** [OHDSI/Vocabulary-v5.0#662]
Dear vocabulary team, 

Could you please add standard codes for post-acute COVID-10 SNOMED-CT codes? These codes are not yet mapped to the standard conceptID of 705076 Post-acute COVID-19.
The codes are available from _https://digital.nhs.uk/services/terminology-and-classifications/snomed-ct   -> NHS Digital SNOMET CT Browser_  and listed below.

Thank you very much!!

**Diagnostic categories**
1325181000000106   Ongoing symptomatic disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)
1325161000000102   Post-COVID-19 syndrome (disorder)
1119303003               Post-acute COVID-19
1119304009               Chronic post-COVID-19 syndrome

**Referral and signposting**
1325031000000108   Referral to post-COVID assessment clinic (procedure)
1325041000000104   Referral to Your COVID Recovery rehabilitation platform (procedure)
1325021000000106   Signposting to Your COVID Recovery (procedure)

**Assessment instruments and outcome measures**
1325051000000101   Newcastle post-COVID syndrome Follow-up Screening Questionnaire (assessment scale)
1325061000000103   Assessment using Newcastle post-COVID syndrome Follow-up Screening Questionnaire (procedure)
1325071000000105   COVID-19 Yorkshire Rehabilitation Screening tool (assessment scale)
1325081000000107   Assessment using COVID-19 Yorkshire Rehabilitation Screening tool (procedure)
1325091000000109   Post-COVID-19 Functional Status Scale patient self-report (assessment scale)
1325101000000101   Assessment using Post-COVID-19 Functional Status Scale patient self-report (procedure)
1325121000000105   Post-COVID-19 Functional Status Scale patient self-report final scale grade (observable entity)
1325151000000100   Post-COVID-19 Functional Status Scale structured interview (assessment scale)
1325141000000103   Assessment using Post-COVID-19 Functional Status Scale structured interview (procedure)
1325131000000107   Post-COVID-19 Functional Status Scale structured interview final scale grade (observable entity)

**Resolved**
1326351000000108   Post-COVID-19 syndrome resolved

**Comment by TinyRickC137** [comment]
Hello, @ajoedicke 
You will be thrilled to know that we are preparing a huge vocabulary release, where SNOMED will take a lead. 
I've just checked: all concepts of your interest will be included there. The release will take place in a couple of days. 

Regarding SNOMED: we don't add concepts by request, but we rather maintain 3 different editions of SNOMED and all the relationships between SNOMED and other vocabularies, that's why a time lag between SNOMED release and OHDSI Snomed release exists. This time lag is about 6-12 months at the moment, which may seem big, but considering the amount of work done every time, it isn't that big.

**Comment by ajoedicke** [comment]
Thank you @TinyRickC137!
Could you let me know when the new vocabulary release will be available?
Many thanks!

**Comment by Alexdavv** [comment]
> Thank you @TinyRickC137! Could you let me know when the new vocabulary release will be available? Many thanks!

It's on its halfway to Athena. I think the relevant ETA is an early next week.

**Comment by adelmestri** [comment]
Hi @TinyRickC137,
Any update regarding the SNOMED vocabulary release please?
Thank you!

**Comment by TinyRickC137** [comment]
Hello, @adelmestri 
Check Athena now, release took place

**Comment by adelmestri** [comment]
Hi @TinyRickC137,
Thank you. I have downloaded the updated vocabularies my project needs and run the "java -Dumls-apikey=xxx -jar cpt4.jar 5" with my apikey as usual. However, I received a number of errors, attached (I have changed the .out extension to .log as github did not accept it). Do you have any suggestion please? Thank you!

[not-processed-concepts-08-31-2022-08-28-58.log](https://github.com/OHDSI/Vocabulary-v5.0/files/9459870/not-processed-concepts-08-31-2022-08-28-58.log)

**Comment by TinyRickC137** [comment]
Well, that's a bit outside my competence, but what I can see as a potential problem: [Athena maintenance](https://forums.ohdsi.org/t/athena-maintenance/4142/26).

Try it later. If it doesn't work, please, go to OHDSI Forum, this is unlikely a vocabulary issue.

**Comment by adelmestri** [comment]
Thanks @TinyRickC137, the problem was unrelated to Athena maintenance and persists. All the unprocessed concepts belong to the CPT4 vocabulary. I will ask in the OHDSI forum.
