### ISSUE TITLE
Add 'Initial Diagnosis' modifier to 'Cancer Modifier' vocabulary.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/Vocabulary-v5.0#664]
Hello.  For Oncology Extension, we need to add a new concept, 'Initial Diagnosis', added to the 'Cancer Modifier' vocabulary .  Here are the details:

concept_id: ?
concept_name: 'Initial Diagnosis'
domain_id: 'Measurement'
vocabulary_id: 'Cancer Modifier'
concept_class_id: 'Extension/Invasion'
standard_concept: 'S'
concept_code:  ?
valid_start_date:  ?
valid_end_date: ?
invalid_reason:

This new concept was requested earlier in the Oncolgy WG repo, but I believe it got lost track of.  See here:

https://github.com/OHDSI/OncologyWG/issues/346

We are in the process of migrating the NAACCR ETL  to target the new 'Cancer Modifier' vocabulary and we need this new concept.  I was not sure about what concept class to place the concept in, but that detail can be debated later if necessary.  For now we need to the new concept move forward on the NAACCR ETL.

**Comment by vladkorsik** [comment]
Hello! Thanks a lot for raising the issue.
Not sure that Cancer Modifier with it's concept class labels has enough potency to represent such entity. May you explain the use case in more details?

**Comment by vladkorsik** [comment]
@cgreich is it  the concept? you are talking about https://athena.ohdsi.org/search-terms/terms/32533 ?

**Comment by vladkorsik** [comment]
And still, the cases listed below are definitely determinants of tumor biology/behavior. 
•In situ disease – create new
•Local disease – create new
•Regional disease – create new
•Metastatic disease – create new.
Initial Diagnosis has nothing mutual to those definitions and represent only time context of the appropriate state of the disease.
Why just not to create the appropriate Condition, and Disease extent/Dynamic records fro the very first Disease observed (with Initial dignosis in tag)?
It's not so complicated to build the concepts manually, but i just want to be informed well to move on.

**Comment by cgreich** [comment]
> you are talking about https://athena.ohdsi.org/search-terms/terms/32533 ?

No, that's just a concept for the table.

> Why just not to create the appropriate Condition, and Disease extent/Dynamic records fro the very first Disease observed (with Initial dignosis in tag)?

Yes, that's the alternative. Instead of explicitly calling out the "initial", we could make it implicit by it being the first Condition with all the necessary Episode assignments. We discussed this. Problem is that many cancer data are incomplete in the sense that diagnosis is done at a large center, but the subsequent treatment is local. That means that the first occurrence of the condition/episodes may not be the one that started the clock (e.g. for overall survival). So, we thought to have this flag "this is the one where the patient was initially diagnosed, and everything else follows).

Ugly either way. Any other good idea?

**Comment by mgurley** [comment]
@vladkorsik @cgreich 

For the time being, this issue is only for creating the 'Initial Diagnosis' concept.  Please ignore anything else mentioned in the old Github issue.  We will tackle those additional concepts in the future. 

The idea is that we need to be able to tag an entry in the Condition table as definitively marking the first time a cancer diagnosis was made.  Absent this information, you don't know whether this is simply the first time a cancer diagnosis appears in the data asset.  Like Christian said, we will be using this concept  later to infer episodes.  But even without the Episode use case, in standard OMOP if you want to run an analysis of 'Initial Diagnosis' versus first appearance, this concept is necessary.
  This problem is especially acute in EHR data sets, where patients transfer from outside institutions to receive treatment lines beyond the first line.  Naively, it might appear that a patient has had a cancer diagnosis once the diagnosis begins appearing on the problem list at the institution administering the subsequent lines of treatment.  But in fact the patient was diagnosed with cancer many years prior at at an another institution that administered the primary course of treatment.

**Comment by cgreich** [comment]
You said it much nicer, but yes, that's the state of affairs, @mgurley.

**Comment by vladkorsik** [comment]
Thank you @mgurley and thank you @cgreich for the rational, I will put it on a  table with next release.

**Comment by vladkorsik** [comment]
Added in New Vocabulary release (Sep2022)
