### ISSUE TITLE
Is there a standard concept_id for gender identity?

### ISSUE THREAD

**Issue by stephanieshong** [OHDSI/Vocabulary-v5.0#667]
**What is the use case for the new vocabulary (please also think about international use of the new vocabulary)?**
Wondering if we have standard concept_ids for gender identity
https://athena.ohdsi.org/search-terms/terms/36675593
https://athena.ohdsi.org/search-terms/terms?query=non-binary

CDM may need to support two different concept values

**What problems will the new vocabulary solve?**

standard gender_concept_id and standard sex_concept_id

**Is there a stable source to refresh the vocabulary?**
OMOP may need to support a new vocabulary that can accommodate both  gender and sex at birth concept ids

**Is there a license restriction?**
I do not think so. 

**How large is the vocabulary (number of concepts)?**
Below is one list that PCORnet model supports: 
 TF=Transgender female/Trans woman/Male-tofemale GQ=Genderqueer/N on-binary SE=Something else MU=Multiple gender categories DC=Decline to answer NI=No information UN=Unknown OT=Other 

**What kind of relationships / mappings need to be created?**
standard concept_ids for gender 

**Are there reference sets for the relationships available or already included with the source data?**

**Is there internal hierarchy (e.g. classification) that needs to be preserved?**
 more detailed information can be found here: 
 https://www.federalregister.gov/documents/2015/10/16/2015-25597/2015-edition-health-information-technology-health-it-certification-criteria-2015-edition-base

**Please provide a thorough description of applying the new vocabulary as an example.**
CDM may need to support both 
sex_concept_id 
gender_concept_id
Reference links:
http://phinvads.cdc.gov/vads/ViewValueSet.action?id=06D34BBC-617F-DD11-B38D-00188B398520
https://www.federalregister.gov/documents/2021/03/16/2021-05233/equal-credit-opportunity-regulation-b-discrimination-on-the-bases-of-sexual-orientation-and-gender

**Comment by stephanieshong** [comment]
PCORnet CDM supports: 
 TF=Transgender female/Trans woman/Male-tofemale GQ=Genderqueer/N on-binary SE=Something else MU=Multiple gender categories DC=Decline to answer NI=No information UN=Unknown OT=Other

**Comment by DaveraGabriel** [comment]
HL7 is opening (September 14-October14, 2022) a ballot that includes Gender identity.  The gender identity value set for that ballot can be found here: https://www.hl7.org/fhir/valueset-gender-identity.html  The full ballot is called "Gender Harmony" and addresses concepts of sex and gender, globally.  [The project information page is here](https://confluence.hl7.org/display/VOC/The+Gender+Harmony+Project)
<html>
<body>
<br class="Apple-interchange-newline">

Code | Display | Definition
-- | -- | --
male | male | the patient identifies as male
female | female | the patient identifies as female
non-binary | non-binary | the patient identifies with neither/both female and male
transgender-male | transgender male | the patient identifies as transgender female-to-male
transgender-female | transgender female | the patient identifies as transgender male-to-female
other | other | other gender identity
non-disclose | does not wish to disclose | the patient does not wish to disclose his gender identity


</body>
</html>Code	Display	Definition
[male](https://www.hl7.org/fhir/codesystem-gender-identity.html#gender-identity-male)	male	the patient identifies as male
[female](https://www.hl7.org/fhir/codesystem-gender-identity.html#gender-identity-female)	female	the patient identifies as female
[non-binary](https://www.hl7.org/fhir/codesystem-gender-identity.html#gender-identity-non-binary)	non-binary	the patient identifies with neither/both female and male
[transgender-male](https://www.hl7.org/fhir/codesystem-gender-identity.html#gender-identity-transgender-male)	transgender male	the patient identifies as transgender female-to-male
[transgender-female](https://www.hl7.org/fhir/codesystem-gender-identity.html#gender-identity-transgender-female)	transgender female	the patient identifies as transgender male-to-female
[other](https://www.hl7.org/fhir/codesystem-gender-identity.html#gender-identity-other)	other	other gender identity
[non-disclose](https://www.hl7.org/fhir/codesystem-gender-identity.html#gender-identity-non-disclose)	does not wish to disclose	the patient does not wish to disclose his gender identity

**Comment by stephanieshong** [comment]
In case it is helpful, https://doi.org/10.1093/jamia/ocab196

**Comment by TinyRickC137** [comment]
Hello, @stephanieshong and @DaveraGabriel 
This issue was addressed in OHDSI multiple times. Shortly, the answer for the reason why the situation is like it is at the moment is mentioned [here](https://forums.ohdsi.org/t/standard-values-for-gender/15614/6?u=zhuk) by Joe Pallas.
 
Gender_concept_id, despite the confusing name, only captures sex at birth. Non-binary genders should be captured in either observation or condition tables. 

More on this topic at the forum:
[Standard values for gender](https://forums.ohdsi.org/t/standard-values-for-gender/15614)
[Source_concept_id for gender, race and ethnicity](https://forums.ohdsi.org/t/source-concept-id-for-gender-race-and-ethnicity/11661)
[Sexual orientation and gender identity](https://forums.ohdsi.org/t/sexual-orientation-and-gender-identity/13080)

So, there is no real need for a new vocabulary to represent Sex/Gender. There are multiple standard concepts among vocabularies for quite any gender. Some of them are mentioned in the topics above.

**Comment by TinyRickC137** [comment]
I am closing this issue, please if you are interested in a discussion on this topic, come to OHDSI Forum
