### ISSUE TITLE
NAACCR grading concepts mapped to Cancer Modifier grading concepts

### ISSUE THREAD

**Issue by mgurley** [OHDSI/Vocabulary-v5.0#668]
**Is your feature request related to a problem? Please describe.**
We need to be able to map from NAACCR source concepts to standard Cancer Modifier concepts for variables related to Grading.   This is being done for the NAACCR ETL.

**Describe the solution you'd like**
The NAACCR vocabulary is post-coordinated (structured like question/answer).  The Cancer Modifier vocabulary is pre-coordinated.  The NAACCR vocabulary is structured as 'NAACCR Variable' concepts with parent/child 'Has Answer'/'Answer of' relationships to 'NAACCR Value' concepts.  The existing CONCEPT_RELATIONSHIP table does not support mappings of multiple source vocabulary concepts to a single standard concept.   To get around this limitation, we have mapped 'NAACCR Value' concepts (answers) to Cancer Modifier concepts.  See attached 'concept_relationship_stage.csv' file. 

We would like to de-standardize all of these newly mapped NAACCR grading concepts (both NAACCR Variable and NAACCR Value) upon instantiation of these mappings. 

For many 'NAACCR Value' concepts  we could not find a suitable map.   Further, we believed that these concepts  do not warrant the creation of new Cancer Modifier concepts.  For these 'NAACCR Value' concepts,  we have made explicit maps to '0'.  This strategy does not look like it has precedent, but we wanted some way to designate a 'NAACCR Value' concept as not relevant to OMOP ETLing and just leaving an absence of 'Maps To' relationship would make it impossible for vocabulary consumers to know if this is a 'NAAACR Value' that has not yet been mapped versus one that has explicitly been mapped as not relevant.  Most of these 'NAACCR Value' concepts mapped to '0' are different varieties of capturing things that did not happen.
  

**Describe alternatives you've considered**
1. Using a wide mapping table but this has not yet been implemented.
2. Creating new pre-coordinated NAACCR concepts that could then be mapped via CONCEPT_RELATIONSHIP

**Additional context**
During the course of making the mappings from the NAACCR vocabulary to the Cancer Modifier vocabulary, we noticed that some concepts lose granularity as they are mapped.  We have added a 'mapping notes' column to the 'concept_relationship_stage.csv' file that annotates these mappings with the phrase, 'concept granularity lost'.  We believe the concept granularity is acceptable.   But we wanted to bring it to your attention to see if the Odysseus team agrees.  Also, we wanted to have these mappings publicly inspect-able, so if anybody objects to any mapping or any granularity lost they can raise their objection as a comment on this issue.

Lastly, we will be potentially demonstrating the updated version of the NAACCR ETL at the Symposium to use these mappings.  So a quick implementation of these mappings would be greatly appreciated.

[concept_relationship_stage.csv](https://github.com/OHDSI/Vocabulary-v5.0/files/9443900/concept_relationship_stage.csv)

**Comment by vladkorsik** [comment]
Added in in Sep2022 Vocabulary release
