### ISSUE TITLE
CPT4, concepts missing from Nov 2015 release?

### ISSUE THREAD

**Issue by DinaSarsam** [OHDSI/Vocabulary-v5.0#67]
I have downloaded both V5 and V4.5 of the latest vocabulary and the concept table is missing Vocabulary_Id 4 (or CPT4 in V5).  Any reason why? Is that a licence issue? Please advise!

**Comment by cgreich** [comment]
Dina:

Did you run the CPT4 "reconstitution" tool?

**Comment by ericaVoss** [comment]
@DinaSarsam did the CPT4 "reconstitution" tool work for you?

**Comment by DinaSarsam** [comment]
Yes it Dina, many thanks. You can close this case!

**Comment by ericaVoss** [comment]
@cgreich you can close this issue.
