### ISSUE TITLE
Please fix typo/misspelling in some concepts related to "post therapy clinical staging".

### ISSUE THREAD

**Issue by mgurley** [OHDSI/Vocabulary-v5.0#671]
**Describe the problem in content**
There is a typo/misspelling in some of the new Cancer Modifier staging variables covering post therapy clinical staging.

**How to find it**
See concepts with typos/misspellings here:

https://athena.ohdsi.org/search-terms/terms?vocabulary=Cancer+Modifier&conceptClass=Staging%2FGrading&standardConcept=Standard&page=1&pageSize=15&query=%22post+therapy+clinica+%22&boosts

Looks like "clinical" was added as "clinica' for 31 concepts.

**Comment by vladkorsik** [comment]
Corrected in New Vocabulary release (Sep2022)

**Comment by vladkorsik** [comment]
Corrected in New Vocabulary release (Sep2022)
