### ISSUE TITLE
Visits in HCPCS vocabulary

### ISSUE THREAD

**Issue by Alexdavv** [OHDSI/Vocabulary-v5.0#672]
**Describe the problem in content**
Despite we partially addressed this issue within the [recent release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20220829_1661776786), there are some missed concepts that represent different flavors of visits. 

**How to find it**
https://forums.ohdsi.org/t/where-should-telehealth-hcps-be-stored/16580/2

**Expected adjustments**

@m-khitrun:
1. Regardless they’re procedures or not, they all have to be mapped with “Maps to” to the respective Visit Domain concepts.
2. If there’s nothing more than a Visit, they have to be deStandardized.
3. They also have to be deStandardized if the entire semantics can be represented with a mapping to the Standard Procedure/Measurement/Observation/etc concepts. Otherwise, they’re added to the hierarchy of Standard concepts. This last 3rd point requires substantial effort so that can be done stepwise.
4. To find different Visits, we need to create a generic repository of regexp patterns and scripts that will be reused among the vocabs going forward.

**Additional context**
Probably this won’t be addressed soon. Rather on the next HCPCS release or major OMOP vocabulary release.

**Comment by m-khitrun** [comment]
Hello,

These concepts were mapped to standard concepts in the Visit domain. The necessary check was created in the repository.

Regards,
Masha
