### ISSUE TITLE
Incorrect mapping for 37587401 (Bladder tumor resection, from MedDRA)?

### ISSUE THREAD

**Issue by adwasser** [OHDSI/Vocabulary-v5.0#679]
**Describe the problem in content**
A clear and concise description of what you found and how it is affecting your processes, ETL or analysis.

I needed a query to find all standard and non-standard cancer conditions in my implementation of the CDM.  By collecting descendant terms of 438112 (SNOMED, Neoplastic disease) and mapping these terms to both standard and non-standard concepts, I found a resulting concepts which were not in the Condition domain.  Of these, Bladder tumor resection stood out as being semantically incorrect.  The others were various invalid Observation concepts that at least were mapped to proper conditions.

The root issue seems to be that bladder tumor resection is mapped to Neoplasm of bladder:

https://athena.ohdsi.org/search-terms/terms/37587401

**How to find it**
Help us reproducing the problem and researching the issue. Links to Athena concepts can be helpful.

See the above link.  Also, below is the query used to find the questionable concepts.

```sql
-- get descendants of Neoplastic disease, map to standard/non-standard
create temporary table cancer_conditions as
select distinct concept.concept_id, concept.concept_name
from omop_cdm.concept as concept,
    omop_cdm.concept_relationship as r,
    omop_cdm.concept as descendant,
    omop_cdm.concept_ancestor as a,
	omop_cdm.concept as ancestor
where concept.concept_id = r.concept_id_1
and r.relationship_id in ('Maps to', 'Mapped from')
and r.concept_id_2 = descendant.concept_id
and descendant.concept_id = a.descendant_concept_id
and a.ancestor_concept_id = ancestor.concept_id
and ancestor.concept_id = 438112
;

-- look for non-condition concepts
select concept.concept_id, concept.concept_name, concept.domain_id, concept.vocabulary_id
from cancer_conditions,
    omop_cdm.concept as concept
where cancer_conditions.concept_id = concept.concept_id
and concept.domain_id != 'Condition';
```

**Expected adjustments**
A clear and concise description of what you expect the Vocabulary Team to change. If you have collected information in a spreadsheet, please share it with us.

I think removing that relationship, `37587401 'Maps to' 200680` makes sense.

**Screenshots**

**Additional context**

**Comment by mik-ohdsi** [comment]
I think I get your point, @adwasser , but here we are in a typical situation where there is no perfect mapping match and we still want to get as much information out of a source term as we can get. A procedure can include an implicit condition (as this procedure would only be performed if that condition is there). We do not find a perfect match for the Bladder tumor resection, either more specific ones like "[Transurethral resection of neoplasm of bladder](https://ontoserver.csiro.au/shrimp/?concept=386792000&version=http%3A%2F%2Fsnomed.info%2Fsct%2F900000000000207008%2Fversion%2F20220228&valueset=http%3A%2F%2Fsnomed.info%2Fsct%2F900000000000207008%3Ffhir_vs)" or just less specific ones like the Resection of lesion of bladder (which might at least be a bit better than the even more unspecific ["Bladder Excision"](https://athena.ohdsi.org/search-terms/terms/4029571) that we map to today). But we would lose the information that there was a bladder neoplasm involved and hence, at least by creating a maps to many for an additional condition, this information is preserved. It would be preferable to always find a perfect target concept, but sometimes, especially in the procedure and condition domain, when source concepts are a bit complex and combine multiple axes that we do not always find a pre-coordinated target for, we split it up. But maybe @MikitaSalavei  - our MedDRA expert has to share additional thoughts here.
Cheers ~ mik

**Comment by adwasser** [comment]
It seems to me like [Resection of lesion of bladder](https://athena.ohdsi.org/search-terms/terms/4212477) is the right level of specificity, and that links to Lesion (as a SNOMED morph abnormality) as well as Bladder as procedure site.  I suppose that the underlying question is, where does the responsibility lie for inferring that any patient who had a bladder tumor resection procedure should have a bladder neoplasm condition?  Regardless, thanks for the additional context @mik-ohdsi !

**Comment by cgreich** [comment]
> inferring that any patient who had a bladder tumor resection procedure

Very good point. Generally, we expect the data to have a bladder cancer record if such a procedure occurs. And usually that works well: They need the diagnosis to justify (and get paid for) the procedure. But there may be situations where this is not the case, and the poor analyst has to figure it out. There is no way the vocabulary can create all possible logical links between all concepts. SNOMED is putting a lot of effort doing that, but that's inside one vocabulary, and even that is not very satisfying.

Sorry, there is no good answer.

**Comment by mik-ohdsi** [comment]
Hey @MSalavei , should we actually replace that ["Bladder Excision"](https://athena.ohdsi.org/search-terms/terms/4029571) with the slightly more accurate [Resection of lesion of bladder](https://athena.ohdsi.org/search-terms/terms/4212477). What do you think? Not every "Bladder Tumor Resection" is a Cystectomy, is it?

**Comment by MSalavei** [comment]
Of course, @mik-ohdsi. We replaced "Bladder Excision" with more accurate concept "Resection of lesion of bladder".  The new version of mapping will appear on next MedDRA refresh.

**Comment by mik-ohdsi** [comment]
Great, thank you!
