### ISSUE TITLE
Request for the addition of new vaccination CPT4|RXNorm codes

### ISSUE THREAD

**Issue by krevett-iqvia** [OHDSI/Vocabulary-v5.0#685]
#@
We would like to have the CPT4 codes added to the vocabulary - see the image below for details of the Code_type, Description, and Source.   These new vaccine codes are required for IQVIA to continue our monthly ETL refresh to support BEST related studies.

![image](https://user-images.githubusercontent.com/99823655/193056058-9cc618d0-2a38-4eba-b378-ded4b8a73e8e.png)

This request is related to ticket #683, for CVX codes 229, 300, and 301.

Thank you very much for looking into this.  @cgreich @mik-ohdsi @MariaRohozhkina

**Comment by krevett-iqvia** [comment]
We are in an urgent state for the inclusion of these codes into Athena. Could you please let us know what the status is for this request? @cgreich @mik-ohdsi

**Comment by cgreich** [comment]
@krevett-iqvia: Will do a hotfix to add them in. Early next week.

**Comment by cgreich** [comment]
And we will put in a mechanism to not fall behind in these situations with the UMLS delay in the future.

**Comment by krevett-iqvia** [comment]
@cgreich Thank you very much!!!!  We understand this is not simple - so we totally appreciate the effort!

**Comment by mik-ohdsi** [comment]
@krevett-iqvia  -  responding to your 911 call did indeed require a bit more than the ordinary as we had to pick the individual codes and names from various individual publications by CPT as they will only appear in the CPT4-2023 or maybe even CPT-2024 version... the [release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20221031_1667231913) is out and I would like to ask you to download the vocabularies and verify the correct representation as you would need it for the FDA-BEST projects. Please close the issue (and the other related ones) if everything worked out.

**Comment by m-khitrun** [comment]
Does everything work properly? May I close this issue? @krevett-iqvia

**Comment by krevett-iqvia** [comment]
Hi @m-khitrun - so sorry - please feel free to close this ticket.
