### ISSUE TITLE
mcg/mL (millicentigram/milliliter) is a valid unit expression, but it is missing the unit_concept_id in the OMOP vocab table. 

### ISSUE THREAD

**Issue by stephanieshong** [OHDSI/Vocabulary-v5.0#690]
**Describe the problem in content**
A clear and concise description of what you found and how it is affecting your processes, ETL or analysis.
mcg/mL (millicentigram/milliliter) is a valid unit expression and a valid UCUM unit. 

**How to find it**
Help us reproducing the problem and researching the issue. Links to Athena concepts can be helpful.
missing from the concept table

**Expected adjustments**
A clear and concise description of what you expect the Vocabulary Team to change. If you have collected information in a spreadsheet, please share it with us.
Need an entry for mcg/mL in the concept table. 

**Screenshots**

**Additional context**

Let me know if I am missing something. Thank you.

**Comment by stephanieshong** [comment]
I went to this site : https://ucum.nlm.nih.gov/ucum-lhc/demo.html
and type the following string : mcg/mL
and it states that 
mcg/mL (millicentigram/milliliter) is a valid unit expression.
accorrding the the NLM UCUM site mcg is milicentigram/milliter and not microgram. 
are you saying the mcg/mL is same as ug/mL?

**Comment by mik-ohdsi** [comment]
millicentigram is a somewhat artificial double prefix, which should be avoided / is obsolete (see "[non-standard prefixes](https://en.wikipedia.org/wiki/Metric_prefix)"). Interesting discussion [here](https://chemistry.stackexchange.com/questions/145521/how-much-is-1-m%CE%BCg) also referencing the "mcg". In medicine, especially medication, mcg/ml is quite often used and indeed means actually microgram / milliliter. I am quite sure, if you check the context in which this unit appears in your source data, you will find medication data. UCUM wants to be very complete but I guess this particular unit is not in (active) use in medicine.

**Comment by stephanieshong** [comment]
ok thank you. We will treat mcg/mL as ug/mL =8859. I am closing this issue.
