### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#691]
With the most recent vocabulary release, some ICD9/10CM concepts now map to the new (newer?) Cancer Modifier Vocabulary. If an institution does not have this vocabulary, then the ICD9/10CM concept will not map to a standard concept.

Solution I would like: When an existing concept is mapped to a new Vocabulary, add this information into the release notes so people will know to download the new vocabulary from Athena.

**Comment by TinyRickC137** [comment]
Linking the forum topic: https://forums.ohdsi.org/t/suggestion-for-vocabulary-release-notes/18956
