### ISSUE TITLE
Hidden characters in content causing error with different versions of PG COPY

### ISSUE THREAD

**Issue by jstroup** [OHDSI/Vocabulary-v5.0#695]
Run the following query, copy the result, and go to position 126 in any text editor.

    select concept_name from vocab.concept where concept_id = 42764118	

Arrow right and observe that the text cursor does not advance for two positions. This means that technically the field is actually 257 characters as opposed to the stated 255 limit of the varchar column.  When the following Postgres copy command is used (from PSQL) to convert CONCEPT.CSV to the CONCEPT table, no error results. 

    \COPY CONCEPT FROM 'CONCEPT.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

When the following copy command is used (from a Java wrapper) a field length error results.  

    COPY concept FROM STDIN (DELIMITER E’\t’, FORMAT CSV, HEADER, QUOTE E’\b’)

So one version of COPY (with the same parameters) works but the other does not. If there's a way to force the latter copy command to copy the content without error then this is not a content issue, otherwise it is and such content needs to be filtered.

**Comment by TinyRickC137** [comment]
Hello, @jstroup 

I think you know more than others regarding this issue :)

I will provide the link to your [forum post](https://forums.ohdsi.org/t/postgresql-copy-command-using-stdin-chokes-on-weird-characters-in-concept-concept-name/17543) here for historical purposes and close this issue. Let the discussion continue on forum if the issue has not been completely resolved

**Comment by jstroup** [comment]
FYI - I was able to solve this by specifying UTF-8 encoding for my STDIN input stream. 


				BufferedReader inStream = new BufferedReader(
				           new InputStreamReader(
				                      new FileInputStream(sourcePath), **javaEncoding**));
