### ISSUE TITLE
Symptom of potential issue with consistency of mappings from ICD9->SNOMED from VocabV4->VocabV5

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#7]
In Vocab V4, the ICD-9 code for Rhabdomyolysis (728.88) is mapped to SNOMED concept 137967 ("Muscle, ligament and fascia disorders"), even though there is a SNOMED concept 4345578 (“Rhabdomyolysis”). (and there are 58 other codes that map into 137967)

In Vocab V5, the same ICD-9 code is not mapped to any SNOMED code.

I would like for us to have a more systematic approach of evaluating them. In this example, there are already a few clues that we could have used to signal a potential problematic mapping:
1.	Mapping to a concept that has zero term similarity with the source term, even though there is a code with 100% similarity
2.	Mapping to  code to which many other codes map

CDM V4 vocab:
select * 
from source_to_concept_map 
inner join concept
on target_concept_id = concept_id
where source_code = '728.88';

CDM V5 vocab:
select concept_1.concept_name,
concept_2.concept_name,
relationship_id
from concept_relationship 
inner join concept concept_1
on concept_1.concept_id = concept_id_1
inner join concept concept_2
on concept_2.concept_id = concept_id_2
where concept_1.concept_code = '728.88';

**Comment by cgreich** [comment]
Patrick:

 

Weird. Vocab 5 has that mapping. Your very own query gives me:

 

Rhabdomyolysis         Muscle, ligament and fascia disorders            Maps to

Rhabdomyolysis         Myositis          ICD9CM - FDB Ind

Rhabdomyolysis         Rhabdomyolysis         ICD9CM – MedDRA

 

Obviously, we are fixing this particular mapping. 

 

But there is no, as I was afraid, systematic loss of mappings. 

 

The question is why you don’t have it in your version.

 

C

**Comment by pbr6cornell** [comment]
I see those mappings now.  So I guess for this issue, I only submit that I'd prefer to see the ICD-9 code for rhabdomyolysis mapped to the SNOMED concept of rhabdomyolysis (4345578).   And I wonder whether these general rules could be applies as quality checking heuristics:

1.  Mapping to a concept that has zero term similarity with the source term, even though there is a code with 100% similarity
2. Mapping to code to which many other codes map

**Comment by cgreich** [comment]
Good point. Should make both of these separate issues.

**Comment by cgreich** [comment]
Fixed.
