### ISSUE TITLE
[RELATIONSHIP] Missing 'Has morphology'

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#70]
The 'Has morphology' RELATIONSHIP_ID is missing from RELATIONSHIP table.

```{SQL}
SELECT *
FROM relationship
WHERE relationship_id IN (
	SELECT relationship_id
	FROM concept_relationship
	WHERE CONCEPT_ID_1 = 40492189
	AND concept_id_2 = 4244567 
	AND invalid_reason IS NULL
)
```

**Comment by cgreich** [comment]
Hm. Not really. I get back:

Has morphology	Has Morphology (SNOMED)	0	0	Morphology of	45754806

Also, the constraint forbids it.

**Comment by ericaVoss** [comment]
In in **v5.0 12-FEB-16** I see it is now `Has asso morph`.

**Comment by cgreich** [comment]
So, are we good? I am confused.
