### ISSUE TITLE
ICD10 CM Non-Hodgkin lymphoma mapped to Hodgkin disease

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Vocabulary-v5.0#702]
https://athena.ohdsi.org/search-terms/terms/45576365

Non-Hodgkin lymphoma, unsp, lymph nodes of multiple sites  has one-to-many mapping, on of  which is  [Hodgkin's disease of lymph nodes of multiple sites](https://athena.ohdsi.org/search-terms/terms/316356)

**Comment by mik-ohdsi** [comment]
@irinazherko  -  the faulty mapping (to Hodgkin's disease) is still in Athena. Can you make sure it is deprecated (or preferably replaced with a correct one) soon while the correct one is preserved?

**Comment by irinazherko** [comment]
We are pleased to inform you that the issue has been successfully corrected during the February 2024 Release. Thank you very much for your contribution!
