### ISSUE TITLE
Malignant melanoma vs Melanoma In Situ mappings from ICD10 to SNOMED

### ISSUE THREAD

**Issue by MeliHenry** [OHDSI/Vocabulary-v5.0#704]
**Description of the problem**
This issue is coming from this [forum post](https://forums.ohdsi.org/t/malignant-melanoma-vs-melanoma-in-situ-mappings-from-icd10-to-snomed/17596).

These four ICD10 codes:
C43.111 | Malignant melanoma of right upper eyelid, including canthus
C43.112 | Malignant melanoma of right lower eyelid, including canthus
C43.121 | Malignant melanoma of left upper eyelid, including canthus
C43.122 | Malignant melanoma of left lower eyelid, including canthus

are all mapped to this CONCEPT_ID
4033836 | Melanoma **in situ** of eyelid, including canthus

This seems to be an outlier, because malignant melanoma is different than melanoma in situ. There is another, probably better code to map to:
40390677 | Malignant melanoma of eyelid including canthus
However, this code is mapped as non-standard

**How to find it**

https://athena.ohdsi.org/search-terms/terms/1595483
https://athena.ohdsi.org/search-terms/terms/1595484
https://athena.ohdsi.org/search-terms/terms/1595485
https://athena.ohdsi.org/search-terms/terms/1595486

**Expected adjustments**
The concept ID "4033836" explicitly states that the malignant melanoma is in situ which doesn't exactly provide a good mapping to any of the aforementioned codes. 
The mapping should be replaced by concept ID 4338760 "Malignant melanoma of the eyelid" as it  offers a more suitable mapping to those ICD10 codes.
The suggested concept ID 40390677 "Malignant melanoma of eyelid including canthus" has been deprecated and replaced by concept ID 4338760 "Malignant melanoma of the eyelid".

**Comment by mik-ohdsi** [comment]
a pity that this wasn't fixed with the last ICD10-CM release. Can you review this, @irinazherko ? thanks!
