### ISSUE TITLE
Assign Visit domain to CPT4 codes and map to respective Visit concepts

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#711]
Please see the list of concepts below.
ER visits were encountered in a patient data, while the other codes I've got by reviewing the CPT4 codes in the vocabulary. Feel free to search for more codes or modify only those I discovered.

ID | CODE | NAME | suggested target concept
-- | -- | -- | --
2514433 | 99281 | Emergency department   visit for the evaluation and management of a patient, which requires these 3   key components: A problem focused history; A problem focused examination; and   Straightforward medical decision making. Counseling and/or coordination of   c... | ER Visit
2514434 | 99282 | Emergency department   visit for the evaluation and management of a patient, which requires these 3   key components: An expanded problem focused history; An expanded problem   focused examination; and Medical decision making of low complexity.   Counseling an... | ER Visit
2514435 | 99283 | Emergency department   visit for the evaluation and management of a patient, which requires these 3   key components: An expanded problem focused history; An expanded problem   focused examination; and Medical decision making of moderate complexity.   Counseli... | ER Visit
2514436 | 99284 | Emergency department   visit for the evaluation and management of a patient, which requires these 3   key components: A detailed history; A detailed examination; and Medical   decision making of moderate complexity. Counseling and/or coordination of   care wit... | ER Visit
2514437 | 99285 | Emergency department   visit for the evaluation and management of a patient, which requires these 3   key components within the constraints imposed by the urgency of the patient's   clinical condition and/or mental status: A comprehensive history; A   comprehe... | ER Visit
  |   |   |  
42738976 | 99333 | Domiciliary or rest   home visit for the evaluation and management of an established patient, which   requires at least two of these three key components: a detailed interval   history; a detailed examination; medical decision making of high com...   (Deprecated) | Home visit
42738975 | 99332 | Domiciliary or rest   home visit for the evaluation and management of an established patient, which   requires at least two of these three key components: an expanded problem   focused interval history; an expanded problem focused examination; m...   (Deprecated) | Home visit
42738974 | 99331 | Domiciliary or rest   home visit for the evaluation and management of an established patient, which   requires at least two of these three key components: a problem focused   interval history; a problem focused examination; medical decision maki...   (Deprecated) | Home visit
42738973 | 99323 | Domiciliary or rest   home visit for the evaluation and management of a new patient, which requires   these three key components: a detailed history; a detailed examination; and   medical decision making of high complexity. Counseling and/or coo...   (Deprecated) | Home visit
42738972 | 99322 | Domiciliary or rest   home visit for the evaluation and management of a new patient, which requires   these three key components: an expanded problem focused history; an expanded   problem focused examination; and medical decision making of mode...   (Deprecated) | Home visit
42738971 | 99321 | Domiciliary or rest   home visit for the evaluation and management of a new patient which requires   these three key components: a problem focused history; a problem focused   examination; and medical decision making that is straightforward or o...   (Deprecated) | Home visit
42739882 | 99539 | Unlisted home visit   service or procedure (Deprecated) | Home visit
42739877 | 99508 | Home visit for   polysomnography and sleep studies (Deprecated) | Home visit
  |   |   |  
2414390 | 99201 | Office or other outpatient visit for the evaluation and management of a   new patient, which requires these 3 key components: A problem focused   history; A problem focused examination; Straightforward medical decision   making. Counseling and/o... (Deprecated) | Outpatient visit
759715 | 99417 | Prolonged office or   other outpatient evaluation and management service(s) beyond the minimum   required time of the primary procedure which has been selected using total   time, requiring total time with or without direct patient contact beyond the   usual s... | Outpatient visit
2414395 | 99211 | Office or other   outpatient visit for the evaluation and management of an established patient,   that may not require the presence of a physician or other qualified health   care professional. Usually, the presenting problem(s) are minimal. | Outpatient visit
42628033 | 99416 | Prolonged clinical   staff service (the service beyond the highest time in the range of total time   of the service) during an evaluation and management service in the office or   outpatient setting, direct patient contact with physician supervision; each   ad... | Outpatient visit
42628640 | 99415 | Prolonged clinical   staff service (the service beyond the highest time in the range of total time   of the service) during an evaluation and management service in the office or   outpatient setting, direct patient contact with physician supervision; first   h... | Outpatient visit
2414396 | 99212 | Office or other   outpatient visit for the evaluation and management of an established patient,   which requires a medically appropriate history and/or examination and   straightforward medical decision making. When using time for code selection,   10-19 minut... | Outpatient visit
2514415 | 99241 | Office consultation   for a new or established patient, which requires these 3 key components: A   problem focused history; A problem focused examination; and Straightforward   medical decision making. Counseling and/or coordination of care with other   physic... | Outpatient visit
2514416 | 99242 | Office consultation   for a new or established patient, which requires these 3 key components: An   expanded problem focused history; An expanded problem focused examination;   and Straightforward medical decision making. Counseling and/or coordination   of ca... | Outpatient visit
2514419 | 99245 | Office consultation   for a new or established patient, which requires these 3 key components: A   comprehensive history; A comprehensive examination; and Medical decision   making of high complexity. Counseling and/or coordination of care with other   physici... | Outpatient visit
2514418 | 99244 | Office consultation   for a new or established patient, which requires these 3 key components: A   comprehensive history; A comprehensive examination; and Medical decision   making of moderate complexity. Counseling and/or coordination of care with   other phy... | Outpatient visit
2414391 | 99202 | Office or other   outpatient visit for the evaluation and management of a new patient, which   requires a medically appropriate history and/or examination and   straightforward medical decision making. When using time for code selection,   15-29 minutes of tot... | Outpatient visit
2514417 | 99243 | Office consultation   for a new or established patient, which requires these 3 key components: A   detailed history; A detailed examination; and Medical decision making of low   complexity. Counseling and/or coordination of care with other physicians,   other... | Outpatient visit
2514399 | 99215 | Office or other   outpatient visit for the evaluation and management of an established patient,   which requires a medically appropriate history and/or examination and high   level of medical decision making. When using time for code selection, 40-54   minutes... | Outpatient visit
2414397 | 99213 | Office or other   outpatient visit for the evaluation and management of an established patient,   which requires a medically appropriate history and/or examination and low   level of medical decision making. When using time for code selection, 20-29   minutes... | Outpatient visit
2414398 | 99214 | Office or other   outpatient visit for the evaluation and management of an established patient,   which requires a medically appropriate history and/or examination and   moderate level of medical decision making. When using time for code   selection, 30-39 min... | Outpatient visit
2414394 | 99205 | Office or other   outpatient visit for the evaluation and management of a new patient, which   requires a medically appropriate history and/or examination and high level of   medical decision making. When using time for code selection, 60-74 minutes of   total... | Outpatient visit
2414392 | 99203 | Office or other   outpatient visit for the evaluation and management of a new patient, which   requires a medically appropriate history and/or examination and low level of   medical decision making. When using time for code selection, 30-44 minutes of   total... | Outpatient visit
2414393 | 99204 | Office or other   outpatient visit for the evaluation and management of a new patient, which   requires a medically appropriate history and/or examination and moderate   level of medical decision making. When using time for code selection, 45-59   minutes of t... | Outpatient visit
2514493 | 99354 | Prolonged service(s)   in the outpatient setting requiring direct patient contact beyond the time of   the usual service; first hour (List separately in addition to code for   outpatient Evaluation and Management or psychotherapy service, except with   office... | Outpatient visit

**Comment by Alexdavv** [comment]
Thanks Dima!
We’re on it right now

**Comment by dimshitc** [comment]
Thanks Sasha:)
any approximate timelines for this?

**Comment by Alexdavv** [comment]
Indian summer... I’ve heard it could be somewhat late depending on where do you live.
“Sasha” works also 😉

**Comment by mik-ohdsi** [comment]
is this somewhat related to issue #672  ?

**Comment by m-khitrun** [comment]
Hello! We mapped the mentioned concepts and assigned the Visit domain to them.

**Comment by Alexdavv** [comment]
Hi @dimshitc!
On the latest OMOP CDM WG meeting we've tried to recall why these mappings were requested by folks and how were they used. Do you have some thoughts?

**Comment by dimshitc** [comment]
Wasn't it a solution made by the vocabulary team alone? 
Something like "the concept says about the visit, so we map it to the visit", like if concept says about Diabetes mellitus we map it to the Diabetes mellitus. And we as a vocabulary team provide users with a correct semantic mapping and then the ETL folks and researches have to deal with it.
