### ISSUE TITLE
Fix vocabulary_name content

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Vocabulary-v5.0#712]
**Describe the problem in content**
Some vocabulary names are not according the the syntax: Database name (authoring organization). The organization is usually abbreviated, unless the abbreviation would be confusing.

**How to find it**
In the VOCABULARY table

**Expected adjustments**
Fix it as following:

update vocabulary set vocabulary_name = 'Census regions of the United States (USCB)' where vocabulary_id='US Census';
update vocabulary set vocabulary_name = 'Veterans Health Administration National Drug File (VA))' where vocabulary_id='VANDF';
update vocabulary set vocabulary_name = 'UK Biobank (UK Biobank)' where vocabulary_id='UK Biobank';
update vocabulary set vocabulary_name = 'OMOP Sponsor' where vocabulary_id='Sponsor';
update vocabulary set vocabulary_name = 'SNOMED Veterinary Extension (VTSL)' where vocabulary_id='SNOMED Veterinary';
update vocabulary set vocabulary_name = 'RxNorm Extension (OMOP)' where vocabulary_id='RxNorm Extension';
update vocabulary set vocabulary_name = 'OMOP Health Plan' where vocabulary_id='Plan';
update vocabulary set vocabulary_name = 'OMOP Plan Stop Reason' where vocabulary_id='Plan Stop Reason';
update vocabulary set vocabulary_name = 'OpenStreetMap (OSMF)' where vocabulary_id='OpenStreetMap';
update vocabulary set vocabulary_name = 'Nebraska Lexicon (UNMC)' where vocabulary_id='Nebraska Lexicon';
update vocabulary set vocabulary_name = 'Normalized Chinese Clinical Drug knowledge base (UTHealth)' where vocabulary_id='NCCD';
update vocabulary set vocabulary_name = 'OMOP Metadata' where vocabulary_id='Metadata';
update vocabulary set vocabulary_name = 'OMOP Language' where vocabulary_id='Language';
update vocabulary set vocabulary_name = 'Korean Revenue Code (KNHIS)' where vocabulary_id='Korean Revenue Code';
update vocabulary set vocabulary_name = 'Korean Payer (KNHIS)' where vocabulary_id='KNHIS';
update vocabulary set vocabulary_name = 'Korean Standard Classfication of Diseases and Causes of Death, 7th Revision (STATISTICS KOREA)' where vocabulary_id='KCD7';
update vocabulary set vocabulary_name = 'International Classification of Diseases, Tenth Revision, Chinese Edition (CAMS)' where vocabulary_id='ICD10CN';
update vocabulary set vocabulary_name = 'International Classification of Diseases, Ninth Revision, Chinese Edition, Procedures (CAMS)' where vocabulary_id='ICD9ProcCN';
update vocabulary set vocabulary_name = 'Korean Electronic Data Interchange code system (HIRA)' where vocabulary_id='EDI';
update vocabulary set vocabulary_name = 'Comparative Toxicogenomic Database (NCSU)' where vocabulary_id='CTD';
update vocabulary set vocabulary_name = 'International Classification of Diseases, Tenth Revision, French Edition (atih)' where vocabulary_id='CIM10';
update vocabulary set vocabulary_name = 'Common Classification of Medical Acts (CEAP)' where vocabulary_id='CCAM';

**Comment by Alexdavv** [comment]
> RxNorm Extension (OMOP)'

> OMOP Health Plan

What's the naming rule here? Some are treated as metadata so they don't have the actual name... Some are full-length authored content with an explicit name provided. What to do with OMOP Extension / Genomic then? Cancer Modifier?

**Comment by cgreich** [comment]
My mistake of course. Should be:

update vocabulary set vocabulary_name = 'OMOP RxNorm Extension' where vocabulary_id='RxNorm Extension';

The unspoken convention is:

Ours: "OMOP Name of the vocabulary"
Not ours: "Full name of vocabulary, not abbreviated (abbrviated is possible authoring organization)"

**Comment by mik-ohdsi** [comment]
why "Common Classification of Medical Acts (CEAP)"? I think the source is ATIH? 
It seems to be outdated information:
_The choice of procedures in this nomenclature was the responsibility of the Commission d'évaluation des actes professionnels (CEAP) of the Haute autorité de santé, which has now been transformed into the Commission nationale d'évaluation des dispositifs médicaux et des technologies de santé de la HAS (CNEDiMTS) ._

**Comment by cgreich** [comment]
Ah, ok.

**Comment by cgreich** [comment]
I just want to make sure we can always claim that we give credit to the originating organization. Therefore, we have to do that painstakingly. In day-to-day life in OMOP, only the vocabulary_id matters, and that is just fine the way we have it.

**Comment by zeuschaeng** [comment]
Korean Standard Classfication of Diseases and Causes of Death, 7th Revision (STATISTICS KOREA)  should be modified to Korean Standard **Classification** of Diseases and Causes of Death, 7th Revision (STATISTICS KOREA). Thanks.
