### ISSUE TITLE
Need to add mapping for a new ICD10CM code -  T43.65 is a new 2023 ICD-10-CM code that became effective on October 1, 2022

### ISSUE THREAD

**Issue by stephanieshong** [OHDSI/Vocabulary-v5.0#717]
**What is the use case for the new vocabulary (please also think about international use of the new vocabulary)?**

T43.65 is a new 2023 ICD-10-CM code that became effective on October 1, 2022.
**What problems will the new vocabulary solve?**
currently it is missing from the concept table.

**Is there a stable source to refresh the vocabulary?**
detail information can be found here: https://www.icd10data.com/ICD10CM/Codes/S00-T88/T36-T50/T43/T43.6-/T43.65

**Is there a license restriction?**
no

**How large is the vocabulary (number of concepts)?**
this is just one new code for the ICD10CM

**What kind of relationships / mappings need to be created?**
need a non-stand to standard mapping

**Are there reference sets for the relationships available or already included with the source data?**
https://www.icd10data.com/ICD10CM/Codes/S00-T88/T36-T50/T43/T43.6-/T43.65

**Is there internal hierarchy (e.g. classification) that needs to be preserved?**
https://www.icd10data.com/ICD10CM/Codes/S00-T88/T36-T50/T43/T43.6-/T43.65

**Please provide a thorough description of applying the new vocabulary as an example.**

**Comment by mik-ohdsi** [comment]
Hi @stephanieshong - the parental (5th position) code and its children are now available in Athena. Due to its fuzzy description (oisoning by, adverse effect of and underdosing ) it is mapped pretty unspecifically, but where possible its more specific children have found their targets. Please review and close this issue if you can go along!

**Comment by stephanieshong** [comment]
@mik-ohdsi  - You want me to review the new code map for  T43.65 to SNOMED CT, new 2023 ICD-10-CM code?

**Comment by stephanieshong** [comment]
mapping to Drug-related disorder | 444363 | SNOMED is too broad, don't you think?
[Drug-related disorder](https://athena.ohdsi.org/search-terms/terms/444363)
444363
SNOMED

**Comment by cgreich** [comment]
Yes, it is too broad, but it is also not precise. Is it poisoning or underdosing? They are mutually exclusive, and it should say "or" in the code. The adverse event can happen with normal dosing as well. However, I agree, we should add something like [Methamphetamine dependence](https://athena.ohdsi.org/search-terms/terms/4141524) as a second mapping. However, we don't know if it is dependence, or single use. Not easy.

**Comment by IrynaZherka** [comment]
@stephanieshong T43.65 code (ICD10CM) is now in the Athena (https://athena.ohdsi.org/search-terms/terms/37403091) mapped to Amphetamine and/or amphetamine derivative overdose (https://athena.ohdsi.org/search-terms/terms/606813).

Thank you for your contribution!
