### ISSUE TITLE
Missing VOCAB_ID - ABMS

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#72]
Noticed that there are codes for VOCAB_ID `ABMS` but no reference for it in the VOCABULARY table.  I'm assuming you just need to add a row to the VOCABULARY table.  

This is for **Vocabulary v5.0 11-MAR-16**

**Comment by cgreich** [comment]
Not sure. select * from vocabulary where vocabulary_id='ABMS'; gives me ABMS	Provider Specialty (American Board of Medical Specialties)	http://www.abms.org/member-boards/specialty-subspecialty-certificates		45756746. Where am I missing it here?

**Comment by ericaVoss** [comment]
I see it in the raw CSV file but not in our load.  Issue in the load from our side.

**Comment by ericaVoss** [comment]
FYI, all our files loaded missing the first row.  This was because the CSVs came with an extra blank space in the header.  Our bulk insert command treats it not as a separate line, but prepends new line symbol to the second row’s first column value (probably because line endings are in unix format).  The easiest solution would be to either have proper header or no header at all; not an empty line like it is now.  (credit to Alexey Arestenko for diagnosing this issue).
