### ISSUE TITLE
"boiler" in HCPCS treats Branded Drugs with deprecated Brand Name as Clinical Drugs

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#722]
https://athena.ohdsi.org/search-terms/terms/2718356

This one is mapped to a concept with a deprecated Brand Name

**Comment by m-khitrun** [comment]
Hello. Thank you for your comment, we'll fix it.

**Comment by m-khitrun** [comment]
@dimshitc 
Please, be informed that this mapping was fixed in the course of the recent release.
