### ISSUE TITLE
Mapping of conditions to the Morphologic abnormality

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#725]
https://athena.ohdsi.org/search-terms/terms/44836904
mapped to Neoplasm 'morphologic abnormality' but should be mapped to Neoplastic disease

**Comment by TinyRickC137** [comment]
@dimshitc Agree regarding Neoplasms and fractures, but what do you suggest for fibrosis?

**Comment by dimshitc** [comment]
For those mapped to Fibrosis, you can improve the Complication due to device part
![image](https://user-images.githubusercontent.com/8568959/233603309-a7a8775f-5e27-4151-9de6-ec90071d17fb.png)
and add  a target "213132005 | Internal prosthetic device causing fibrosis to the mapping".
You can leave "Fibrosis" (morph abn) as a target concept as well

**Comment by irinazherko** [comment]
We are pleased to inform you that the issue has been successfully corrected during the February 2024 Release.
