### ISSUE TITLE
UK Biobank Cholesterol measurement incorrectly mapped to Creatinine LOINC

### ISSUE THREAD

**Issue by lmcewen-helix** [OHDSI/Vocabulary-v5.0#727]
**Describe the problem in content**
UK Biobank Blood Biochemistry Cholesterol incorrectly mapped to Creatinine LOINC

**How to find it**
https://athena.ohdsi.org/search-terms/terms/35814427

**Expected adjustments**
The relationship of 'maps to' for the UK Biobank Blood Biochemistry measurement for Cholesterol (concept_code = 
30690) should be revised from Creatinine (concept_id = 3020564) to Cholesterol (concept_id = 3019900).

**Comment by TinyRickC137** [comment]
Good news: this small bug has been fixed!
https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20230831_1693510428.000000
