### ISSUE TITLE
SNOMED concept name truncated in OMOP

### ISSUE THREAD

**Issue by murphyke** [OHDSI/Vocabulary-v5.0#74]
I'm seeing some SNOMED concepts that have different preferred concept names but get assigned the same `concept_name` in the OMOP vocabulary:

```
select * from concept where concept_name = 'Closed fracture of orbital floor';
 concept_class_id |   concept_code    | concept_id | concept_level |           concept_name           | domain_id | invalid_reason | standard_concept | valid_end_date | valid_start_date | vocabulary_id
------------------+-------------------+------------+---------------+----------------------------------+-----------+----------------+------------------+----------------+------------------+---------------
 Clinical Finding | 11303761000119101 |   45757291 |               | Closed fracture of orbital floor | Condition |                | S                | 2099-12-31     | 2015-01-31       | SNOMED
 Clinical Finding | 49346003          |     435661 |               | Closed fracture of orbital floor | Condition |                | S                | 2099-12-31     | 1970-01-01       | SNOMED
```

`49346003` should be "Closed fracture of orbital floor (blow-out)".

I haven't done a systematic search, but other concept names having the same problem are "Ingrowing toenail", "Moderate cigarette smoker", and "Malignant neoplasm of cerebrum".

Is there an ETL process that is failing to handle parentheses in the concept name properly?

I'm using the v5.0 vocabulary.

**Comment by cgreich** [comment]
@murphyke:

Two things:

1, The parenthesis gets taken away because it is usually used for indicating the concept class (Clinical finding in this case). We can look into doing a cleaner parsing job. In the mean time, use the concept_synonym table, there you got them with the parentheses.

2. We have brought up with SNOMED that there are these duplicates or almost duplicates. Will push it again.

**Comment by ericaVoss** [comment]
Testing in 20180609

Looks like SNOMED still thinks they both exist

```SQL
SELECT CONCEPT_ID, CONCEPT_NAME, CONCEPT_CODE
FROM CONCEPT
WHERE CONCEPT_CODE IN ( '49346003','11303761000119101')
```

```
CONCEPT_ID	CONCEPT_NAME	                        CONCEPT_CODE
45757291	Closed fracture of orbital floor	11303761000119101
435661	        Closed fracture of orbital floor	49346003
```

Worth pinging SNOMED again and/or closing this issue?

**Comment by cgreich** [comment]
None yet. Working on it.

**Comment by TinyRickC137** [comment]
Not happening anymore, 49346003 now has (blow-out) in name
