### ISSUE TITLE
Maps to Value concept violates requirement that Observation value as concept id be in 'Meas Value' domain

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#741]
**Describe the problem in content**
Concept 35211429 (Abnormality of albumin) is in the Measurement domain.  It has a 'Maps to value' relationship to concept 4135493 (Abnormal) which is in the Spec Disease Status domain.  In doing an ETL the maps to value will go into value_as_concept_id. This will be flagged as an error by the Data Quality Dashboard because concept in value_as_concept_id should be in the Meas Value domain.

**How to find it**
This query returns about 80 row
```
SELECT base.concept_id, base.concept_name baseConceptName, base.domain_id baseDomain
     , mapTo.concept_id, mapto.concept_name, mapTo.domain_id
  FROM concept base
  JOIN concept_relationship ON concept_id_1 = base.concept_id
  JOIN concept mapTo On mapTo.concept_id = concept_id_2
WHERE base.domain_id = 'Measurement'
  AND relationship_id = 'Maps to value'
  AND mapTo.domain_id != 'Meas Value'
```
**Expected adjustments**
Update the Maps to value concepts with concepts in the Meas Value domain.  For example change the current concept for Abnormal to 45878745 (Abnormal) which is a Standard concept in the Meas Value domain.

**Screenshots**

**Additional context**

**Comment by mik-ohdsi** [comment]
Thanks, @don-torok !
Looks like a good catch and a regrettable oversight on our side. @cgreich , do you agree?
~mik

**Comment by Alexdavv** [comment]
This was done intentionally because there no other good concepts. We will bring back these concepts home to SNOMED with a proper Domain. For the Disease Status we'll create new dedicated OMOP-made concepts.

**Comment by dimshitc** [comment]
There's [Abnormal Meas Value](https://athena.ohdsi.org/search-terms/terms/45878745) 
 and for these concepts
![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/8568959/2449a563-b095-4f95-8759-5d49ef7f745e)
High alcohol level in blood should be maps_to_concept_id, not a value_as_concept_id

**Comment by m-khitrun** [comment]
Hello, @don-torok 

Please, be informed that concepts [Normal](https://athena.ohdsi.org/search-terms/terms/4069590), [Abnormal](https://athena.ohdsi.org/search-terms/terms/4135493), and [Malignant ](https://athena.ohdsi.org/search-terms/terms/4066212)have been moved from Spec Disease Status to Meas Value domain.

Regards,
Masha.
