### ISSUE TITLE
Request for additional HCPCT/CPT codes for ATHENA

### ISSUE THREAD

**Issue by krevett-iqvia** [OHDSI/Vocabulary-v5.0#747]
@cgreich @mik-ohdsi 

I am making this request in order to expand the CPT codes for our FDA project  - specifically, we are seeking the addition of additional codes for the bivalent COVID vaccines.

This request is merely to ask for expanded coverage of covid codes
What we would like to request is the following:

2 codes for the Moderna bivalent booster pediatric code:
91316
0164A

2 codes for the Pfizer bivalent, third primary series pediatric codes:
91317
0173A

We would respectfully ask you to elevate this request to be on your priority list?  it is crucial for our studies with the FDA.

Thank you,

Ken Revett

**Comment by m-khitrun** [comment]
Hello, @krevett-iqvia!
Please, find the reqiured concepts in Athena: [91316](https://athena.ohdsi.org/search-terms/terms/733014), [0164A](https://athena.ohdsi.org/search-terms/terms/733012), [91317](https://athena.ohdsi.org/search-terms/terms/733013), [0173A](https://athena.ohdsi.org/search-terms/terms/733011)
