### ISSUE TITLE
MedDRA not in v5.0 16-JAN-23 (EULA provided)

### ISSUE THREAD

**Issue by mpatel-cai** [OHDSI/Vocabulary-v5.0#748]
Selected MedDRA when downloading a new bundle, but do not see it in the list of vocabularies when downloading.

**Comment by TinyRickC137** [comment]
Hello, @mpatel-cai 
Are you sure? I've just checked it: there are MedDRA concepts in download when you select them. Could you try it again, please?

**Comment by mpatel-cai** [comment]
I'll try again and get back to you
