### ISSUE TITLE
CPT4 failed to reconstitute in v5.0 16-JAN-23

### ISSUE THREAD

**Issue by mpatel-cai** [OHDSI/Vocabulary-v5.0#749]
logs are attached
[logfile.log](https://github.com/OHDSI/Vocabulary-v5.0/files/10453210/logfile.log)
[not-processed-concepts-01-18-2023-19-53-05.txt](https://github.com/OHDSI/Vocabulary-v5.0/files/10453212/not-processed-concepts-01-18-2023-19-53-05.txt)

**Comment by mik-ohdsi** [comment]
Hi @mpatel-cai - [we are on it](https://forums.ohdsi.org/t/athena-cpt-script-failure/17978/4), Meera. We hope to provide a patch rather soon.

**Comment by mik-ohdsi** [comment]
a patch has been provided, @mpatel-cai ... please create a new package and download. Please let us know if this works for you (and close the issue if it does).

**Comment by mpatel-cai** [comment]
Trying now will update once it is complete
