### ISSUE TITLE
CPT4 failed to completely reconstitute in v5.0 23-JAN-23

### ISSUE THREAD

**Issue by mpatel-cai** [OHDSI/Vocabulary-v5.0#752]
log file results:
```
733009		Measurement	CPT4	CPT4	S	0362U	20230101	20991231	
733010		Measurement	CPT4	CPT4	S	0363U	20230101	20991231	
733015		Measurement	CPT4	CPT4		0355U	20230101	20991231	
733017		Measurement	CPT4	CPT4	S	0357U	20230101	20991231	
733016		Measurement	CPT4	CPT4	S	0356U	20230101	20991231	
733019		Measurement	CPT4	CPT4	S	0359U	20230101	20991231	
733018		Measurement	CPT4	CPT4	S	0358U	20230101	20991231	
733020		Measurement	CPT4	CPT4	S	0360U	20230101	20991231	
733021		Measurement	CPT4	CPT4	S	0361U	20230101	20991231	
```

**Comment by mik-ohdsi** [comment]
yes, sorry, Meera @mpatel-cai 
an unexpected addition of items not yet available through UMLS. We need to patch the CPT4.jar file to cover those. Please bear a moment with us...

**Comment by evanetteburrows** [comment]
@mik-ohdsi Having the same issue. Following for updates!

**Comment by mik-ohdsi** [comment]
Hang in there! We have a tested solution but it still has to go through the deployment process. Hope to have it soon. Small drawback: to also cope with the recently enforced UMLS API restrictions we had to slow down the processing. It runs a bit more than 5 hours now. We hope to be able to find a better solution together with UMLS soon. @cgreich - anyone you can blackmail there?

**Comment by mik-ohdsi** [comment]
Hey @evanetteburrows and @mpatel-cai , it [looks](https://forums.ohdsi.org/t/cpt4-concept-processing-issue/17911/13) as if there is a new CPT4 tool. Thanks, @konstjar . 
Please request a new download (do not try your old download link). Some additional information: to comply with certain access restrictions by the UMLS API, the tool has been slowed down considerably and it takes now 5+ hours for it to complete. Please factor this in. We hope to find a better solution soon with the UMLS people. 
As soon as one of you has successfully run the tool and all concepts have been reconstituted, can you come back here and close this issue? ~Mik

**Comment by mpatel-cai** [comment]
Worked fine! Took longer than usual but ran in the background so it was no big deal. Thanks!

**Comment by evanetteburrows** [comment]
Worked for me as well! Thanks @mik-ohdsi !
