### ISSUE TITLE
ICD10 'O26.0 | Excessive weight gain in pregnancy' has better mapping

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#758]
ICD10 'O26.0 | Excessive weight gain in pregnancy' has better mapping:
607211	1149345007	[Excessive weight gain during pregnancy](https://athena.ohdsi.org/search-terms/terms/607211)

**Comment by irinazherko** [comment]
We are pleased to inform you that the issue has been successfully corrected during the February 2024 Release.
