### ISSUE TITLE
ICD-9 v15.82  has no valid 'Maps to' relationship

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#76]
V15.82 (Personal history of tobacco use) has no valid 'Maps to' relationship, only a 'Maps to value' relationship. I would expect a 'Maps to' relationship with 'History of clinical finding in subject' (4214956).

**Comment by ericaVoss** [comment]
**20160620**

Still an issue 

```{sql}
SELECT *
FROM CONCEPT c
	JOIN CONCEPT_RELATIONSHIP cr
		ON concept_id_1 = c.concept_id
		AND cr.relationship_id = 'Maps to'
	JOIN CONCEPT c2
		ON c2.concept_id = cr.concept_id_2
WHERE c.CONCEPT_CODE = 'V15.82'
```

**Comment by ericaVoss** [comment]
Still in 20160817

**Comment by aostropolets** [comment]
@schuemie @ericaVoss 
maps to  43530634 History of tobacco use

**Comment by ericaVoss** [comment]
Confirm that we should close this ticket.  20171201.
