### ISSUE TITLE
NSAID concept_id missing for drug table

### ISSUE THREAD

**Issue by cipherome-lisa** [OHDSI/Vocabulary-v5.0#760]
We noticed there is no concept_id for NSAID in the drug table but only in the condition table. It seems to make more sense to have one in the drug table and would like to request a concept_id for it.

**Comment by TinyRickC137** [comment]
Hello, @cipherome-lisa 

Could you specify which concept_id for NSAID you see in the Condition table?

NSAIDs are a very heterogenous drug group. You can read more regarding OHDSI best practices on the Forum [here](https://forums.ohdsi.org/t/classification-type-drug-groups-in-source-data/16612) and [here](https://forums.ohdsi.org/t/drug-concepts-with-lower-granularity-medicine-groups/13609)
The closest you can use for drug group identification is ATC [ANTIINFLAMMATORY AND ANTIRHEUMATIC PRODUCTS, NON-STEROIDS](https://athena.ohdsi.org/search-terms/terms/21603933)

**Comment by cipherome-lisa** [comment]
Hi @TinyRickC137 

I see the only standard concept_id for NSAID is: [3190272](https://athena.ohdsi.org/search-terms/terms/3190272) and that [ANTIINFLAMMATORY AND ANTIRHEUMATIC PRODUCTS, NON-STEROIDS](https://athena.ohdsi.org/search-terms/terms/21603933) does not have a standard concept_id. We're looking for standard concept_ids to use for NSAID use but I understand it is a group of drugs so was wondering what would be the best way to indicate this in a standard way.

Thanks!

**Comment by cgreich** [comment]
You cannot. DRUG_EXPOSURE can only hold a drug, which is a concept defined at least by an ingredient. Drug classes, which are OR-buckets of multiple ingredients, cannot be written into the table. In other words you can give a patient diclophenac or ibuprofen, but you can't administer an NSAID.
