### ISSUE TITLE
44827910 and 35209473 need better mapping

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#761]
**Describe the problem in content**
44827910 and 35209473 are icd codes that are mapped to SNOMED as 'Finding of menstrual bleeding'

**How to find it**
Search for the concept id

**Expected adjustments**
maybe map to 197607.

**Screenshots**

**Additional context**
'Finding of menstrual bleeding' is a lossy mapping. This snomed concept is mapped to several other concepts. This makes the mapping not useful

**Comment by conovermitch** [comment]
I think there might be one minor correction to your post.  conceptId=35209473 (ICD-10-CM code N92.1 "Excessive and frequent menstruation with irregular cycle" does not map to conceptId=4078455 "Finding of menstrual bleeding" (SNOMED).  It maps to conceptId=4171394 "Abnormal menstrual cycle" (SNOMED).

**Comment by gowthamrao** [comment]
Similar problem 1571584. lossy mapping to snomed

**Comment by irinazherko** [comment]
@gowthamrao We are pleased to inform you that the issue has been successfully corrected during the February 2024 Release. Thank you very much for your contribution!
