### ISSUE TITLE
HCPCS Concept lost its mapping

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#764]
https://athena.ohdsi.org/search-terms/terms/2617289

**Comment by dimshitc** [comment]
Oh, there are a whole bunch of these

G0202
G0206
G0204
G0479
G0436
G6040
J2560
G0477
G0515
G0478
G0437
G0455
G0375
G0464
G0173
G6024
G0505
G6022
G6028
G6025
C9736
G6027
G0514
G9599
G6019

**Comment by stephanieshong** [comment]
more HCPCS codes that are missing in Athena
A0101
A0102
A0103
A0104
A0105
A0106
A0107
A0108
A0109
A0110
A0201
A0202
A0203
A0204
A0205
A0206
A0207
A0301
A0302
A0303
A0304
A0305
A0305
A0401
A0402
A0403
A0404
A0405
A0406
A0407
A0501
A0502
A0503
A0504
A0505
A0506
A0601
A0602
A0602

**Comment by stephanieshong** [comment]
there is more that are missing:
A0603
A0604
A0701
A0702
A0703
A0704
A0801
A0802
A0803
A0804
A0805
A0806
A0901
A0902
A0903
A0904
A1001
A1002
A1003
A1004
A1081
A1101
A1201
A1202
A1203
A1204
A1301
A1303
A1304
A1401
A1402
A1403
A1404

**Comment by stephanieshong** [comment]
A1501
A1502
A1503
A1504
A1601
A1602
A1603
A1604
A1701
A1702
A1703
A1704
A1705
A1801
A1802
A1803
A1804
A1805
A1806
A1902
A1903
A1904
A2001
A2002
A2003
A2004
A2005

**Comment by stephanieshong** [comment]
B section: 
B0101
B0102
B0103
B0104
B0105
B0106
B0107
B0108
B0109
B0110
B0202
B0203
B0204
B0205
B0207
B0301
B0302
B0303
B0304
B0305
B0402
B0403
B0404
B0405
B0406
B0407
B0501
B0502
B0503
B0504
B0505
B0506
B0601
B0602
B0603
B0604
B0701
B0702

B0703
B0704
B0801
B0802
B0803
B0804
B0805
B0806
B0901
B0902
B0903
B0904
B1001
B1002
B1003
B1004
B1101
B1102
B1103
B1201
B1202
B1203
B1303
B1304
B1305
B1401
B1402
B1403
B1404
B1501
B1502
B1503
B1504

**Comment by m-khitrun** [comment]
@stephanieshong , hello!
Maybe I'm mistaken, but these codes look like [HIPPS ](https://www.cms.gov/Regulations-and-Guidance/Guidance/Transmittals/2019downloads/R4368CP.pdf) codes, not HCPCS.

**Comment by cgreich** [comment]
@stephanieshong: Probably a different Github issue. And it should work, even if you are not logged in. Try again.

**Comment by stephanieshong** [comment]
ok, thank you.

**Comment by m-khitrun** [comment]
@dimshitc 
The mapping of these concepts was fixed. Please, note, that some of these HCPCS concepts are now mapped to standard concepts in CPT4 vocab and are not reflected on Athena. We'll consider remapping them to SNOMED in the course of the nearest release.
