### ISSUE TITLE
adalimumab-atto NDC Addition

### ISSUE THREAD

**Issue by mrechkem** [OHDSI/Vocabulary-v5.0#766]
Hi-

We have a new drug, AMJEVITA (adalimumab-atto), as of January 31, 2023. It is a biosimilar to Humira, and I found the precise ingredient within Athena (concept ID 35201854). Would it be possible to add the [NDCs](https://www.accessdata.fda.gov/drugsatfda_docs/label/2016/761024lbl.pdf) to the vocabulary?     

Thanks,
-Brad

**Comment by mrechkem** [comment]
For some additional context, below are the source codes for all forms of Amjevita currently. We may also want to consider adding some RxNorm for mapping the source codes below to the adalimumab ingredient level. A potential solution might be to create branded dose group for the three dosing groups below: 20/0.4, 40/0.8, 40/0.8 autoinjector.


![image](https://user-images.githubusercontent.com/70781546/221325270-00f5c2cf-37ae-44c4-bfef-f0970ca21596.png)

**Comment by mrechkem** [comment]
Hi @mik-ohdsi - I wanted to follow-up with this issue to see if any additional information would be helpful for processing this request.

Much appreciated,
-Brad

**Comment by mik-ohdsi** [comment]
Hi @mrechkem - we are investigating. There is a bit of a delay between publication and availability in Athena and I presume it wasn't part of the previous delivery / release but should be available with the next one (probably within this month). However, it is likely that RxNorm didn't [catch up](https://mor.nlm.nih.gov/RxNav/search?searchBy=String&searchTerm=adalimumab-atto) with it yet and therefore we will have to wait for that until we can provide proper relationships into a matching target (we cannot create our own RxNorm entries just for OHDSI). NDC codes typically map into some (quantified) branded drug level like [this one](https://athena.ohdsi.org/search-terms/terms/44935752). For your ETL you could wait for the arrival of the NDC codes in Athena but would have to provide your own mapping to the ingredient level (precise ingredient is not a standard concept) for the time being.

**Comment by mik-ohdsi** [comment]
or a Quant Clinical Drug like [this](https://athena.ohdsi.org/search-terms/terms/19098170), derived from the Australian [Amgevita](https://athena.ohdsi.org/search-terms/terms/2902291) in RxNorm Extension...
The source NDC value would then identify your particular product. @mrechkem - Can you close this issue once you have received the NDC codes from the next vocab release?
