### ISSUE TITLE
Read codes should be mapped to new Smoking hierarchy concepts

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#768]
for example https://athena.ohdsi.org/search-terms/terms/45441534
https://athena.ohdsi.org/search-terms/terms/45478365 
etc

**Comment by MariaRohozhkina** [comment]
Thank you for the report! It has been fixed in [this release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20230831_1693510428.000000).
