### ISSUE TITLE
Read code mapped to both CVX and RxNorm

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#769]
[this](https://athena.ohdsi.org/search-terms/terms/45475578) concept is mapped to both RxNorm and CVX.
Is this done intentionally?

**Comment by MariaRohozhkina** [comment]
Thank you for the report! It has been fixed in [this release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20230831_1693510428.000000). 
Now you can find improved mapping of this [concept](https://athena.ohdsi.org/search-terms/terms/45475578) in the Athena.
