### ISSUE TITLE
mapping to 2 close concepts, which one is correct?

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#770]
https://athena.ohdsi.org/search-terms/terms/45508690

**Comment by MariaRohozhkina** [comment]
Thank you for the report! It has been fixed in [this release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20230831_1693510428.000000). 
Now you can find improved mapping of this [concept](https://athena.ohdsi.org/search-terms/terms/45508690) in the Athena.
