### ISSUE TITLE
Wrong Read vaccine mapping

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#771]
https://athena.ohdsi.org/search-terms/terms/1397845

it shouldn't be mapped to "hepatitis B vaccine, unspecified formulation"

**Comment by dimshitc** [comment]
In general Read vaccines mapping is a mess

**Comment by MariaRohozhkina** [comment]
Thank you for the report! It has been fixed in [this release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20230831_1693510428.000000). 
Now you can find improved mapping of this [concept](https://athena.ohdsi.org/search-terms/terms/1397845) in the Athena.
