### ISSUE TITLE
Make release notes more accessible

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Vocabulary-v5.0#772]
Right now if I go to wiki and click on Releases I don't see the release notes right away. Instead, I need to click on the word "releases" in the first paragraph to get to the notes. Would be nice to have it more explicit (eg just have a sentence "Release notes can be found here").

**Comment by TinyRickC137** [comment]
> The OMOP Standardized Vocabularies change over time. To manage the change of content, but to allow users to use and refer to a defined set of vocabularies, the whole resource is issued in [releases](https://github.com/OHDSI/Vocabulary-v5.0/releases). Releases do not (yet) happen in a standard frequency, but usually within one or two months. Twice a year, a major release is issued, which differs from the rest by having a larger number of issues fixed and vocabularies updated. These happen usually in summer and winter.

The link is there, actually. The first page describes the structure of the release notes, the second one contains the release notes themselves.

**Comment by aostropolets** [comment]
Yes, absolutely, the link is there. For me it took some time to realize that the link leads to release notes. So can be as simple at changing “releases” to “release notes”.
