### ISSUE TITLE
Mantle cell lymphoma - what is the logic for how the ICD9 codes (200.4*) got mapped into SNOMED

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#78]
All ICD-9-CM codes in the 200.4 series are 'mantle cell lymphoma', and then provide further specification of the lymph nodes for which they refer to.  However, in the mapping of these ICD9 codes into SNOMED, only a few of these codes map into the SNOMED concept of 'mantle cell lymphoma' and the other codes map to other non-specific malignant lymphoma concepts.  Here's a listing from the vocab v5.0 11-MAR-16:

| concept_id | concept_code | concept_name | vocabulary_id | relationship_id | concept_id | concept_name | vocabulary_id |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 44829826 | 200.40 | Mantle cell lymphoma, unspecified site, extranodal and solid organ sites | ICD9CM | Maps to | 40481901 | Mantle cell lymphoma | SNOMED |
| 44820625 | 200.41 | Mantle cell lymphoma, lymph nodes of head, face, and neck | ICD9CM | Maps to | 440350 | Malignant lymphoma - lymphocytic, intermediate differentiation | SNOMED |
| 44828748 | 200.42 | Mantle cell lymphoma, intrathoracic lymph nodes | ICD9CM | Maps to | 440350 | Malignant lymphoma - lymphocytic, intermediate differentiation | SNOMED |
| 44820626 | 200.43 | Mantle cell lymphoma, intra-abdominal lymph nodes | ICD9CM | Maps to | 200349 | Malignant lymphoma of intra-abdominal lymph nodes | SNOMED |
| 44832139 | 200.44 | Mantle cell lymphoma, lymph nodes of axilla and upper limb | ICD9CM | Maps to | 441521 | Malignant lymphoma of lymph nodes of axilla AND/OR upper limb | SNOMED |
| 44826419 | 200.45 | Mantle cell lymphoma, lymph nodes of inguinal region and lower limb | ICD9CM | Maps to | 440350 | Malignant lymphoma - lymphocytic, intermediate differentiation | SNOMED |
| 44821743 | 200.46 | Mantle cell lymphoma, intrapelvic lymph nodes | ICD9CM | Maps to | 440350 | Malignant lymphoma - lymphocytic, intermediate differentiation | SNOMED |
| 44835692 | 200.47 | Mantle cell lymphoma, spleen | ICD9CM | Maps to | 40479608 | Mantle cell lymphoma of spleen | SNOMED |
| 44830994 | 200.48 | Mantle cell lymphoma, lymph nodes of multiple sites | ICD9CM | Maps to | 132841 | Malignant lymphoma of lymph nodes of multiple sites | SNOMED |

produced from the following query:

select c2.concept_id, c2.concept_code, c2.concept_name, c2.vocabulary_id, cr1.relationship_id, c1.concept_id, c1.concept_name, c1.vocabulary_id
from concept_relationship cr1
inner join concept c1
on cr1.concept_id_2 = c1.concept_id
and c1.vocabulary_id = 'snomed'
inner join concept c2
on concept_id_1 = c2.concept_id
where concept_id_1 in (44829826, 44820625,  44828748, 44820626, 44832139, 44826419, 44821743,   44835692, 44830994)
order by c2.concept_code;

**Comment by cgreich** [comment]
Yeah. It's the mismatch between the hierarchies:

Mantle cell lymphoma (200.4) is combined with the affected anatomical sites to make 200.40-200.48. SNOMED doesn't have those pre-coordinations, except spleen (200.47), which is mapped properly. The others are mapped a little unfortunate, I agree. They should just become the same Mantle Cell Lymphoma as the ancestor.

This problem happens all the time. One dictionary combines different dimensions than another. The original SNOMED actually had them all split up. Mantle Cell Lymphoma of the spleen would have been:

Morphology=Mantle Cell Lymphoma
Anatomical Site=Spleen or lymph nodes of the neck of whereever.

ICD9 and 10 pre-coordinate these things much more heavily than SNOMED, which makes mapping hard. One idea is to return to the three dimensions Morphology, Anatomical Site and Cause in addition to the pre-coordinated condition_concept_id. If you have a simple map, you would fill in those other dimensions from the SNOMED relationships (they always give that to you). That way, you could do searches like "Give me all diseases of the spleen" without having to know which of them have the speen implicitly or explicitly mentioned. 

I'll add this to the WG proposals.

**Comment by dimshitc** [comment]
Actually, "440350	Malignant lymphoma - lymphocytic, intermediate differentiation" is a synonym of 	"40481901	Mantle cell lymphoma", so we can map to any, but I agree that it's better to have a consistency and keep one of them,  let it be "40481901	Mantle cell lymphoma".
So there is another SNOMED problem - when they make different concepts from disease synonyms.
Proper way is to have  "40481901	Mantle cell lymphoma" as a concept and "Malignant lymphoma - lymphocytic, intermediate differentiation" as a synonym.

**Comment by ericaVoss** [comment]
Testing in 20180609

I think this is resolved now, do you agree @pbr6cornell ?

**Comment by dimshitc** [comment]
Yes, we can close. Now, if we don't have equivalent SNOMED concept, we map the source to two concepts, like this:


44820626 | 200.43 | Mantle cell lymphoma, intra-abdominal lymph nodes | ICD9CM | Maps to | 40481901 | Mantle cell lymphoma | SNOMED
-- | -- | -- | -- | -- | -- | -- | --
44820626 | 200.43 | Mantle cell lymphoma, intra-abdominal lymph nodes | ICD9CM | Maps to | 200349 | Malignant lymphoma of intra-abdominal lymph nodes | SNOMED
