### ISSUE TITLE
Adding additional tables/column to existing CDM table.

### ISSUE THREAD

**Issue by tjeygds** [OHDSI/Vocabulary-v5.0#782]
Is it a good practice to add new tables/columns to CDM tables. 
Whether any code break happens for OMOP tools if we add additional column to existing tables. Is their any other mechanism we can accommodate new columns/tables to the CDM

**Comment by cgreich** [comment]
This is a question for the OMOP CDM, not the vocabularies. If you want to add fields or tables it is called an Expansion. You can just do that. The tools won't care or even notice. If you want to make it a permanent part of the model it is called an Extension, and the process is here: https://ohdsi.github.io/CommonDataModel/cdmRequestProcess.html.

**Comment by mik-ohdsi** [comment]
@cgreich - could you please transfer this issue to the [CommonDataModel](https://github.com/OHDSI/CommonDataModel) repository? (I do not have that particular super-power...)
