### ISSUE TITLE
HCPCS 2718234	Injection, alpha 1 proteinase inhibitor (human), not otherwise specified, 10 mg - wrong mapping

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#785]
2718234	Injection, alpha 1 proteinase inhibitor (human), not otherwise specified, 10 mg
wrong mapping

should be linked to concept with this ingredient https://athena.ohdsi.org/search-terms/terms/1169352
it even Has form (RxNorm)
[alpha 1-proteinase inhibitor, human](https://athena.ohdsi.org/search-terms/terms/40181679)

and [RxNorm Extension concept](https://athena.ohdsi.org/search-terms/terms/36274609) should be de-standardized

**Comment by m-khitrun** [comment]
@dimshitc 
Please, be informed that this mapping was fixed in the course of the recent release. Thank you for your comment.
