### ISSUE TITLE
Rilpivirine - 2 Multilex codes not captured by RxNorm

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Vocabulary-v5.0#79]
Hi,

In Vocab v5.0 as of March 11, 2016, along with the latest we were able to pull up as of May 5, 2016:

The HIV drug Rilpivirine has 16 standard drug concept matches, with 4 being from Multilex. However, when selecting the Ingredient matches (43534954, 43534953, and 40238930), their descendants do not include 2 of those Multilex matches: 43535173 and 43535169. Can these 2 Multilex codes be mapped to the Rilpivirine ingredients?

Thanks,
Ajit

**Comment by cgreich** [comment]
Ajit:

Multilex is about to die. CPRD and THIN are no longer using them. We are finalizing Gemscript, which is the successor, as we speak. So, no effort put into Multilex.

Does that work?

**Comment by alondhe** [comment]
Yep, that works. Thanks!
