### ISSUE TITLE
wrong mapping ICD10 Primary biliary cirrhosis -> SNOMED Primary biliary cholangitis

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#790]
see 
https://athena.ohdsi.org/search-terms/terms/45557676
https://athena.ohdsi.org/search-terms/terms/37610557

**Comment by TinyRickC137** [comment]
It's basically the same condition, proof: [SNOMED synonyms](https://athena.ohdsi.org/search-terms/terms/4135822), [ICD10CM synonyms](https://www.aapc.com/codes/icd-10-codes/K74.3#:~:text=ICD%2D10%20code%20K74.,Diseases%20of%20the%20digestive%20system%20.), a random related [article from the internet](https://www.mayoclinic.org/diseases-conditions/primary-biliary-cholangitis/symptoms-causes/syc-20376874#:~:text=Primary%20biliary%20cholangitis%2C%20previously%20called,helps%20you%20absorb%20certain%20vitamins.)

**Comment by dimshitc** [comment]
Thanks @TinyRickC137, I'm happy to be wrong when I say "the wrong mapping"
