### ISSUE TITLE
wrong domain of CPT4 2108163 Therapeutic apheresis; for plasma pheresis

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#791]
It's Measurement currently, previously it was Procedure, and Procedure is a correct domain since it's a therapeutic procedure.

**Comment by m-khitrun** [comment]
@dimshitc 
Please, be informed that the domain was fixed in the course of recent release: https://athena.ohdsi.org/search-terms/terms/2108163
