### ISSUE TITLE
CPT domains

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Vocabulary-v5.0#792]
Should this CPT-4 concept be Procedure instead of Device?

2109019 Tube or needle catheter jejunostomy for enteral alimentation, intraoperative, any method (List separately in addition to primary procedure)
https://athena.ohdsi.org/search-terms/terms/2109019

**Comment by linikujp** [comment]
I agree. Jejunostomy is the surgical creation of an opening (stoma) through the skin at the front of the abdomen and the wall of the jejunum (part of the small intestine). It can be performed either endoscopically, or with open surgery.(https://en.wikipedia.org/wiki/Jejunostomy)

**Comment by m-khitrun** [comment]
@aostropolets, @linikujp 
Please, be informed that the domain was fixed in the course of the recent release: https://athena.ohdsi.org/search-terms/terms/2109019
