### ISSUE TITLE
Neuropsychiatric Scores and Scales - Deduplication request [Psychiatry WG]

### ISSUE THREAD

**Issue by p-talapova** [OHDSI/Vocabulary-v5.0#795]
Hi there! During our work in the Psychiatry Working Group on Neuropsychiatric OMOP Scores and Scales, we have identified several duplicates in the OMOP Extension concepts that overlap with standard concepts. We have created a replacement mapping to address this issue, please see the table below (also, attached as a CSV):

concept_id_1 | concept_code_1 | concept_name_1 | relationship_id | concept_id_2 | concept_code_2 | concept_name_2
-- | -- | -- | -- | -- | -- | --
40219533 | OMOP5000498 | Psychotic depression assessment scale | Concept replaces | 606842 | 1148703001 | Psychotic Depression Assessment Scale
40219511 | OMOP5000475 | Family environment scale | Concept replaces | 609177 | 472631000124105 | Family Environment Scale
40219586 | OMOP5000552 | Altman self-rating mania scale | Concept replaces | 3654719 | 838442002 | Altman Self-Rating Mania Scale
40219571 | OMOP5000536 | Yale-Brown obsessive compulsive scale | Concept replaces | 3654881 | 840418002 | Yale-Brown Obsessive Compulsive Scale
40219516 | OMOP5000480 | Wechsler memory scale | Concept replaces | 4158884 | 273921009 | Wechsler memory scale
40219605 | OMOP5000571 | Medication adherence rating scale | Concept replaces | 0 | 1231438009 | Medication Adherence Rating Scale
40219502 | OMOP5000465 | Calgary depression scale for schizophrenia | Concept replaces | 0 | 1231439001 | Calgary Depression Scale for Schizophrenia
40219449 | OMOP5000410 | Piers-Harris children's self-concept scale | Concept replaces | 0 | 1231440004 | Piers-Harris Children's Self-Concept Scale
40219520 | OMOP5000484 | Internet addiction scale | Concept replaces | 0 | 1231441000 | Internet Addiction Test
40219583 | OMOP5000548 | Children's loneliness scale | Concept replaces | 0 | 1231442007 | Children's Loneliness Scale
40219577 | OMOP5000542 | Bush Francis catatonia rating scale | Concept replaces | 0 | 1231443002 | Bush-Francis Catatonia Rating Scale
40219445 | OMOP5000407 | Adolescent life change events scale | Concept replaces | 0 | 1231453001 | Adolescent Life Change Event Scale
40219532 | OMOP5000497 | Hamilton anxiety rating scale | Concept replaces | 0 | 1231454007 | Hamilton Anxiety Rating Scale
40219535 | OMOP5000500 | Liebowitz social anxiety scale | Concept replaces | 0 | 1231512007 | Liebowitz Social Anxiety Scale
40219431 | OMOP5000393 | Conners comprehensive behaviour rating scale | Concept replaces | 0 | 1231513002 | Conners Comprehensive Behavior Rating Scales
40219476 | OMOP5000437 | Social avoidance and distress scale | Concept replaces | 0 | 1231515009 | Social Avoidance and Distress Scale
40219424 | OMOP5000466 | Social anxiety scale for children revised | Concept replaces | 0 | 1231516005 | Social Anxiety Scale for Children-Revised

The duplication occurred because SNOMED added new terms that cover concepts that were previously created as OMOP Extensions. However, some of the SNOMED expressions needed for deduplication are not yet available in Athena (they have 0 in the concept_id_2 field).

We are hopeful that the vocabulary team will be able to implement a replacement mapping for the detected OMOP Extension duplicates, once the SNOMED is refreshed in the OMOP Vocabulary.

[Psychiatry WG - OMOP scales duplicates.csv](https://github.com/OHDSI/Vocabulary-v5.0/files/11171054/Psychiatry.WG.-.OMOP.scales.duplicates.csv)

**Comment by dimshitc** [comment]
what if we make this as a cross-team collaboration?
@p-talapova what if you provide the concept_manual and concept_relationship_manual tables to the vocabulary team and they'll just run them? 
@Alexdavv @TinyRickC137 this is something you prefer as well, right?

**Comment by TinyRickC137** [comment]
@dimshitc @p-talapova @MariaRohozhkina 
Agree. Let's do it. 
We will try to release it in May

**Comment by TinyRickC137** [comment]
Getting back to this issue

Seems like OMOP Extension concepts were introduced before Snomed concepts. This situation is clear. 

My question is: why do you try to replace Snomed concepts with OMOP Extensions now? We can do it the other way like we always do. Normally we deprecate OMOP Extension concepts when Snomed or any other vocabulary introduces a good replacement. There must be a good reason to replace Snomeds with OMOP Extensions. Are there any reasons for that?

**Comment by p-talapova** [comment]
Hi there! 

> why do you try to replace Snomed concepts with OMOP Extensions now? We can do it the other way like we always do. Normally we deprecate OMOP Extension concepts when Snomed or any other vocabulary introduces a good replacement. There must be a good reason to replace Snomeds with OMOP Extensions. Are there any reasons for that?

@TinyRickC137 It was unclear to us because some SNOMED terms are still absent in Athena. However, I agree that a better approach would be to destandardize the OMOP Extension concepts. Therefore, we have prepared submission template #3 for the Vocabulary team's review, which is available [here](https://drive.google.com/drive/u/1/folders/1I_iYotG-FJizArSIEx3ON75dN4usSx10).

**Comment by dimshitc** [comment]
@TinyRickC137 I've noticed Polina created two versions of concept_relationship_manual, since in the submission documentation it is allowed to create only 'Maps to' relationships. While both 'Maps to' and 'Concept replaced by' are correct links.
Should @p-talapova create a version where both relationships are present?
I also noticed that some SNOMED concepts are missing in Athena yet, and SMOMED release is planned for the Winter release, February 2024. So that means that this change will be planned for the winter release as well, right?

**Comment by Alexdavv** [comment]
@TinyRickC137 Not always, but usually we do it that way. The only exception I remember apart from the authored vocabularies like Cancer Modifier is COVID lab test set where we'd created much more rich hierarchy with lots of attributes. It way a constant pain to put in the SNOMEDs in between. I think, some of them are still there.

@p-talapova But if you have a good reason (better design, consistency or something else) pleas speak out.

@dimshitc Right. Or could be a step-wise when the 1st portion goes to the nearest release.

**Comment by MariaRohozhkina** [comment]
Hi @p-talapova @dimshitc!
We are glad to inform that you can find requested mappings in the Athena since [new vocabulary version](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20240229_1709217174.000000) is released.
