### ISSUE TITLE
Respiratory therapy should be a procedure and not observation?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#797]
**Describe the problem in content**
These appear to be incorrectly placed in Observation domain
Physiotherapy of chest is a procedure that is performed on a patient https://athena.ohdsi.org/search-terms/terms/4144548 

Positive airway therapy https://athena.ohdsi.org/search-terms/terms/4039922

**How to find it**
see above

**Expected adjustments**
move to procedure domain

**Screenshots**

**Additional context**

**Comment by m-khitrun** [comment]
Hello, @gowthamrao,

Please, be informed that we moved these concepts to the Procedure domain in the course of this release.

Regards,
Masha.
