### ISSUE TITLE
Map Chronic respiratory failure, unspecified whether with hypoxia or hypercapnia to Chronic respiratory failure

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#798]
**Describe the problem in content**
[Chronic respiratory failure, unspecified whether with hypoxia or hypercapnia](https://athena.ohdsi.org/search-terms/terms/45548131)
is mapped to
SNOMED [Respiratory failure](https://athena.ohdsi.org/search-terms/terms/4256228)

when better mapping available 

[Chronic respiratory failure](https://athena.ohdsi.org/search-terms/terms/314971)

**Comment by IrynaZherka** [comment]
@gowthamrao Thanks a lot for your contribution!
We have fixed the mapping during the August release 2024
