### ISSUE TITLE
Standard concept and source concept don't match

### ISSUE THREAD

**Issue by hwalker23** [OHDSI/Vocabulary-v5.0#806]
Hello!

We noticed a discrepancy in the standard and source concepts for the condition "High grade squamous intraepithelial lesion on cervical Papanicolaou smear." "High grade squamous intraepithelial lesion on cervical Papanicolaou smear" concept code=[62061000119107](https://athena.ohdsi.org/search-terms/terms/45763589) has the source concept name "High grade squamous intraepithelial lesion on cytologic smear of anus (HGSIL)". This condition's source concept code is [R85.613](https://athena.ohdsi.org/search-terms/terms/45577819), which also indicates an anal sample in the ICD dictionary. HGSIL for cervical samples is [R87.613](https://athena.ohdsi.org/search-terms/terms/45582729). In ICD, it appears this condition was mistakenly coded as relating to the cervix when it should be relating to the anus (Please see table below).

<html>
<body>

Concept Code | Vocab | Name | Maps to SNOMED
-- | -- | -- | --
R85.613 | ICD10CM | High grade squamous intraepithelial lesion on cytologic smear of **anus** (HGSIL) | 62061000119107 High grade squamous intraepithelial lesion on _cervical_ Papanicolaou smear
R87.613 | ICD10CM | High grade squamous intraepithelial lesion on **cervical** Papanicolaou smear | 62061000119107 High grade squamous intraepithelial lesion on **cervical** Papanicolaou smear
796.74 | ICD9CM | Papanicolaou smear of **anus** with high grade squamous intraepithelial lesion (HGSIL) | 126291000119105 High grade squamous intraepithelial lesion on **anal** Papanicolaou smear (finding)

</body>
</html>

We would like the mapping for R85.613 to be updated to SNOMED code "126291000119105"

Please let me know if you have any questions or need any additional context for this request. Thank you!

**Comment by TinyRickC137** [comment]
This one looks like a bug. Thank you, we will fix it. 

Please, look forward for new releases of the vocabularies

**Comment by irinazherko** [comment]
@hwalker23 We are pleased to inform you that the issue has been successfully corrected during the February 2024 Release. Thank you very much for your contribution!
