### ISSUE TITLE
non-standard concept_ids not mapping to standard concept_ids

### ISSUE THREAD

**Issue by hwalker23** [OHDSI/Vocabulary-v5.0#807]
Hello!

Our data science team at the Data and Research Center (DRC) was curious as to why all non-standard concept_ids don't map to standard concept_ids.

One example of this is [CPT4 concept code 44970](https://athena.ohdsi.org/search-terms/terms/2109144) (laparoscopy, surgical, appendectomy) not being included under the SNOMED code for [appendectomy](https://athena.ohdsi.org/search-terms/terms/4243973) even though it seems like it meets the criteria to be classified as such.

Please let me know if you need additonal information or need additional examples of this issue. Thanks!

**Comment by m-khitrun** [comment]
Hello, @hwalker23!

Thank you for your question.
Indeed, our aim is to embed CPT4 into the hierarchy of SNOMED. But in case of full semantic coincidence CPT4/HCPCS codes are mapped to SNOMED codes ('Maps to' relationships are built) and deStandardized to avoid creation of semantic duplicates. The case you provided is an example of such a semantic coincidence. 
In Atlas you can find such concepts among non-Standard source codes mapped to Standard SNOMED concepts.

I hope I've answered your question.

Regards, 
Masha.
