### ISSUE TITLE
dose form "pack" needs adjustment

### ISSUE THREAD

**Issue by tiozab** [OHDSI/Vocabulary-v5.0#813]
**Describe the problem in content**
The dose form "pack" contains multiple different dose forms. 

**Expected adjustments**
please put these drugs with both the corresponding dose form (like a drug concept id which has two different ingredients)

**How to find it**
[pack.txt](https://github.com/OHDSI/Vocabulary-v5.0/files/11334532/pack.txt)

**Comment by aostropolets** [comment]
This is how RxNorm codes packs, which are two different drugs in a package. How come it is a concern for you?

**Comment by tiozab** [comment]
@aostropolets thanks for your answer! like I said, we would like to have them linked with two dose forms that we can actually work with :-) @cgreich

**Comment by TinyRickC137** [comment]
@tiozab you can undertake one additional step from Packs to Drugs in these packs and then check their forms. 
This is the way how RxNorm has been built as @aostropolets said. 

There are a lot of cases when packs contain drugs with more than one different dose form and it would create ambiguity if packs were linked to something other than 'Pack' dose form. It would also highly likely interfere with the BuildRxE script that processes non-US drugs.
