### ISSUE TITLE
HCPCS not mapped to a standard concept_id

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#830]
The following concept_ids are not mapped to standard concept_ids:

2617289
2617293
2617291
40658649
937606
45890657
40218795
40663151
40658645
43533190
1314315
2617289
2617261
40659056
40218792
2617291
40664492
45890669
40660370
40660779
2617293
1314317
40659722
45890654
1314316
40659941
40664586
40661558
40661557

**Comment by m-khitrun** [comment]
Hello, @MelaniePhilofsky,
 
Thank you for your comment. The nearest release will include these mappings. 
Please, note, than some of the mentioned HCPCS codes are mapped to CDT concepts, and these mappings are not reflected in Athena.

Regards, 
Masha.

**Comment by m-khitrun** [comment]
Hello, @MelaniePhilofsky,
 
Please, be informed all of these concept have mapping now. I've found that some of them are mapped to CPT4 standard concepts (2617293, 2617291, 1314315, 2617261, 2617291, 2617293, 1314317, 1314316) and we cannot see them in the common Athena either. I shall consider remapping them to SNOMED in the course of the Summer release to maintain consistency of Procedure mapping.

Regards,
Masha.
