### ISSUE TITLE
Duplicate Standard Concepts for PROCEDURE codes when using SOURCE_TO_STANDARD logic

### ISSUE THREAD

**Issue by lizzieLepoo** [OHDSI/Vocabulary-v5.0#833]
There seem to be some non-standard concepts in class/domain "Procedure" which map to multiple standard concepts in the class/domain "Procedure"

An example is source concept id 4213637 (code '417384007') which "maps to" both standard concepts 4230536 (code '359953009') and 44792016 (code '308111000000102')

I can't see logic within CONCEPT_ANCESTOR or other CONCEPT_RELATIONSHIP that would show which was the dominant option.

They do have different validity start dates but both are still currently valid and open (end date 31 Dec 2099)

Is this to be expected and if so are there rules on which should be use as the CONCEPT_ID when importing assigning the procedure_concept_id on import into CDM PROCEDURE_OCCURRENCE.

**Comment by TinyRickC137** [comment]
Hello, @lizzieLepoo 

You need all of the relationships to be imported into CDM Procedure occurrence. In OMOP multiple mappings mean that all of the events happened. The reason behind that logic is the fact that we often cannot represent the complex information in source data using only one concept, like in your example. 

_Administration of second booster of low dose diphtheria and inactivated poliomyelitis and tetanus vaccine_
If we map it to vaccine only like it was until some time ago, you need to do some SQL exercise to distinguish between the first dose and the second dose of vaccine. With the current mapping, you are more agile.

Speaking of valid end dates. 31 Dec 2099 means eternity in OMOP. Standard Valid concepts should have 31 Dec 2099 as their end date. The start date is usually the date when relationships have been constructed.

**Comment by TinyRickC137** [comment]
Linking the respective forum topic: https://forums.ohdsi.org/t/duplicate-standard-concepts-for-procedure-codes-when-using-source-to-standard/18991

The issue may be reopened in future if needed

**Comment by cgreich** [comment]
> some SQL exercise to distinguish between the first dose and the second dose of vaccine

That's what it should be like. We don't have concepts counting their previous occurrences. Plus, those data are *very low quality*, as we all know from the Corona vaccination campaigns.
