### ISSUE TITLE
CPT4 duplicative concepts with 'Deprecated' in concept_name

### ISSUE THREAD

**Issue by varvarenius** [OHDSI/Vocabulary-v5.0#839]
While carrying out an ETL process, it was observed that certain codes within the CPT4 vocabulary are classified as both Standard and Valid, but they exhibit variations in their naming. Specifically, some of the codes have the suffix "(Deprecated)" in their concept_name.

Here is an example of Query to retrieve these codes 
```
select *
from concept c1
join concept c2 on c1.concept_name = c2.concept_name || ' (Deprecated)'
where c1.vocabulary_id = 'CPT4'
and c1.standard_concept = 'S'
and c1.invalid_reason is null
and c2.vocabulary_id = 'CPT4'
and c2.standard_concept = 'S'
and c2.invalid_reason is null;
```

**Comment by m-khitrun** [comment]
Hello,

These concepts were deduplicated: deprecated codes were mapped to their new equivalents or standard concepts in SNOMED/OMOP ext.
