### ISSUE TITLE
Retired Multilex?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#84]
**v5.0 20-JUN-16**

Have we retired Multilex?  When comparing 20160311 to 20160620 I see 77K Multilex CONCEPT_IDs that no longer exist.

``` sql
SELECT b.*
FROM [VOCABULARY_20160311].[DBO].[CONCEPT] B /*PREVIOUS VOCAB*/
WHERE CONCEPT_ID NOT IN (
      SELECT A.CONCEPT_ID
      FROM CONCEPT A    /*CURRENT VOCAB*/
      INTERSECT
      SELECT B.CONCEPT_ID
      FROM [VOCABULARY_20160311].[DBO].[CONCEPT] B /*PREVIOUS VOCAB*/
) 
AND VOCABULARY_ID = 'Multilex'
ORDER BY CONCEPT_ID
```

Example missing CONCEPT_IDs:

``` text
concept_id  concept_name    domain_id   vocabulary_id   concept_class_id    standard_concept    concept_code    valid_start_date    valid_end_date  invalid_reason
43056019    None known  Drug    Multilex    Ingredient  S   1   2012-12-20  2099-12-31  NULL
43056020    pantothenic acid    Drug    Multilex    Ingredient  NULL    10  2012-12-20  2099-12-31  NULL
43056021    aminoglutethimide   Drug    Multilex    Ingredient  NULL    100 2012-12-20  2099-12-31  NULL
43056022    bambuterol  Drug    Multilex    Ingredient  NULL    1000    2012-12-20  2099-12-31  NULL
43056023    lemon spirit    Drug    Multilex    Clinical Drug   S   10000004    2012-12-20  2099-12-31  NULL
```

**Comment by cgreich** [comment]
It's all there. You need to click it when you download (and whoever does it have the permission).

But it will be retired in a couple days.

**Comment by ericaVoss** [comment]
@cgreich weird, I usually double check I have all boxes checked off.

**Comment by cgreich** [comment]
We are adding a "click all" button for you as we speak. :)

**Comment by ericaVoss** [comment]
@cgreich - Just requested only the Multilex Vocab.  No good.  It isn't exporting with the Vocab from Athena.

**Comment by cgreich** [comment]
Because you are not listed as the license owner. The email you got should have told you that. Did it not? Can you forward? And who are "you"? ericaStanoch@gmail.com or Evoss3@its.jnj.com?

**Comment by ericaVoss** [comment]
I use ericaStanoch@gmail.com because the JNJ spam filter eats the Athena emails.

**Comment by cgreich** [comment]
Try now.

**Comment by ericaVoss** [comment]
I just downloaded 20160817 and I'm missing 'Multilex'.

```{sql}
SELECT *
FROM CONCEPT
WHERE VOCABULARY_ID = 'Multilex'
```

I get 0 rows.  Do you think this is ATHENA messing up my gmail account again?

**Comment by ericaVoss** [comment]
I still am not getting it (on my most recent request for 20161107)

**Comment by cgreich** [comment]
Done.

**Comment by ericaVoss** [comment]
Confirm it works.  Thank you!
