### ISSUE TITLE
Concept available through Athena but not from source vocabulary itself

### ISSUE THREAD

**Issue by Shinatoow** [OHDSI/Vocabulary-v5.0#840]
**Describe the problem in content or desired feature**
A concept is available through Athena and is classifed as "from SNOMED", but this concept is not available through SNOMED itself

**How to find it**
The concept through ATHENA is available here : https://athena.ohdsi.org/search-terms/terms/44790895

**Expected adjustments**
This concept could be placed as invalid

**Screenshots**
![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/73115715/d77cc1b7-e6d7-4fd3-9f90-027bd1cef9ca)
![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/73115715/e05e45a4-960e-4172-a69e-320412fef5b4)

**Comment by aostropolets** [comment]
This one is coming from SNOMED UK: https://termbrowser.nhs.uk/?perspective=full&conceptId1=248211000000106&edition=uk-edition&release=v20230412&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=999001261000000100,999000691000001104

Right now, we have SNOMED CT, SNOMED UK and SNOMED Int under SNOMED in the Vocabularies. So no deprecation needed.
