### ISSUE TITLE
ICD10CM: Limb vs. Lip in Carcinomas mapping

### ISSUE THREAD

**Issue by p-talapova** [OHDSI/Vocabulary-v5.0#845]
Hello there,

During the mapping review of ICD10CM codes for the N3C project, we encountered some limb-lip incompatibilities that can directly affect the number of included persons in cohorts with limb and lips carcinomas respectively. 

The following are the details:

icd_code | icd_name | relationship_id | concept_id | concept_code | concept_name
-- | -- | -- | -- | -- | --
[C44.621](https://athena.ohdsi.org/search-terms/terms/45552255)| Squamous cell carcinoma of skin of unspecified upper limb, including shoulder | Maps to | 4115027 | 285307007 | Squamous cell carcinoma of skin of upper lip
[C44.62](https://athena.ohdsi.org/search-terms/terms/45547501) | Squamous cell carcinoma of skin of upper limb, including shoulder | Maps to | 4115027 | 285307007 | Squamous cell carcinoma of skin of upper lip
[C44.629](https://athena.ohdsi.org/search-terms/terms/45556982) | Squamous cell carcinoma of skin of left upper limb, including shoulder | Maps to | 4115027 | 285307007 | Squamous cell carcinoma of skin of upper lip
[C44.622](https://athena.ohdsi.org/search-terms/terms/45581216) | Squamous cell carcinoma of skin of right upper limb, including shoulder | Maps to | 4115027 | 285307007 | Squamous cell carcinoma of skin of upper lip

We kindly request the Vocabulary team to address and rectify these mappings since ICD10CM is the officially supported terminology. However, if you require a template #6 submission from us for these cases, please inform us, and we will be able to provide it to you at a later time.

**Comment by aostropolets** [comment]
Thanks so much for catching it! Errors indeed.

Given that ICD10CM is not on the roadmap for August, could you please transform it into community contribution (so that we can incorporate it into August release)? Template 6 is absolutely the right place and would be much appreciated :)

**Comment by p-talapova** [comment]
Hi there, 

@aostropolets, I've created a sub-folder for the submission. Here's the [link](https://drive.google.com/drive/folders/1itRfUPOwkMO9ASuayR_nTsiQt6sYUAK0?usp=drive_link).
I hope it is not too late for the August release.

**Comment by TinyRickC137** [comment]
Done: https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20230831_1693510428.000000
