### ISSUE TITLE
CONCEPT_ID = 40 Missing

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#85]
This CONCEPT_ID no longer exists:

``` text
concept_id  concept_name    domain_id   vocabulary_id   concept_class_id    standard_concept    concept_code    valid_start_date    valid_end_date  invalid_reason
40  Generic Metadata    Domain  Domain  NULL    OMOP generated  1970-01-01  2099-12-31  NULL
```

**Comment by ericaVoss** [comment]
Was this retired?  Still missing in 20160817.

**Comment by ericaVoss** [comment]
I'm assuming this is gone - should we just close this issue?

**Comment by cgreich** [comment]
to be honest, I forgot what happened. In general, concept_ids should never disappear, even when they are retired. But there is concept_id=7:

7	Metadata	Metadata	Domain	Domain		OMOP generated	01-JAN-70	31-DEC-99

Is that what you need?
