### ISSUE TITLE
To fix that ICD10CM "substance use with other disorders" mapped to Mood disorder 

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#856]
These are wrongly mapped to the Mood disorder. 
I'll make a community contribution with the corrected mapping

45581430 | F15.19 | Other stimulant abuse with unspecified stimulant-induced disorder | Condition | Non-Standard |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
 45591110 | F15.188 | Other stimulant abuse with other stimulant-induced disorder | Condition | Non-Standard |   |   |  
1568156 | F15.18 | Other stimulant abuse with other stimulant-induced disorder | Condition | Non-Standard |   |   |  
1568205 | F19.98 | Other psychoactive substance use, unspecified with other psychoactive substance-induced disorders | Condition | Non-Standard |   |   |  
45576528 | F19.29 | Other psychoactive substance dependence with unspecified psychoactive substance-induced disorder | Condition | Non-Standard |   |   |  
1568200 | F19.28 | Other psychoactive substance dependence with other psychoactive substance-induced disorders | Condition | Non-Standard |   |   |  
45562033 | F19.288 | Other psychoactive substance dependence with other psychoactive substance-induced disorder | Condition | Non-Standard |   |   |  
45605461 | F11.29 | Opioid dependence with unspecified opioid-induced disorder | Condition | Non-Standard |   |   |  
1568112 | F11.28 | Opioid dependence with other opioid-induced disorder | Condition | Non-Standard |   |   |  
45566785 | F11.288 | Opioid dependence with other opioid-induced disorder | Condition | Non-Standard |   |   |  
45591084 | F10.29 | Alcohol dependence with unspecified alcohol-induced disorder | Condition | Non-Standard |   |   |  
45571709 | F10.288 | Alcohol dependence with other alcohol-induced disorder | Condition | Non-Standard |   |   |  
 45576495 | F10.19 | Alcohol abuse with unspecified alcohol-induced disorder | Condition | Non-Standard |   |   |  
1568099 | F10.18 | Alcohol abuse with other alcohol-induced disorders | Condition | Non-Standard |   |   |  
45576494 | F10.188 | Alcohol abuse with other alcohol-induced disorder | Condition | Non-Standard

**Comment by dimshitc** [comment]
found more codes of this type (also included anxiety and delusional disorders being targets of unspecified disorders), submitted the file
https://drive.google.com/drive/u/0/folders/1Rok8PIuzFlVG_50nw-TgA9xS5wFm1z0T

**Comment by dimshitc** [comment]
Not sure, who I need assign this task to, assigned it to Anna and Alex. let me know if there is a standard point of contact when submitting such a contribution

**Comment by TinyRickC137** [comment]
For ICD10 it would be @irinazherko @IrynaZherka 

In general, you can ping me or leave it as is - we are keeping track of Github Issues and Forum posts

**Comment by irinazherko** [comment]
We are pleased to inform you that the issue has been successfully corrected during the February 2024 Release
