### ISSUE TITLE
International Normalized Ratio INR are measurements? None seen in measurement domain

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#857]
**Describe the problem in content or desired feature**
I would expect the conceptId 4306239 and its descendants to be measurements.
They are currently observations which are probably faulty.
I also do not see any other measurement concepts that semantically correspond to INR in the measurement domain, This would mean that we cannot populate measurement table with INR values. 

**How to find it**
4306239

**Expected adjustments**
Change to measurement domain. This allows populating measurements in measurement table

**Comment by gowthamrao** [comment]
Maybe this ?

![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/13936600/b0e9565d-fded-424a-9a50-fd0eea113789)

**Comment by TinyRickC137** [comment]
Hey, @gowthamrao 
Thank you for this catch. I was going to check this concept and answer something like "indeed, we worked so hard, but our work resulted in some bugs, we will fix it, sorry about that". But my answer would be more complicated. 

Good things first. All the INRs in LOINC are measurements, so please use them. However, in Snomed there are [INR in Observation domain](https://athena.ohdsi.org/search-terms/terms/4306239) (one from the example), and [INR in Measurement domain](https://athena.ohdsi.org/search-terms/terms/4261078).

If we dive into hierarchy, we would see the difference between these two concepts, coming from Snomed itself. First one is embedded into hierarchy of Observable Entities (Hematology observable) together with some "features" of Leukocytes and Platelets. Second one is from the Procedural axis and is used as related concept by Snomed for concepts such as [INR Raised](https://athena.ohdsi.org/search-terms/terms/4196718), [INR - international normal ratio abnormal](https://athena.ohdsi.org/search-terms/terms/4306577) and others with relationship_id _Interprets of (SNOMED)_. So second one is clearly measurement.

First one is Observable entity, not measurement according to Snomed. Children of this problematic concept are coming from local Snomeds, which makes this situation even more complicated. First one is semantically measurement, but hierarchically... I would say at least debatable.

Currently, Snomed domains are assign through the system of peaks and with help of concept_classes if no peaks assigned for the concept. "Peak" means a concept in hierarchy that is used to define a domain for it's children. The problem with this approach is complex snomed hierarchy that changes with each release and complex snomed hierarchy, in which one concept may have unlimited number of ancestors and descendants. This is a killer-feature of Snomed, what makes it unique in terms of terminologies, but makes our work harder. 
According to our [Roadmap](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Release-planning), Snomed overhaul is planned for Winter release, February 2024. We are working on domain overhaul as well as on other tasks to simplify the system of domain assignments.
