### ISSUE TITLE
Filtering of synonyms too strict?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#86]
I'm not getting much value out of the concept_sysnonym table for mapping drugs. One important example: The synonym 'Paracetamol' is not linked to the standard ingredient 'Acetaminophen'. I know this information is in UMLS. Would it be possible to revise the synonym selection logic?

**Comment by cgreich** [comment]
Hm. "Paracetamol" is neither a synonym in RxNorm, nor in UMLS. It's the name of a mapped concept (from ATC, for example). Not sure what you want us to do.

With the upcoming RxNorm Extension we will add synonym from equivalent source concepts from international drug vocabs. That will help this.

**Comment by schuemie** [comment]
"RxNorm Extension"? What's that?

Remind me why you don't like UMLS equivalency? Both ATC and RxNorm map to the same CUI (C0000970). I would consider those synonyms,

**Comment by cgreich** [comment]
It's upcoming. :)

We found that the concepts from the various international drug references (JMDB for example) are so junky that we cannot use them as standard. So, we bit the bullet (big yucky bullet) and now built a process for creating real RxNorm concepts from those international drugs. You won't be able to tell the difference, except that vocabulary_id='RxNorm Extension'. We will have it covered at the Symposium.

**Comment by cgreich** [comment]
UMLS: They are equivalent, but not synonyms. In many cases it's just fine, in others it isn't. We have all those UMLS ones, but they are mapping or other relationships. So, if you want to use them just create another join bringing them in.

**Comment by schuemie** [comment]
Ah, got it, that might actually be a good idea for Usagi (where if a synonym is wrong it should be ok because a human should review it anyway).

**Comment by cgreich** [comment]
Totally agree.
