### ISSUE TITLE
READ codes in measurement domain are mapped to SNOMED codes in measurement domain

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#866]
https://athena.ohdsi.org/search-terms/terms?domain=Measurement&vocabulary=Read&page=1&pageSize=15&query=

Should we not just use LOINC as standard and make SNOMED in measurement domain non standard?

**Comment by aostropolets** [comment]
In 99% of the cases LOINC and SNOMED have different levels of granularity and are not equivalent. In this case, building join hierarchy is the way to go (there is a recording and slides from yesterday Vocab WG call discussing the current efforts on the subject in Vocab subgroup channel). You may found that some of deprecated LOINCs are mapped to SNOMED but other than that the links are hierarchical. Do you have specific cases where you'd like to change mappings?

**Comment by TinyRickC137** [comment]
Hello, @gowthamrao 
I will close this issue. Please feel free to reopen it if is still needed.
