### ISSUE TITLE
Sexual activity concepts in the incorrect domain of Condition.Should be Observation

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Vocabulary-v5.0#872]
# Instructions

**0. Create the initial issue.**
I am mapping uncoded sexual activity source data to standard concept_ids. The best matches for these source values are in the Condition domain. However, these are not Conditions, these are Observations about a person. These are lifestyle facts. 

**1. Read the documentation.**

Done.

**2. Choose the category of submission.**

- Template 5: Modify attributes of existing concept(s): domain, name, etc.;

**3. Fill the template.**

Done

**4. Upload the template.**

Done

**5. Reference the template in this issue.**

[Link](https://docs.google.com/spreadsheets/d/1OVvIW0Q2qLk46BQBdzzhtNm1WhbAq8zW/edit?pli=1#gid=417018096)

**6. Get the feedback.**

'Modify content' contributions are  reviewed by the Vocabulary Team. We will look at the submission. We will let you know if further discussion with the community is needed.

**Comment by m-khitrun** [comment]
Hello, @MelaniePhilofsky,

Please, be informed that concepts that represent sexual activity now refer to the Observation domain.
Thank you for your contribution.

Regards,
Masha.
