### ISSUE TITLE
Mapping issue:  ‘Z85.42’ Personal history of malignant neoplasm of other parts of uterus to Family history of clinical finding

### ISSUE THREAD

**Issue by lmcewen-helix** [OHDSI/Vocabulary-v5.0#883]
**Describe the problem in content or desired feature**
Possible incorrect mapping identified. ICD10CM ‘Z85.42’ ("Personal history of malignant neoplasm of other parts of uterus") is mapping to the SNOMED term (“Family history of clinical finding”). 

**How to find it**
Search for [concept_id: 45566466 (Z85.42)](https://athena.ohdsi.org/search-terms/terms/45566466)

**Expected adjustments**
I think the mapped relationship for Non-standard to Standard map (OMOP) should be ['History of Event' ](https://athena.ohdsi.org/search-terms/terms/1340204) maybe?

**Screenshots**
[Z85.42.pdf](https://github.com/OHDSI/Vocabulary-v5.0/files/12541858/Z85.42.pdf)

**Comment by TinyRickC137** [comment]
Hello, @lmcewen-helix 
It is a bug indeed. We will fix it. Thank you for this catch.

**Comment by irinazherko** [comment]
@lmcewen-helix We are pleased to inform you that the issue has been successfully corrected during the February 2024 Release. Thank you very much for your contribution!
