### ISSUE TITLE
Vocabulary available for download in Athena is not up-to-dated ["SNOMED"]

### ISSUE THREAD

**Issue by teenwyman** [OHDSI/Vocabulary-v5.0#886]
Dear OMOP Team,

It is found that the SNOMED vocabulary available for download in Athena are not up-to-dated.

The last update date of SNOMED available for download is 28-Jan-2022. 
![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/114593559/83813447-0625-402c-a5a0-856075ebb4b6)
In which, these three concepts are standard:
concept_id | concept_name | domain_id | vocabulary_id | concept_class_id | standard_concept | concept_code | valid_start_date | valid_end_date | invalid_reason
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
4052466 | Date ceased smoking | Observation | SNOMED | Observable Entity | S | 160625004 | 37287 | 73050 |  
4141787 | Smoking started | Observation | SNOMED | Clinical Finding | S | 266929003 | 37287 | 73050 |  
4275495 | Tobacco smoking   behavior - finding | Observation | SNOMED | Clinical Finding | S | 365981007 | 37287 | 73050 |  

However, when I search these three concept in Athena, it shows that all of them are non-standard. 
https://athena.ohdsi.org/search-terms/terms/4052466
https://athena.ohdsi.org/search-terms/terms/4141787
https://athena.ohdsi.org/search-terms/terms/4275495

The new standard concept mapped from these non-standard SNOMED concepts provided by `OMOP Extension` with ***valid start date = 05-Jan-2023***

**Comment by TinyRickC137** [comment]
Dear @teenwyman 

Updating Snomed is a huge effort, because we need to coordinate basically every other vocabulary. 

Currently, we refresh vocabularies according to the [roadmap](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Release-planning), where Snomed refresh is planned for February 2024.

**Comment by teenwyman** [comment]
Dear @TinyRickC137 

Thank you for your reply. I understood and appreciate your team's effort. 

One more question. 
I downloaded the SNOMED from Athena yesterday with the latest update = 28-Jan-2022.
![](https://user-images.githubusercontent.com/114593559/268679846-83813447-0625-402c-a5a0-856075ebb4b6.png)

Comparing these three concept_ids with the one I downloaded in Jan, the standard_concept flag in the latest one has been removed. It seems that the vocabulary latest update date is incorrect in this case. In addition to the vocabulary latest update date, is there any additional information shows that the vocabulary has been updated?

Thank you.

**Comment by TinyRickC137** [comment]
It is actually a great question for us to think about. 

We publish [release notes](https://github.com/OHDSI/Vocabulary-v5.0/releases) to be as transparent as we can. Latest_update indicates a full update of the vocabulary, including sources.

**Comment by teenwyman** [comment]
> So if you see the vocabulary in statistics delta - something has been changed.

Sorry, I don't quite catch it. How can I see the vocabulary in statistics delta?
