### ISSUE TITLE
disconnected CPT standard vocabulary concepts

### ISSUE THREAD

**Issue by clarkevans** [OHDSI/Vocabulary-v5.0#899]
While most CPT concepts are connected to the SNOMED hierarchy, there are a few that seem to be isolated, such as [46257516](https://athena.ohdsi.org/search-terms/terms/46257516).

**Comment by TinyRickC137** [comment]
Hi, @clarkevans 

You are right! It is a work in progress, and we improve CPT4 - SNOMED relationships (all of them, not only Maps to / Is a, but also SNOMED - CPT4 cat and SNOMED - CPT4 eq) every release.
Current stats are [here](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Known-Issues-in-Vocabularies). And [release notes](https://github.com/OHDSI/Vocabulary-v5.0/releases) for the most recent release explain more about SNOMED - CPT4 cat and SNOMED - CPT4 eq relationships coming from UMLS.
