### ISSUE TITLE
Link in description not working  

### ISSUE THREAD

**Issue by solmazeradat** [OHDSI/Vocabulary-v5.0#901]
Hi,

Under the section [Availability, License, Download](https://github.com/OHDSI/Vocabulary-v5.0/wiki/General-Structure,-Download-and-Use#availability-license-download) there are couple of points outlining on how to load the downloaded csv files. 

The link to the scripts to load the csv files is resulting a 404 error when you click here (**Highlighted in Yellow**). Provided the screenshot below:

![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/11243960/f23cc87d-b2c9-41da-9d4d-624aca138c27)

Many thanks,
Solmaz

**Comment by aostropolets** [comment]
Thanks, Solmaz! There was an extra dot at the end of the hyperlink, fixed now.
