### ISSUE TITLE
building contraints error missing concept_id in table concept

### ISSUE THREAD

**Issue by theompm** [OHDSI/Vocabulary-v5.0#904]
**Describe the problem in content or desired feature**
hey team ohdsi

i have a problem builing constraints after inserting inserting vocabulary (from athena) 

cdm version 5.4.1

1. creating tables - dll
2. inserting vocabulary rxnorm from athena (2023-10-23)
3. buildung primary keys
4. buildung indices
5. **ERROR** while building constraints

**ERROR:**
(psycopg2.errors.ForeignKeyViolation) insert or update on table "concept_synonym" violates foreign key constraint "fpk_concept_synonym_language_concept_id"
DETAIL:  Key **(language_concept_id)=(4175771)** is not present in table "concept".

[SQL: --postgresql CDM Foreign Key Constraints for OMOP Common Data Model 5.4

**Comment by TinyRickC137** [comment]
You also need to import SNOMED. Concept_synonym table references snomed concepts for Languages.

In general, I would recommend you to download and import at least all pre-checked vocabularies to avoid potential errors.

If you have other questions, not issues on our side, please ask questions on the [Forum](https://forums.ohdsi.org/).
