### ISSUE TITLE
SNOMED - RxNorm/RxNorm Extension deduplication

### ISSUE THREAD

**Issue by makc4us** [OHDSI/Vocabulary-v5.0#914]
Hi!

During the workflow on the creation of Toxin Vocabulary (https://github.com/OHDSI/GIS/issues/218) within the scope of work of GIS Vocab Package, the same toxic substance were found in both SNOMED and RxNorm vocabularies.

To enhance cross-dictionary interoperability, I purpose the deduplication of such concepts by adding mappings from existing SNOMED concepts to existing RxNorm/RxNorm Extension concepts. The file attached consist of 386 rows of possible mappings that can expand the connection between those vocabularies.

Link for the template: https://docs.google.com/spreadsheets/d/1iaY5yzqOylzAZSV5nhw6qGHK0HU6znmp/edit?rtpof=true#gid=955413031

The pathway to it is: Community Contribution folder => Modify Content folder => 914_SNOMEDRxNormDeduplication_MaksymTrofymenko folder.

**Comment by TinyRickC137** [comment]
Hi, @makc4us 

Thank you, this contribution definitely makes sense. 

Could you please double check the data formats, because some codes look like this: '3.53811E+15'

**Comment by makc4us** [comment]
Hi, @TinyRickC137

Thanks for the feedback.
I have checked and fixed these codes.
Take a look, please.
