### ISSUE TITLE
OMOP Standard Concepts Deduplication Request

### ISSUE THREAD

**Issue by p-talapova** [OHDSI/Vocabulary-v5.0#915]
Hi there. 

I have been working on critical and intensive flowsheet data mapping at Tufts CTSI. 
During the process, we have revealed some duplicates among the OMOP standard concepts. By using SSSOM, we collected all such cases relevant to our data and are now ready to submit the findings to the OHDSI Core Vocabulary Team. 
The submission template is uploaded [here](https://drive.google.com/drive/u/1/folders/1TIvuxLm64afuH1wcD4_9CEI-Aro2DWvT).

Additionally, there is an attached lookup table for further reference: [StandardConceptsDedupRequestLookup.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/13394289/StandardConceptsDedupRequestLookup.xlsx)

Thank you in advance!

**Comment by aostropolets** [comment]
Wow, thanks so much! Looks awesome!

This submission is opens up a broader question: what precedence we have in vocabulary standardization?

In drugs it is clear: RxNorm-> RxNorm Extension
In conditions it is probably SNOMED-> everything else
In procedures it seems we do SNOMED-> CPT4/HCPCS/ICD10PCS/ICD9Proc. Not clear where LOINC fits here.
In measurements, do we prioritize SNOMED or LOINC?

We will need to have the conversation in a broader group, but what do you think?

**Comment by TinyRickC137** [comment]
Great contribution, thank you!

LOINC should be a priority in the Measurement domain, since it is more granular. SNOMED Measurements are great for mapping of not-so-grannular data, but we could not recommend it over LOINCs.

**Comment by aostropolets** [comment]
And procedures? I see SNOMED procedures mapped to LOINC procedures in the file (and an RxNorm Oxygen mapped to SNOMED Oxygen, which seems like an occasional error).

**Comment by TinyRickC137** [comment]
> And procedures? I see SNOMED procedures mapped to LOINC procedures in the file (and an RxNorm Oxygen mapped to SNOMED Oxygen, which seems like an occasional error).

I agree that SNOMED-> CPT4/HCPCS/ICD10PCS/ICD9Proc (LOINC should be in the list, but again - it is the subject of discussion).

Regarding RxNorm to Snomed mappings, that would not be accepted of course.

**Comment by p-talapova** [comment]
I chose LOINC because it seems to be more widely used than SNOMED CT for coding and categorizing radiology-related procedures in real-world data. However, this prevalence of use does not necessarily serve as the definitive criterion for determining a standard's appropriateness or superiority here, in OMOP. That is why placing procedures categorized by SNOMED on top is a good idea, and I agree with this approach.

The RxNorm-to-SNOMED mapping is the error, and I apologize for that. Thank you for noticing that.

**Comment by p-talapova** [comment]
Regarding **measurements**, I favor LOINC over SNOMED CT when both standards are available, primarily due to LOINC's well-structured architecture, the broad spectrum of concepts, and its practical orientation towards real-life applications.

**Comment by Alexdavv** [comment]
For the Measurements the current approach was:
- if you really have something "more granular" in the source, you'd naturally map it to the vocabulary with generally more granular concepts which is LOINC. But it's not a question of prioritization - you just don't want to lose your granularity and since both target vocabularies are proper targets, you end up with the best match.
- when you really choose between the two concepts which are identical, then you go for SNOMED just because it's on the top of LOINC in the hierarchy. And this approach is much easier to implement technically.

**Comment by m-khitrun** [comment]
Hello, @p-talapova!

Just to let you know, your mappings have been included in this release and are already published in Athena.
We added some more mappings of vital signs measurements from SNOMED to LOINC for complete deduplication of these concepts.
Mappings of radiographic procedures were reversed with LOINC maps to SNOMED, as SNOMED is a standard vocabulary for procedures.
Mappings of SNOMED Qualifier Values to LOINC Answers were declined as we have no unified approach for mapping survey data.

Thank you very much for your contribution!

Regards,
Masha.
