### ISSUE TITLE
Non-english characters in name of standard concept 3008995

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/Vocabulary-v5.0#916]
**Describe the problem in content or desired feature**
I assume (although I'm not sure if correctly) that standard concept names are restricted to be in the english alphabet characters. Concept ID 43008995 and some of its descendants do not adhere to this.

**How to find it**
https://athena.ohdsi.org/search-terms/terms/43008995

**Expected adjustments**
Should the concept name be changed, removing the special characters?

**Screenshots**
N/A

**Additional context**
N/A

**Comment by cgreich** [comment]
> I assume that standard concept names are restricted to be in the english alphabet characters.

No such assumption. But if you don't want to deal with UTF-8 or the like you could replace all special characters with ASCII before loading. Tons of solutions for that on the internet.

**Comment by cgreich** [comment]
Sounds like the database encoding wasn't set up correctly. Happens all the time.

A couple years ago we actually were thinking to turn everything to ASCII. But there were reasons prohibiting that. I forgot why.
