### ISSUE TITLE
ICD10CM G92.0 Immune effector cell-associated neurotoxicity syndrome (ICANS) ->Maps to SNOMED 1230414002 Immune effector cell-associated neurotoxicity syndrome

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#920]

**Comment by dimshitc** [comment]
https://docs.google.com/spreadsheets/d/1Ckhezu1EErWocIf8xZI9oYuHPfZfxc4f/edit#gid=29877645

**Comment by irinazherko** [comment]
We are pleased to inform you that the issue has been successfully corrected during the February 2024 Release.
