### ISSUE TITLE
Drug concept with no relationships

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/Vocabulary-v5.0#927]
**Describe the problem in content or desired feature**
This valid NDC code has no relationships, rendering it useless in analysis: https://athena.ohdsi.org/search-terms/terms/3970976.

**How to find it**
https://athena.ohdsi.org/search-terms/terms/3970976

**Expected adjustments**
Add relationship(s) for this concept (i.e., non-standard to standard mapping).

**Comment by aostropolets** [comment]
So, Katy, would you like to consider community contribution of proposing the mapping for this concept? :)

**Comment by katy-sadowski** [comment]
I can give it a go!  I've actually got a little list of other bugs/mapping issues that I just haven't had time to file issues for yet...could I contribute all of those in 1 go?  (I skimmed the docs and looks like I should open a Contribution issue and list the proposed changes first?)

**Comment by aostropolets** [comment]
sorry for delay. probably would be better to keep each use case separate (especially if the concern different templates). E.g. if one issue is missing mappings and another is changing domains I'd probably create two separate issues. If it's all adding mappings, can be totally one submission. Thanks so much for considering, that would help tremendously!

**Comment by katy-sadowski** [comment]
OK sounds good!  I'll convert this issue to missing mappings, and if there are other types of problems I'll open separate issues for those.

**Comment by TinyRickC137** [comment]
This issue has been fixed (in February, actually, I just forgot to close this issue). 

@katy-sadowski if you have more - please submit a community contribution, we will be happy to accept it for the next February release, since August is just around the corner, there is no rush.
