### ISSUE TITLE
Lovastatin 60 MG Maps to Lovastatin 20 MG

### ISSUE THREAD

**Issue by mrechkem** [OHDSI/Vocabulary-v5.0#928]
It appears that several non-standard codes for "lovastatin 20 MG Oral Tablet [Mevacor]" (NDC), are mapped to the single standard "24 HR lovastatin 60 MG Extended Release Oral Tablet [Altocor]" (ID: 42707418- RxNorm). This is a concern since the standard mapping will capture statins with both 60mg and 20mg doses. I'm proposing the remapping of those non-standard NDC to all fall under the standard "lovastatin 20 MG Oral Tablet [Mevacor]"  (ID: 19031830- RxNorm).

Submission Document: [928_Lovastatin60MGMapstoLovastatin20MG_BradRechkemmer](https://docs.google.com/spreadsheets/d/1-zcciQTzs6tTt-AaYMPhYWqBg-Z4UEOj/edit?usp=drive_link&ouid=115789168781806558633&rtpof=true&sd=true)

CC: @chadwae & @Sathyaraos

**Comment by TinyRickC137** [comment]
Thank you very much for your contribution!

We aim for a two-month deadline for contributions to be included in the release, and for the February release it was even more, given the complexity of upcoming changes. Therefore, we can't guarantee that your mapping will be included, but we will try hard to include it in the release.

**Comment by mrechkem** [comment]
@TinyRickC137 - Great, thank your support! Please let us know if you have any additional questions for us.

**Comment by TinyRickC137** [comment]
Fixed in OMOP Vocabularies due to your contribution! Check the new release in Athena.

Thank you, we encourage you to contribute more

**Comment by mrechkem** [comment]
Thanks, @TinyRickC137 and team!
