### ISSUE TITLE
CPT-4 codes Issue

### ISSUE THREAD

**Issue by dachohan** [OHDSI/Vocabulary-v5.0#929]
Hi,

I downloaded V5.0 31-AUG-23 vocabularies from Athena and tried to run the CPT-4 batch file to add them in my concept file. I got my API key from UMLS site.

I followed the steps in the email and read me file but at the end of the batch file run it said "NOT PROCESSED CPT4 CONCEPTS: 13348. See the log file to find more information about errors". 

I opened the log file and all the fatal errors are: FAIL. The code value for id ********* is [ ] (* are the IDs of all the not processed CPT-4 concepts)  

I followed the same process for V5.0 23-JAN-23 previously and did not have this issue. Is there anything I am missing or are there any changes I need to make before downloading CPT-4 codes in concept files?

Attached is the log file and command line output for reference.  

[logfile.log](https://github.com/OHDSI/Vocabulary-v5.0/files/13865487/logfile.log)
![CommandLine](https://github.com/OHDSI/Vocabulary-v5.0/assets/71529071/2e1a80c9-fa32-491c-b472-2db96e86fefb)

**Comment by don-torok** [comment]
I just had a similar experience. However, I tried re-running the CPT-4 batch file, and it looks like the batch file recognizes records that failed to process the first time and is now attempting to load just those records that failed.

**Comment by dachohan** [comment]
I ran it 3 times but had the same issues, all 3 times I downloaded vocabularies again from Athena site and unzipped them in different folders. Did you rerun it under the same folder against the same concept file? @don-torok

**Comment by dachohan** [comment]
Resolved: Reran the CPT-4 batch file on the same concepts under the same folder. 
@don-torok  Thank you 👍
