### ISSUE TITLE
ICD10 Hepatitis C linked to Hepatitis B

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#93]
**Vocab Version 20160817**

There is an ICD10CM `B17.11-	Acute hepatitis C with hepatic coma` linked to the following standard concept `4314443-Hepatic coma due to acute hepatitis B`.  Does this make sense?

```{SQL}
SELECT c.CONCEPT_ID, c.CONCEPT_NAME, c.CONCEPT_CODE, 
	c2.CONCEPT_ID, c2.CONCEPT_NAME
FROM CONCEPT c
	JOIN CONCEPT_RELATIONSHIP cr
		ON cr.CONCEPT_ID_1 = c.CONCEPT_ID
		AND cr.INVALID_REASON IS NULL
	JOIN CONCEPT c2
		ON c2.CONCEPT_ID = cr.CONCEPT_ID_2
		AND c2.STANDARD_CONCEPT IS NOT NULL
WHERE c.CONCEPT_CODE = 'B17.11'
```

**Comment by dimshitc** [comment]
Thanks Erica, 
Yeah, mapping is wrong.
Currently my team is working on this ICD10 (CM) mappings so it'll be fixed in about 1 month

**Comment by ericaVoss** [comment]
I wouldn't expect it to be in this version already, but since I'm testing I'll make a note of it:

This issue exists in 20161117.

**Comment by ericaVoss** [comment]
This issue exists in 20161218

**Comment by dimshitc** [comment]
Yes, we know, thanks,
but should be fixed in the first release of 2017

2016-12-22 18:48 GMT+02:00 ericaVoss <notifications@github.com>:

**Comment by ericaVoss** [comment]
This still looks to be an issue in Vocab 20170503.

**Comment by ericaVoss** [comment]
Just making a note that this is still an issue in 20170920.

**Comment by ericaVoss** [comment]
Making a note still in 20171201

**Comment by cgreich** [comment]
@ericaVoss: It ain't. It's mapped to 46270037 "Hepatic coma due to acute hepatitis C". Or what's wrong?

**Comment by ericaVoss** [comment]
Using the query above that is not what I see in 20171201.  Does the more recent copy of the Vocab fix this?

![image](https://user-images.githubusercontent.com/6305439/34080567-471d023c-e30e-11e7-9cf8-e7b8d1c4e946.png)

**Comment by cgreich** [comment]
Fixed in the current. Returns

45605221	Acute hepatitis C with hepatic coma	B17.11	46270037	Hepatic coma due to acute hepatitis C

**Comment by aostropolets** [comment]
@ericaVoss  could you please close?

**Comment by ericaVoss** [comment]
Yes, Hepatitis C = Hepatitis C in 20180609
