### ISSUE TITLE
Newly FDA-approved drug talquetamab needs to be updated

### ISSUE THREAD

**Issue by ratardif** [OHDSI/Vocabulary-v5.0#931]
The FDA approved the drug Talvey (talquetamab) in August of 2023. It needs to be updated with the new RxNorm IDs for the ingredients and dosages.

I have provided the RxNorm information below:
Ingredient- talquetamab = RxNorm 2644447
Precise Ingredient- talquetamab-tgvs = RxNorm 2644448
Brand Name- Talvey = RxNorm 2644454
talquetamab-tgvs 2 MG/ML [Talvey] = RxNorm 2644455
talquetamab-tgvs 40 MG/ML [Talvey] = RxNorm 2644463

Please let me know if you need anything else.
Thank you.
Robin

**Comment by TinyRickC137** [comment]
Hi, @ratardif 

I am happy to inform you that the RxNorm has been updated during the [recent release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20240229_1709217174.000000) and these codes are now available in Athena.
