### ISSUE TITLE
Vocabulary "Type Concept" does not exist at Downloads, or its name is obscure

### ISSUE THREAD

**Issue by dmkuzsib** [OHDSI/Vocabulary-v5.0#932]
Hello OHDSI,

using the [download page](https://athena.ohdsi.org/vocabulary/list) I tried to obtain the vocabulary providing e.g. these terms:
[Case Report Form](https://athena.ohdsi.org/search-terms/terms/32809)
[EHR](https://athena.ohdsi.org/search-terms/terms/32817)

I could not find vocabulary with ID "Type concept" at vocabulary downloads
If it is there under another name, I suggest make its name consistent across all pages.

thanks
Dmitry

**Comment by dmkuzsib** [comment]
Found it myself

**Comment by TinyRickC137** [comment]
Hi, @dmkuzsib 

So sorry no one replied! One small tip: you can ask questions on the [forum](https://forums.ohdsi.org/), more people are willing to help there!
