### ISSUE TITLE
Autoimmune polyendocrine syndromes

### ISSUE THREAD

**Issue by aaronabend** [OHDSI/Vocabulary-v5.0#940]
There are currently 4 autoimmune syndromes in the vocabulary. The first 2 are "polyglandular autoimmune..." and the second 2 are "autoimmune polyendocrine".  To avoid confusion, I propose using the second template for all of these syndromes:

autoimmune polyendocrine syndrome type 1 - new name
autoimmune polyendocrine syndrome type 2 - new name
autoimmune polyendocrine syndrome type 3 - no change
autoimmune polyendocrine syndrome type 4 - no change

I actually do not care if someone prefers to make them all "polyglandular autoimmune syndrome #" as long as they are consistent. 

If you think it is necessary, I could create synonyms for all 4 syndromes using the second format, but at this time, that format seems less common. There is also "autoimmune polyglandular syndrome" but that also appears less frequently in the book, "The Autoimmune Diseases" (Rose & Mackay, 5th Ed), which is the authority on the science (though it is not consistent in the use of the names - I am contacting the editors to correct this). 

I have used Template 5 to propose the 2 name changes.

**Comment by vojtechhuser** [comment]
![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/7526119/906c5c68-7a08-4c10-bf9a-e11e734fd2ed)

**Comment by m-khitrun** [comment]
@aaronabend 
Hello! Have you reported this issue to SNOMED CT already?
