### ISSUE TITLE
Smoking

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#96]
I'm just adding this post here:
http://forums.ohdsi.org/t/smoker-in-the-snomed-vocabulary-condition-occurence/1078/10

There is definitely a mix on what domain this belongs too (at least in 20161107)

```{sql}
SELECT *
FROM CONCEPT
WHERE CONCEPT_NAME LIKE '%SMOKER%'
AND STANDARD_CONCEPT = 'S'
```

**Comment by aostropolets** [comment]
Yes, you are right. These are non-drugs.

**Comment by ericaVoss** [comment]
Still see the same mixture in 20161218.

Examples:
```{text}
concept_id	concept_name	domain_id
4144273	Trivial cigarette smoker	Condition
4145798	Ex-light cigarette smoker	Condition
4148415	Ex-trivial cigarette smoker	Condition
4148416	Ex-cigarette smoker amount unknown	Condition
```

**Comment by ericaVoss** [comment]
They look in better domains now.  I'm closing.
