### ISSUE TITLE
Ventilation assist and management codes mapped only to the Visit

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#965]
https://athena.ohdsi.org/search-terms/terms/2314000
https://athena.ohdsi.org/search-terms/terms/2314001
these are 
Ventilation assist and management, initiation of pressure or volume preset ventilators for assisted or controlled breathing; hospital inpatient/observation, each subsequent day /  initial day

and they are mapped only to [Inpatient Hospital](https://athena.ohdsi.org/search-terms/terms/8717) Visit.

Do you think the information that patient was on ventilation is useless in this case?

**Comment by dimshitc** [comment]
I didn't review it systematically, probably there are more codes of such kind

**Comment by m-khitrun** [comment]
These concepts were also mapped to the SNOMED [procedure](https://athena.ohdsi.org/search-terms/terms/4097246), but their target was deprecated in the course of SNOMED update. Thank you for the catch, we'll fix it.

**Comment by m-khitrun** [comment]
Hello,

Please, be informed that these concepts were mapped to the SNOMED [Ventilator care management](https://athena.ohdsi.org/search-terms/terms/4251737) procedure.
Thank you!

Sincerely,
Masha
