### ISSUE TITLE
recreate link in readme is broken

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/Vocabulary-v5.0#97]
The link in https://github.com/OHDSI/Vocabulary-v5.0/blob/master/README.md to http://www.ohdsi.org/web/wiki/doku.php?id=documentation:vocabulary:vocabulary_creation_etl_process goes to a non-existent wiki page.

**Comment by aostropolets** [comment]
@Sigfried 
fixed

**Comment by ericaVoss** [comment]
@Sigfried this issue is closed, would you mind closing it?

**Comment by ericaVoss** [comment]
@Sigfried  can you close this ticket?
