### ISSUE TITLE
CPT4 'Biopsy' Is a 	 'Excision and Destruction Procedures on the Pharynx, Adenoids, and Tonsils'

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#972]
https://athena.ohdsi.org/search-terms/terms/45887831

**Comment by m-khitrun** [comment]
Regarding the hierarchy itself, I see no problem: the descendants of this concept are related to nasopharynx and oropharynx.
Unfortunately, the UMLS gives us this non-specific name. We'll discuss how we can fix it. 
Thank you!
