### ISSUE TITLE
didn't postcoordinate Family history of human immunodeficiency virus [HIV] disease

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#974]
Z83.0	Family history of human immunodeficiency virus [HIV] disease	Maps to	438998000	Family history of human immunodeficiency virus infection

Should now all the Family and personal history mapping be postcoordinated?

**Comment by aostropolets** [comment]
Others can weight in here as well but in a nutshell Family history overhaul was decided to be de-prioritized in lie of more important items on the Vocab WG SNOMED discussion calls.

**Comment by dimshitc** [comment]
Good to know. I agree, it's not that urgent

**Comment by Alexdavv** [comment]
Will be a part of the family history fix (we know the problem)
