### ISSUE TITLE
801165	Injection, cabotegravir and rilpivirine, 2mg/3mg fixing mapping

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#978]
https://docs.google.com/spreadsheets/d/1SYTk7fLkPnuRqblr0P8ozooVKNsV3Hbl/edit?usp=sharing&ouid=113285728784887787047&rtpof=true&sd=true

**Comment by m-khitrun** [comment]
Hello!

Thank you for your contribution, this [mapping](https://athena.ohdsi.org/search-terms/terms/801165) has been implemented already.

Sincerely,
Masha.
