### ISSUE TITLE
CONCEPT table: Some Read concepts have null CONCEPT_NAME 

### ISSUE THREAD

**Issue by hamedabedtash** [OHDSI/Vocabulary-v5.0#98]
The latest version of CONCEPT table downloaded from Athena has some Read records with CONCEPT_NAME = NULL. This is a required filed (NOT NULL) that triggers error when uploading the table to the database. 

Attached, is the list of concepts with null concept names.

[Read concepts with CONCEPT_NAME=null.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/693862/Read.concepts.with.CONCEPT_NAME.null.xlsx)

**Comment by ericaVoss** [comment]
These were all deprecated at the time.  Should we just close this ticket?

We can find all of them like this:
```{SQL}
SELECT *
FROM CONCEPT
WHERE CONCEPT_NAME = ''
```

Tested in 20171201 and there are 12,841 concepts where the name is empty but they are all invalid.
