### ISSUE TITLE
XW03*, XW04* ICD10PCS mapping improvement

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#980]
https://docs.google.com/spreadsheets/d/1MQGZm71K4BgpwqgzCbrj9HwbvvURyviV/edit?usp=sharing&ouid=113285728784887787047&rtpof=true&sd=true

**Comment by m-khitrun** [comment]
Hello, @dimshitc 
Thank you for your contribution. 
Fields concept_id_2 and concept_code_2 appear empty in the concept_relationship_manual spreadsheet (a technical problem apparently). Could you please fix it and fill in other metadata fields in the right part of the sheet? Thanks.

**Comment by dimshitc** [comment]
@m-khitrun thank you for noticing, 
it's fixed now

**Comment by m-khitrun** [comment]
Hello!

Please, be informed that your contribution has already been implemented. Thank you!

Sincerely,
Masha
