### ISSUE TITLE
DBeaver Vocabulary Upload Issue - Multiple Failed Batch Inserts (concept.csv)

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#982]
Hi, this is an issue that was posted to the CDM github: 

### Issue Summary:

I'm currently following the demo outlined in the OHDSI YouTube channel [video link](https://youtu.be/FCHxAQOBptE) in order to upload the vocabularies I got from Athena (I already followed the procedures for the CPT4 vocabulary).

### Current Status:

The process is "almost" working. I've successfully inserted at least a part of the `concept.csv` vocabulary into the `CONCEPT` table using the same procedure and tools demonstrated in the video (DBeaver DBMS and PostgreSQL database). Just to be extra clear, I also truncated the `CONCEPT` table as requested in the video.

### Issue Encountered:

However, as the procedure progresses, I'm encountering errors with the following structure multiple times:

```
Error occurred during batch insert
(you can disable batch insert in order to skip particular rows).

Cause:
 SQL Error [22001]: Batch entry 1.249 INSERT INTO "cdmDatabaseSchema".concept
 ---[[[multiple lines of the csv are reported in this instead of this line, the next line is an example]]]---
 45102506 SM ELASTIC BANDAGE 3','Drug','NDC','11-digit NDC','','49348041291','20131002','20991231','')
 was aborted: ERROR: value is too long for type character varying(255). Call getNextException to see other errors in the batch.
 ERROR: value is too long for type character varying(255)

```
### Current Approach:

For now, I've been ignoring the error each time it occurs during the batch insert. However, I'm uncertain if this will result in a complete `CONCEPT` table.

### Next Steps:

I'm seeking guidance on how to address this specific error during the batch insert and whether there are potential implications for the integrity of the `CONCEPT` table. Any assistance or insights would be greatly appreciated.

**Comment by AlaikseiKatyshou** [comment]
Hi @clairblacketer,

According to the example you gave, some of the concept names contain the unescaped double-quote:

> "

And since you use double-quote as the "Quote char" in DBeaver, this causes an error.

I would suggest trying to use next character (just copy from here):

>ˆ

![quote_char](https://github.com/OHDSI/Vocabulary-v5.0/assets/159019348/73f76693-83e8-4117-97bf-a850a9bb54da)

**Comment by AlaikseiKatyshou** [comment]
Seems to be the user-end issue, not the vocabulary or CDM issue
