### ISSUE TITLE
Q2041 code reuse results in misleading 'concept replaced by' relationship

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#985]
https://athena.ohdsi.org/search-terms/terms/40664685
it's 
Upgraded
Remapped to [Injection, von willebrand factor complex (human), wilate, 1 i.u. vwf:rco](https://athena.ohdsi.org/search-terms/terms/40664859)

which is true for the old meaning of the Q2041. 
currently it's mapped correctly, but before 01-Apr-2018 it meant  von willebrand factor indeed,
so if you'll create a previous version of Q2041 as a separate concept (addressing code reuse), this concept will have Concept replaced by link. while the existing 40664685 Q2041 should not have it.

**Comment by m-khitrun** [comment]
Hello!

Just letting you know, that this erroneous replacement link was [deprecated](https://athena.ohdsi.org/search-terms/terms/40664685).

Sincerely,
Masha
