### ISSUE TITLE
ICD10CN mapping overwrites the ICD10CM mapping in O99.512

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#986]
![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/8568959/2044808b-4dde-43da-8865-88bcc80fc5bd)
ICD10CN mapping overwrites the ICD10CM mapping, 
O99.512	ICD10CM obtains acute respiratory syndrome mapping from ICD10CN concept, 

This should be rare, but if possible would be nice to investigate if other cases like this exist.

added fix of this concept mapping into #979

**Comment by TinyRickC137** [comment]
This is our Common Data Environment backfiring. Needs fixing, thank you.

Let's keep https://github.com/OHDSI/Vocabulary-v5.0/issues/979 as a primary issue for this.

**Comment by TinyRickC137** [comment]
GitHub says 'not planned' is a synonym for duplicate, I apologise for the confusion.
