### ISSUE TITLE
Bad mapping - limb to lip?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#994]
The concepts below (in table) have bad mapping.

Limb (source) is mapped to lip (standard)

![image](https://github.com/OHDSI/Vocabulary-v5.0/assets/13936600/b925a21e-3d58-48f2-abc4-ca286486d8f3)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/grao9/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/grao9/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Id | Code | Name | Class | Domain | Vocabulary
-- | -- | -- | -- | -- | --
45581216 | C44.622 | Squamous   cell carcinoma of skin of right upper limb, including shoulder | 6-char   billing code | Condition | ICD10CM
45556982 | C44.629 | Squamous   cell carcinoma of skin of left upper limb, including shoulder | 6-char   billing code | Condition | ICD10CM
45552255 | C44.621 | Squamous   cell carcinoma of skin of unspecified upper limb, including shoulder | 6-char   billing code | Condition | ICD10CM
45547501 | C44.62 | Squamous   cell carcinoma of skin of upper limb, including shoulder | 5-char   nonbill code | Condition | ICD10CM

</body>

</html>

**Comment by TinyRickC137** [comment]
Hi, @gowthamrao 
The good news with this one: everything has been fixed in the February Release, I see the correct mappings in Athena.
